- src/fheroes2/battle/battle_interface.cpp
> Fix animation order of creatures during combat

- .github/workflows/osx_pull_request.yml
- .github/workflows/osx_release.yml
> Don't update brew for MacOS

- src/fheroes2/monster/monster.cpp
- src/fheroes2/world/world_pathfinding.cpp
Fixes #2584 .
Also a typo fix for monster quality check.
> AI: check for special objects that you can't move through

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/gui/interface_icons.cpp
- src/fheroes2/gui/interface_icons.h
> QuickInfo dialogs have fixed position when clicked from right bar

- src/fheroes2/dialog/dialog_armyinfo.cpp
there were also a few other bugs there, like the "no room is garrison" text
never disapearing
> Fix joining creature logic with the lack of gold

- src/fheroes2/battle/battle_interface.cpp
> Change highlighted cursor area for spells during battle

- src/engine/audio_music.cpp
- src/engine/engine.cpp
- src/engine/engine.h
- src/engine/localevent.h
- src/engine/math_base.h
- src/engine/rand.h
- src/engine/serialize.cpp
- src/engine/serialize.h
- src/engine/smk_decoder.cpp
- src/engine/system.h
- src/engine/thread.h
- src/engine/timing.cpp
- src/engine/timing.h
- src/engine/types.h
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/game/game_static.cpp
- src/fheroes2/gui/interface_status.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
> Remove SDL timer

- fheroes2.vcxproj
- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/battle/battle_only.cpp
- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/castle/castle_mageguild.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_frameborder.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/dialog/dialog_guardian.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/dialog/dialog_thievesguild.cpp
- src/fheroes2/game/game_credits.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/gui/ui_window.cpp
- src/fheroes2/gui/ui_window.h
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
- src/fheroes2/kingdom/puzzle.cpp
> Add new standard window with shadow

- src/fheroes2/heroes/heroes_spell.cpp
> Fix town portal buttons in good interface

- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/maps/ground.cpp
> Display correct text when righ-clicking on map tile

- src/fheroes2/battle/battle_interface.cpp
> Fix castle's object positions

- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_interface.cpp
> Show pointer cursor most of the time during combat

- src/fheroes2/battle/battle_interface.cpp
> Display troop counter only for static animations

- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/battle/battle_only.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_levelup.cpp
- src/fheroes2/dialog/dialog_skillinfo.cpp
- src/fheroes2/gui/skill_bar.cpp
- src/fheroes2/gui/skill_bar.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/heroes/skill.h
- src/fheroes2/kingdom/kingdom_overview.cpp
> Show Spade of Necromancy artifact bonus in Necromancy Skill window

- src/fheroes2/castle/castle_heroes.h
- src/fheroes2/kingdom/kingdom_overview.cpp
> Fix Kingdom overview crash

- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/heroes/route.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
close #2496
close #2470
also small speed up of drawings of world map
> Fix pathfinding issues and missing path display

- src/fheroes2/battle/battle_interface.cpp
> Correction of spell area shadow

- src/engine/image.cpp
- src/engine/image.h
- src/engine/screen.cpp
- src/engine/smk_decoder.cpp
- src/engine/smk_decoder.h
- src/fheroes2/game/game_video.cpp
- allow Copy function to cut ROIs instead of failing
- add parametrized version of Resize function (might be used for View
World implementation)
- speed up video rendering
- fix issues with 8-bit image rendering due to incorrect pixel line size
> Multiple enhancements to rendering engine

- src/fheroes2/battle/battle_interface.cpp
> Don't draw wall for destroyed bridge

- src/fheroes2/battle/battle_troop.cpp
> Allow Anti-magic spell on mirror master creature

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Add empty line for visited info

- src/fheroes2/agg/icn.cpp
Fix castle flag drawing
before
after
> Fix castle flag drawing

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
> Fix Berserk logic

- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
> Do not play dwarves' resist sound during mass spells

- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
- hero: allow banned sec. skills upgrade
- battle: high objects are an obstacle for archers
> Remove few experimental options

- src/fheroes2/game/game_loadgame.cpp
> Fix missing music for Load Game option

- src/fheroes2/battle/battle_interface.cpp
> Cancel spell selection with ESC button in combat

- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/battle/battle_main.cpp
> Fix issue with fading at the start of the battle

- src/fheroes2/heroes/skill.cpp
> Cap necromancy bonus to 100% instead of 90%

- src/fheroes2/dialog/dialog_selectfile.cpp
> Align dates by left in the load file dialog

- VisualStudio/SDL1.props
- VisualStudio/SDL2.props
- VisualStudio/common.props
That allow these props files to be included from project files in non-root locations
Related to discussion in #2669
> Add include/lib folders resolve relatively to props files.

- src/fheroes2/game/game_startgame.cpp
> Play music after showing New Week/Month dialog

- src/fheroes2/dialog/dialog_levelup.cpp
> Change the text for the number of secondary skills in level up window

- src/fheroes2/castle/castle.h
- src/fheroes2/castle/castle_dialog.cpp
> Disable actions while buying a hero or during construction

- src/fheroes2/castle/castle_building.cpp
> Fix overlapped flag in Knight's castle

- src/fheroes2/ai/normal/ai_normal_battle.cpp
> Do not block shooters with overpowered army

- src/fheroes2/dialog/dialog_quickinfo.cpp
while trying to check a town or a hero on uncharted territory
relates to #2568
> Fix a crash in debug mode

- src/fheroes2/ai/normal/ai_normal_hero.cpp
> Add more logic for AI jumping into whirlpools

- src/fheroes2/battle/battle_arena.cpp
Hello!
This is a fix for #2646. It needs to be checked before merge. Can I have a save file to reproduce?
> [Bugfix][2646] Ability to retreat when player has no towns

- src/fheroes2/dialog/dialog_armyinfo.cpp
> Do not show marketplace icon for joining creature dialog is none is built

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_troop.cpp
> Battle screen, area-based spells vs Anti-Magic

- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/resource/resource.cpp
- calculate danger level for all castles
- fix resource calculation formula
relates to #2158
> Fix AI castle defence mechanics

- src/fheroes2/ai/normal/ai_normal_hero.cpp
> Don't visit useless objects by AI heroes

- src/fheroes2/ai/ai.h
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> Optimize AI hero movements

- src/fheroes2/game/game_over.cpp
> Fix infinite AI turns

- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/world/world_loadmap.cpp
Fix #2719
Fix #2718
relates to #2717
> Fix incorrect info when righ-clicking on terrain tiles

- src/fheroes2/ai/ai_common.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
> AI should buy spellbook if doesn't have one

- .travis.yml
Thanks to Travis-CI team to break all builds for a month.
> Fix Travis-CI deployment

- src/engine/rand.cpp
- src/engine/screen.cpp
- src/engine/tools.cpp
- src/engine/xmi2mid.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/dialog/dialog_marketplace.cpp
- src/fheroes2/dialog/dialog_system.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
- src/fheroes2/gui/interface_radar.cpp
> Small speedups

- src/engine/screen.cpp
and speedup a little as well for this mode
> Fix rendering with mouse emulation

- src/Makefile
- src/engine/dir.cpp
- src/engine/dir.h
- src/fheroes2/army/army_bar.cpp
- src/fheroes2/army/army_bar.h
- src/fheroes2/battle/battle_grave.cpp
- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/game/game_io.cpp
- src/fheroes2/gui/interface_gamearea.h
- src/fheroes2/gui/skill_bar.cpp
- src/fheroes2/gui/skill_bar.h
- src/fheroes2/gui/text.cpp
- src/fheroes2/gui/text.h
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_regions.h
> Add -Wshadow compilation flag

- src/Makefile
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/game/game_static.cpp
- src/fheroes2/game/game_static.h
- src/fheroes2/monster/monster.cpp
- src/fheroes2/monster/monster.h
- src/fheroes2/world/world_pathfinding.cpp
> Add -Wfloat-equal compilation flag

- src/Makefile
- src/fheroes2/game/game.h
- src/fheroes2/kingdom/kingdom.h
> Add -Wredundant-decls compilation flag

- src/engine/image.cpp
- src/fheroes2/agg/bin_info.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/battle/battle_animation.h
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/castle/castle.h
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/dialog/dialog_guardian.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/game_io.cpp
- src/fheroes2/gui/interface_border.cpp
- src/fheroes2/gui/interface_border.h
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/gui/interface_radar.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/kingdom/kingdom_overview.cpp
- src/fheroes2/world/world_loadmap.cpp
> Bug fixes and code cleanup

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_over.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_border.h
- src/fheroes2/gui/interface_buttons.cpp
- src/fheroes2/gui/interface_buttons.h
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_focus.cpp
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/gui/interface_status.cpp
- src/fheroes2/gui/interface_status.h
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/maps/maps_tiles.cpp
> Interface code cleanup

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_base.h
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
- src/fheroes2/spell/spell_book.cpp
- src/fheroes2/spell/spell_book.h
This contains a small refactor of spellbook (1st commit) and the fix for issue #51
> Fix spell book status on hovering

- src/fheroes2/gui/interface_gamearea.cpp
little faster is always better
> Speed up rendering of World Map

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Change text for abandoned mines

- src/fheroes2/game/game_startgame.cpp
> Fix crash when entering ally castle

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/castle/castle_dialog.cpp
When hover over building display information about units which can be bought if this is that kind of building. For other building just display name of the building
Closes #1730
> Change building status message

- src/engine/image.cpp
> Fix application crash for drawings

- fheroes2.vcxproj
- src/fheroes2/game/game_interface.cpp
- src/fheroes2/gui/interface_border.cpp
- src/fheroes2/gui/interface_border.h
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/interface_gamearea.h
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/gui/interface_radar.h
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/kingdom/view_world.cpp
- src/fheroes2/kingdom/view_world.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
Here's a big PR that enables the "View World" window
What is missing:
- incorrect offset for some icons
- resource name is not written in the icons
I did some timings:
- pre-generation of the terrain takes 0.1 sec at map loading for XL maps
- adding fog etc for the terrain takes 0.03 sec when loading the view world screen for XL map
- redrawing the map when scrolling etc takes a few ms
> Implement "View World"

- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
- Change text in map size hint, to be displayed in more pleasant manner.
See #1235
> Change text in map size hint, to be displayed in more pleasant manner.

- src/fheroes2/dialog/dialog_file.cpp
> Main menu, loading game from the adventure map

- src/fheroes2/battle/battle_interface.cpp
> Use same colour for all battlegrounds

- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
- src/fheroes2/game/game_campaign.cpp
> New scenario bonus data (Spell, Starting Race, Skill)

- VisualStudio/Release.props
relates to #2219
thanks @Killbrum for the idea!
> Enable multi-processor compilation on VS release build

- README.md
- script/macos/install_sdl_1.sh
- script/macos/install_sdl_2.sh
> Add gettext package for MacOS scripts

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
> Fix magic gardens priority if object capture is enabled

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
Related to #2158.
AI could have been tricked before if guest hero had small army.
> Fix garrison strength estimation by AI

- src/engine/math_base.h
- src/engine/screen.cpp
- src/engine/screen.h
- src/fheroes2/dialog/dialog_resolution.cpp
- src/fheroes2/game/game_interface.cpp
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/world/world.cpp
now most of systems will have more than 1 resolution
> Optimize screen resolution logic

- src/engine/smk_decoder.cpp
- src/fheroes2/game/game_video.cpp
for some types of videos
close #2528
> Add logic to support video frame rescaling

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/dialog/dialog_system.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
Sped up AI battles as well by removing unnecessary delay, now it happens almost instantly.
Added auto-combat and auto spellcasting settings and included them in base interface:
I hope this will be useful for many, especially people debugging the game.
> Add auto battle resolve mode to the game

- src/engine/endian_h2.h
PS Vita support in endian_h2.h
> PS Vita support in endian_h2.h

- src/engine/agg_file.cpp
- src/engine/agg_file.h
- src/engine/serialize.cpp
- src/fheroes2/agg/agg.cpp
> Speed up file reading

- src/engine/screen.cpp
> Add resizable window support on SDL2

- src/fheroes2/battle/battle_board.cpp
> Fix overlapped battleground objects

- src/fheroes2/dialog/dialog_settings.cpp
> Fix autosave option logic

- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/castle/castle_town.cpp
> Reduce income window area in towns

- Makefile
- VisualStudio/SDL2.props
- src/Makefile
- src/engine/image_tool.cpp
> Fix compilation with SDL image

- src/fheroes2/game/game_startgame.cpp
> Fix incorrect castle focus while visiting by a hero

- src/fheroes2/castle/castle_well.cpp
> Fix well's max button

- src/fheroes2/heroes/heroes_action.cpp
> Fix post Daemon Cave music

- src/fheroes2/gui/interface_events.cpp
> Don't show waiting cursor for an exhausted hero

- src/fheroes2/gui/interface_status.cpp
> Add middle resolution status support

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/agg/agg.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/dialog/dialog_recrut.cpp
close #1744
close #838
close #1743
> Change logic in monster hiring window

- src/fheroes2/game/game_startgame.cpp
> Focus on hero after exiting castle window

- src/fheroes2/castle/castle_building.cpp
> Castle screen, animation of emerging boat always goes simultaneously with new building appeared

- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/kingdom/kingdom.cpp
> Fix missing last lost hero condition reset

- src/fheroes2/battle/battle_interface.cpp
> Fix missing animation frame for wince

- src/engine/image.cpp
- src/engine/tools.cpp
- src/fheroes2/agg/bin_info.cpp
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_data.h
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/gui/cursor.cpp
- src/fheroes2/gui/cursor.h
- src/fheroes2/gui/interface_buttons.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
> Fix multiple code smells

- src/fheroes2/heroes/heroes_move.cpp
> Fix hero shadow drawing on world map

- src/fheroes2/ai/normal/ai_normal_battle.cpp
> Check if space is taken when selecting a moat cell

- src/fheroes2/dialog/dialog_levelup.cpp
> Allow to modify a hero during level up

- src/fheroes2/agg/agg.cpp
> Fix ACCEPT button font for Good Interface

- src/engine/screen.cpp
> Add missing shadow for arrow cursor on SDL2

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Fix object's visited info #293 + fix grammar

- src/engine/image.cpp
- src/fheroes2/agg/agg.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/agg/til.h
- src/fheroes2/gui/interface_radar.cpp
No need to check useless stuff
> Small image loading optimization

- src/fheroes2/ai/normal/ai_normal_battle.cpp
> Disable retreat for auto battle mode

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
- "heroes: surrendering gives some experience"
- "heroes: recalculate movement points after creatures movement"
> Remove few buggy experimental options

- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
> Fix assertion at the start of battle

- src/fheroes2/heroes/heroes_action.cpp
> Fix barrier fade

- src/fheroes2/dialog/dialog_thievesguild.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
> Fix "Artifacts:" category in Oracle Screen

- src/fheroes2/castle/mageguild.cpp
- src/fheroes2/spell/spell_storage.cpp
> Do not allow the visiting hero to learn Library spells if the Library hasn't been built yet

- src/fheroes2/gui/ui_button.cpp
- src/fheroes2/gui/ui_button.h
Hi!
Found a TODO, attempted to fix.
> Cache released disabled button sprite

- src/fheroes2/agg/agg.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/heroes/heroes_spell.cpp
> Add new button sprites

- src/fheroes2/agg/agg.cpp
- src/fheroes2/agg/icn.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/dialog/dialog_recrut.cpp
- src/fheroes2/dialog/dialog_selectcount.cpp
> Fix MIN and MAX button drawings

- src/fheroes2/castle/buildinginfo.cpp
> Still show the build window if there is not enough resources to build this building

- src/fheroes2/battle/battle_action.cpp
> Fix double attack direction against large units

- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_over.cpp
- src/fheroes2/game/game_video.cpp
- src/fheroes2/game/game_video.h
> Wait for user input at the end of Winning video

- src/engine/system.h
- src/fheroes2/dialog/dialog_system.cpp
> Do not show external music option with an absent folder

- src/fheroes2/dialog/dialog_recrut.cpp
- src/fheroes2/maps/maps_tiles_quantity.cpp
> Fix City of the dead incorrect monster info

- src/tools/82m2wav.cpp
- src/tools/82m2wav.vcxproj
Clean up VS project file and add a missing line to avoid empty wav output
> Update sound extractor tool

- src/fheroes2/battle/battle_interface.cpp
Hi! 
This is a fix for #2006 
But I'm unsure if it works well with current localisation mechanism (that apparently uses a string hash to find a translation?)
> Change damage description log message for few mass spells

- src/fheroes2/spell/spell_book.cpp
> align spells in the magic book

- .gitignore
add fheroes2 executable and file/save directory
> add some game-related objects to .gitignore

- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
- src/fheroes2/battle/battle_bridge.cpp
- src/fheroes2/battle/battle_bridge.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_pathfinding.cpp
- src/fheroes2/battle/battle_troop.cpp
> Allow to place units in moat in front of the bridge

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_settings.cpp
> Remove Interface options from the list

- src/fheroes2/dialog/dialog_system.cpp
> Show full 1-pixel black border for Show Interface option

- src/fheroes2/heroes/heroes_spell.cpp
> Show normal monster names in Visions spell

- src/fheroes2/heroes/heroes_spell.cpp
close #614
close #615
close #616
close #621
close #622
close #623
> Add initial implementation of View spells

- src/fheroes2/game/game_startgame.cpp
> Fix incorrect icon over ally's castle

- src/fheroes2/game/game_startgame.cpp
> Fix last focus option

- src/fheroes2/world/world_loadmap.cpp
> Use rule of 9 for Ultimate Artifact placement

- src/fheroes2/agg/agg.cpp
> Fix missing sounds within System dialog

- src/fheroes2/castle/captain.cpp
- src/fheroes2/castle/captain.h
> Fix rendering of the Castle Captain's spell points bar

- src/fheroes2/battle/battle_dialogs.cpp
> Fix incorrect drawings for battle OKAY button

- src/fheroes2/battle/battle_board.cpp
> Fix distance calculation between cells on battlefield

- src/fheroes2/kingdom/kingdom_overview.cpp
> Fix Kingdom Overview selection drawings

- src/fheroes2/world/world.cpp
> Fix logic of placing monsters for a New Month

- src/fheroes2/dialog/dialog_selectcount.cpp
> Allow to use mouse wheel anywhere for split troop dialog

- src/fheroes2/army/army_bar.cpp
- src/fheroes2/gui/interface_itemsbar.h
Solves #2389. Also #2682 because turns out it shouldn't be much work to do (logic for this is done in LeftMouseSingleClick()
A bit wary on the cross army drag split fix/feature since I'm editing a base interface.
> Implement Cross army drag split

- src/fheroes2/dialog/dialog_recrut.cpp
> Fix Max/Min button position in monster recruit dialog

- src/fheroes2/castle/buildinginfo.cpp
- src/fheroes2/castle/castle_town.cpp
close #1754
plus small code speedup
> Standartize icon position in town's dialog

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/dialog/dialog_settings.cpp
> Fix scrollbar position in multiple places

- src/fheroes2/battle/battle_interface.cpp
> Fix possibly incorrect arrow direction from shooters

- src/fheroes2/battle/battle_arena.cpp
> Do not give additional 500 experience to the hero who won the battle if the opposing hero surrenders or flees

- src/fheroes2/resource/artifact.cpp
> Fix rendering of Arm of the Martyr

- VisualStudio/Debug.props
- VisualStudio/Release.props
> Fix VS compilation on 32-bit OSes

- src/fheroes2/battle/battle_main.cpp
Found a bug related to instant battles when hero spell points spent were not restored once you enter the manual mode.
Also saved hero pointer to avoid calling .GetCommander() every time.
> Reset hero spellpoints when restarting a battle

- src/fheroes2/dialog/dialog_recrut.cpp
> Fix creature recture window UI

- src/engine/rect.cpp
- src/engine/rect.h
- src/fheroes2/agg/icn.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/army/army.h
- src/fheroes2/castle/buildinginfo.cpp
- src/fheroes2/castle/buildinginfo.h
- src/fheroes2/castle/captain.cpp
- src/fheroes2/castle/captain.h
- src/fheroes2/castle/castle_mageguild.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/castle/mageguild.cpp
- src/fheroes2/castle/mageguild.h
- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/gui/statusbar.cpp
- src/fheroes2/gui/statusbar.h
- src/fheroes2/heroes/heroes_indicator.cpp
- src/fheroes2/heroes/heroes_indicator.h
- src/fheroes2/kingdom/race.cpp
- src/fheroes2/kingdom/race.h
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/pairs.h
- src/fheroes2/system/bitmodes.h
- src/fheroes2/world/world_regions.cpp
- src/fheroes2/world/world_regions.h
> Remove unused code

- src/fheroes2/gui/interface_events.cpp
> Check that the hero is able to move before focusing him and starting his movement

- .travis.yml
> Add deployment for PSV build

- src/fheroes2/kingdom/kingdom.cpp
> Make recruitment of heroes more random

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/ai/normal/ai_normal_spell.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
Some of the defensive mode (when AI army has more shooters than the enemy) bugs that I missed after the latest refactor.
> AI: fix defensive unit behaviour

- src/fheroes2/army/army.cpp
> Fix merging of the castle guardian army

- src/fheroes2/gui/interface_buttons.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
> Prohibit the guardian hero from casting adventure spells

- src/fheroes2/ai/normal/ai_normal_spell.cpp
Before the fix it would skip them.
> Fix resurrect check for units still standing

- VisualStudio/common.props
- fheroes2-vs2015.vcxproj
- fheroes2-vs2019.vcxproj
- src/tools/icn2img.vcxproj
- src/tools/til2img.vcxproj
- src/tools/xmi2mid.vcxproj
I miss that incorrectly missing files.
Also since common files used everywhere, TargetName cannot be set in shared files
> Fix building tools again

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
Adding a flat bonus based on buildings in the castle. Strength multiplier now accounts for moat and how suited is attacking army for castle assault.
> Improve castle garrison estimation

- .github/workflows/pr_author_auto_assign.yml
> Add an action to auto assign assignee of PR

- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_video.cpp
> Fix Choose Your Lord video sound

- src/engine/screen.cpp
> Fix incorrect window resolution in fullscreen mode

- src/fheroes2/game/game_io.cpp
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
> Rescan heroes paths only when we have full info about players

- src/engine/rand.cpp
- src/engine/rand.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/kingdom/puzzle.cpp
- src/fheroes2/kingdom/puzzle.h
- src/fheroes2/world/world.cpp
Adding a way to share random device. Also replaced last instance of `random_shuffle`.
> Randomize attack position choice and replace random_shuffle

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/ai/normal/ai_normal_spell.cpp
Do not cast a spell if it's lower than the base threshold.
> Conserve AI hero spellpoints

- src/fheroes2/heroes/heroes_action.cpp
> Fix Sphinx missing rewards

- src/fheroes2/battle/battle_arena.cpp
> Add proper Large Obstacle generation for battlefields

- src/fheroes2/kingdom/kingdom_overview.cpp
> Display Lighthouse count in Kingdom Overview

- src/fheroes2/gui/interface_events.cpp
> Add missing dot to sentences in few windows

- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
> Fix full artifact bag message

- src/fheroes2/battle/battle.h
- src/fheroes2/castle/castle.h
> Fix many enumeration compilation warnings

- src/fheroes2/game/game_startgame.cpp
> Don't overwrite meaningful event processing result in Interface::Basic::HumanTurn()

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/gui/interface_cpanel.cpp
- src/fheroes2/gui/interface_cpanel.h
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_pathfinding.cpp
also some small performance optimizations as well
> Speed up ICN loading and remove useless image copying

- src/fheroes2/heroes/skill.cpp
> Fix for the #3117

- src/fheroes2/game/game.cpp
> Fix game score calculation

- src/engine/image.cpp
- src/engine/image.h
> Migrate Image::_data to std::unique_ptr

- src/engine/dir.cpp
- src/engine/dir.h
- src/fheroes2/game/game_video.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
> Load correct video files to be played

- src/fheroes2/army/army.cpp
> fix dragon city guardians

- .github/workflows/macos_pull_request.yml
- .github/workflows/macos_release.yml
https://github.com/Homebrew/discussions/discussions/691#discussioncomment-600559
> Fix Homebrew issues on macOS builds

- src/fheroes2/heroes/heroes_action.cpp
> add message when visit Oracle

- src/fheroes2/battle/battle_board.cpp
> Fix large object coverage in battles

- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_main.cpp
Closes #1497
Closes #1498
Some examples of the new necromancy window:
> implement new necromancy window

- src/fheroes2/battle/battle_interface.cpp
> Highlight Lich's shot area

- src/fheroes2/battle/battle_arena.cpp
> Preserve the order of catapult shots

- src/fheroes2/heroes/heroes_indicator.cpp
> Hero info window, "Blood" morale shouldn't include exclamation mark

- src/fheroes2/maps/maps_tiles_quantity.cpp
> fix gold and exp dialog for the demon cave

- src/fheroes2/battle/battle_arena.cpp
> Fix mixed-up heroes in Battle::Arena::CanSurrenderOpponent()

- src/fheroes2/heroes/heroes_action.cpp
> Visit artesian springs independently

- .github/workflows/linux_pull_request.yml
> Enable builds for Linux with DEBUG on pull request

- src/fheroes2/army/army_troop.cpp
- src/fheroes2/maps/maps_tiles_quantity.cpp
> Fix object slicing issues

- src/engine/image.cpp
- src/engine/image_tool.cpp
- src/engine/screen.cpp
- src/fheroes2/battle/battle_catapult.h
- src/fheroes2/battle/battle_cell.cpp
- src/fheroes2/battle/battle_cell.h
- src/fheroes2/battle/battle_command.h
- src/fheroes2/battle/battle_only.h
- src/fheroes2/castle/captain.h
- src/fheroes2/game/game_delays.h
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/gui/ui_tool.h
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps_tiles.cpp
make SonarQube even more happier
> Fix multiple SonarQube issues

- src/fheroes2/battle/battle_interface.cpp
> Fix highlighting of the Lich shot area behind the castle walls

- src/fheroes2/spell/spell_book.cpp
> set spells order as OG

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps_objects.cpp
- add titles for dialogs;
- check the first 4 characters of answer only.
fix #1361
fix #1362
fix #1363
fix #1364
fix #1365
> Fix sphinx riddle dialogs

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Fix information displayed in castle quick info window

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/agg/agg_image.h
- src/fheroes2/agg/icn.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/gui/text.cpp
- src/fheroes2/gui/text.h
in order to have such support you're obligated to have needed (French/Polish/German/Russian and etc) version of the game.
For now only the map's text is supported.
close #2453
> Add proper support of other languages

- src/fheroes2/game/game_video.cpp
- src/fheroes2/gui/cursor.cpp
- src/fheroes2/gui/cursor.h
Only for software emulation mode and SDL 1
> Fix cursor during video playback

- src/fheroes2/dialog/dialog_thievesguild.cpp
> aling horizontal positions of columns and flags at oracle dialog

- src/fheroes2/agg/agg.cpp
- src/fheroes2/kingdom/puzzle.cpp
> Set requested music as current only if it is actually played

- src/fheroes2/heroes/heroes_move.cpp
> Dont redraw objects under hero

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Fix the display of the army in the castle quick info window

- src/fheroes2/battle/battle_arena.cpp
> Don't run animation of lowering the bridge on bridge destruction if bridge is already lowered

- src/fheroes2/battle/battle_board.cpp
> Fix passability for some big obstacles in battles

- .github/workflows/sonarcloud.yml
- .travis.yml
It will also need to create a repository secret with name SONAR_TOKEN and set it to SonarCloud token.
> Migrate SonarCloud analysis to GitHub Actions

- .github/workflows/sonarcloud.yml
- sonar-project.properties
Should drastically speed up the SonarCloud analysis.
> Use SonarCloud cfamily cache to speed up analysis

- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_interface.cpp
> Show correct message for hero's option dialog buttons

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/game/game_interface.cpp
- src/fheroes2/game/game_interface.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
also now it's much faster in terms of performance
close #1039
> Dimension door animation

- src/fheroes2/dialog/dialog_arena.cpp
> Add title to Arena dialog

- src/fheroes2/heroes/heroes_action.cpp
> Add titles to Alchemist Tower and Stables dialogs

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/castle/castle_mageguild.cpp
close #1306
also some code cleanup
> Show Mage Guild always in center

- src/fheroes2/agg/agg_image.cpp
> Add initial support of russian localization

- src/fheroes2/battle/battle_arena.cpp
> Allow the hero to retreat if, while in the castle, he attacks the hero outside the castle

- src/engine/image.cpp
- src/engine/image.h
- src/engine/image_tool.cpp
- src/engine/image_tool.h
- src/fheroes2/agg/agg_image.cpp
> Fix shadows for all monster mini sprites

- src/fheroes2/kingdom/puzzle.cpp
- src/fheroes2/resource/artifact_ultimate.cpp
- src/fheroes2/resource/artifact_ultimate.h
Use lazy loading technique to avoid useless resources usage (saving about 5% of save loading time).
> Do not generate Puzzle image on map loading

- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
as such option could be exploited for fast resource production
> Remove world: abandoned mine random resource option

- src/fheroes2/battle/battle_interface.cpp
> Teleport battle spell: verify target cell passability for the correct (teleporting) unit

- src/fheroes2/ai/normal/ai_normal_spell.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
fix #2425
fix #3269
Sorry to make a single PR for these two (at first sight) unrelated issues but it's really easier to fix them together.
> Battle log & spell resistance fix

- src/fheroes2/battle/battle_arena.cpp
Reported by @Branikolog https://github.com/ihhub/fheroes2/pull/3279#issuecomment-830005288
> Fix ability to retreat for a hero defending a town

- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_data.h
- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/world/world.cpp
> Add special Victory conditions for campaign scenarios

- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
> Display empty indicator when hero has less than 3 spell points

- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/maps/maps_tiles.cpp
to compensate the changes we made recently
> Speed up World Map drawings

- src/fheroes2/battle/battle_interface.cpp
> Remove incorrect background for Graveyard

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/army/army_troop.cpp
- src/fheroes2/army/army_troop.h
- src/fheroes2/battle/battle_animation.cpp
- src/fheroes2/battle/battle_animation.h
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_army.h
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
- src/fheroes2/world/world_regions.h
> Partial unused code cleanup

- src/fheroes2/gui/interface_gamearea.cpp
fix #3314
I'm not sure, may be it's better to fix this in some other manner...
> Retain position of the Adventure Map view after the Ultimate Artifact puzzle is viewed

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
- src/fheroes2/world/world.cpp
> Remove "world: new version WeekOf (+growth)" option

- src/fheroes2/battle/battle_arena.cpp
> Check that unit is (im)movable after each unit action

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/dialog/dialog_thievesguild.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
> Add additional info for oracle dialog

- src/engine/localevent.cpp
> Disable controller for any OS except gaming consoles

- src/fheroes2/resource/artifact.cpp
> Do not offer to exchange artifact with spell book

- src/fheroes2/game/fheroes2.cpp
> Print more verbose info about -d option in the app's command-line help message

- src/fheroes2/battle/battle_army.cpp
* check `part1` once
* use function instead of lambda
> Simplify ForceGetCurrentUnitPart

- src/fheroes2/gui/interface_list.h
> Fix broken behavior of scrollbars

- src/engine/math_base.h
- src/fheroes2/dialog/dialog_frameborder.cpp
Try to avoid default argument values
> Fix non-standard dialog rendering

- src/fheroes2/kingdom/view_world.cpp
> Fix View spells rendering

- src/engine/image_tool.cpp
- src/engine/timing.h
- src/engine/tools.cpp
- src/engine/translations.cpp
- src/fheroes2/agg/agg.cpp
- src/fheroes2/army/army_bar.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/game/game_delays.cpp
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/monster/monster.cpp
- src/fheroes2/monster/monster.h
- src/fheroes2/world/world.cpp
cleaner the code easier to maintain
> Fix some compilation warnings and SonarQube code smells

- src/fheroes2/kingdom/kingdom.cpp
> Fix the "world: use unique artifacts for resource affecting" option

- src/engine/serialize.cpp
> Speed up MIDI loading

- src/engine/localevent.cpp
fix #3368
Need to carefully retest drag&drop split mechanics after this change.
> Reset MOUSE_RELEASED mode along with MOUSE_CLICKED on successful mouse click processing

- src/engine/rand.cpp
- src/engine/rand.h
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
> Generate obstacles on battlefield based on the battle tile index

- src/fheroes2/dialog/dialog_thievesguild.cpp
This variant is more likely with OG.
> Fix elements layout for oracle/thieves dialog

- src/engine/localevent.cpp
- src/engine/localevent.h
> Add Home and End button support for save naming

- src/fheroes2/system/settings.cpp
> Fix a crash while loading a new save

- src/fheroes2/dialog/dialog_thievesguild.cpp
> Fix flags in Oracle/Thieves' Guild dialog

- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
> Fix incorrect rendering of View World image

- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_move.cpp
> Unveil the fog at the start of hero's movement

- src/fheroes2/spell/spell_book.cpp
To comply with the rest of windows
> Add shadow for Spell Book

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/dialog/dialog_system.cpp
- src/fheroes2/system/settings.cpp
> Add an option to hide AI movements

- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_mainmenu.cpp
> Remove configuration file created at first failed run

- src/fheroes2/ai/ai_hero_action.cpp
> Speed up AI hero movement

- src/fheroes2/heroes/heroes_spell.cpp
> Do not count monsters under fog for Visions spell

- src/fheroes2/ai/normal/ai_normal_castle.cpp
> Build Mage Guild before Special building for AI

- src/fheroes2/battle/battle_troop.cpp
> Fix Tower shooting logic during castle's siege

- .github/workflows/linux_pull_request.yml
- .github/workflows/linux_release.yml
> Cache Vita SDK to avoid build failures on SDK installation issues

- fheroes2-vs2015.vcxproj
- fheroes2-vs2019.vcxproj
- src/engine/screen.cpp
- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_video.cpp
- src/fheroes2/game/game_video_type.h
Diamonds in videos are not animated yet
> Add video playback for Succession Wars scenarios

- src/fheroes2/campaign/campaign_savedata.cpp
- src/fheroes2/campaign/campaign_savedata.h
- src/fheroes2/game/game_io.cpp
- src/fheroes2/game/game_io.h
- src/fheroes2/game/game_loadgame.cpp
> Directly show next campaign scenario for end of scenario save

- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/world/world.cpp
> Fix move points and spell points replenishment logic for heroes from hero pool

- src/fheroes2/battle/battle_dialogs.cpp
close #1566
close #1567
Works only for non-captains
> Add an option to open Hero Screen within battle

- src/fheroes2/castle/castle_well.cpp
> Fix well's max button hiring logic

- src/fheroes2/game/game_campaign.cpp
> Fix incorrect hero receiving a spell bonus

- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
> Make Ultimate Crown artifact for campaign scenarios

- src/fheroes2/ai/ai_hero_action.cpp
> Play hero's vanishing sound after AI vs human battle

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_spell.cpp
> Combat, AI behavior, AI hero Hector casts the Blind spell which does not give any benefit because the hero has only 1 point of Spell Power

- src/fheroes2/kingdom/puzzle.cpp
> Fix puzzle drawings

- src/fheroes2/maps/mp2.cpp
> Fix Stables and Alchemist's Tower passabilities

- src/fheroes2/maps/mp2.cpp
> Fix WaterWheel passability

- src/engine/localevent.cpp
- src/engine/localevent.h
fix #3392
May be there is a better way to fix this (suggestions are welcome), but I decided to do it this way.
> Force display rendering on app activation

- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
It doesn't work properly anyway.
> Remove "dynamic interface" experimental setting

- src/fheroes2/game/game_campaign.cpp
> Add an option to replay Intro video for campaign

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes_action.cpp
> Fix cheating AI behavior for dwellings with defenders

- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> Recruit an AI hero if none exists

- src/fheroes2/gui/cursor.h
Fix a few SonarCloud code smells.
> Make Cursor and CursorRestorer non-copyable and non-assignable

- src/fheroes2/heroes/heroes_base.cpp
> Don't clear morale modifiers too early

- src/fheroes2/heroes/heroes_move.cpp
close #3185
also some code cleanup and speed up for fading animation
> Fix incorrect hero position facing left

- fheroes2-vs2015.vcxproj
- fheroes2-vs2019.vcxproj
- src/fheroes2/castle/castle_ui.cpp
- src/fheroes2/castle/castle_ui.h
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/gui/interface_icons.cpp
> Draw correct castle icon in popup window

- src/fheroes2/maps/maps_tiles.cpp
> Fix moving AI hero out of hero drawings

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
> Fix shadows for random resources and artifacts

- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_video.cpp
also make campaign selection as 2 pixel thick
> Fix cursor apprearance between videos and fix corrupted last frame

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Hide cursor for popup windows

- src/engine/screen.cpp
- src/engine/screen.h
fix #1442 (after merging of #3403)
fix #2917
> Implement hiding & showing cursor with SDL2

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
> Fix inaccessible beach tiles

- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
> Add configuration option for first game run

- src/engine/smk_decoder.cpp
- src/engine/smk_decoder.h
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_video.cpp
- src/fheroes2/game/game_video.h
without video playback for now
> Add The Price of Loyaty campaign selection

- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
> Do not show gray flag over Haunted mine

- src/fheroes2/battle/battle_cell.cpp
- src/fheroes2/battle/battle_cell.h
- src/fheroes2/battle/battle_interface.cpp
close #1628
also make SonarQube littlem ore happier
> Show extended shadow for 2-hex monsters in battle

- src/fheroes2/game/game_startgame.cpp
> Fix incorrect game ending during time loss condition

- src/fheroes2/battle/battle_interface.cpp
> Fix incorrect cell shadowing for 2-hex monster

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
Do not visit if nothing is to uncover
> Fix AI obsession over Observation Towers

- src/fheroes2/maps/maps.cpp
- src/fheroes2/world/world_pathfinding.cpp
> Make fog uncovering task for AI more efficient

- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
fix some user's issues with map names
> Read campaign files in non-case sensitive manner

- src/fheroes2/world/world_pathfinding.cpp
> Fix game freezing during AI movements

- src/fheroes2/battle/battle_interface.cpp
> Fix 2-hex unit shadow movement

- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
> Fix multiple issues with AI and spell logic using distance evaluation

- src/fheroes2/gui/ui_button.cpp
- src/fheroes2/gui/ui_button.h
small performance optimization
> Do not render full screen on button event

- script/demo/demo_windows.ps1
- script/windows/install_packages.bat
Requested in #3582
* demo_windows.ps1: display a message at the startup to notify that downloading takes some time
* demo_windows.ps1: use Invoke-WebRequest if available (it shows download progress)
* Minor fixes
> Improvements for Windows scripts

- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/kingdom/kingdom.cpp
> Fix crash in Roland 10 scenario

- script/demo/demo_unix.sh
- script/demo/demo_windows.bat
- script/demo/demo_windows.ps1
Related to #3218, should be merged after it
> Adapt scripts for downloading the demo version to multi-user environment

- appveyor.yml
- fheroes2.iss
- script/windows/fheroes2.iss
Use Inno Setup for creating installers with optional download of demo version files.
Fixes #942.
> Create Windows executable installers

- script/windows/fheroes2.iss
As suggested in https://github.com/ihhub/fheroes2/pull/3582#issuecomment-853742022 and https://github.com/ihhub/fheroes2/pull/3582#issuecomment-853816497
> Fix Windows shortcuts

- .clang-format
> Update clang-format to C++11

- src/fheroes2/world/world.cpp
> Adventure map, after the teleportation the Boat should not be positioned in the Whirlpool on an already occupied square

- src/fheroes2/battle/battle_action.cpp
> Combat, when a troop of Dwarves resists a spell, the message should be displayed only after the animation of the spell 

- src/fheroes2/maps/maps_tiles.cpp
fix #3207
fix #3620
Hope I did everything right.
> Maps::Tiles::setBoat(): properly set unique id for pushed addon

- src/fheroes2/dialog/dialog_marketplace.cpp
> Dialog::Marketplace() : Fix usage of wrong kingdom during battle (if called from surrender dialog)

- src/fheroes2/army/army_bar.cpp
> Fix number of choices when splitting a troop into multiple troops

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/world/world_pathfinding.cpp
> Adventure map, it should be possible to attack a hero located on a Temple

- src/fheroes2/maps/maps_tiles.cpp
For example "New Enemies" map has no roads.
> Fix missing road identification

- src/fheroes2/system/players.cpp
> Scenario with random players, in the original game, random opponents are generated so that all castles are present and different when possible

- src/fheroes2/heroes/heroes.cpp
> Adventure map, Alamar can still move but there is no yellow part in the hero movement indicator in the hero list

- src/fheroes2/dialog/dialog_recrut.cpp
> Fix title background for recruit dialog

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/army/army_bar.cpp
> Fixed the displayed text in the army bar

- src/fheroes2/ai/ai_hero_action.cpp
> Fix typo in AIToMagellanMaps()

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/dialog/dialog_recrut.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/gui/ui_button.cpp
- src/fheroes2/gui/ui_button.h
- src/fheroes2/heroes/heroes_dialog.cpp
> Make proper rendering of some of disabled buttons

- src/fheroes2/ai/normal/ai_normal.cpp
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_base.h
Adjusting few things to make sure AI won't be making blatant mistakes in the early game and play somewhat safer.
> Fix AI spellcasting and army estimates

- CMakeLists.txt
discussed in #3669
Hi @winterheart how about this variant?
> CMake: install demo version installation scripts into ${CMAKE_INSTALL_DOCDIR}/demo

- .gitignore
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
Fixes #3470 
Only one hero will be able to visit an Artesian Spring in a week.
Fix notes:
Probably there is a more convenient way to iterate through all colors, but I couldn't find it. Maybe `IsAnyKingdomVisited` should be a member of `World` and `Kingdoms` should be an iterable class? It would simplify code.
> Visit artesian spring once a week

- src/Makefile
> Add -Wextra-semi compilation warning flag for makefile compilation

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- allow AI hero to revisit castle more than once
- reduce the value of spells which can be obtained visiting castle and ignore Adventure spells since AI doesn't know (yet) how to use them
- take into account monster upgrading value if visiting a castle
- increase the value of objects offerring a free monster upgrade
> Small AI improvements

- src/fheroes2/agg/agg.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_video.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
> Combine the functions Settings::GetListFiles() and Settings::FindFiles() into one, use the exact filename match in Settings::GetLastFile()

- appveyor.yml
- script/windows/fheroes2.iss
As discussed in https://github.com/ihhub/fheroes2/pull/3596#discussion_r644780992.
> Set app version from AppVeyor

- src/fheroes2/monster/monster_info.cpp
> Fix Bone Dragons' description

- src/engine/tools.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/maps/maps_objects.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/world/world.cpp
Use `all_of` and `any_of` instead of comparing result of `find_if` with container's end.
> code cleanup: Replace find_if with more suitable functions

- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/mp2.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
close #3308
close #2305
close #2201
relates to #3183
> Fix rendering priorities of map's objects

- src/fheroes2/maps/maps_tiles.cpp
> Fix incorrect object sorting logic

- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
> Cache campaign map data in Campaign::tryGetMatchingFile() to speed it up

- src/fheroes2/heroes/heroes_meeting.cpp
> Fix missing update in hero meeting dialog

- src/fheroes2/gui/interface_events.cpp
> Use spacebar only for activating object

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
> Fix blocking way AI heroes

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/heroes/heroes_action.cpp
also fix Hut of Magi behavior for human players
> Make AI to use Hut of Magi and Jail objects

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- don't visit Observation Tower if there's nothing to uncover
- don't visit Morale related objects if the fully army is Undead
- don't visit Witch Hut if the given skill is useless at the current time
close #3716
> Add extra conditions for object visiting by AI

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Adventure map, Haunted and Abandoned Mines, the information about the number of ghosts is not indicated in the mine information window

- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_focus.cpp
> Fix multiple issues with castle music

- src/fheroes2/castle/captain.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/kingdom/luck.cpp
- src/fheroes2/kingdom/luck.h
- src/fheroes2/kingdom/morale.cpp
- src/fheroes2/kingdom/morale.h
> Add morale and luck normalize functions

- src/fheroes2/castle/castle_ui.cpp
> Do not show x marker for fully built castle icon

- src/fheroes2/game/game.h
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/gui/interface_events.cpp
> Add an option to restart Campaign scenario

- src/fheroes2/world/world.cpp
> Fix placement of creatures during Month of Monster event

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_data.h
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_spell.cpp
close #3480
Also fix AI behavior for monster joining cases.
> Add Bane / Alliance monster behavior for campaign scenarios

- src/engine/screen.cpp
- src/engine/tools.cpp
- src/engine/tools.h
- src/fheroes2/battle/battle_cell.cpp
* Split `GetCommonRect` and replace `getCommonRoi`
* Remove unused functions
* Fix includes
> Cleanup tools

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
The new version doesn't produce any allocation
Also removed AllTroopsIsRace(): unused
> Removed Army::GetUniqueCount() and replaced it with AllTroopsAreSame()

- src/fheroes2/ai/ai_hero_action.cpp
Fixes some crashes due to assertion
> Add Alchemist Tower to the list of objects to be avoided by AI

- src/fheroes2/world/world_pathfinding.cpp
> AI should check if an object is guarded while unveiling fog

- src/fheroes2/castle/castle.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/world/world_loadmap.cpp
> Fix town passability for some cases

- files/lang/cs.po
- files/lang/es.po
- files/lang/fheroes2.pot
- files/lang/fr.po
- files/lang/hu.po
- files/lang/lt.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
- src/fheroes2/campaign/campaign_scenariodata.cpp
> Fix typo in Fizbin Medal

- src/engine/dir.cpp
Fixes mixed up scenario/campaign save files on save game dialog.
> Add additional getFilesFromDirectory() filtering on Vita

- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
Doesn't summarize with bonus for defeating hero.
Fixes #3833.
> Add 500 EP for conquering a town regardless of defending hero existence

- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
- src/fheroes2/world/world_loadmap.cpp
close #3801
also fixes a crash after the completion of this scenario
> Fix Wizards scenario 3 with custom Ultimate Artifact

- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/monster/monster.cpp
- src/fheroes2/monster/monster_info.cpp
- src/fheroes2/monster/monster_info.h
> Fix missing monster spell casting during battles

- src/fheroes2/ai/ai_base.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/gui/interface_buttons.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/kingdom/kingdom.cpp
> Fix inifinte loop during AI turn

- src/fheroes2/world/world_pathfinding.cpp
don't waste movement resources if we can archieve the same goal with
smaller amount
> Make fog discovery by AI more efficient

- src/engine/localevent.cpp
- src/fheroes2/agg/m82.cpp
- src/fheroes2/ai/ai_common.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/monster/monster.cpp
- src/fheroes2/resource/artifact.cpp
Fix some clang-tidy [bugprone-branch-clone](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-branch-clone.html) warnings.
> Group duplicated switch branches

- src/fheroes2/ai/normal/ai_normal_battle.cpp
> Make AI to use Lich's ability properly

- src/fheroes2/army/army.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/heroes/direction.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
Some slow systems suffer from low FPS
> Small performance optimizations

- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_io.cpp
- src/fheroes2/system/settings.cpp
works on SDL 1 as well and only for game versions with correct language
alphabet
> Add translation support without Unicode

- src/fheroes2/castle/castle.cpp
- src/fheroes2/world/world.cpp
> Fix missing castle list

- src/fheroes2/heroes/heroes_meeting.cpp
> Fix simultaneous activation of buttons in hero meeting screen

- src/engine/localevent.cpp
> Render on window resizing event

- src/engine/image.cpp
- src/engine/image.h
> Remove unused AlphaBlit overload

- .github/workflows/clang_tidy_comments.yml
Should fix this:
https://github.com/ihhub/fheroes2/runs/3150484374?check_suite_focus=true
> Don't run clang-tidy-pr-comments if there is no fixes.yml file

- VisualStudio/SDL2.props
- src/Makefile
- src/engine/CMakeLists.txt
- src/engine/image_tool.cpp
- src/tools/CMakeLists.txt
- src/tools/icn2img.cpp
- src/tools/til2img.cpp
> Fix FHEROES2_IMAGE_SUPPORT build

- src/fheroes2/game/game_startgame.cpp
> Fix incorrect cursor icon over castle

- src/fheroes2/castle/castle.cpp
- src/fheroes2/game/game.h
> Fix town fog area revealing

- .clang-tidy
- .github/workflows/clang_tidy.yml
- src/fheroes2/game/game.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/puzzle.cpp
> Restore background music after playing short-term music effects

- README.md
- docs/README.md
> Improve project description in README.md and docs/README.md

- src/fheroes2/battle/battle_interface.cpp
> Highlight cells from where a monster will attack

- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
> Do not draw flags for puzzle image

- src/fheroes2/battle/battle_interface.cpp
If one of the targets have full resistance the game will stuck in infinite loop. Checl this save file:
[4_TEARS_0150.zip](https://github.com/ihhub/fheroes2/files/6886391/4_TEARS_0150.zip)
> Fix infinite loop after chain lightning spell

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/ai/normal/ai_normal_spell.cpp
> AI: the first target of Chain Lighting can't be immune to it

- src/fheroes2/kingdom/kingdom_overview.cpp
> Fix UI defects in Kingdom castle dialog

- src/fheroes2/ai/normal/ai_normal_battle.cpp
> Fix AI archer avoid handfighting battle logic

- src/fheroes2/ai/ai_base.cpp
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/heroes/heroes_action.cpp
> Don't play ambient sounds during AI turn, move all battle sound-related stuff to Battle::Interface

- src/engine/tinyconfig.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
Didn't touch `src/fheroes2/spell/spell_book.cpp` since it's handled in #3870.
> Use erase-remove idiom

- fheroes2-vs2015.vcxproj
- fheroes2-vs2019.vcxproj
- src/engine/translations.cpp
- src/engine/translations.h
- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_game_settings.h
- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/game/game_credits.cpp
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/gui/ui_language.cpp
- src/fheroes2/gui/ui_language.h
- src/fheroes2/system/settings.cpp
to change resolution, language and experimental options
> Add normal Game settings dialog

- fheroes2.key
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/game/game.h
- src/fheroes2/game/game_hotkeys.cpp
hotkeys 1-6 for each creature tier and M button for max (buy all)
No particular issue that needs to be solved, but nice to have since we already have town screen hotkeys up already
> Add hotkeys for Well dialog

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_spell.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
close #3943
Can't reproduce myself on given save but it looks like it's the correct
fix
> Fix a crash while AI uses Summon Elemental spell during battle

- src/engine/dir.cpp
Fix build on PSV (broken due to latest changes in Vita SDK, I suppose?)
> Fix build on PSV

- src/fheroes2/battle/battle_arena.h
> Remove duplicated arena size defines

- src/fheroes2/army/army.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/monster/monster.h
Like in the original game.
close #2817
close #987
close #3336
> Fix monster joining logic

- .github/workflows/make.yml
- Makefile.switch
I'm sorry that I didn't do separate PRs, but these changes are really minor:
* Make workflow: use single cp command to copy both README.txt and README_PSV.md;
* Makefile.switch: all and clean should be .PHONY
> Minor improvements

- src/fheroes2/dialog/dialog_adventure.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
> Add titles to some dialogs

- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/interface_gamearea.h
> Display the position of a hero or a castle on radar while right clicking

- files/lang/pl.po
I have translated and updated some translation. Is there any Polish native to review it? (@dimag0g?)
> Update Polish translation

- src/fheroes2/heroes/heroes_action.cpp
> Update status window in WhirlpoolTroopLooseEffect() if troops has fallen overboard

- docs/INSTALL.md
Web preview is available here:
https://oleg-derevenetz.github.io/fheroes2/
> INSTALL.md: add download links for PS Vita and Switch

- files/lang/Makefile
> Fix polish encoding

- docs/INSTALL.md
> Fix installation guide for pacman-based Linux

- CONTRIBUTING.md
- docs/DEVELOPMENT.md
* DEVELOPMENT.md: better url encoding for issue search links;
* CONTRIBUTING.md: change the list of a relevant information for bug report;
* CONTRIBUTING.md: fix the url to open issues.
> Minor documentation fixes

- src/engine/tinyconfig.cpp
- src/engine/tinyconfig.h
> Replace TinyConfig::AddEntry with simple insert

- CONTRIBUTING.md
- README.md
- cmake/README.md
- cmake/README_fheroes2.md
- docs/DEVELOPMENT.md
- docs/INSTALL.md
- docs/README.md
- docs/README.txt
- docs/README_PSV.md
- docs/README_cmake.md
- docs/README_switch.md
- script/demo/README.md
- script/packaging/debian/README.Debian
- script/windows/README.md
* Break too long lines, remove extra empty lines;
* README.md: add links to the installation guide in the Copyright section;
* Add note about the preferable version of the game;
* Add information that demo version of the is in English only;
* Highlight the "please note" sections.
close #3997
> Documentation fixes

- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/kingdom/view_world.cpp
- src/fheroes2/kingdom/view_world.h
Split `ChangeZoom()` to `zoomIn()` and `zoomOut()`.
> Remove zoomIn flag from ViewWorld::ZoomROIs::ChangeZoom

- src/engine/dir.cpp
Also reduce number of comparisons using `StrCmp` type.
> Move duplicated code to filterByName function

- src/fheroes2/dialog/dialog_selectfile.cpp
> allow player to immediately edit save file name without clicking on the input field

- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
Use range-based for to iterate over kingdoms.
> Convert Kingdoms::size() method to static member

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_troop.cpp
Remove `invert` flag from `GetCommander()`, add `getEnemyCommander()` as replacement.
> Optimize Battle Arena related code

- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
- src/fheroes2/world/world_loadmap.cpp
> Do not let the player get a random artifact that allows him to win the game

- src/fheroes2/dialog/dialog_selectcount.cpp
> Fix too many free slots in cross-army splitting

- src/fheroes2/dialog/dialog_marketplace.cpp
- src/fheroes2/gui/interface_list.h
- src/fheroes2/gui/ui_scrollbar.cpp
- src/fheroes2/gui/ui_scrollbar.h
Once mouse is released the position of the scrollbar should be updated as in the original game.
close #2652
close #2444
close #2443
> Update scrollbar logic

- src/fheroes2/battle/battle_catapult.cpp
- src/fheroes2/resource/artifact.cpp
> Fix max ballista shots

- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_fileinfo.h
> Display same name maps in the list of available maps

- src/engine/audio.cpp
- src/fheroes2/agg/agg.cpp
> Audio: make valid atomic

- src/fheroes2/maps/maps_tiles.cpp
> Fix incorrect rendering on fog tile

- src/fheroes2/kingdom/kingdom_overview.cpp
to be consistent with the rest of the game
> Add popup dialogs in Kingdom Overview UI

- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_list.h
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/kingdom/kingdom_overview.cpp
> Remember UI position in Kingdom Overview dialog

- src/fheroes2/battle/battle_main.cpp
> Properly restore captain's spell points after quick battle

- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/dialog/dialog_system_options.cpp
> Handle Escape/Enter keys in various settings dialogs

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/ai/normal/ai_normal_spell.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_catapult.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_base.h
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/spell/spell.cpp
- src/fheroes2/world/world.cpp
And add separate `bool hasArtifact`.
And simplify some calculations related to `artifactCount`.
> Rename HeroBase's HasArtifact to artifactCount for readability

- src/fheroes2/kingdom/kingdom_overview.cpp
> Fix scrollbar position in Kingdom Overview dialog

- src/fheroes2/ai/normal/ai_normal_hero.cpp
> AI can capture Haunted mines

- src/engine/zzlib.cpp
- src/fheroes2/army/army_troop.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/kingdom/color.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/spell/spell_storage.cpp
- src/fheroes2/world/world.cpp
std::ostringstream is much slower than std::string so the code in the most obvious places was changed
> Replace ostringstream by string

- src/fheroes2/army/army.cpp
Fix the undead morale penalty:
* all undead get no modificator
* artifact "Arm of the Martyr" discards "All race troops +1" bonus
> Fix the logic in Army::GetMoraleModificator()

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
> Add base roles for AI heroes

- src/fheroes2/dialog/dialog_selectfile.cpp
useful to find save file location.
This is how it looks:
> Add short save file description

- files/lang/cs.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/lt.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
We made some changes in text recently.
> Update translation files

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/world/world.cpp
Fixes #1640
The original code needs rework, IMO, as it's abstraction leaks all the way down, but for now just fix the reported issue.
> Remove flags from most of the captured objects when losing

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_quickinfo.cpp
close #4143
also moved all functions under anonymous namespace
> Fix incorrect object info when a hero stands on it

- src/fheroes2/heroes/heroes.cpp
> Fix medium portrait issues

- files/lang/de.po
it's just copy-pasted as a test that translation works
> Add first German translation

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes_action.cpp
> Boat boarding animation speed doesn't depend on hero speed

- src/fheroes2/maps/maps_tiles.cpp
close #4142
tested in comparison with OG and it works in the same way.
> Fix Faerie Ring passability

- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/game/game_highscores.cpp
missing even in the original game
> Add popup dialogs for some buttons

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/world/world_pathfinding.cpp
> Fix ability to attack a monster through a barrier

- src/fheroes2/maps/maps_tiles.cpp
> Fix passability of mines

- src/engine/screen.cpp
Only for SDL2 in full-screen mode
> Lock mouse within the window in multi-display device

- src/fheroes2/game/game.h
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_mainmenu.cpp
> Fix incrementing days spent value after reloading a campaign save

- src/fheroes2/gui/interface_border.cpp
> Fix adventure border rendering on higher resolutions

- src/fheroes2/battle/battle.h
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_main.cpp
Fix #1511
The capture of human player's ultimate artifact is harder to handle, because it happens in a different place in the code: https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_main.cpp#L238-L257
This logic is duplicated in the dialog code that this PR changes, but there it is interleaved with display code...
> Display message about Ultimate Artifact after the battle

- src/fheroes2/game/game.cpp
- src/fheroes2/game/game.h
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
- src/fheroes2/world/world.cpp
> Fix Maps::getAroundIndexes()

- src/fheroes2/battle/battle_main.cpp
> Fix post battle crash

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
> Remove bugged union experimental options

- src/engine/serialize.cpp
- src/engine/serialize.h
- src/fheroes2/game/game_static.cpp
> Remove more unused functions

- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_list.h
> Reset focus when hero was dismissed, use KEY_RETURN for EVENT_OPENFOCUS by default

- files/lang/cs.po
- files/lang/de.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
- src/engine/types.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/castle/mageguild.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/dialog/dialog_guardian.cpp
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/maps/ground.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/spell/spell.cpp
- src/fheroes2/spell/spell.h
- src/fheroes2/world/world.cpp
Besides this:
- fix few spell messages in the game
- optimize ground type translation calls (no need to translate all in once)
- remove MAXU16 macro
- remove resource cost and state of spells. They were always 0. Relates to #3903
- add translations to some missing strings
- fix few compilation warnings
- fix one Polish sentence (missing capital letter)
> Add Spell description window in monster info dialog

- src/fheroes2/battle/battle_dialogs.cpp
> align elements on artifact combat dialog

- src/fheroes2/ai/ai_base.cpp
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_command.cpp
- src/fheroes2/battle/battle_command.h
- src/fheroes2/battle/battle_interface.cpp
* Remove unused battle commands;
* Remove the unused variant of MSG_BATTLE_MOVE;
* Change the type of the battle command type to a named enum class.
> Battle command cleanup

- src/fheroes2/kingdom/view_world.cpp
- src/fheroes2/maps/maps_tiles.cpp
> Fix passabilities related to cracks

- src/fheroes2/battle/battle_interface.cpp
Should be close to the original now
> Correct battle speed change for monsters

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/game/game_highscores.cpp
> give 15 char limit when inputing player name in highscores

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
> Fix passability for tall objects

- src/fheroes2/kingdom/kingdom.cpp
Iterate over heroes just once.
> Optimize artifacts income calculation in Kingdom::GetIncome

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
> Fix bridge animation during battle

- src/engine/system.cpp
- src/fheroes2/agg/bin_info.cpp
- src/fheroes2/castle/castle_building.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/heroes/direction.cpp
- src/fheroes2/heroes/route.cpp
here and there to make the game run a bit faster
> Tiny code speedups

- src/fheroes2/army/army.cpp
> Fix troop position in the Pyramid

- src/fheroes2/ai/normal/ai_normal_hero.cpp
> AI can visit Pyramids

- src/fheroes2/castle/buildinginfo.cpp
> Fix active building area in castle window

- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
> Fix passabilities of action objects

- src/fheroes2/world/world_pathfinding.cpp
> Fix AI hero being stuck on Stoneliths

- src/fheroes2/maps/maps_tiles.cpp
> Fix Altars' passabilities

- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> Develop castle during AI hero purchase

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/dialog/dialog_selectscenario.cpp
Since we do not have sorting by victory/loss conditions or by number of player adding extra buttons for Map Type makes no sense unless we make a brand new dialog for all options.
close #1411
> Show map type icons in New Map lists

- src/fheroes2/dialog/dialog_settings.cpp
> Grey out experimental disabled option

- src/fheroes2/heroes/heroes_action.cpp
> Add title to all artifact related windows

- src/engine/image.cpp
- src/fheroes2/resource/artifact.cpp
> Fix artifact selection area

- src/fheroes2/heroes/heroes.cpp
> Correct evaluation of AI hero recruitment and meeting

- src/fheroes2/battle/battle_board.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
close #1629
plus very minor code cleanup
> Add monster double attack cell highlighting

- src/fheroes2/heroes/heroes_action.cpp
> Add confirmation message in Alchemist Tower

- src/fheroes2/heroes/heroes_action.cpp
> Fix well when hero has mana >= max

- src/fheroes2/kingdom/kingdom.cpp
> Kingdom::isVisited(): return the correct result for a tile with a hero on it

- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps_tiles_quantity.cpp
> Fix rewards in the demon cave

- src/fheroes2/heroes/heroes_action.cpp
> Add headers for all Daemon Cave dialogs

- src/engine/rand.h
- src/fheroes2/kingdom/week.cpp
- src/fheroes2/kingdom/week.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
This make new week deterministic once the map is created
It may not 100% be what we want as in heroes 2 I think it's also partly
random once the map is created
> New week is only determined through current day + map seed

- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/gui/ui_text.cpp
- src/fheroes2/gui/ui_text.h
> Correct resource position in castle window

- src/fheroes2/gui/interface_border.cpp
> Use within-loop variables in repeatPattern()

- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/maps/maps_tiles.cpp
> Fix monster position on World Map

- src/fheroes2/battle/battle_main.cpp
> Before manual battle we should reset artifacts that are planned for transfer after instant battle

- src/fheroes2/maps/maps_tiles.cpp
> Cover more cases for shadow tile images

- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/mp2_helper.cpp
regression from #4514
relates to #4519
> Fix incorrect map loading algorithm

- src/fheroes2/maps/mp2.cpp
> Fix interaction passability with water objects

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/agg/agg_image.cpp
close #2614
This is how it looks:
> Correct original Waterfall images to remove Cave

- src/fheroes2/maps/maps_tiles.cpp
> Remove extra assertion for Reefs

- src/fheroes2/game/game_credits.cpp
We must respect the original team and show them all in the credits.
> Add credits to original HoMM2 team

- src/fheroes2/dialog/dialog_marketplace.cpp
> Fix Marketplace messaging

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/castle/castle_building_info.cpp
> Fix rendering of Captain's Quarters in Warlock castle

- src/fheroes2/castle/castle.cpp
Bringing building requirements back to the original values. Was reported by users in discord.
> Fix Stonehenge building requirements

- src/fheroes2/dialog/dialog_gameinfo.cpp
> Do not leak the hotkey state from the experimental settings dialog to the scenario info dialog

- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/maps/mp2.h
> Fix interaction with Shipwreck object

- src/fheroes2/castle/castle.cpp
> Use OG Prerequisistes for Upgraded Jousting Arena and Upgraded Cathedral

- docs/INSTALL.md
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>
> Add Homebrew install instructions

- src/fheroes2/maps/maps_tiles.cpp
Tested on 5 maps. Also fixed rare cases wit Reefs.
relates to #4545 comments given by @LeHerosInconnu .
> Fix water object passabilities

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/agg/agg_image.h
- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/dialog/dialog_language_selection.h
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/gui/ui_language.cpp
- src/fheroes2/gui/ui_language.h
- src/fheroes2/system/settings.cpp
start from Polish (not fully completed)
> Add runtime language generation

- src/fheroes2/game/game_campaign.cpp
Improve convenience: ESC is bound to Cancel, but Okay could only be clicked.
> Add hotkey to Okay button in Campaign select window

- src/fheroes2/agg/agg_image.cpp
relates to #2211
add German, French and Russian (which is disabled) languages
> Add multiple languages from the box

- src/fheroes2/heroes/heroes_action.cpp
> Fix sound effects when receiving artifacts from world map

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
> Use the path from the AI pathfinder when determining the nearest reachable cell instead of simply comparing distances

- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
> Set starting army in Archibald 7 scenario

- src/fheroes2/battle/battle_dialogs.cpp
> Allow to change Battle Speed using mouse wheel

- src/engine/system.cpp
- src/fheroes2/agg/agg.cpp
- src/fheroes2/agg/agg.h
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/castle/castle_building.cpp
- src/fheroes2/dialog/dialog_spriteinfo.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- replace image copy places with mostly std::swap calls
- replace single character appending by a character instead of a string
- rework battle and castle rendering code to avoid copying images
- remove unused parameter from function that reading data from AGG
> Don't copy data if it's unnessesary

- src/fheroes2/dialog/dialog_marketplace.cpp
This fixes the issue in the comment https://github.com/ihhub/fheroes2/issues/4484#issuecomment-957622031_  
Relates to PR #4535 .
> Use correct message in marketplace for first exchange when not enough resources

- src/fheroes2/maps/maps_objects.cpp
relates to #4598
As of now we just display the same messages for signs and bottles.
> Add random sign message

- src/fheroes2/castle/buildinginfo.cpp
- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_recrut.cpp
- src/fheroes2/heroes/heroes_action.cpp
> Fix monster recruit window position on World Map

- src/fheroes2/agg/agg_image.cpp
> AGG::LoadModifiedICN(): fix invalid Sprite::resize() call

- CMakeLists.txt
- Makefile
- Makefile.switch
- Makefile.vita
- VisualStudio/Release.props
- src/Makefile
- src/fheroes2/CMakeLists.txt
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/system/settings.cpp
> Remove BUILD_RELEASE macro

- src/fheroes2/ai/normal/ai_normal_hero.cpp
> Fix AI obsession with whirlpools and being always in sea

- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/gui/ui_language.cpp
- src/fheroes2/gui/ui_language.h
extended support for multi-language solution
> Fix language names being incorrectly displayed in the list

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/world/world.cpp
> Properly handle the day-week-month routine

- files/lang/cs.po
- files/lang/de.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/it.po
- files/lang/lt.po
- files/lang/nb.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
- src/fheroes2/maps/mp2.cpp
> Fix With's Hut name

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Show available creature count for PoL monster objects

- src/fheroes2/gui/interface_radar.cpp
> Show heroes on minimap

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/world/world_loadmap.cpp
> Add default castle's name is none is specified by editor

- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_events.cpp
> Make consistent campaign info dialog

- src/engine/audio.cpp
- src/engine/audio.h
- src/fheroes2/game/game.cpp
> Play sounds from closest surrounding objects first

- src/fheroes2/heroes/heroes_action.cpp
> Add Champion image for Stables object

- src/fheroes2/castle/castle_tavern.cpp
Currently in the Tavern there's the "Yes" button. The "OK" button is used in the OG and this is also what makes sense.
> Use the OK button for the Tavern window

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
> Properly draw battle grid

- src/fheroes2/game/game_interface.cpp
> Fix passability for Dimension Door spell

- src/fheroes2/game/game_campaign.cpp
> Show credits at the end of campaign

- src/fheroes2/dialog/dialog_game_settings.cpp
> Add popup window to OK button in game settings

- src/fheroes2/castle/buildinginfo.cpp
> Fix vertical position of building construction name

- src/fheroes2/heroes/heroes_action.cpp
> Add sound for visiting Observation Tower

- src/engine/smk_decoder.h
- src/fheroes2/game/game_newgame.cpp
fixing few flaws presented in the original game
> Add video playback in PoL campaign selection window

- src/fheroes2/dialog/dialog_skillinfo.cpp
> Fix vertical text position in skill icon

- src/fheroes2/castle/buildinginfo.cpp
- src/fheroes2/castle/castle_well.cpp
> Adjust monster recruit position for some dialogs

- src/fheroes2/dialog/dialog_system_options.cpp
when user changes the type of music
> Update background music on the fly

- src/fheroes2/maps/maps_tiles.cpp
> Always mark the entrance to the castle/town as a road, do not automatically mark the tile south of the entrance as a road

- src/fheroes2/campaign/campaign_scenariodata.cpp
> Fix regression in campaign bonuses logic

- fheroes2-vs2015.vcxproj
- fheroes2-vs2019.vcxproj
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/castle/castle_mageguild.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/dialog/dialog_spellinfo.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/spell/spell.cpp
- src/fheroes2/spell/spell.h
- src/fheroes2/spell/spell_book.cpp
- src/fheroes2/spell/spell_info.cpp
- src/fheroes2/spell/spell_info.h
> Add additional spell info for spells owned by a hero

- src/fheroes2/game/game_scenarioinfo.cpp
- src/fheroes2/gui/player_info.cpp
Makes it easier to go back (and forward) through the player classes.
> Allow to select player class using mouse wheel

- src/fheroes2/maps/maps_tiles.cpp
> Fix River being considered as a Road

- src/engine/image.cpp
- src/engine/screen.cpp
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/gui/ui_button.cpp
Crop function will produce the same type of image. In this case we have some slowdown in button creation logic but fixing 30% performance drop for PS Vita.
> Fix performance drop in rendering

- src/fheroes2/agg/agg_image.cpp
> Generate Russian letters by default

- src/fheroes2/ai/normal/ai_normal_battle.cpp
> Improve AI behavior during castle defense

- src/engine/audio.cpp
- src/engine/audio.h
- src/engine/system.cpp
- src/engine/system.h
> Fix handling of national symbols in the paths to music files on Windows

- .github/workflows/clang_analyzer.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/cmake.yml
- .github/workflows/make.yml
- .github/workflows/sonarcloud.yml
- script/windows/install_packages.bat
- script/windows/setup_packages.bat
* Ensure that apt-get update is running in unattended mode;
* Run brew update before brew install;
* Windows: migrate from SDL2-2.0.12 to SDL2-2.0.18.
> Build system improvements

- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/dialog/dialog_selectscenario.h
Useful for finding the location of the file and checking the map type
> Add popup dialog for map information

- script/windows/install_packages.bat
- script/windows/setup_packages.bat
It generate a huge non-proportional cursors on SDL 2
> Revert back  SDL version for Windows

- src/fheroes2/army/army.cpp
somehow AI managed to get invalid army
> Fix a crash during AI turn

- src/fheroes2/dialog/dialog_marketplace.cpp
closes #4803 
The x position of the left block was considered to be 0 relative to the frame. So I have instead move the right block 2 pixels to the left with the buttons to center them.
> Moved trading resources slightly to the left

- src/fheroes2/dialog/dialog_recrut.cpp
> Allow translation for "cost per troop:" text

- src/fheroes2/agg/agg_image.cpp
> Generate proper russian E with 2 dots on top

- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
"game: autosave on" setting makes no sense to even exist.
> Always enable Autosave

- src/fheroes2/game/game_video.cpp
> Add support of Buka Anim2 directory

- src/fheroes2/spell/spell_book.cpp
> Add a spell title when no enough SP window appears

- src/fheroes2/game/game_io.cpp
> Show proper language name for mismatched by language save files

- src/fheroes2/agg/agg_image.cpp
> Fix CPU player icon's extra color column

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_troop.cpp
- fix calculation of tower strength for neutral castle
- don't set AI in defensive strategy if no towers are present
> Improve AI behavior during castle defence

- src/fheroes2/agg/agg_image.cpp
> Fix glowing red pixel in Warlock's Red Tower

- src/fheroes2/heroes/route.cpp
- src/fheroes2/heroes/route.h
> Minor Route::Path cleanup

- src/fheroes2/dialog/dialog_giftresources.cpp
> Show only in-game players for Gift marketplace option

- src/fheroes2/maps/maps_tiles.cpp
> Fix water tiles with OBJ_COAST

- src/fheroes2/battle/battle_dialogs.cpp
> Changed captain's name

- src/engine/tools.cpp
The reasons for this change are described in https://github.com/ihhub/fheroes2/issues/4868
> added missing casts to unsigned char for isspace, isdigit, and tolower

- src/fheroes2/dialog/dialog_arena.cpp
closes #4835 
Here's what it looks like with my changes:
> Centered Knowledge sprite

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/world/world.h
- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
close #4464
Hi @ihhub here is the test map file: [WTRTEST.ZIP](https://github.com/ihhub/fheroes2/files/7803018/WTRTEST.ZIP). I didn't touch AI part however, but it seems that AI is trying to sail to neighboring islands and even to the island with my castle. I need your advice in regard to further AI-related changes.
> AIWorldPathfinder: encourage the AI-controlled heroes to overcome water obstacles using boats

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/game/game_campaign.cpp
> Fix Russian small k per in both fonts and expand campaign scenario startup choice text area

- src/fheroes2/battle/battle_troop.cpp
> Fix Mass Dispel usage during battle

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
> Display dead monster information during battle

- src/fheroes2/agg/agg_image.cpp
Based on @Branikolog's feedback
> Fix position of Russian e with 2 dots on top

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/maps/mp2.h
- src/fheroes2/world/world_pathfinding.cpp
Discussed in #4904.
The proposed approach to expanding the list of objects that AI can visit for the purpose of fog discovery.
Hi @ihhub what do you think?
> Improve the AI fog discovery logic

- src/engine/image.cpp
- src/engine/localevent.cpp
- src/engine/localevent.h
- src/engine/screen.cpp
- src/engine/serialize.cpp
- src/engine/tools.cpp
- src/engine/tools.h
- src/engine/xmi2mid.cpp
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/game_io.cpp
- src/fheroes2/kingdom/color.h
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
from 75 to 50. Little more efforts and we can make all warnings to be treated as errors.
> Reduce SDL dependency and the amount of warnings in Visual Studio

- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/dialog/dialog_selectscenario.h
fix #4924
Regression after #4828.
> Scenario selection dialog: fix the display of properties for maps from the list

- src/fheroes2/agg/agg_image.cpp
> Fix small font for Polish GoG version

- src/fheroes2/ai/normal/ai_normal_hero.cpp
> AI: apply the "anti-stuck" heuristics even to the last available hero

- src/fheroes2/castle/castle_well.cpp
to be consistent with the castle
> Show monster info on right click in castle's well

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_recruits.cpp
- src/fheroes2/heroes/heroes_recruits.h
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
fix #3191
fix #3662
Here are some more notes on this topic - what this PR fixes and what it DOESN'T fix:
* ~~Previously, hiring heroes in castles was done by all kingdoms from a single pool, and the heroes offered for hire could intersect in different kingdoms at the same time - for example, the same hero could be offered for hire in the Blue Kingdom and in the Green one. Now the set of heroes is fixed for the whole week (except for the surrendered heroes) - related to the #3662. The problem here is that there is not enough heroes in the game. We have only 9 heroes in each of the 6 fractions, so if there are 6 players in the game and each of them will hire 8 heroes (max number), then that's what will happen for certain players:~~
~~So it's impossible to have non-intersecting heroes for …
> Redesign the hero recruitment process

- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
> Fix campaign text translation

- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/game/game_campaign.cpp
> Made language area and campaign choice selection to cover text too

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/agg/agg_image.cpp
> Fix some SonarQube bugs

- src/fheroes2/gui/ui_text.cpp
also show ? symbol instead of invalid characters
close #4936
> Fix crashes due to assertions while rendering a text

- src/engine/image_tool.cpp
- src/engine/serialize.cpp
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_objects.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/world/world.cpp
cleaner the code easier to read
> Fix some SonarQube smells

- src/fheroes2/battle/battle_interface.cpp
> Fix attack cursor during battle

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_pathfinding.cpp
- src/fheroes2/battle/battle_pathfinding.h
Fix the issue described in #4970
Before (note that the Hydra affected by the Berserk spell skips a turn):
https://user-images.githubusercontent.com/32623900/152168694-f1a71c38-036a-4c0a-9c0a-1f4714576d1f.mp4
After:
https://user-images.githubusercontent.com/32623900/152168713-421d7bcb-39ff-41c2-8738-d4020cf60b58.mp4
---
Also fixed a bug that caused the castle towers not to target berserkers.
> Rework the Berserker's logic, bringing it closer to the logic of a regular AI-controlled unit

- src/fheroes2/battle/battle_interface.cpp
> Fix a crash due to an assertion while finding an attack cursor type during battle

- appveyor.yml
> AppVeyor: do not run separate build for feature branch with open pull request

- .github/workflows/clang_analyzer.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/clang_tidy_comments.yml
- .github/workflows/make.yml
- .github/workflows/sonarcloud.yml
Should also fix some false positives like [this one](https://sonarcloud.io/project/issues?id=ihhub_fheroes2&open=AXvcoXaXC5s14wGGLda2).
> Also analyze the code related to debugging

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/gui/player_info.cpp
- src/fheroes2/heroes/heroes_move.cpp
Fix a few SonarCloud code smells.
> Remove outdated commented out code

- src/engine/system.cpp
- src/engine/system.h
- src/engine/xmi2mid.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/gui/interface_radar.h
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/maps/mp2.h
- src/fheroes2/maps/position.h
- src/fheroes2/resource/resource.cpp
- src/fheroes2/resource/resource.h
- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
Also `MapPosition::isPosition()` was made virtual, because it is overridden in `Castle`.
> Another round of removing unused code

- src/fheroes2/heroes/heroes_action.cpp
fix #1976
OG:
https://user-images.githubusercontent.com/32623900/154133608-6a505adf-b562-44cf-a666-53a9d00ea7db.mp4
fheroes2:
https://user-images.githubusercontent.com/32623900/154133641-059d87c6-e24a-46ec-95fc-dfa474dbee80.mp4
> Fix sounds of Lean-To and Skeleton

- src/engine/translations.cpp
- src/fheroes2/monster/monster_anim.h
> Fix possible errors for translation related code

- src/fheroes2/heroes/heroes.cpp
> Fix hero name not being updated while switching languages

- src/fheroes2/dialog/dialog_resolution.cpp
To be consistent with the rest of the code
> Add popup dialogs for right mouse click in resolution dialog

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/battle/battle_tower.cpp
close #4589
fix a regression from #4708 of not displaying battle grid over moat and caste's background
> Fix battle grid and ballista info area

- src/engine/translations.cpp
- src/fheroes2/gui/ui_language.cpp
- src/fheroes2/gui/ui_language.h
CD Projekt released Czech location of Heroes of Might and Magic 2 in about year 2002.
> Add Czech language support

- files/lang/Makefile
- files/lang/cs.po
> Use CP1250 encoding for Czech translation

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/ai/normal/ai_normal_spell.cpp
Fixes #4656 .
Happens when AI makes last spell cast before fleeing the battle and planning to invoke power mass spell like Armageddon.
> AI should save current unit if retreating

- src/engine/translations.cpp
- src/engine/translations.h
- src/fheroes2/system/settings.cpp
> mofile::ngettext(): strip the context if the translation was not found

- src/engine/dir.cpp
- src/engine/system.cpp
- src/fheroes2/game/fheroes2.cpp
> Fix directory and file detection on Windows

- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
> Add missing artifact discovery event description

- src/fheroes2/heroes/heroes_action.cpp
> Fix Sirens action dialogs

- src/fheroes2/gui/interface_radar.cpp
> Display the correct size of player-owned objects on mini-map

- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/maps/maps_tiles.cpp
> Fix a crash caused by a broken object being rendered on mini-map

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/gui/skill_bar.cpp
- src/fheroes2/gui/skill_bar.h
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_meeting.cpp
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/heroes/skill.h
- src/fheroes2/monster/monster_info.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
We must not associate anything related to other versions of HoMM series (relates to #1272 )
Also code cleanup.
> Remove H3 related option

- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/dialog/dialog_selectscenario.h
- src/fheroes2/game/game_scenarioinfo.cpp
> Remember map size selection

- src/fheroes2/game/game_campaign.cpp
> Add popup windows for campaign scenario dialog buttons

- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
> Show captain quick info dialog

- src/fheroes2/dialog/dialog_arena.cpp
> Add popup dialogs for Arena's skill choices

- src/fheroes2/maps/maps_tiles_quantity.cpp
> Fix rare case of Shipwreck having no battle

- src/fheroes2/game/fheroes2.cpp
> Increase the number of sound channels to 32

- files/lang/cs.po
- files/lang/de.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/it.po
- files/lang/lt.po
- files/lang/nb.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_system_options.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
> Use Okay over OK

- files/lang/cs.po
- files/lang/de.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/it.po
- files/lang/lt.po
- files/lang/nb.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
- src/engine/timing.h
- src/fheroes2/agg/icn.h
- src/fheroes2/castle/castle_tavern.cpp
- src/fheroes2/game/game_delays.cpp
- src/fheroes2/game/game_delays.h
- src/fheroes2/gui/ui_dialog.cpp
- src/fheroes2/gui/ui_dialog.h
- src/fheroes2/resource/artifact_ultimate.cpp
- src/fheroes2/resource/artifact_ultimate.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
- introduce new dynamic image UI element used for animations within a dialog
- introduce text UI element which can be used together with other UI elements
- fix incorrect translation of Tavern's rumors ( close #4795 )
- fix animation speed in Tavern's dialog
> Fix translation and UI in Tavern dialog

- src/fheroes2/gui/ui_dialog.cpp
> Do not show experience value in popup window

- files/lang/cs.po
- files/lang/de.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/it.po
- files/lang/lt.po
- files/lang/nb.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/game/game_mainmenu.cpp
close #4794
partially relates to #4789
> Dynamically update Game Language dialog

- src/engine/audio.cpp
- src/engine/localevent.cpp
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game.h
- src/fheroes2/game/game_static.cpp
- src/fheroes2/game/game_static.h
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
- remove a lot of static variables from game_static.cpp
- fix some compilation warnings on Visual Studio
> Another round of code cleanup

- src/engine/screen.cpp
- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/dialog/dialog_language_selection.h
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_video.cpp
- src/fheroes2/game/game_video.h
- src/fheroes2/maps/maps_fileinfo.cpp
- speed up video file detection (reduced the amount of I/O calls). It is noticeable for systems with slows disks
- set window title when creating window in SDL 2. No need to waste CPU power for an extra call
- fix missing language setup when no language or only one language are present
- remove extra code while reading MP2 files
> More performance improvements

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/castle/castle_well.cpp
> Fix incorrect popup monster window in Well

- script/windows/setup_packages.bat
> Add libFLAC DLL into Windows packages

- src/fheroes2/battle/battle_interface.cpp
> Add a popup window for battle log

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
> Take the weekly growth into account when calculating monthly population growth bonuses and fines

- CMakeLists.txt
> Fix typo in CMakeLists

- src/fheroes2/castle/castle_well.cpp
Also some code cleanup for that file. close #1796
> Fix rendering of bottom bar in Well dialog

- src/fheroes2/heroes/heroes_action.cpp
> Fix incorrect artifact discovery description

- src/fheroes2/castle/castle_mageguild.cpp
the same as it was done for Well dialog.
> Fix Mage Guild bottom status bar rendering

- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_base.h
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
- src/fheroes2/resource/artifact_info.h
- src/fheroes2/spell/spell.h
- src/fheroes2/spell/spell_storage.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
They are clashing with the future artifact modding approach.
> Remove experimental options related to Artifacts

- .github/workflows/clang_tidy.yml
- .github/workflows/clang_tidy_comments.yml
- .github/workflows/make.yml
- src/fheroes2/game/game_interface.cpp
- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_startgame.cpp
fix #5203
It would be good to check this on multi-monitor systems as well.
https://user-images.githubusercontent.com/32623900/161856562-90697848-6300-4727-993a-2e51e413053c.mp4
> Fix scrolling in full-screen mode in case of an aspect ratio mismatch

- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/monster/monster.cpp
- src/fheroes2/monster/monster.h
> Fix a crash due to an assertion failure when the shooter hits back at a unit under Berserk spell

- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
- src/fheroes2/spell/spell_storage.cpp
> Fix a crash while opening Magic Book

- src/fheroes2/agg/agg_image.cpp
This generates a Battle Only button if French resources are available:
Relates to this:
https://github.com/ihhub/fheroes2/issues/5114
I tried to center and align as good as possible - The box is an odd number so a perfect centering is not possible.
I don't want to bother you since I know you're quite busy, but if you should have the time to give a quick glance with your talent for spotting at the above image @LeHerosInconnu , then I would be very grateful! Don't mind that the buttons themselves are not aligned specifically in that image, that is just a quick cut and paste of them - the text is what matters.
> Generate French Battle Only button

- src/fheroes2/agg/agg_image.cpp
Related to: https://github.com/ihhub/fheroes2/issues/5114
> Generate Polish Battle Only button

- src/engine/screen.cpp
fix #5233
It seems that black bar with notch is not a part of the app's window.
Hi @zenseii can the reporting user test this change?
> Always grab the mouse in fullscreen mode to properly support devices with notch

- src/fheroes2/resource/artifact.cpp
> Fix a crash when a hero tries to get a second magic book

- src/resources/fheroes2.rc
> Update copyright year in Windows executable file

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_main.cpp
fix #5238
Also fixed an issue when win/loss music wasn't played in the battle result dialog.
> Allow to change the auto battle settings if player's army doesn't have a commander (for example, when defending a castle without a hero or a captain)

- .github/workflows/clang_analyzer.yml
- .github/workflows/code_style_check.yml
- script/tools/check_code_format.sh
- script/tools/check_copyright_headers.py
- script/tools/check_copyright_headers.sh
- script/tools/copyright_headers/full_header_cxx.txt
- script/tools/copyright_headers/full_header_mkf.txt
- script/tools/copyright_headers/header_template_cxx.txt
- script/tools/copyright_headers/header_template_mkf.txt
- src/resources/fheroes2.rc
>  Check copyright headers in makefiles and resources, check LegalCopyright date in fheroes2.rc

- src/fheroes2/dialog/dialog_frameborder.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_border.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
fix #5251
Also this PR fixes the issue with event processing order in the "hidden interface" mode. Before:
https://user-images.githubusercontent.com/32623900/163254650-ca1ad7be-16ad-473a-8783-7714723d029d.mp4
After:
https://user-images.githubusercontent.com/32623900/163254696-9456c29f-05f1-4fea-b511-c4d016077b19.mp4
> Multiple fixes related to the interface settings

- src/fheroes2/dialog/dialog_levelup.cpp
- src/fheroes2/heroes/heroes.cpp
Thanks to assertion in first place
> Fix call to get secondary skill name leading to a crash

- src/fheroes2/agg/agg.cpp
Also introduce caching mechanism to avoid extra I/O calls.
close #5267
> Fix failing music file search

- src/fheroes2/dialog/dialog_game_settings.cpp
These are relevant options for the dialog. This will be the way for any new option added into the game. A proper UI is mandatory to keep with the game's style.
> Add music control options to configuration dialog

- src/fheroes2/ai/ai.h
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_base.h
- src/fheroes2/heroes/heroes_spell.cpp
> Hero should be able to cast spells that consume movement points if he is able to move from his current tile

- src/fheroes2/gui/ui_font.cpp
Addresses issue https://github.com/ihhub/fheroes2/issues/5283.
> Fix French smallfont Cedilla ç

- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/gui/ui_dialog.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
> Fix rendering of the Arm of the Martyr's shadow

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_base.h
- src/fheroes2/world/world_pathfinding.cpp
Heroes are often running out of spell points especially in case of heavy Dimension door use. Also includes small pathfinding fix.
This won't affect early game.
> AI should replenish lost spell points more frequently

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
fix #5320
This method is somewhat slower, but absolutely accurate.
> Properly calculate the number of travel days to the destination tile for a hero

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/heroes/heroes_base.cpp
> Fix calculation of morale & luck modifiers for in-castle army without a commander

- src/engine/audio.cpp
- src/engine/core.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/maps/maps.cpp
Fix a few more code smells found by SonarCloud.
> Remove a few more semicolons from the end of macros

- src/CMakeLists.txt
- src/Makefile
Remove the `-Wdouble-promotion` for a while.
> Fix build with SDL 2.0.22 in strict mode

- src/fheroes2/campaign/campaign_scenariodata.cpp
fix #5214
Added all current possible secondary skills to futureproof it.
> Add Translation Context for Secondary Skill Campaign Bonuses

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/gui/ui_dialog.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
It's an assert problem so we're fixing it during loading the image only once.
> Use more efficient approach for rendering Arm of the Martyr

- src/fheroes2/heroes/heroes_spell.cpp
> Disable Town Portal dialog OK button by default

- src/engine/screen.cpp
SDL really doesn't work properly with resolutions so we have to do some hacky way like this.
close #5293
> Populate resolution list based till the lowest resolution

- files/lang/be.po
- files/lang/uk.po
- src/engine/translations.cpp
This adds empty PO files to these langauges and adds their plural forms to `translations.cpp`.
> Add Ukrainian and Belarusian languages

- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/gui/ui_text.cpp
- src/fheroes2/gui/ui_text.h
As per request to fix endless efforts to fit text within campaign UI.
> Add text truncation method

- src/engine/localevent.cpp
- src/engine/localevent.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_recrut.cpp
- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_hotkeys.h
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/gui/interface_list.h
- fix regression for SDL from #5356 where the application hangs on a startup
- add hotkey for map size selection
- reduce SDL dependency in localevent code (we shouldn't assign SDL key values directly to our enumeration entries)
- fix a bug when digital pad keys couldn't been used for entering numbers
> Redesign keyboard key handling

- src/fheroes2/world/world_pathfinding.cpp
> Add more conditions to define a blocking way AI hero

- fheroes2-vs2015.vcxproj
- fheroes2-vs2019.vcxproj
- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_hotkeys.cpp
- src/fheroes2/dialog/dialog_hotkeys.h
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_hotkeys.h
- src/fheroes2/gui/cursor.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
> Add HotKey window and expand the list of system options

- src/fheroes2/dialog/dialog_adventure.cpp
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_hotkeys.h
- src/fheroes2/game/game_startgame.cpp
- add missing hotkey for Adventure Options window
- add missing hotkeys for options within Adventure Options window
> Expand Hotkey usage on adventure map

- src/fheroes2/agg/agg_image.cpp
relates to #5163
Also fixed a possible issue with ICN::ARTIFACT. It should return true, not break.
> Fix Red Tower rendering with Rainbow

- src/fheroes2/gui/ui_campaign.cpp
To be even more user-friendly.
> Add window header for campaign awards and bonuses

- src/fheroes2/castle/castle.h
- src/fheroes2/castle/castle_well.cpp
Close #5243
Close #5236 
Text.h was removed from inclusions.
<details>
<summary>Picture </summary>
</details>
> Well MAX buy: add condition for not enough room, make recruitment happen in guest hero's army too, more text flexibility

- files/lang/uk.po
> Next batch of translation to Ukrainian

- CMakeLists.txt
- script/packaging/common/fheroes2.appdata.xml
Required for flatpak packaging.
> Extend CMakeLists.txt with icon, desktop-file and appdata.xml

- src/engine/translations.cpp
If a language doesn't have a translation then we shouldn't even show it in the list of languages.
> Do not show languages with empty translations

- src/fheroes2/heroes/heroes.cpp
We should proper images instead of some fillers.
> Fix incorrect hero icon in adventure interface

- src/fheroes2/dialog/dialog_quickinfo.cpp
> Fix dwelling popup window on adventure map

- src/fheroes2/agg/agg_image.cpp
> Add truncated shadow to Scenario Information window

- src/fheroes2/dialog/dialog_game_settings.cpp
> Show evil resolution icon for Evil interface

- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/highscores.cpp
- src/fheroes2/game/highscores.h
> Highlight latest highscore after completion scenario/campaign

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
The higher AI hero's role the higher need to have a better army and set of artifacts.
> Take into account AI hero's role during meeting

- src/fheroes2/game/game_interface.cpp
- src/fheroes2/system/settings.h
Before:
https://user-images.githubusercontent.com/32623900/171303319-4d897787-b796-4808-9d71-93d1aba5d7a1.mp4
Now:
https://user-images.githubusercontent.com/32623900/171303344-ef323246-aa0b-455a-87db-c483d920cfe1.mp4
> Fix the invalid behavior of "no interface" mode

- src/fheroes2/agg/m82.h
- src/fheroes2/game/game.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
The original game does use a sound with seagulls but we have an object with them so why not to use?
> Add sound for rocks in water

- files/lang/Makefile
- files/lang/uk.po
~~See also #5380 ~~
Other in https://github.com/burrbull/fheroes2/tree/uk3
> ukrainian translation (places)

- src/fheroes2/audio/audio_manager.cpp
relates to #5505
regression from #5504
> Fix a case when overall sound volume did not change sound effects

- src/fheroes2/audio/audio_manager.cpp
> Fix missing looping sounds after stopping mixer

- src/fheroes2/dialog/dialog_system_options.cpp
Regression after #5490
I removed this `Reset()` call in that PR and it turns out that it was in vain.
> Reset the interface when changing the UI theme, just redraw it is not enough

- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_interface.cpp
> Don't waste time playing the pre-battle sound if the game sounds are turned off

- src/fheroes2/agg/m82.cpp
- src/fheroes2/agg/m82.h
- src/fheroes2/agg/mus.cpp
- src/fheroes2/agg/mus.h
- src/fheroes2/agg/xmi.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/heroes/heroes_action.cpp
- add an environmental sound for Freeman's Foundry
- update sounds and music before a hero making an action
- update comments for unused sounds to track them in the future
- code cleanup for Music
> Update audio related logic

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/game/game_interface.cpp
- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/interface_icons.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
fix #5533
Also this PR fixes a ton of issues with `RadarUpdater` in the "no interface" mode. Currently in the `master` branch:
https://user-images.githubusercontent.com/32623900/173959820-e228ccf4-32f5-4f4f-a491-3e11cf73fca6.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/173959949-129aff8d-e0a9-4c61-84be-6b2cc67c5b86.mp4
---
Also this PR fixes an issue with "disappearing" focus [when hero casts a spell on the adventure map. Currently in the `master` branch (notice the lost focus in the icons panel and radar which position is failed to update):
https://user-images.githubusercontent.com/32623900/174280225-cdbc5ab5-532d-4bee-9d5e-7cc60ba5f5df.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/174280501-232761d3-dd8d-4f6b-ac31-46215d0dcae5.mp4
> Fix multiple issues with RadarUpdater from the quick info window

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_hotkeys.cpp
- src/fheroes2/dialog/dialog_marketplace.cpp
- src/fheroes2/dialog/dialog_resolution.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/gui/interface_cpanel.cpp
- src/fheroes2/gui/interface_cpanel.h
- src/fheroes2/gui/ui_scrollbar.h
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
In relation to the scrollbar slider.
> Fix typo: "silder" -> "slider"

- src/engine/audio.cpp
- src/engine/audio.h
I thought I had already done it, but it somehow got lost in the process of multiple rewrites.
> Add and update a few comments in the audio module

- src/fheroes2/dialog/dialog_levelup.cpp
> align hero button vertically

- src/fheroes2/maps/maps.h
- src/fheroes2/world/world_loadmap.cpp
> Respect the Ultimate Artifact's radius specified by the map creator

- src/fheroes2/gui/ui_dialog.cpp
> Fix displaying of negative resources in dialog

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/spell/spell.cpp
- src/fheroes2/spell/spell.h
Fixes #4227 .
AI is no longer stupid to use Adventure spells.
> Add individual Spell strategic value for AI

- files/lang/be.po
- files/lang/bg.po
- files/lang/cs.po
- files/lang/de.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/it.po
- files/lang/lt.po
- files/lang/nb.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ro.po
- files/lang/ru.po
- files/lang/sv.po
- files/lang/tr.po
- files/lang/uk.po
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/monster/monster_info.cpp
Even stating in the manual that it has 10% in reality this value is 20%.
Also fix some translation strings.
> Update Genie special ability
