ihhub/fheroes2

appveyor.yml, fheroes2.vcxproj
then we don't need zlib dynamic library for Windows
=> Remove SDL image usage as well make zlib as a part of application

src/fheroes2/army/army_bar.cpp
=> Fix number of monsters being displayed in black box

src/fheroes2/gui/interface_buttons.cpp, src/fheroes2/gui/interface_events.cpp
Disabled Continue Movement button for a hero which doesn't have chosen path. Resolves #107
=> Disabled Continue Movement button

src/fheroes2/agg/agg.cpp
Fixes #11 
Missing maps is already OK.
Error message is there, I don't know why it was disabled. Tested on Linux with SDL 1.2: an error window is displayed and dismissed with a click.
=> Display error window if no original data detected

src/fheroes2/kingdom/kingdom.cpp
Check array size before write it to avoid memory corruption
relates to #131
=> Unchecked array access leading to potential corruption

src/fheroes2/game/game_static.cpp
As I see it, issue #154 has two parts to it:
1. The view distance data for the observation tower is wrong. The value should be increased. I set it to 20, which might be wrong, but it definitely seems to be closer to the answer (see result below).
2. The formula that calculates whether to reveal a tile is incorrect. To reveal a circular area, as in the original game, the vector length should be used, instead of the sum of x and y distances, [here](https://github.com/ihhub/fheroes2/blob/81da835ba4f0403ae8c41c61cace46f69de8b6d2/src/fheroes2/maps/maps.cpp#L318).
This PR addresses the first point. Result:
=> fix: increase view distance for observation tower

src/fheroes2/maps/maps.cpp
As mentioned in PR #163 one of the problems in issue #154 is that the distance calculation is wrong. This PR fixes that. Result:
=> fix: use euclidean distance calculation for map reveal

src/fheroes2/dialog/dialog_armyinfo.cpp
In the original game font color is yellow, not white.
This fixes #152.
=> Fix font color for creature name

script/demo/demo_linux.sh
Linux filesystem is case-sensitive, so paths which worked for Windows
are unavailable for this OS.
=> Fix application execution after unpacking demo

src/fheroes2/gui/interface_buttons.cpp
Cast a Spell button on main screen must be disabled if castle is selected.
This fixes #147.
=> Disable cast a spell for castles

src/engine/surface.cpp, src/engine/surface.h, src/fheroes2/battle/battle_interface.cpp
Shadow which is used to highlight hexes available for unit to move is
displayed incorrectly - it doesn't use alpha channel and overwrites
vertical boundaries of hex.
This fixes #143.
=> Fix shadow for hexes in the battle

src/dist/Makefile, src/fheroes2/system/settings.cpp
Third part of the version used to be subversion revision; once the project moved to Git source control version it's no longer required.
This fixes #40.
=> Remove third component of app's version

src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_startgame.cpp, src/fheroes2/kingdom/kingdom_overview.cpp
Remove image artifacts while being in the castle
When hero's details dialog is opened from inside the castle, after exiting it interface buttons are drawn under the troops panel.
Similar problem is encountered if one opens hero's details dialog from heroes/castles statistics dialog.
This fixes #144.
=> Fix interface buttons in hero dialog

script/demo/demo.bat, script/windows/install_packages.bat
If running scripts by double click instead of manually opening cmd- On completion of installation and demo scripts, cmd closes automatically, preventing user from seeing the installation status(whether succeeded or failed at any step)
After the added instructions- both scripts at the completion looks like below screenshots-
=> make installation scripts readable at completion

src/fheroes2/gui/interface_status.cpp
Fixes #204 
Now it looks like this:
=> Make found resources message amount show below resource icon

src/fheroes2/gui/button.cpp, src/fheroes2/gui/button.h, src/fheroes2/heroes/heroes_dialog.cpp
- Added visibility for buttons
- set visibility to false for Dismiss button when in town, readonly or NONDISMISS mode
=> Remove Dismiss button for unhired hero in town

.travis.yml, appveyor.yml
Both `fheroes2.cfg` (default config) and `fheroes2.key` (default key bindings) must present in deploy package.
This closes #193.
=> Add configuration file into deployment packages

src/engine/surface.cpp
Set default alpha channel depth to 32 bit for SDL 2
relates to #176
=> Fix shadows in SDL 2

.travis.yml
There is not need to put SDL2 script for SDL1 build and vice versa
=> Do not put all scripts into deployed package

src/fheroes2/agg/agg.cpp, src/fheroes2/agg/sprite.cpp
Spellbook is shown in semi-transparent way on Windows build using SDL1.
This fixes #34.
=> Fix transparency for Spellbook

VisualStudio/Debug.props
`WITH_DEBUG` must be used for Windows debug builds. Also `_DEBUG` must
be set (it's used in TinyXML).
This fixes #239
=> Add WITH_DEBUG macro for debug builds on VS

src/engine/serialize.cpp, src/engine/tools.cpp, src/fheroes2/system/settings.cpp
- load empty configuration file
- load corrupted configuration file
Previous configuration file saving was incorrect because **StreamFile** adds
file size information at the beginning of the file causing a crash while
reading text from it.
relates to #255
=> Fix crash for configuration file cases

src/engine/localevent.cpp, src/engine/system.cpp, src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/kingdom/world_loadmap.cpp, src/fheroes2/maps/maps_fileinfo.cpp
This is alternative solution for #249, #250.
The reason game was crashed is that only basename of a file of the map was serialized to savegame file, and on read it was expected to be full path.
It makes sense to store path with dirname cause user can set additional paths to maps in `fheroes.cfg`.
Also, I commented here throwing Cancel exception if game's windows is closed during the game (`SDL_QUIT` event) - it crashes game instead of graceful exit, and prevents any leakdumper (e.g. Address Sanitizer) from dumping actual leaks. As a side effect, there can be freezes on exit in some rare cases, please report them if you find any.
=> Fix the crash on starting a new game after loading any save

src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/maps_objects.cpp, src/fheroes2/maps/mp2.h
Signs loaded from a map don't have a uid, so each one overwrote the old one in the `world.map_objects` map.
Using the map object index as uid solves this.
Note: I am not familiar enough with the engine to check for all possible side effects. From my quick play test I did not encounter any.
relates to #235
=> Fix signs not displaying any information

src/fheroes2/dialog/dialog_recrut.cpp
=> Fix MAX button state for monster change in recruitment window

src/fheroes2/dialog/dialog_selectfile.cpp
Implement the same logic as in the "new map" screen (add `selectOk` property).
=> Allow file selection by double-clicking a list entry (#337)

src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/heroes/heroes_dialog.cpp
Close window button cancel current dialog for castle and heroes. This fixes https://github.com/ihhub/fheroes2/issues/321
=> Cancel dialog by close windows button (#321)

src/fheroes2/game/game_interface.h, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_events.cpp
Fixes ihhub#335
Verified by pressing `n` in-game and confirming the _New Game_ dialog appears. Works the same as opening File Options and pressing the _New Game_ button.
=> Add hotkey N to start a new game

src/fheroes2/battle/battle_army.cpp
The FIXME is misleading as surrendering with 3 Titans does cost 7500 gold, which is the same as the original.
_Surrendering with 3 Titans in FHeroes2_
_Surrendering with 3 Titans in HoMM2_
Closes ihhub#127.
=> Remove FIXME

src/fheroes2/dialog/dialog_recrut.cpp
Yes I read CONTRIBUTING.md, but I can't resist offering an case insensitive access on *nix systems. You have an script/demo/demo_linux.sh that will dl zip, after extraction data directory named by default as "DATA" and need to rename it manually. Please accept the patch, because different HOMM2 distributives have different naming and manual renaming on *nix is a time wasting.
Fixes: #424
=> Recruit Creature Info window has an incorrect position in higher than default resolution

src/fheroes2/battle/battle_interface.cpp
This is a straightforward fix for #216, tested in both branches.
=> Flying movement animation is shifted during battle

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/heroes/heroes.cpp
The previous ratios were ridiculous; I've set it to original formulas. Fixes #236  and fixes #221 
Now luck can trigger on both double attacks and isn't disabled by the bless.
=> Fix morale and luck events

src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/battle/battle_only.cpp, src/fheroes2/dialog/dialog_recrut.cpp, src/fheroes2/dialog/dialog_selectcount.cpp
Currently it was impossible to enter a number starting from anything else than 1. Since `PressIntKey` handles only one keystroke validation should be done outside. Plus fixed a title string on BattleOnly screen.
=> GUI: Fix value input selectors

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_troop.cpp
Self-explanatory title; fixing chance and the effect of special ability. Important to use it before any damage is applied.
Correct chance is pulled from HEROES2W file, it's checking for Genies at 0x04806CC.
=> Battle logic: fix Genie special ability

src/fheroes2/battle/battle_arena.cpp, src/fheroes2/game/game_loadgame.cpp
Fixes #433 
Fixes #435 
Checked OG to make sure it behaves the same.
=> Music: Loop battle music and switch to main tune when loading

src/fheroes2/castle/castle_mageguild.cpp, src/fheroes2/spell/spell_book.cpp
Fixes #538 . A bit of pixel pushing here, the core of the problem is that every spell sprite is not centered.
Also fixed spellbook sorting crash which happened if there's adventure spell with name (i.e. Set Water Guardian) previous to the combat spell (i.e. Steelskin).
=> Fix spell sorting crash and mage guild positioning

src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/dialog/dialog_system.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_delays.cpp
Fixes #518 
Refactored a bunch of old code, including BlitSpeed adjustment. I tested in different configs with resulting blit speeds from 5 to 20, however when timing battle rounds in battle_interface.cpp I still seen pretty consistent numbers for each animation. Our event loop will eat those tiny render delays, because of the way it is structured.
Actually this speed adjustment was the reason why animation speed varied so much between SDL1 and SDL2 versions; this annoyed me for while.
=> Fix hero movement at low speeds

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/gui/interface_status.cpp
Fixes #203 
1. Army in status window (using OG values and text to the side rather than under the icon).
2. Castle window update: shifted top part and re-aligned the troops. Amount of information depend on thief guild level rather than Scouting skill - we can do it later.
3. Hero window rework: hide stats for enemy heroes and align the army accordingly.
=> Fix hero, castle and status army info

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_armyinfo.cpp
relates to #562
and also fix shooter's spell icons offset
=> Show reflected monster animation in a dialog

src/engine/display.cpp
=> Do not shift window while loading a map for SDL 2

src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_interface.cpp
Reminder to myself: code after `||` won't be executed.
Fixes #606 .
=> Fix idling condition check

src/fheroes2/game/game_delays.cpp, src/fheroes2/system/gamedefs.h
Avoid linear scaling for time delays. Converted adjustment to 16% per setting, now it becomes:
Speed 1 = 150%
Speed 4 = 100% (OG Normal)
Speed 6 = 66% (OG Fast)
Speed 8 = 33% (OG Very Fast)
Speed 10 = 0%
Fixes #560
=> Battle speed adjustment formula

src/fheroes2/battle/battle_interface.cpp
relates to #261
relates to #534 
Before we had like this (many monster have overlapped window);
After the fix:
=> Fix monster count window position during battle

src/fheroes2/battle/battle_interface.cpp
relates to #640
Spells are: Teleport, Summon Elemental (any), Mirror Image, Blood Lust, Disrupting Ray
=> Fix multiple spell frame jumps

src/engine/surface.cpp, src/engine/surface.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/game/game_delays.cpp
Fixes #645. 
Ripple function is very magical. We should reuse it later: teleport effect uses similar logic.
=> Fix ray spells: ripple effect for disrupting ray and correct drawing

src/fheroes2/battle/battle_interface.cpp
Fixes #636.
Waiting for sound sample before going to the next step. Applied to both luck animations as well as teleport spell. Also fixed alpha and removed troop count on a teleport.
The only problem here is that the sound obviously doesn't scale with the game speed and on higher settings player has to wait a considerate time. On lower settings it's perfect.
=> Fix teleport and luck animation

src/fheroes2/battle/battle_action.cpp
Happened during AI turn - mass spell was used which Dwarves resisted, invalidating the iterator.
=> Fix crash when unit resists a spell

src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_icons.cpp, src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/kingdom/kingdom_overview.cpp
Easy to reproduce: select a castle instead of the hero and then right click other heroes to view the Quickinfo dialog.
=> Fix hero quick info crash

src/fheroes2/battle/battle_interface.cpp
A monster does not move during teleportation
=> Fix monster sprite shift teleport spell

src/engine/tools.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_catapult.cpp, src/fheroes2/battle/battle_catapult.h
Fixes #747 . Fixes #728 . Fixes #739 
Corrected missile angle when Y distance is 0. 
Corrected ballistics skill effect to replace assumptions with real values.
Corrected tower shooting order/renamed a def to avoid confusion.
Removed artifact effect stacking.
=> Castle siege logic fixes

src/fheroes2/ai/simple/ai_simple_battle.cpp, src/fheroes2/battle/battle_board.cpp
Fix battle A star pathfinding crash when AI is moving wide units.
Fix target selection to avoid unnecessary moves.
=> Simple AI battle pathfinding

src/fheroes2/gui/cursor.cpp, src/fheroes2/gui/cursor.h
Fixes #365. Fixes #802.
Updating correct cursor offsets and applying it immediately after sprite switch.
=> Fix cursor offsets

src/fheroes2/maps/maps_tiles.cpp
Fixes #869 .
Self-explanatory fix, adding missing object indexes to tiles affected by cycling.
=> Missing lava animation in volcanoes

src/engine/display.cpp, src/engine/display.h, src/engine/localevent.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/gui/cursor.cpp, src/fheroes2/gui/cursor.h
relates to #427
After detailed investigation of the problem there are multiple observations:
- the slowdown happens when we refresh screen too fast. The current implementation refreshes screen on the event of mouse move, method `void Cursor::Move( s32 x, s32 y )`. Even if we move the mouse a little we still refresh the whole screen
- after applying most of changes from #515 we still faced a problem of slow response of the main screen due to a fact that screen refresh time now doesn't depend on mouse movement. The problem was related to a problem that we don't call **Flip()** method of Display class.
- we don't update screen if we don't explicitly draw anything. I added a simple implementation to forcefully update the screen in such case every 0.5 second
Hi @shprotru and @idshibanov , I …
=> Fix display drawing during mouse movement in SDL 2

src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game_interface.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/gui/interface_gamearea.h, src/fheroes2/gui/interface_radar.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/kingdom/puzzle.cpp, src/fheroes2/maps/maps_tiles.cpp
- fixed World Map display on huge resolutions. We do not allow to scroll
if there is nothing to scroll
- fixed Dimension Door area for 4K (relates to #893 )
- fixed hero centering (relates to #727 )
- fixed screen jumping for hero's movement (relates to #797)
- fixed pop-up dialog area for no-interface case
- fixed Ultimate Artifact generation on huge resolutions
- fixed missing drawing during scrolling for World Map (relates to #779)
=> Fix World Map drawings and screen jumping during hero movement

src/fheroes2/agg/agg.cpp, src/fheroes2/agg/agg.h, src/fheroes2/agg/pal.cpp, src/fheroes2/agg/pal.h, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/game/game_interface.h, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_focus.cpp, src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/gui/interface_gamearea.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
Another chapter of our color cycling adventure. Monsters on the map and army in status window now are being animated. Also added a faster `AGG::ReplaceColor` method that we should prefer to use.
In addition added a few standing frames to monster's animation cycle to avoid them fidgeting too much. Related to #744 . I don't want to double the animation delay because it looks smoother right now.
=> Monsters strategic map animation

src/engine/display.cpp, src/engine/display.h
Recently Display.Flip() became our biggest bottleneck, slowing down the rest of the game. This is very noticeable when setting hero and AI speed to 9 or 10: you would not see a real speed up because of the amount of flipping. `SDL_CreateTextureFromSurface` is a very expensive call that we should avoid.
Idea here is simple: instead of building a new texture every time we'll overwrite existing one. I finally see comparable hero speed to pre cycling/smooth animation change.
Example of the difference between two calls:
=> Reuse SDL2 texture for display flip

src/engine/display.cpp
don't allow random resolutions
relates to #919 and #921 
also relates to #887
=> Fit the screen to closest resolution in SDL 2

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/heroes/route_pathfind.cpp, src/fheroes2/maps/ground.cpp, src/fheroes2/maps/ground.h, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps_tiles.cpp
Fixes #880 . Fixes #979 .
Fixed diagonal move cost and updated pathfinding heuristic accordingly. Updated road logic/directions so it would recognize them correctly. Updated the path display to show actual move cost, not the one based on terrain.
There's still bugs with impassibility rules over object corners that will be addressed separately. A lot of the logic there is arbitrary as usual.
=> Pathfinding fixes: roads, move cost and display

src/fheroes2/battle/battle_animation.cpp, src/fheroes2/battle/battle_animation.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h
Fixes #884 .
Corrected general position (both X and Y) applying offsets from original FRM BIN data files. Added additional check if there's unit in front and adjusting x offset accordingly.
=> Fix troop counter position

src/fheroes2/agg/agg.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/kingdom/world_loadmap.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/mp2.h
Fixes #742.
1. Fixed random castle sprites initialization when map is loaded, fool-proofed it from overlap.
2. Found new bug and fixed town to castle upgrade when it is built. This had the same effect as in original bug.
3. Fixed existing shadows bug when it would flicker as hero is moving over it.
4. Corrected shadow sprites (it reused Warlock as default).
Example of bug no.2:
Screenshot of "after":
=> Fix castle initialization, shadows and drawing

src/fheroes2/battle/battle.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h
Fixes #792. Fixes #1006 .
- Moved `PostKilledAction` call from `ApplyDamage` to when animations are done.
- Added custom drawing call for fading mirror images.
- Added custom alpha field to every unit that will be used for drawing.
- Removed b_current_alpha global variable and cleaned up the overall logic.
=> Update death logic and animations

src/fheroes2/battle/battle_interface.cpp
Fixes #1044 .
Evened out amount of frames for blur fade in/fade out.
Set overall spell duration to 3000ms (adjusted by battle speed) to match original.
@Branikolog Test to see if you like how it looks.
=> Adjust holy shout delay and alpha mask

src/fheroes2/gui/cursor.cpp
Fixes #1034 .
This creates perception that battle interface "active areas" are shifted when actually it was a mouse cursor issue.
=> Fix battle pointer cursor offset

src/fheroes2/battle/battle_dialogs.cpp
Fixes #1099.
Dialog sprite included big shadow on the left that was throwing off alignment calculations. After adjustment:
=> Adjust hero battle dialog to align text

src/fheroes2/castle/castle_dialog.cpp
Fixes #984 .
Wanted a cleaner solution, but it wasn't possible without major refactor of the castle dialog. Removed unused QVGA code snippet as well.
=> Add boat building animation

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
Fixes #936 . Fixes #812 .
There's two ICN files with monster sprites: MONS32 (full one, for UI) and MINIMON (with animation, split in two parts). Wrong sprite cause animation shift because offsets are different.
=> Fix map monster attack and fade animation

src/fheroes2/gui/interface_gamearea.cpp
Caught the oversight causing object remove animation to jump. Test by hero picking up something.
=> Fix regression introduced in #1106

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/kingdom/world.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/maps_tiles_quantity.cpp
Fixes #1007 .
1. Fixed major logic flaw for teleporters - hero would exit at any type of teleporter.
2. Fixed another logic bug - if allied hero blocked the exit hero would still move over.
3. Fade in/fade out and screen centering animation for teleporters, whirlpool and boats.
=> AI hero fade animations

src/fheroes2/battle/battle_arena.cpp
Infinite loop (not crash, but almost) is created when AI's dead unit gets a morale event. Checking if unit is valid before pushing second battle action.
=> Fix infinite morale bug

src/fheroes2/ai/ai_hero_action.cpp
Fixes #1051 .
Resume the music at the end of AI hero action in case local battle (involving player) happened. `AGG::PlayMusic` call will check if it's already playing and return.
=> Resume AI music after battle that was shown

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp
Fix for #1053 
In current version when hero step in teleport/whirlpool we have 2 additional movepoint penalties
```
hero.ApplyPenaltyMovement() (WHY???)
hero.Move2Dest() (move hero to location)
```
Not found any functions for **just** move hero to specific location and don't use ```hero.Move2Dest()```
So fastest way is just add additional move points as compensation for ```hero.Move2Dest()```
=> Remove move penalty for visiting whirlpool/teleport

src/fheroes2/battle/battle_interface.cpp
=> Don't show start and end position for monster log movement

src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/heroes/heroes.cpp
Fixes #1198 .
Three bugs here, two are regressions.
1. AI hero losing a battle but penalty still applies resulting in nullptr crash
2. Dead units not removed from the battlefield during AI battle causing infinite battle
3. Wide unit is asked to path to impossible position, resulting in a crash
=> Fix AI turn crash and battle board cleanup

src/fheroes2/maps/maps_tiles.cpp
`isPassable()` call regression not caught in the recent refactoring.
=> Fix ultimate artifact regression

src/fheroes2/battle/battle_troop.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
These options will be removed completely:
- game: also confirm autosave
- battle: archmage can resists (20%) bad spells
- battle: magical creature resists (20%) the same magic
These options will be removed from configuration page:
- game: battle show grid
- game: battle mouse shadow
- game: battle move shadow
=> Remove some redundant / useless config options

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/castle/castle_well.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
- remove "heroes: after battle move to target cell" option
- make "castle: allow buy from well" always on (practically cannot turn off). This option doesn't change anything but makes an extra addition to the game
=> Update configuration options

src/fheroes2/battle/battle_dialogs.cpp
closes #1568 
Added dot at the end of text sentence in "Cast Spell" Info Window.
=> Add dot at end in Cast Spell Info Window

src/tools/icn2img.cpp
Building with option WITH_TOOLS=1 is failed with error:
icn2img.cpp:172:24: error: ‘ColorBlack’ was not declared in this scope
This change fix it.
=> fix building tools

src/fheroes2/heroes/heroes.cpp, src/fheroes2/world/world_pathfinding.cpp
Fixes #1647 . If stack of monsters was spawned nearby a hero his path could lock up in invalid state.
=> Validate and fix the path if hero was stuck

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/battle/battle_pathfinding.h
Added strength - distance ratio (inspired by OG logic) to make sure they don't target only the strongest unit.
Added logic handling AI attacking castles.
Updated decision tree to avoid going over target selection twice.
Additional fixes for battle arena pathfinder (mostly for flying units).
=> Combat AI: improve target selection

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/gui/interface_gamearea.h, src/fheroes2/kingdom/puzzle.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/world/world_loadmap.cpp
Fixes #145 . Fixes #1523 . Fixes #1524 . Fixes #1526 . Fixes #1537 . Fixes #1818 .
Might be fixing #1536 as well, that issue is defined very vaguely.
- Fixed the puzzle map draw, including offset for the center marker.
- Now ignoring selected objects for the puzzle based on data from original game (offset 0x004F0B50)
- Fixed the ultimate artifact position selection.
- Switch the palette used from BROWN to TAN.
- Draw puzzle after map editor object is removed.
- Minor refactor of tile check code.
=> Fix puzzle and ultimate artifact logic

src/fheroes2/maps/maps.cpp
Fixes #1815 .
Ignore protection rules for pickup objects if you can reach them (because you don't move onto that tile when pathing).
=> Fix tile protection for pickup objects

src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
Fixes #1635 . Fixes #1288 .
Fixed random castle shadows when new scenario started.
Fixed town to castle upgrade shadows. Works only on new saves because data is already corrupted on the old ones.
Lowered draw priority on roads/rivers so shadows will be put over it.
=> Fix castle shadows and shadow draw priority

src/fheroes2/kingdom/kingdom.cpp
Related to #1526 .
Reset puzzle bitset when Kingdom is cleared (new game, game re-loaded, etc).
=> Reset puzzle between games

src/fheroes2/maps/maps_tiles_quantity.cpp
Currently when hero hops into boat added in map editor and sails away game leaves a tiny sprite behind. We have to clean it up on map load.
=> Remove map editor boat sprite on map load

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/army/army.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
Fixes #1012 .
Removing "world: save count monster after battle" option from the config. Making sure it saves the armies by default.
=> Save neutral army after battle

src/fheroes2/system/settings.cpp
Existing debug options aren't very useful, a lot of ENGINE logging at the time when engine code is solid.
GAME flags are for in adventure mode events including castle building and map data.
BATTLE for battle arena and all most things that happen during combat.
AI for decisions made during computer's turn (including battles).
Running through new debug options (in fheroes2.cfg file):
- 0-2: Warning/Info/Trace for everything.
- 3: In case you _have to_ debug the engine.
- 4: Standard debugging config without excessive logging.
- 5-7: Tracing Game/AI/Battle individually.
- 8-11: Same tracing options, but with special DBG_DEVEL mode that unlocks extra tools.
If you want to watch AI fight each other use "debug = 7" for example.
=> Update debug option selection

src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Happens when if player has only towns without castle upgrade (can't buy hero there).
=> Fix AI hero recruit crash

src/fheroes2/heroes/skill.cpp
"Your knowledge determines how many spell points your hero may have. Under normal cir[c]umstances..."
=> Fix typo in description of "Knowledge" skill at hero screen

src/fheroes2/resource/artifact.cpp
Making sure Anduran artifacts won't be rolled randomly in regular scenarios. Some artifacts are locked to be campaign only.
=> Fix price of loyalty artifact selection

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/game/game_delays.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_move.cpp
- make the animation smooth without jumps
- reduce screen offset after visiting objects from 4 pixels to 1 pixel
(relates to #885)
- add animation of boarding boat and offboarding it (relates to #1186)
- make AI slightly faster when they board or unboard ships under fog
=> Fix heroes movement animation

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_castle.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/army/army.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp
Adjusted sailing logic to prevent heroes landing back on the same spot.
AI can now buy boats for themselves.
Also adjusted heuristics to make sure AI plays a bit safer.
Finally I can make use of my world region algorithm.
=> Strategic AI: better heuristics and boat handling

src/fheroes2/maps/maps_tiles_quantity.cpp
Forgot to change the most significant line cause units to double every week...
Also fixed the base count for genies in a lamp.
=> Fix monster dwelling unit count

src/fheroes2/gui/interface_gamearea.cpp
Objects were drawn in a wrong loop after a recent fix for another issue (shadows).
=> Fix the clipped boat sprite

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_board.cpp
Fix an error in GetAdjacentEnemies that prevented archers finding a unit that was blocking them for melee retaliation.
Also added extra validation to spell selection function to avoid log spamming.
=> Battle AI: fix target adjacency

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h, src/fheroes2/world/world_pathfinding.cpp
Bug caused edge cases where you couldn't move on a summoned boat without re-selecting hero.
Any map change should use `Tiles::SetObject` function.
=> Reset pathfinder cache on a map change

src/Makefile.bsd, src/engine/tools.cpp
1. FreeBSD: both base iconv and libiconv follow POSIX prototype
Fix build on FreeBSD requiring the same const_cast as on other platforms.
Base iconv removed the const qualifier back in 2015.
For the record: https://github.com/freebsd/freebsd/commit/b0813ee288f64f677a2cebf7815754b027a8215b
2.  FreeBSD: fix build with both base iconv and libiconv present
Include path most likely contains LOCALBASE, and that will make us
pick up the /usr/local/include/iconv.h, which requires linking
against libiconv (as compared to base iconv being in libc).
Force /usr/include/iconv.h inclusion explicitly if it's present to
fix the build.  The other choice is to always link against libiconv
as it will most likely be already installed due to other dependencies,
but linking against the base one if we can just …
=> FreeBSD: iconv build fixes

src/fheroes2/heroes/heroes_spell.cpp
only for non-movement spells
relates to #659
=> Allow to cast a spell with no move points

src/fheroes2/battle/battle_interface.cpp
relates to #1369
followup of #1963
=> Use 1 instead of 'one' in battle log

src/fheroes2/ai/normal/ai_normal_battle.cpp
Happens when AI's enemy has shooters mainly army. Matters especially during castle sieges, should help to reduce the casualties.
=> Battle AI: make it more agressive when dealing with archers

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/castle/castle.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/heroes/route.cpp, src/fheroes2/heroes/route.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h
Fixes #1946 .
Fix regression that broke path building on non-debug builds.
Teach AI to collect/capture multiple objects on the same move.
Adjust heuristics to make sure AI doesn't miss important objects.
Optimize common Army functions that slowed down the calculations.
Fixed a bug where AI was able to buy boats in a castle without shipyard.
=> Strategic AI: fix hero paths

src/fheroes2/battle/battle_main.cpp
In cases as described in #1859 map data can become corrupted and invalid armies appear on the map.
Handling these before the battle screen loads. Also fixed the outcome of such event (making sure that attacking hero won't retreat and lose his army).
=> Check armies for validity before starting the battle

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/castle/castle.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h, src/fheroes2/game/game_static.cpp, src/fheroes2/game/game_static.h, src/fheroes2/heroes/heroes.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/maps/maps.cpp
Fixes #657 .
Moved difficulty-related code into the same namespace.
Added missing bonuses to the appropriate calculations and corrected the existing logic.
Also added an important fix to the AI scouting logic.
=> Use original difficulty bonuses for the game

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp
Allow AI player to start its move with an Action (to teleport for example).
Add a safeguard for similar future issues that would show the warning and end turn.
=> Fix potential infinite loop when AI is stuck on teleporters

src/fheroes2/heroes/heroes.cpp
Fixes #1955 .
GetObject without false returns hero instead of actual object hero is standing at.
=> All parts of wide objects have to be flagged as visited

src/fheroes2/maps/maps_tiles.cpp
Missed this when was implementing #2030 . Without this fallback boats will be invisible (on older savegames) before they are used.
=> Fix boat sprite on older saves

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_static.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/world/world.cpp
To fix https://github.com/ihhub/fheroes2/issues/132
Is this what's required or should it be like the other structures as `scoute = 2` ?
=> fix(world): lighthouse doesn't reveal additional squares

src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/maps_tiles.cpp
Fixes #2072 .
Should stop the unknown monsters appearing on the map. Wasn't cleared properly when fighting adjacent units.
=> Fix adjacent monsters when removing one

src/fheroes2/gui/interface_gamearea.cpp
=> Fix pass image position on the world map

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/maps/maps_tiles.cpp
Fix #1311 . Fix #1349 .
Boats before (notice how hero boat is basically swimming on land):
Boats after:
=> Fix boat and hero position

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/castle/castle.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
Fixes #2073 . Fixes #1313 . Fixes #1312 .
Removed useless game option "battle: merge armies for hero from castle". Armies merge should work by default now.
Added two enhancements: game will try to avoid merging unit stacks if there's free room and will try to keep original troop positions as long as possible.
`JoinStrongest` is used when any castle is attacked (to merge defending armies if there's a guest hero) and by AI when merging or reinforcing armies.
=> Army merge logic improvement

src/fheroes2/battle/battle_only.cpp
Two issues:
1. Human/AI switch wasn't displaying the current state although control was switched.
2. Setting custom army for second hero should work (applied when you start the battle).
=> Fix battle only mode

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/mp2.cpp
Fixes #1387 . Fixes #1517 .
Select correct image/sprite index.
Show animations when hero is standing on the mine.
=> Fix mine guardians sprites

src/Makefile.mingw, src/engine/tools.cpp
Tested on MinGW64/MSYS2 with both SDL and SDL2 targets.
There is no shell icon, window icon displays just fine.
WSock32 requirement untested, since I never tested network (nor do I know if it's implemented).
Never managed to build with Audio CD support, so that's also commented out.
=> Fixes for MinGW Build

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/heroes/route.cpp, src/fheroes2/heroes/route.h, src/fheroes2/world/world_pathfinding.cpp
Do not show teleport animation when AI hasn't reached the intended destination.
Updated Route::Step struct to include additional info, added line for saves compatibility.
=> Do not show teleport animation in some AI cases

src/fheroes2/ai/normal/ai_normal_hero.cpp
When AI hero is evaluating potential tasks value will be lost more rapidly further the map object is (`n log n` scale). This is needed to make sure heroes won't rush after something of moderate importance to return back and pick up less valuable objects.
Priority = value - ( distance * log( distance ))
Also includes a small fix to Patrol hero orders.
=> AI: apply logarithmic growth to distance scaling

src/fheroes2/battle/battle_action.cpp
Fixes #2071.
I think the check was forced previously because animations weren't done properly. FRM data will have walking frames too.
=> Fix slowed flying creature movemnt

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_castle.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h, src/fheroes2/world/world_loadmap.cpp, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_regions.cpp, src/fheroes2/world/world_regions.h
Overall improvements based on feedback and recent testing. Follow-up on #2108 .
- Optimize threat distance calculations. AI turns are twice as fast on average.
- Track map region stats for better decision-making (especially coast landing from boats).
- Improved castle build order (priority on gold income buildings).
- Recruit heroes in castles other than the first one in the list.
- Skip teleports if every exit was already explored.
- Protect high value (based on buildings built) castles first.
- Another round of adjustments to hero object values, heroes are scared of strong enemy armies.
- Move battle-related debugging logs from AI to BATTLE mode.
- Minor refactor of World post load logic (split into two parts: ProcessNewMap and PostLoad).
=> Strategic AI: general improvements

src/fheroes2/objects/objdsrt.cpp, src/fheroes2/objects/objlava.cpp, src/fheroes2/objects/objmult.cpp, src/fheroes2/objects/objwatr.cpp, src/fheroes2/objects/objxloc.cpp
Relates #2162.
This checks are for avoiding old gcc bug. And gcc 4.4 is pre-c++11 compiler.
=> remove obsolete __GNUC__ checks

src/fheroes2/battle/battle_only.cpp, src/fheroes2/dialog/dialog_guardian.cpp, src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/heroes/heroes_indicator.cpp, src/fheroes2/heroes/heroes_indicator.h, src/fheroes2/heroes/heroes_meeting.cpp
I used battle only mode very frequently for testing.
Morale and luck indicators have image restorer that was overwriting whole display. This caused cases when UI seemed unresponsive (i.e. you change a hero and it still shows the default one).
=> Fix portraits/hero information display in battle only mode

src/fheroes2/castle/castle.cpp
Fix for #454 
Update hero availability pool after hero purchase, otherwise the list will be the same until you open castle menu again
=> Update hero availability pool after hero purchase

src/fheroes2/game/game.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_io.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_scenarioinfo.cpp
Fixed small typo on map loading screen.
Perhaps someone has missed adding an apostrophe. Like "map's". But generally, it shouldn't also be shorted.
=> Fix map loading typo

script/windows/install_packages.bat, script/windows/setup_packages.bat
Upgrade SDL2 to 2.0.12 for Windows platform. No issues during compilation. Requires manual remove of previous SDL files. No in game issues found so far.
=> #1084 Upgrade SDL2 to 2.0.12 for Windows platform

src/fheroes2/castle/captain.cpp, src/fheroes2/kingdom/kingdom_overview.cpp
_Captain portraits appear after change_
_No captain portraits even when Captain present before_
_Hero portrait takes precedent_
_No portrait when there is no captain and no hero_
Fixes #1848
=> Add captain portraits in Kingdom Overview

src/engine/audio_mixer.cpp
Hello! 
This is a fix for #756. As suggested, `Mixer::isPlaying` returns 0 if music is disabled
=> Mixer::isPlaying returns false if music is disabled

src/fheroes2/heroes/heroes.cpp
#2185 
This pull request solves an issue that occurs when the player does not enough gold to buy the magic book. As shown in the before/after below, the graphic of the magic book will now be included on the popup window. 
**Before**
**After**
=> Added magic book sprite to popup window #2185

src/fheroes2/agg/agg.cpp, src/fheroes2/army/army.cpp
relates to #1335
Archimage, Ranger, Veteran Pikeman, Master Swordsman and Champion are corrected
These images before and after correction:
=> Correct few sprites of mini-monsters

src/fheroes2/army/army.cpp, src/fheroes2/battle/battle_army.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/heroes/heroes.cpp
Without this, a full copy of castle instance is made at every call
to GetGuest() and GetGuard()
Also, the copy done is incorrect, as the copy contains incorrect fields
=> Fix lambda capture in AllHeroes

src/fheroes2/army/army.h
I delete the methods that are otherwise auto-generated by the compiler
and that would be buggy. This should also remove some sonar warnings
=> Prevent auto-generation of buggy methods in army.h

src/fheroes2/heroes/direction.cpp, src/fheroes2/heroes/direction.h, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/world/world_pathfinding.cpp
This avoids a full allocation/copy each time this method is called.
NB : I do'nt know why this method is needed, it can be refactored
so clients don't need a full vector<direction> to access all directions
=> Directions::All now return a reference

src/fheroes2/army/army_bar.cpp
Solves #1289
Implemented logics:
- Allow splitting to another troop of the same stack via right click and mouse drag (cursor)
- Minor adjustment to mouse drag logic so that the dragging doesn't have to start from an empty troop
=> Adjustments to mouse-based splitting

src/fheroes2/army/army_bar.cpp
Solves #2368
What this PR does
- Merge, and not try to split units when clicking a troop with the same as the selected unit
- Do NOT attempt to split the unit when selecting a unit and then clicking on an empty troop slot.
- It's still possible to split a unit by clicking the LMB on a unit and then dragging it to an empty troop slot
=> revert mouse drag logic in mouse split logic adjustment PR

src/fheroes2/army/army.cpp
Fixes #1693
Fixes #1265
I generated a lot of starting heroes in the original game and I think I've determined the starting unit quantity formula.
You get 0.8 to 1.2 times the growth rate for tier one units, and 0.4 to 0.6 times the growth rate for tier two units. 10% of the time you get no tier two units. Peasants are an exception, you get an additional +30 modifier to the starting number of peasants.
=> Fix starting unit values

src/fheroes2/resource/artifact.cpp
Original Issue - #1686
This change simply changes the info bar text on the hero screen when hovering over the magic book from "Open Book" to "View Spells". 
**Before:**
**After:**
=> Hero Screen, updated info bar text at bottom of screen when hovering over magic book.

src/fheroes2/dialog/dialog_selectcount.cpp
Solves #278
Tested on 640 x 480, 800 x 600 and 1280 x 720 and all of them seems to be consistent with each other. But note that the dialog position is also moved for other situations which are
- Splitting inside a single hero's screen
- Splitting inside a hero meeting
Example images:
These are the results for the new dialog position in a castle.
Inside a hero screen
Inside a hero meeting screen
@Branikolog Can you check whether this one is positioned good enough for all cases? Thanks in advance!
=> Adjust troop separation dialog position

src/engine/image.cpp, src/engine/image.h
We are reducing the amount of memory allocations and deallocations by 2
holding both image layers in 1 array. This also gives a better chance of
data caching which potentially lead to faster execution.
=> Reduce the amount of memory operations for Image class

src/engine/system.cpp
I found this while porting the game to Nintendo Switch platform, but decided to submit this separately as it's not specific to Switch. If you prefer, I can add Switch-specific changes to the same PR.
=> Add error handling to SDL_GetPrefPath

VisualStudio/common.props, fheroes2.vcxproj, src/fheroes2/campaign/campaign_data.cpp, src/fheroes2/campaign/campaign_data.h, src/fheroes2/dialog/dialog_file.cpp, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/game/fheroes2.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/game/game_io.h, src/fheroes2/game/game_loadgame.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
Solves #323 
So far the actual saving and loading seems alright for standard and campaign maps. However, I haven't saved the extra things needed for campaign maps.
@ihhub @idshibanov Any pointers on what to save? I think it should the player's hero data so maybe one of the `heroes` stream operators?
=> Differentiate save files based on game type

src/fheroes2/dialog/dialog_selectfile.cpp
Fixes a bug that appears upon merging the campaign PR - When saving, the default save file name no longer appears if a save with the same name does not exist.
Thanks @dimag0g for the info
=> Fix default save file name not appearing

src/engine/localevent.cpp, src/engine/localevent.h
- CLICK_LEFT and others are used to detect click events
- for a click event, the code checks that we have both CLICK_LEFT and not
MOUSE_PRESSED (to activate on mouse release)
- However CLICK_LEFT was never reset at each frame, so CLICK_LEFT event
is activated forever until it is consumed
- with this commit we reset CLICK_LEFT flag at each frame, and set it
up correctly in the event logic
1) either when there is a mouse pressed event (already there)
2) on the frame where there is a mouse release event
=> Fix logic in mouse button press

src/fheroes2/heroes/heroes_indicator.cpp
=> Correct size for spell point and experience point zone in hero window

sonar-project.properties
it is not a part of our project
=> Exclude third-party code from SonarCloud analysis

src/fheroes2/ai/ai_hero_action.cpp
With this, the window doesn't jump around when it turn for the next player
because it will already be centered on the latest hero
Fix for #2507
=> After AI loses to either castle or other player, center the view on them

src/engine/localevent.cpp
Max position of emulated cursor should be `display.width() - 1` and `display.height() - 1`
=> Fix controller cursor max position

src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Related to #2158.
During turn prep it considered coast a valid object, so tiles became "non-empty" islands for AI.
=> AI: avoid disembarking on empty tiles

src/engine/pathfinding.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/battle/battle_pathfinding.h, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h
Fixes #2576 .
Patrol distance comparison was flawed, so AI perceived targets behind teleporter as "closer".
Also includes a fix to avoid hero in patrol mode leaving intended position.
=> AI: fix path selection for hero in patrol

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h
Here's a refactor of quick dialog info: now we have separated variables for scouting level for a given tile, and option settings etc. Previously all was merged into a "scoute" int which caused lots of complicated code
This fixes the following:
- bug where hero with scouting can see army size number even with "extended scouting" option off
- same bug with guarded mines
- #1460
- #1459
=> Fix scouting bugs + make crystal ball work

src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
As byproduct the penalty information shown for all empty terrain tiles, not only neighborgoud tiles for currently selected hero.
See #2575
=> Add a separate option for displaying terrain penalty.

src/fheroes2/resource/artifact.cpp
Fixes #2465
Grammar correction. When transcribing a spell scroll, the hero is now prompted with "Cost of spell points:" rather than "Cost of spell point:"
=> Fix Transcribe Spell text

src/fheroes2/army/army_bar.cpp
Solves #2392
Current logic
- Fixed right click split regression (at the risk of introducing a coding antipattern)
- When selecting a stack with 1 unit and right-clicking another stack with the same troop type, it will show the right-clicked troop's dialog info
- Ditto above but when right-clicking another stack with a different troop type. I think this one is already as it should be.
The regression issue is due to the press coming before the click so I made the press try to do click logic first. And if the click logic returns true skip the press logic. I am not too sure about this one since it feels like an antipattern to me. For left mouse click we got away with that one because we don't override `LeftMouseHold()` anywhere at the moment.
Also refactors RedistributeArmy so that it's more …
=> Fix right mouse split regression

src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_interface.cpp, src/fheroes2/game/game_interface.h, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/gui/interface_icons.cpp, src/fheroes2/gui/ui_window.cpp, src/fheroes2/gui/ui_window.h, src/fheroes2/kingdom/kingdom_overview.cpp
Fix #2302
Fix #2594
The idea is that:
- for castle window, we don't need to update focus when opening the
window through Kingdown window
- for hero window, we already don't update focus, except when dismissing
heroes where this is forced
In order to have an up-to-date UI when a hero is dismissed from the
Kingdom view (ie, correct heroes icon bar and correct world map focus),
what I'm doing is redrawing the main window, then redrawing the
Kingdom UI on top. This ensures that the UI is always correct for all
resolutions
I'm also updating the list element in the Kingdom UI when a hero is
dismissed, otherwise we have bugs because we try to draw the hero army etc for a hero not in our kingdom
=> Fix bugs in Kingdom View

src/fheroes2/heroes/heroes.cpp
Fixes #2417
I noticed the method for setting direction does not follow the naming convention - it's used only in few places, so I fixed it as well.
=> Reset hero direction when recruiting

src/fheroes2/game/game_startgame.cpp
These dialogs implement their own event processing (cursor theme resets
immediately), however after closing those dialogs the other event
queues might not expect changed cursor theme and keep using the dialog
cursor.
This happens in following situation:
1. On the strategic map, hover over your hero (cursor should change to
"helmet cursor").
2. Enter the Hero Dialog via left-click.
3. Without moving cursor, leave the Hero Dialog using escape key.
The cursor on the strategic map stays as "arrow" cursor set by the dialog
instead of resetting back to the "helmet" cursor.  Consequently, left
click will not open the Hero dialog any more until user moves it to
point to another tile and then back again to point to the hero.
Same bug happens after opening/leaving the Castle dialog.
There are two …
=> Restore cursor theme after HeroDialog or CastleDialog

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
Related to #2481 .
Refactored Heroes::Action() so when AI heroes are moving through whirlpool tiles it won't trigger again.
=> Fixes to whirlpool logic

appveyor.yml
to do not depend on VS Redistributable 2015
close #192
=> Put needed DLLs for x86 Windows build

src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_box.cpp, src/fheroes2/dialog/dialog_frameborder.cpp
close #2736
Memory usage for interface reduced by 10 MB for 1024 x 768 pixels
resolution. Which means it's faster on slower machines.
=> Fix extensive memory usage by windows

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/army/army.cpp
Related to #2158.
Based on archer unit count in the army to space them out so they won't be blocked by one unit.
=> Optimize AI's troop placement before the battle

src/fheroes2/game/game_campaign.cpp
Solves #2382
The betrayal missions require custom scripting to switch to another campaign and to display the betrayal mission. So it should be a different issue.
=> Succession Wars full campaign data, excluding the betrayal missions

src/Makefile.switch, src/engine/logging.cpp, src/engine/logging.h
Hi @ihhub,
I merged the latest changes into my Nintendo Switch branch. Here are the manual changes I made in the process, which I think belong to the master branch:
- `logFile` variable is made visible in `logging.h` in order to be used in `COUT` macro
- the Switch-specific data path is no longer hardcoded, instead it is passed via `CONFIGURE_FHEROES2_DATA` macro from the Makefile
- Switch-specific Makefile fixes
With these changes, the master branch can be built for Nintendo Switch. The only remaining changes exclusive to my switch branch are:
- custom hardcoded screen resolution (848x480)
- related touchscreen fixes in `localevent.cpp`
I don't think there is a need for such custom resolutions in the master branch, let me know if there is. I could think of a way to implement this in a …
=> Nintendo switch logging / path fixes

src/engine/localevent.cpp, src/fheroes2/system/settings.cpp
Changed config option name for controller pointer speed to `controller pointer speed`.
Also included fix for correct touch coordinate translation for non-centered windows/game areas.
=> Fix wrong controller pointer speed option name and touch coordinates translation

src/Makefile, src/fheroes2/agg/agg.cpp, src/fheroes2/agg/agg.h, src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game_credits.cpp, src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/game_loadgame.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_focus.cpp, src/fheroes2/heroes/heroes_move.cpp
SDL Mixer can execute tasks only in one thread. In this case some systems face huge delays during gameplay. To avoid such horror we are shooting asynchronous tasks for cases when we don't expect music to be executed immediately.
close #1008
=> Add asynchronous execution of MIDI calls

script/linux/install_sdl_1.sh, script/linux/install_sdl_2.sh
In Ubuntu and Debian for compilation fheroes2 g++, libpng-dev and gettext should be installed.
Also speed-up installation of libsdl*-dev libraries
=> Speed up SDL installation via scripts

src/fheroes2/game/game.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
Should fix #2441 and #2442
Also we should draw animate for monsters and boats only if `drawMonstersAndBoats == true`, also we should draw animate for monsters and boats before redraw top, because boat have long shadow.
=> Fix object fading animation

src/fheroes2/ai/normal/ai_normal_battle.cpp
Fixes #2727 .
Very straightforward fix. Situation happens only when AI's melee units are on the offense action. Increased distance penalty rather than ignoring faster units to deal with archers first. Flyers are always "faster" than walkers.
=> AI: do not chase after faster units

src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/battle/battle_pathfinding.h
Fixes #2753 .
Refactored battle pathfinding to resolve long outstanding bugs. This PR should fix issues when AI's wide walker unit (such as Boar or Wolf) skips a turn because it couldn't find a path. Also it should account for moat penalty during castle sieges.
=> AI wide units pathfding and moat logic

src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_pathfinding.cpp
Fixes #2737 . Fixes #2871 .
Self-explanatory solution. `std::max` safeguard covers us from situations when cost is higher than unit can move in a turn.
=> Pathfinder should know that moat consumes all remaining movement

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/ai_common.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_castle.cpp, src/fheroes2/battle/battle_main.cpp
Fixes #2863 .
Added a bool argument to PreBattle/PostBattle hooks that determines if we can actually shift the troops. Also moved code to `ai_common.cpp` and added optimization call on couple other events to compensate.
=> Optimize army placement during AI turn only

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/army/army_bar.cpp, src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_selectcount.cpp
Solves
- #2823 -> Stacks remain highlighted when splitting, and the highlight will be gone after the splitting or otherwise
- #2824 -> Shift hotkey for splitting when clicking a stack similar to how ctrl and alt hotkeys
- #2679 -> Cancel highlighted troop after ctrl/alt/shift split hotkeys are used
- #2671 -> The `2` option for fast splitting in the split window. For cross-army splitting, this will bring all troops of the splitted stack into the other army
Edit for 2671 -> The original stack will stay, also allow to split up to 6 different stacks including its own if doing cross-army fast splits.
=> Fix Split-related issues, and Implement some new ones

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h
Now AI should be less likely to retreat early: checking if unit stack was lost or army was small in the first place. Also army power ratio now depends on game difficulty (Easy AI should rarely run).
=> AI: improve retreat condition

src/fheroes2/kingdom/kingdom_overview.cpp
fix #2715 
A similar operation in Heroes View is intended to fix an issue when the old hero was fired or a new one was hired, but for castles (as far as I understand) it does not make sense. Needs review though.
=> Do not force reinitialization of castle data on redraw in Kingdom View event loop

src/fheroes2/battle/battle_troop.cpp
=> Preserve unit direction in battle if it moves strictly vertically

src/engine/localevent.cpp, src/engine/localevent.h
Related to #2842
At the moment, MouseRelease* events (used by drag&drop logic in ArmyBar) are not one-shot events, this leads to excessive FPS issues after clicking on creature stack in this bar. In this patch I suggest the somewhat naive approach to this issue. Also I'm not sure that these events should be one-shot by design (and some other part of the code does not count on the fact that they are NOT one-shot events), so may be some different, more complex approach is needed here.
=> Make MouseRelease* events one-shot to fix excessive FPS issue

src/fheroes2/kingdom/kingdom.cpp
fix #2647
It seems that players now have an extra day of life, and I don't know why. Any ideas? Maybe this is necessary for some in-game mechanics?
=> Don't give an extra day of life to a player without castles

src/fheroes2/world/world_pathfinding.cpp
fix #2888
Alternative approach to #2910 - just don't apply (flawed) logic with restrictions on the passage of protected cells. This should work OG-style: hero can pass by the monster via adjacent cell (and will be attacked by one of the monsters guarding the cell), but not pass through the monster, as it happening now.
=> Fix the pathfinding near monsters (OG-style)

src/fheroes2/battle/battle_pathfinding.cpp
Fixed wide unit tail check when planning paths to make sure attacker can squeeze through tight spaces. This should eliminate cases of units going around instead of attacking what's in front of them.
Also renamed some variables and added comments for code clarity.
=> AI: improvements for wide unit pathfinding

src/fheroes2/heroes/heroes_meeting.cpp
fix #2681
Companion PR of #2920.
=> Don't open the hero screen in readonly mode if it was opened from the meeting screen

src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/world/world_pathfinding.cpp
Related to #2932 .
Fixed an issue when pathfinder wouldn't for wide unit to move backwards in a straight line (through a bridge for example). Also improved moat penalty calculation and added extra tail check to mirror changes in linked Bridge PR.
=> Fix ArenaPathfinder backwards move logic

src/engine/audio_music.cpp, src/engine/localevent.cpp, src/engine/localevent.h
Hello!
This a _partial_ fix for #2822 (MacOS/SDL2/**SDL_Mixer**)
What was done:
1. SDL2 window event handling logic was moved into a separate function (`OnSdl2WindowEvent`) beause `LocalEvent::HandleEvents` is too big and complex;
2. Changed detected events types from window hidden/shown to focus lost/acuired;
3. Unfortunately, SDL_Mixer doesn't pause played music _immediately_. I didn't consider halting and restarting music on focus change because it would restart a song each time - probably not good. Instead, here is a workaround - store current volume, set to zero and restore when focus is aquired
=> [Bugfix][2822] Sound off when minimized

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h
Fixes #2936 .
Before blind was reset during attack action, now it's when unit receives damage. Tested with hydras, castle towers and mass spells.
=> Reset blind upon taking any damage

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/battle/battle_pathfinding.h, src/fheroes2/battle/battle_troop.cpp
Fixes #2735 .
Considerate refactor of melee target selection code for both offensive and defensive modes:
Split quality calculations into target and position heuristics.
Added a few helper methods to evaluate potential double cell attacks.
Added logic to determine best attack angle.
We will need another round of AI testing after all recent changes.
=> AI: predict double cell attacks in combat

src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/heroes/heroes_indicator.cpp, src/fheroes2/heroes/heroes_indicator.h
=> more detail display for morale and luck

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_bridge.cpp, src/fheroes2/battle/battle_bridge.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/battle/battle_troop.cpp
In the original game, flying unit could not land on the gates cell, even if gates are already open or destroyed:
At the moment, in fheroes2 flying units don't interact with gates and bridge in any way, what leads to situations like this:
In this PR I propose some changes that will cause flying units to interact with the bridge like everyone else - the bridge should be lowered first to allow landing on the gates cell:
=> Fix interaction with the castle bridge for flying units

src/fheroes2/dialog/dialog_levelup.cpp
Fix an issue (not mentioned in Issues though, or I wasn't able to find it) where the mouse cursor remains hidden if the Secondary Skill Info dialog was called from the Level Up dialog by left-clicking on the skill icon.
=> Don't hide mouse cursor if the Skill Info dialog called from the Level Up dialog contains OK button

src/fheroes2/game/game.cpp, src/fheroes2/gui/player_info.cpp, src/fheroes2/gui/player_info.h, src/fheroes2/system/players.cpp, src/fheroes2/system/players.h
fix #2378
Please note that this PR also implements an ability to swap player names & classes in multiplayer mode even if players aren't supposed to be humans. For example, we cannot swap GOOD and BAD players here:
But we are able to swap BAD and UGLY:
I also changed the logic of the swap buttons on the bottom of the dialog window. Previously, they used to swap absolutely everything, including color (?!). Now they work exactly the same way as using mouse. If this is an unwanted change, I can roll it back.
=> Rewrite player switching in multiplayer dialog

src/fheroes2/kingdom/kingdom.cpp
Steps to reproduce the issue:
1. Load the game from attached save file;
2. Skip the moves until the blue player will be attacked by AI. Surrender the castle and let the player lose;
3. Save the game;
4. Load the game from the save file you just made;
5. Try to save a game or just skip the move (with autosave enabled);
6. Game crashed.
The reason for the crash is that vanquished player's focus never reset, despite the fact that it doesn't have heroes or castles anymore, so the focus info is saved and loaded incorrectly. Perhaps it's better to fix it in some other way, but I propose to do it this way.
[Slugfest_Before_Attack.zip](https://github.com/ihhub/fheroes2/files/6212358/Slugfest_Before_Attack.zip)
=> Fix game crash when trying to save/autosave a loaded game with vanquished human-controlled player

src/fheroes2/heroes/heroes_action.cpp
=> Don't apply morale penalty to a hero if he wins a battle in a Graveyard, Shipwreck or Derelict Ship

src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/dialog/dialog_giftresources.cpp, src/fheroes2/dialog/dialog_marketplace.cpp, src/fheroes2/heroes/heroes_action.cpp
fix #2191
Hi @ihhub I will be grateful for the idea how to remove/update "Not enough gold" message properly, without redrawing the entire dialog window :) So far I've just removed it.
=> Show the surrender dialog even if there is not enough gold to surrender

src/fheroes2/army/army.cpp, src/fheroes2/gui/interface_status.cpp
- align position of sprites as OG;
- draw only 2-monster army in one line ( instead 3-monster);
- align big numbers of monsters.
Issues #1417, #2049.
=> update positions of monster sprites and numbers on army status panel

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_troop.cpp
fix #3032
Additionally fix potentially reduced retaliation damage if unit was killed while blinded and then resurrected.
=> Fix blind spell

README.md
I extract each platform as separate section, so that block would be easier to read.
Also add instructions how to compile application on Gentoo.
=> Reformat installation instruction and add Gentoo

src/fheroes2/heroes/heroes_move.cpp
Prevent redrawing tile which far away from hero
before
after
=> Unneeded redraw

src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_army.h
fix #1609
Also rework a little "soft wait" battle mode to make it more HoMM3-like: units move in the exact reverse order after waiting (if possible, summoned creatures can somewhat break this on the turn on which they was summoned).
=> Respect initial order of units (from top to bottom) when determining the order of unit moves in battle

src/fheroes2/battle/battle_troop.cpp
Self-explanatory fix. Melee attacks include retaliation. Found the bug while testing.
=> Archers shouldn't lose shots when attacking in melee

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h
Fixes #2418 .
`JoinTroop` method merged matching troops first; now we can pick the condition.
=> Force units into empty slots first during merge

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_spell.cpp, src/fheroes2/army/army.cpp, src/fheroes2/heroes/heroes_base.cpp, src/fheroes2/heroes/heroes_base.h
Follow-up on recent spell changes.
Added a method to estimate hero spell casting strength. Using new value to better asses who to attack on strategic map plus in-battle heuristics. AI should avoid using Antimagic altogether if there's no hero or spell threat.
Also including a few behavior fixes to prevent sub-optimal spell casting. Avoid using mind influence and damage spells on blind targets as well as resurrect on tiles blocked by another unit. Summon spell value should account for hero's attack and defense bonus.
=> AI: estimate hero spell strength

src/fheroes2/dialog/dialog_quickinfo.cpp
=> Remove the mobility index sprite info from the hero Quick Info dialog

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_spell.cpp
Used to be 0 because of "spell is already applied" check.
=> Fix dispell value estimation

src/fheroes2/battle/battle_troop.cpp
General battle logic. Noticed that paralyze was still on after unit got hit by the fireball.
=> Reset paralyze state when receiving spell damage

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/battle/battle_pathfinding.h
Related to #2954 .
Applied only for melee units in offense mode where there isn't a target within reach already. Also cleaned up attack outcome comparison logic.
=> AI: fast units should try to get the first strike

src/engine/screen.cpp, src/engine/screen.h
relates to #3046
Using move semantics prevents potential memory leaks as well as saves previous objects which we can reuse later.
=> Update Display class capabilities

src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/maps/maps_tiles.cpp
Fixes digging problem from #3058
fix #2317
fix #2733
I think logic of `Maps::Tiles::GoodForUltimateArtifact()` should be like this, but I may be wrong.
Also I have some doubts regarding logic of `Maps::Tiles::isShadow()` (now it returns `true` if there is a shadow sprite in this tile AND there is at least one non-shadow tile addon, why such logic?). Needs a review from someone familiar with map tiles and passability mechanics. `isShadow()` is not used anymore in `GoodForUltimateArtifact()`, but it is still used in `Maps::Tiles::UpdatePassable()`.
=> Fix ultimate artifact digging logic

src/fheroes2/heroes/heroes_spell.cpp
=> Immediately hide hero's path before executing the animation of the Dimension Door spell

src/fheroes2/ai/ai_hero_action.cpp
=> Reset the spell on tile when AI-controlled hero has successfully captured an object

src/engine/image.cpp, src/fheroes2/castle/buildinginfo.cpp
fix #3145
std::vector::resize() performs value-initialization (zero-initialization for primitive types) of new members, while new[] doesn't. Also I wonder, why not use std::unique_ptr<T[]> for _data instead of raw pointer? There is no overhead in terms of memory usage, but there will be no room for dangling references.
=> Zero-initialize _data in Image::resize(), don't leave _data dangling in Image::operator=()

src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_army.h
fix #395
As usual: needs to be thoroughly tested in different situations, with AI and human-controlled players, with and without soft wait option (with and without reverse wait order), with and without "show army order option" and so on.
=> Implement the "faster monster of opposite army goes first" logic in the battle mode

src/fheroes2/gui/interface_events.cpp
=> Recalculate hero path on focus change in Interface::Basic::EventNextHero()

.github/workflows/linux_pull_request.yml, .github/workflows/linux_release.yml, .github/workflows/macos_release.yml, .travis.yml
Recently I noticed that recent snapshot builds are not available for Linux anymore, latest available build is for commit from May 2020. This PR is intended to partially solve this problem (test builds and snapshot builds for x86 and PSV at least). Also it implements more readable description for macOS builds.
=> Partially migrate Linux builds from Travis to GitHub Actions

src/fheroes2/maps/maps.cpp
fix #3180
Stone Lith becomes unavailable for teleportation if this Stone Lith's cell is occupied by a hero at the start of the game.
=> Fix issue with Stone Liths 

src/fheroes2/system/settings.cpp
Currently in Settings::Read() scroll speed is expected in range 1-4, but in Settings::String() it is saved "as is" (4-32).
=> Fix saving scroll speed in the game config file

.github/workflows/scan-build.yml, src/fheroes2/kingdom/kingdom.cpp
As far as I noticed, currently the scan-build workflow doesn't fail if any bugs are found. This PR fixes this. Also it fixes the following false-positives (reported also by SonarCloud):
https://sonarcloud.io/project/issues?id=ihhub_fheroes2&open=AXhxYwUmQocKC9FrtX__&resolved=false&rules=cpp%3AS2259&types=BUG
https://sonarcloud.io/project/issues?id=ihhub_fheroes2&open=AXhxYwUmQocKC9FrtYAA&resolved=false&rules=cpp%3AS2259&types=BUG
As far as I can tell, there is no way that `hero` and `castle` can somehow become `nullptr` here, so I added `assert()` calls to convince scan-build of this.
=> Force the scan-build workflow to fail if any bugs found

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_troop.cpp
As @Branikolog [rightly pointed out](https://github.com/ihhub/fheroes2/pull/3095#issuecomment-816917628), at this time troops after waiting can't get a positive morale event, just a negative one, and this doesn't look fair. This PR is called to correct this injustice.
Also, although it may seem that pressing the wait button again is the same as skipping turn, it's actually not quite the same thing, which I think is also not quite right. This PR removes those subtle differences.
=> Enable triggering of positive morale event after soft wait

src/engine/math_base.h, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world_loadmap.cpp
- don't inherit from std::vector
- add an extra container to store position of castle sprites, so
that Get() method is in O(1)
This should fix #2385 , but it's mostly a proposal
This adds more a data structure that contains one byte per tile, but even on biggest map size this should be an extra 10KB
=> Refactor for AllCastles

src/fheroes2/spell/spell_book.cpp
There is currently an issue with spells in the spellbook: when you click on some spell, some other spell is in fact selected. How to reproduce:
1. Run fheroes2 and load the attached savefile;
2. Press on "Cast an adventure spell" button;
3. Press and hold the right mouse button on "View Mines" and "Summon Boat" spells.
This PR is intended to fix this issue.
[Broken_Alliance_Boat.zip](https://github.com/ihhub/fheroes2/files/6330742/Broken_Alliance_Boat.zip)
=> Fix issue with incorrect rendering of spells in spellbook

src/fheroes2/game/game.h, src/fheroes2/game/game_delays.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_events.cpp
fix #1159
Also fixes an issue when cursor isn't turned into Cursor::WAIT when hotkey is used to start the hero's movement.
=> Don't allow the player to scroll world map while hero is moving

.github/workflows/cmake_build.yml
I just noticed that cmake_build.yml workflow is launched on ANY branch. Thus, when @ihhub makes a pull request from some branch in this repository, all cmake workflows run in two instances - one on push in that branch, and another one on pull request to master. This PR is intended to fix this. However, if this behavior is intentional, I'll close it.
=> Run cmake_build.yml workflow only on master branch

src/fheroes2/heroes/heroes_action.cpp
fix for #1368
In this commit, the message displayed when capturing a mine is changed.
Haunted mines now display what resource they provide.
Abandoned mines display the correct message that the ghosts have been beaten.
=> Display correct message when capturing abandoned mine

src/fheroes2/dialog/dialog_selectfile.cpp
At the moment, there is no way to load a savefile with a name containing dots.
=> ResizeToShortName(): properly handle filenames with dots

src/fheroes2/gui/interface_list.h
At the moment, scenario selection window shows incorrect information about victory and loss conditions. How to reproduce:
1. Run the game, press "New Game", choose "STANDARD GAME";
2. Press "SELECT" button;
3. Scroll the list of available scenarios, press and hold right mouse button on victory and loss conditions of various scenarios.
This PR is intended to fix this.
=> Fix Interface::ListBox::GetFromPosition()

src/fheroes2/battle/battle_action.cpp
I noticed that currently bridge operation for flying units doesn't work quite right in "no interface" mode. Since the "real" movement of a flying unit in this mode is performed later than bridge is checked for the possibility of raising it up, this leads to the fact that bridge does go up when it shouldn't (or, in some cases, does not go up when it should). This PR should fix this.
P.S. This could be easily checked by adding `&& false` here:
https://github.com/ihhub/fheroes2/blob/57bb9e5a7e06a84e79517dc4f33a028db180cffc/src/fheroes2/battle/battle_action.cpp#L318
and by starting a siege battle as usual (in interface mode).
=> Fix bridge operation for flying units in the "no interface" mode

src/fheroes2/battle/battle_tower.cpp
=> Don't take Mage Guild level into account when calculating count of archers in castle towers

src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
If we redraw top objects on tile near hero, we should also redraw some top objets below this tile.
Before
After
=> Fix redrawing some objects near hero

src/fheroes2/dialog/dialog_armyinfo.cpp
=> Fix rendering of "Not enough gold" text in Dialog::ArmyJoinWithCost()

src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/dialog/dialog_levelup.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/heroes/heroes_meeting.cpp
fix #3262
Also make dismiss button behavior more OG-like - in OG it is disabled only if this specific hero can't be dismissed due to map scenario, and is hidden in other cases.
=> Allow switching heroes in hero dialog if it was opened from meeting dialog

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_catapult.cpp, src/fheroes2/battle/battle_catapult.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h
=> Fix catapult miss animation: show this animation near the actual target object

src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/game/game_io.h
While testing campaign awards, @Branikolog remarked that in the OG, when we complete a campaign scenario the OG creates a save file which will immediately lead you to the campaign scenario selection window (or probably the credits, if it's the last one).
I'm pretty sure this will have merge conflicts with the big campaign award PR, so when either of the PRs are merged I will resolve the conflicts asap.
Example: Good_1_Complete
=> Save Completed Campaign Scenario to file

src/engine/localevent.cpp, src/fheroes2/game/fheroes2.cpp
Just don't init it on anything else than Switch/Vita
Tested with Xbone One X controller on Linux
=> Disable controller on non console platforms

src/fheroes2/game/game_startgame.cpp
Related to #3244: https://github.com/ihhub/fheroes2/issues/3244#issuecomment-828855227
=> Reset current music from the previous turn in the beginning of a new human turn

src/fheroes2/army/army_bar.cpp, src/fheroes2/army/army_bar.h
There is a bug that prevents to view troop info after moving a single unit between army bars. How to reproduce:
1. Run the game and load attached savefile;
2. Enter the Burlock castle (Sorceress);
3. Move the single black dragon from Roxana's army (the rightmost stack) to garrison using drag&drop;
4. Try to view troop info for this black dragon using right mouse button. You will not be able to do this.
The same issue is observed when drag&drop is used to move a single unit between meeting heroes. The proposed patch is intended to fix this.
[Army_Troop_Info_Bug.zip](https://github.com/ihhub/fheroes2/files/6446493/Army_Troop_Info_Bug.zip)
=> Fix issue when troop info window isn't shown after moving a single unit between army bars using drag&drop

src/fheroes2/dialog/dialog_skillinfo.cpp
There is a bug: mouse cursor not visible after left-clicking on hero's secondary skill in Kingdom Overview. How to reproduce:
1. Run the game and start any new game with starting hero;
2. Open the Kingdom Overview screen and left-click on any secondary skill of the starting hero;
3. Secondary skill overview dialog is opened, but no cursor is visible on the screen.
This PR is intended to fix this issue.
There is a big mess with cursors in game, they are controlled by hand in an arbitrary way, often contradictory. Need to think about how to better organize this...
=> Fix bug with mouse cursor not visible after left-clicking on hero's secondary skill in Kingdom Overview

src/fheroes2/agg/agg.cpp, src/fheroes2/agg/icn.cpp, src/fheroes2/campaign/campaign_savedata.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle_building.cpp, src/fheroes2/castle/castle_town.cpp, src/fheroes2/dialog/dialog_system.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/game/game_io.h, src/fheroes2/heroes/heroes.cpp, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_fileinfo.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/resource/artifact.cpp, src/fheroes2/system/players.h, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world_loadmap.cpp
- new saves will have a flag indicating about the original (The Succession Wars) map version or the add-on (The Price of Loyalty)
- all old saves will be considered as using the original map (The Succession Wars). It could lead to some issues with add-on related maps but we have to do this
- remove support of save files older than 0.9.1
- some code cleanup (I'm sorry I can't look at so many voids) and small code optimizations
close #1759 
close #3158
=> Add correct support of The Price of Loyalty add-on

src/engine/endian_h2.h
This trivial patch allows us to build a working version of the application for OpenBSD. No additional code changes were required, everything works as expected. Thank you in advance.
=> Fix build on OpenBSD

src/engine/localevent.cpp
Related to #3415
On MacOS, `SDL_APPACTIVE` doesn't work properly: it is coming only when app is minimized (`gain == 0`), but not when app is activated back (`gain == 1`), not to mention the fact that, according to the documentation, it doesn't come when window simply sent to background without minimizing.
=> Fix sound mute in background on MacOS with SDL1

src/fheroes2/heroes/heroes.cpp
Some PRs ago I made changes to `heroes.cpp` in which I didn't add PoL-exclusive heroes in non-PoL maps. Unfortunately this causes a crash on development builds where debug hero is used.
So I'll be re-adding unknown heroes in place of the PoL-specific ones for non PoL maps. Alternatively, we could use a std::find_if lambda when heroID == DebugHero but I think the current solution is more consistent with the rest of the code so far.
=> Fix crash on non-PoL maps because the heroes vector isn't full

src/fheroes2/heroes/heroes.cpp
=> Unveil the fog on instant hero's movement (for example, via Stone Lith)

src/fheroes2/game/game_io.cpp
Remove duplicate calls to `fz >> Campaign::CampaignSaveData::Get();`.
=> Fix campaign save files not loading in the latest version

src/fheroes2/heroes/heroes.cpp
Closes #3460 
This was another regression from #3436 that was supposed to fix a regression. 
In the previous PR, we didn't make an unknown hero to replace Jarkonas for non-PoL maps and so, when we are looking for debug hero we get an unknown instead. And that "unknown" is invisible and blocks the road in front of the castle.
=> Fix heroes blocked in front of player's castle for Debug Mode

src/fheroes2/heroes/heroes.cpp
=> Don't reset hero mana points to maximum in the beginning of a new week if they are above maximum

src/fheroes2/game/difficulty.h, src/fheroes2/game/game.cpp
close #3501
The only scenario which has difficult diffuculty is the second map for
both campaigns
=> Set proper difficulty level for campaign scenario

src/fheroes2/army/army.cpp
=> Troops::JoinTroop(): make sure that the candidate slot not only contains the same troops, but also that troops are valid

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/battle/battle.h, src/fheroes2/battle/battle_animation.cpp, src/fheroes2/battle/battle_animation.h, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_army.h, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_cell.cpp, src/fheroes2/battle/battle_cell.h, src/fheroes2/battle/battle_command.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/battle/battle_main.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h, src/fheroes2/world/world_regions.cpp, src/fheroes2/world/world_regions.h
* Remove unused code
* Get the virtual methods in order
* Make methods const if possible
* Add missing copy constructors and assignment operators (mostly =deleted), as well as destructors (=default)
* Use =default constructors and destructors instead of empty ({})
* Use explicit keyword to disable converting constructors where possible
* Make function parameters reference-to-const where possible
=> Code cleanup

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/world/world.cpp
Currently heroes from PoL cannot be used in "battle only" mode (they turn into Heroes::UNKNOWN) and I suppose that there may be also issues with artifacts from PoL if this addon is not available on player's machine.
Need a review from someone who is familiar with PoL addon mechanics to make sure that I do the right things here and didn't forget anything. PoL doesn't add new secondary skills, spells or monsters, right?
=> Support PoL heroes & artifacts in "battle only" mode

src/fheroes2/heroes/heroes_action.cpp
=> Clear the hidden mode for the hero's path after moving through Whirlpool

src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
This option must be always enabled.
=> Remove "world: only the first monster will attack (H2 bug)" option

src/engine/system.cpp, src/engine/system.h, src/fheroes2/game/fheroes2.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/system/settings.cpp
Use `$XDG_CONFIG_HOME/fheroes2`on Linux (`~/.config/fheroes2` by default) for `fheroes2.bin`, `fheroes2.cfg`.
Use `$XDG_DATA_HOME/fheroes2` on Linux (`~/.local/share/fheroes2` by default) for `data`, `files/save`, `maps`.
On other platforms use directory returned by `GetHomeDirectory`.
Close #2860.
Close #3118.
=> Use XDG directories

src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps.h, src/fheroes2/maps/maps_tiles.cpp
In original game, sprite of a monster attacked by hero (or attacking hero) changed before battle to the "attacking" sprite. This was the case in fheroes2 too if "world: only the first monster will attack (H2 bug)" option wasn't enabled. Recently this option was removed, so I decided to make this "attacking" sprite work again (and properly).
fix #1142 (sprite change logic was fixed)
fix #885 (still should fix that! 😛)
fix #2537 
fix #2377
=> Fix attacking monster sprite behavior

src/engine/dir.cpp, src/engine/dir.h, src/engine/system.cpp, src/engine/system.h, src/fheroes2/game/fheroes2.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
fix #3636
It seems that there is already a ready-made mechanism for such situations - `Settings::GetLastFile()`, it is already used for `fheroes2.key` as well. As I understand, the order of search will be the following:
1. List of the matching files is created by scanning directories in the following order: directory from $FHEROES2_DATA env var first, then app's directory, then user config directory, then user data directory, then OS specific directories (like "ux0:..." on PS Vita);
2. The **last** file is taken from this list. If there is no matching files, just file name is taken, which effectively means "file with this name in current directory".
Need to test this on consoles too - to not break anything.
=> Prefer per-user config file over global one

src/fheroes2/system/settings.cpp
Some comments contains obsolete info (like comment for `debug`), and there is a comment that doesn't start with `#`.
=> fheroes2.cfg: fix typos and update comments a bit

src/fheroes2/ai/ai_hero_action.cpp
fix #3632
While hero is on tile, tile object is set to `MP2::OBJ_HEROES`, and hero saves original tile object into its `save_maps_object` property, so when tile object changes, we need update this property. `Maps::Tiles::UpdateAbandoneMineSprite()` doesn't update tile object by itself, so `SetHeroes()` for this tile will not help, we need to explicitly call `SetMapsObject()` method of a hero on that tile. Tile object will be updated automatically once hero will leave that tile.
=> Fix issue when abandoned mine becomes OBJ_ZERO when captured by AI-controlled hero

script/linux/install_sdl_1.sh, script/linux/install_sdl_2.sh
In [compilation instructions for Linux](https://github.com/ihhub/fheroes2#macos-and-linux) it's implied that you just need to run **install_sdl_2.sh** or **install_sdl_1.sh** to install dependencies (no other steps are present).
However both of these files are missing **gettext** package so if you follow the instruction, your compilation will fail.
=> Adding gettext to the list of installed packages

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h
fix #717
fix #1183 (sort of, hero should not attack creatures when moving using the Dimension Door)
=> Don't let nearby monsters automatically attack hero if he moved to this tile using Stone Lith, Whirlpool or Dimension Door

doc/README_PSV.md, src/engine/localevent.cpp
Added more key mappings for gamepad on Vita and Switch (switching between heroes/castles, end turn and the last one to open a spell book).
=> More gamepad hotkeys added

CMakeLists.txt, doc/README.txt, script/packaging/debian/README.Debian
Currently I'm adding fheroes2 port to MacPorts: https://github.com/macports/macports-ports/pull/11307, and I want to minimize all these `post-destroot` stage manipulations in future releases. LICENSE file is usually required anyway, and, even if it's not required, there will be no harm in delivering it.
=> CMake: install LICENSE into ${CMAKE_INSTALL_DOCDIR}, paraphrase some sentences in README.txt

src/engine/image.cpp, src/engine/localevent.cpp, src/engine/tools.cpp, src/fheroes2/agg/bin_info.cpp, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game.cpp, src/fheroes2/gui/ui_tool.cpp, src/fheroes2/heroes/heroes_indicator.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/world/world_pathfinding.cpp
Issues caught by MacPorts buildbot:
1. `#include <cstdlib>` is required for `std::abs()` with int argument and `std::div()`: [buildbot log](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/145739/steps/install-port/logs/stdio)
=> Fix build with older Xcode versions

src/fheroes2/heroes/heroes.cpp
fix #3680
It looks like this method is intended to mark object as visited for hero's kingdom too, but currently it is not the case.
=> Heroes::setVisitedForAllies(): set object as visited for this hero's kingdom as well, not just for allied kingdoms

src/fheroes2/resource/artifact.cpp
=> Adventure map, Alchemist's Tower, Sphere of Negation should not be considered a cursed artifact

src/fheroes2/ai/ai_common.cpp, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/world/world_pathfinding.cpp
- improve fog revealing algorithm for AI
- fix Stables movement bonus
- fix AI heroes interaction between each other (reset meeting flag if a hero updates an army)
- a chance to choose experience from treasure boxes reduced from 50% to 10%
- AI heroes don't visit signs anymore
- AI don't visit shrines for useless spells
- fix some incorrect situations of missing hero meeting or attacking another one
- improve Magellan Maps object value
- improve some other objects values
close #3417
close #3413 
close #3381
=> AI improvements

src/fheroes2/battle/battle.h, src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/monster/monster_info.h, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
There is no solid explanation why this value was chosen.
Plus a small code cleanup.
=> Remove "battle: skip increase +2 defense" option

src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/heroes/heroes_base.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
close #1300
This option should be always enabled to have the same behavior as in the original game
=> Remove "world: use unique artifacts for morale/luck" option

src/fheroes2/maps/maps.cpp
=> Fix the tileId calculation in Maps::GetAroundIndexes()

src/fheroes2/gui/interface_focus.cpp
Regression introduced in #3768. This leads to an issue when all terrain music and ambient sounds start from the beginning after each hero movement or action.
=> Don't reset mixer on each focus update

src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game_interface.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/maps_tiles_quantity.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world_loadmap.cpp
The original code was based on hacks and it wasn't reliable. The current approach uses an algorithm and a set of conditions to determine passability of a tile.
close #1951
close #3750
close #3745
close #1521
close #496
close #2601 
close #2401 
close #2364 
close #3246
=> Fix passabilities of objects on map

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h, src/fheroes2/world/world_loadmap.cpp
Every time when we load saves we recalculate passability rules. This is incorrect as objects on map never being changed (for now). This change fixes old saves as well as new ones if there are any issues.
=> Fix passabilities for old saves being resaved

src/engine/dir.cpp
fix #3770
P.S. It seems that PSV variant is bugged - current implementation for all other platforms implies that if a `nameAsFilter` is true, then the filename should **END** with `name`, and not just **CONTAIN** it (which is logical, considering that filtering is mainly performed by file extensions).
=> getFilesFromDirectory(): FindFirstFile() searches for both long and short variants of names, so we need additional filtering

files/lang/Makefile, files/lang/cs.po, files/lang/es.po, files/lang/fheroes2.pot, files/lang/fr.po, files/lang/hu.po, files/lang/lt.po, files/lang/nl.po, files/lang/pl.po, files/lang/pt.po, files/lang/ru.po, files/lang/sv.po, files/lang/tr.po, src/engine/translations.cpp
This consists of 3 commits related to #2211:
- update the .pot file and merge .po files with it (fully automated change)
- fix a bug in the crc32b function which makes the calculated CRC independent of the input data
- add a call to `iconv/konwert` to replace language-specific characters with ASCII. `iconv` is pretty standard but doesn't handle Russian. `konwert` is less widespread (it's packaged for Debian though) and handles Russian pretty well. It also has a /1 option which forces a 1-to-1 replacement (so that `ä` is replaced with `a` rather than `ae` or `"a`), which is useful when checking whether translations fit on their respective interface elements.
I'm currently working on FR/RU translations (I own a French GoG HoMM2 version and a Russian edition of HoMM2 from "Buka" which is …
=> Update translation files and fix in-game translation function

src/fheroes2/ai/normal/ai_normal_hero.cpp
fix #3795
The intent of this line was to reduce the threat when a castle was empty. But since I forgot to check if there was actually a threat, it was instead decreasing the value of an empty castle. This PR should fix it.
=> AI heroes don't ever capture empty castles

src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps.h, src/fheroes2/maps/maps_tiles.cpp
Related to #3576: since after merging of #3494 there is a variant of `ScanAroundObject()` with `ignoreHeroes` parameter, use it in `Maps::Tiles::GetMonsterSpriteIndices()` instead of replicating its logic, move `Maps::GetAroundIndexes()` and `Maps::MapsIndexesFilteredObject()` back to the anonymous namespace.
Fix a typo in the `ComparsionDistance`, while I'm here.
=> Revert some auxiliary changes introduced in #3576

src/fheroes2/game/game.cpp, src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/game_hotkeys.cpp
Fix clang-tidy [readability-redundant-string-cstr](https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability-redundant-string-cstr.html) warnings.
=> code cleanup: Remove redundant c_str() calls

src/fheroes2/battle/battle_dialogs.cpp
This fixes an issue when on AI's turn the mouse cursor in the necromancy dialog is shown as `Cursor::WAIT`.
=> DialogBattleNecromancy(): set cursor to Cursor::POINTER

src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_army.h, src/fheroes2/battle/battle_main.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h
fix #3786
Apparently the behavior described in #775 is wrong - if all creatures from the initial army were killed in a battle, then the hero should lose regardless of using Resurrect during the battle.
=> If the hero's army does not have any of the original troops left alive at the end of the battle, then the hero should lose

src/fheroes2/maps/maps.cpp
=> Fix crash in Maps::GetFreeIndexesAroundTile()

src/fheroes2/campaign/campaign_data.cpp
The root cause of the issue is explained in Campaign data doesn't get translated. #3807.
Here are the screenshots before the change:
and after the change:
=> Display translated text in campaign dialog

src/fheroes2/dialog/dialog_skillinfo.cpp, src/fheroes2/gui/ui_text.cpp
close #3273
We should use this class for any new future texts.
This is how it looks now:
=> Align text evenly inside secondary skill window

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_interface.cpp
Hi all,
I don't know if it's really worth it (considering the new (Dijkstra's based?) pathfinding engine from battle_pathfinding.cpp), but here is my proposal of greedy (in the sense of making the locally optimal choice at each stage) recursive pathfinding algorithm as a possible temporary replacement for old GetAStarPath(). This algorithm may be suboptimal in some situations, but it is simple and (at first sight) it shows much better results than old (in my opinion, weird or incorrectly implemented A* based) pathfinding algorithm, especially in the case of wide units.
Anyway, there is definitely one useful commit in this PR that fixes Board::GetDistance() function. Previous implementation gave incorrect results in a number of cases.
fix #2951
=> Refine battle pathfinding using a recursive greedy depth-limited approach

src/fheroes2/gui/interface_events.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h
Fixes #3364
A hero with non-zero move points can be chosen as next even if movement is not possible on predetermined path
=> Fix next hero choose logic

src/fheroes2/castle/castle_mageguild.cpp, src/fheroes2/dialog/dialog_spellinfo.cpp
Add them to spell info dialog.
Fixes #633.
=> Remove required spellpoints from scroll in Mage Guild

.github/workflows/clang_tidy.yml
This should fix an issue when `clang_tidy.yml` fails to perform PR decoration when PR is made from a fork.
=> Clang-Tidy workflow: use pull_request_target instead of pull_request

src/fheroes2/dialog/dialog_selectcount.cpp
=> Centering fast separation buttons

.clang-tidy
Related to the clang-tidy run in #3769. `modernize-use-trailing-return-type` check is no use and I believe `readability-implicit-bool-conversion` should be turned off too, because in many cases readability is better with implicit bool conversions than without them, but this is debatable. Also I'm not sure about `readability-braces-around-statements` - on the one hand, "no braces for one-liners" is error-prone, but on the other hand this style is very common in this project. Hi @ihhub what do you think?
P.S. Also it seems that "reviewed" line numbers are wrong - however, given that there are quoted pieces of code, it's not that big a deal.
=> Clang-Tidy: disable some checks

.clang-tidy
=> Clang-Tidy: disable cppcoreguidelines-avoid-magic-numbers, readability-braces-around-statements and readability-magic-numbers

.github/workflows/clang_tidy.yml
It seems that issues with wrong line numbers occur because `actions/checkout` in the case of `pull_request_target` checkouts a wrong ref - not the head ref, but the target ref instead. This PR should fix this.
=> Clang-Tidy: fix repo checkout for pull_request_target

.github/workflows/clang_tidy.yml
I have concerns regarding security of the Clang-Tidy workflow. This workflow have r/w access to the main repo and access to repo secrets (due to the nature of `pull_request_target` and the need to post code reviews), but it works with untrusted code from forks, so in theory it may run malicious scripts (using specially crafted `CMakeLists.txt`, for example). That's not good. I'll change it to not run in the `pull_request_target` mode but in the regular `pull_request` mode instead (it doesn't have any r/w access or access to secrets) and it will be run only for PRs originated from the main repo, not from forks.
=> Don't run the Clang-Tidy workflow on PRs from forks

files/lang/Makefile, files/lang/fr.po, files/lang/ru.po
I've finished my work on RU/FR translations. It's far from perfect, but at least there are no untranslated strings now. I'll be happy to apply changes affecting many strings, especially concerning rules of thumb listed below. Fixing individual strings should IMO be done by subsequent pull requests which don't modify half of the file and are easily mergeable.
I have tried to follow these rules, at least for new translations:
- specific names (buildings/items/spells/etc.) should be translated exactly as in official games. I used the GoG version for French and the Buka version for Russian.
- Longer sentences should not be copied (to avoid copyright issues). I mostly used Deepl translations with a manual check for gender / plural form issues, especially around variables. Specific names in …
=> Update ru/fr translations and the Makefile

.github/workflows/clang_tidy.yml, .github/workflows/clang_tidy_comments.yml
Run the analysis itself on `pull_request` event with minimal permissions and then run the separate workflow on `workflow_run` event with elevated permissions to perform the PR decoration.
Currently the `clang_tidy_comments.yml` uses my own fork of Action to perform the PR decoration because original Action ([platisd/clang-tidy-pr-comments](https://github.com/platisd/clang-tidy-pr-comments)) is not able to accept the PR id as a parameter, but I made the https://github.com/platisd/clang-tidy-pr-comments/pull/4 PR, and I'll update this workflow once it will be merged. @ihhub or, if you wish, you can make your own fork of this Action (with my changes) to be able to fully control it.
=> Implement the secure way to run clang-tidy checks from forks

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/campaign/campaign_scenariodata.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_over.cpp
I found several cases of awkward English phrasing while working on translations, which I would like to fix:
- Replace "Fizbin Medal" with "Fizbin of Misfortune", as in the original game.
- Expand incomplete phrases like "MirrorImage created", "%{name} skipping turn" etc. to proper sentences.
- Replace "up, to" with "up to", finish victory conditions with a dot to match the loss conditions.
- A few other fixes.
=> Fix English phrasing and punctuation

.clang-tidy
Suggested `variant` is C++17 feature. Related to #3887.
=> clang-tidy: disable cppcoreguidelines-pro-type-union-access

src/fheroes2/gui/ui_language.cpp
Sorry I was late for the party when #3897 was being worked on.
I have installed all HoMM versions which are available to me and calculated the font checksums. The alternative Russian version (XXI Vek, "21st Century") uses exactly the same CP1251 encoding as Buka, so there's no added effort to support it. Personally I find XXI Vek interface to be horrible, the font face they used makes me feel dyslexic ([check out for yourself](https://user-images.githubusercontent.com/10945319/126991533-68bc1583-3216-4248-b619-a2e078fe9831.png)), but hey, it's a matter of taste.
FIY, I'm working on a German translation right now, it's about 40% completed.
=> Add font checksums for Polish / German / alt. Russian (XXI Vek) versions

src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/game/game_over.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/kingdom/week.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world_loadmap.cpp
- world: show visited content from objects (this is enabled by default now)
- world: ban for WeekOf/MonthOf Monsters
- world: ban plagues months
- world: Months Of Monsters do not place creatures on map
- world: Starting heroes as Loss Conditions for Human Players
- world: Only 1 hero can be hired by the one player every week
- world: Each castle allows one hero to be recruited every week
=> Remove some useless experimental options

.github/workflows/clang_tidy_comments.yml
Need to sync the [fheroes2/clang-tidy-pr-comments](https://github.com/fheroes2/clang-tidy-pr-comments) with the upstream first though.
=> Delete the fixes.yml existence check - it is no longer needed

src/fheroes2/battle/battle_interface.cpp
for wide monsters which are at the end of the battlefield
regression from #3911
=> Fix an assertion call during battle shadow rendering

src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_interface.cpp
Found when testing the #3931. In the following situation:
neither of these two wide units will attack each other, they just will do one step forward instead (the same is observed when AI controls them during auto battle). This PR is intended to fix this.
=> Fix attacking after turning back in some cases

src/fheroes2/heroes/skill.cpp
The secondary skill order is similar to the OG order. Meaning:
- Knight: Leadership->Ballistics
- Sorc: Navigation->Wisdom
- Warlock: Scouting->Wisdom
- Necro: Necro->Wisdom (as per @LeHerosInconnu remark; to be consistent with the Editor but different than the OG)
Fixes #1677.
=> Update skill order for new heroes

src/fheroes2/gui/player_info.cpp
I fixed a bug in the game info window that incorrectly displayed the player icon for computer-only players. For more details, please read my comment in the #3475. It fixes #3475. 
This is a continuation of [the following pull request](https://github.com/ihhub/fheroes2/pull/3912).
Below some screens from my tests:
Before:
After:
Before:
After:
=> Fix incorrect icons for scenario information dialog

src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/world/world.cpp
Inline sort by distance in only caller.
=> Remove sortTiles flag from Maps::GetAroundIndexes

.clang-tidy
=> Clang-Tidy: disable cppcoreguidelines-pro-bounds-constant-array-index

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
People often forget to attach a screenshot or a save file. You can test these templates in my repo:
https://github.com/oleg-derevenetz/fheroes2/issues
Just click on the "New issue" button.
=> Provide issue templates for the most common issue types

docs/DEVELOPMENT.md, docs/INSTALL.md
As usual, you can see how it looks like in the website mode here:
https://oleg-derevenetz.github.io/fheroes2/
Also I added links to PSV and Switch-specific READMEs to INSTALL.md (they still contain useful data about which data should be copied to where, although this does not apply to devices with official firmware), if it is better not to do this, I can remove them.
=> Add links to README_switch.md in INSTALL.md and DEVELOPMENT.md, rename "PS Vita" to "PlayStation Vita"

.clang-tidy
Reason: `char *` is widely used in this project to represent null-terminated strings, and `char[]` literals are often passed as arguments to functions that accept `char *`. At the same time we are not going to use GSL yet, so `gsl::span` is not available anyway, and neither `std::span` (from C++20) nor `std::string_view` (from C++17) are available.
=> Clang-Tidy: disable cppcoreguidelines-pro-bounds-array-to-pointer-decay

.clang-tidy
Reason: namespace-scope and module-scope variables are routinely used in this project.
=> Clang-Tidy: disable cppcoreguidelines-avoid-non-const-global-variables

src/fheroes2/dialog/dialog_game_settings.cpp
Fix #3991
This approach still allows to set unsupported languages (like Spanish or Lithuanian) via `fheroes2.cfg`. However, user shouldn't try to choose the language through the GUI in this case.
=> Game settings dialog: reset current language to English if game resources doesn't support other languages

src/fheroes2/gui/interface_events.cpp
A "not visited" obelisk remains "not visited" after the Ultimate Artifact has been found. Fixes #438.
In this PR, I am fixing a bug when all obelisks become visited when the Ultimate Artifact is found (even if a player never visited any obelisk). For future enhancements, pls visit #438 or create a new issue.
=> A not visited obelisk remains not visited after the UA has been found.

src/fheroes2/dialog/dialog_system_options.cpp, src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
Use setters in `Settings::Read` in instead of copypaste.
Change scroll speed enum values to simplify read/write.
Use `clamp` and `min` instead of manual comparisons.
Also fix `battle_speed` initial value.
=> Deduplicate settings code

sonar-project.properties
=> SonarCloud: fix sonar.links.ci

src/fheroes2/game/game.cpp
fix #4031
Hi @ihhub I was unable to reproduce this issue on my own hardware (apparently it's too fast), so I borrowed an ancient Lenovo T420, but it was taken back from me recently. Do you have a hardware slow enough to test this patch?
=> Game::EnvironmentSoundMixer(): remove extra Audio::isValid() check that blocks the main thread

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_cell.cpp, src/fheroes2/battle/battle_cell.h, src/fheroes2/battle/battle_interface.cpp
Today I ran into an interesting problem:
Although the Cavalry can occupy each of the highlighted cells separately, it can't occupy them BOTH AT THE SAME TIME. If I press the left mouse button here, Cavalry just skips the turn, and this is completely logical - Cavalry can't reach those cells from inside the castle because of the moat, and it can't reach those cells from outside, because the head cell (the rightmost one) is too far.
This problem apparently cannot be solved within the current pathfinding paradigm, because each of both cells have the valid `direction` field, so I decided to introduce separate info for the head (`_reachableForHead`) and tail (`_reachableForTail`) of units and also replace direction (`int`) by reachability (`bool`) since all that was done with them was a …
=> Battle pathfinding: store passability info separately for the head and tail of wide units, improve AI pathfinding a bit

src/engine/screen.cpp
The reference returned from `front()` is no longer valid after use of
`emplace_back`, so we should store current resolution by value instead.
=> Fix invalid reference in FilterResolutions

src/engine/screen.cpp
Use of "greater or equal" at the last place is not correct.
=> Ensure strict ordering in SortResolutions

.clang-tidy
For example, in #4035 we have an abstract class with virtual defaulted destructor, no need to add copy/move constructors and assignment operators in such cases.
=> clang-tidy: enable AllowSoleDefaultDtor option for cppcoreguidelines-special-member-functions check

src/fheroes2/maps/maps_fileinfo.cpp
Fixes #945
Also affects how map names are ordered (e.g. in the "New Game" dialog), but
that should be fine in general.
=> Implement CaseInsensitiveCompare for filename sorting

src/engine/image.cpp
Passing unexpected images is a programming error, we should bail out instead
of pretending nothing happened.
=> Don't ignore in<>out mismatch in Image Transpose

src/fheroes2/castle/castle_dialog.cpp
Use `Transpose()` to make sure it looks differently from "Meet heroes".
Additionally, improve both buttons alignment on screen.
=> Use distinct image for the "Swap heroes" button

src/engine/serialize.cpp, src/engine/serialize.h, src/fheroes2/agg/bin_info.cpp, src/fheroes2/army/army_bar.cpp, src/fheroes2/system/players.cpp, src/fheroes2/system/players.h, src/tools/CMakeLists.txt, src/tools/bin2txt.cpp
* Replace `reinterpret_cast` by `static_cast` or `dynamic_cast` where appropriate;
* Remove `reinterpret_cast` usage from the `bin2txt` tool - this led to unaligned accesses at least.
I compared the `bin2txt` output from `master` branch and from this branch for some `.bin` files - it seems that nothing has been broken.
=> Eradicate more reinterpret_cast calls

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/kingdom/kingdom.cpp
I've seen similar AI behavior during a siege many times:
If I press the "AUTO" button now, Paladin does this:
Utter failure. My initial (not a very thorough) investigation showed that this is not a pathfinding problem, but now I did a proper investigation and it showed that I was wrong - AI pathfinder really believes that Paladin is not able to reach Unicorn here(?!). So I replaced AI pathfinder by my pathfinder from `Battle::Board` (for the purpose of making decisions on the reachability of units for attack), and...
The pathetic unicorns were defeated, as they should have been.
Hi @ihhub regarding your sentence from #4064:
> And that's why our AI is weak!
**_That's why it is weak_** - at least, one of the real reasons. Pathfinding issues will ruin even the most sophisticated battle …
=> Fix AI behavior during siege

src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h
This fixes an ability to upgrade units in castle guardian armies (and, may be, something else).
=> Heroes::inCastle(): respect GUARDIAN mode

src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_cell.cpp, src/fheroes2/battle/battle_cell.h, src/fheroes2/battle/battle_interface.cpp
* Simplify logic a bit: cells occupied by the unit are always reachable for the same unit, if cell is occupied by another unit, it is unreachable anyway;
* Make it clear that passability-related functions will work only with "current unit" - the unit for which cell passability information is currently calculated.
=> Simplify passability logic a bit, clarify function descriptions

files/lang/fr.po
Archi-mage -> Grand mage
---------
The lasts few points to discuss/decide about to finish this translation:
Lasts points to discuss/decide about:
**subis -> infligés**
Do we really replace "subis (taken)" by "infligé (inflicted)" everywhere?
I don't think it's an improvement.
**"Archmagi"** was "Grand mage" in the French original H2. But "Archi-mage" sounds more used in recent years than it was in 1996. :D What name to stick with? (My opinion is to stick with original H2: "Grand mage")
Campaigns texts: full review needed.
1034: "ou vos rivaux seront sûrement arrivés à la source avant vous."
This sentence sounds wrong. (and any sentence translated with "surely" words too.)
"Dwarfbane" -> No better translation in french?
"Iles Pirates" -> "Îles Pirates" (once the replace i -> î in the …
=> Update French translation 

src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_fileinfo.h, src/fheroes2/system/settings.cpp
fix #4117
The root cause of this issue is that the list of maps can be read from the `MAPS` subdirectory of current directory, and if we run the `fheroes2.exe` from the directory that contains the `MAPS` subdirectory, then the files in this `MAPS` subdirectory are processed twice - the first time as maps from the current directory, and the second time as maps from the app installation directory. I really don't think that we should process any files from the current directory in any case, so this PR contains an optional commit that removes the processing of files from the current directory (I can revert it if there are some real reasons to do this).
Also move local functions in game_scenarioinfo.cpp to anonymous namespace.
P.S. Hi @ihhub you may want to sync …
=> Return only unique maps (based on map file name) from PrepareMapsFileInfoList()

src/fheroes2/dialog/dialog_gameinfo.cpp
Fix for issue #1890 
The horizontal window alignment didn't take the border width into consideration when calculating its position.
The vertical position was misaligned due to sprite reporting a height of 476px when the actual size is 472px
=> Alignment fix of scenario info window

.clang-tidy, src/fheroes2/campaign/campaign_data.cpp, src/fheroes2/campaign/campaign_savedata.cpp, src/fheroes2/gui/ui_button.cpp, src/fheroes2/heroes/heroes_base.cpp
Fix clang-tidy [readability-redundant-member-init](https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-member-init.html) warnings.
Disable check for unnecessary base class initializations within copy constructors since gcc generates warning if it removed.
=> Remove redundant member initializations

src/engine/audio.cpp
On NixOS SDL2_mixer was not configured fully against timidity,
but it was not immediately clear:
10:02:38: [ERROR]       PlayMusic:  music parameter was NULL
With the patch error reporting is more straightforward:
10:03:45: [ERROR]       Play:  Couldn't open /etc/timidity/freepats.cfg
The change makes error handling in
void Music::Play( const std::vector<uint8_t> & v, const bool loop )
void Music::Play( const std::string & file, const bool loop )
identical.
=> audio_music: log the reason why mixer could not be created

src/fheroes2/kingdom/view_world.cpp, src/fheroes2/kingdom/view_world.h
Fix #3157
This prevents displaying beyond the edges of the map, ~but seems to introduce a problem when changing position by clicking on the world: it might jump around unpredictably.  Not sure why that would be the case.~
In general with big screen resolution and a small map we will display back area around the map anyway, so maybe it's not critical to try to fix it at all.
=> Fix black edges on view world

src/fheroes2/gui/interface_events.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h
fix #4146
Hi @Branikolog in fact, hero still has 100MP after teleporting to the Snow terrain (you can make sure of this by viewing hero's quick info), so no movement penalty is in fact applied. I suppose that hero still should be able to traverse through teleports if he has non-zero movement points, even if he is not able to make a step over the terrain on which teleport resides due to this terrain's penalty? If yes, then this PR should fix the issue. If no, then there is no issue :)
=> Allow hero to traverse Stone Liths and Whirlpools even if he has no movement points left

src/engine/serialize.cpp
The result is the same, but OR makes more sense for bit operations (and should
be slightly more performant, though that's probably never an issue for the
data volumes we process).
=> Use bitwise OR instead of addition in deserialization code

src/fheroes2/resource/artifact.cpp
The artifact was appearing as Level 3 artifact while in the original game it's level 2.
Also did some code cleanup to preparation for bigger changes
=> Fix incorrect level of Lightning Rod artifact

src/fheroes2/campaign/campaign_data.cpp
fix #4062
This doesn't fix old saves though since previously we set the wrong `_currentScenarioID` (we get crown's scenario ID when playing gauntlet and vice versa)
=> Fix wrong campaign award in Roland Campaign's branching scenario

src/fheroes2/game/game_static.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h
* Remove unused `kingdom_starting_resource` array.
* Remove intermediate redundant `UpdateStartingResource` method.
* Make `GetKingdomStartingResources` private and format according to codestyle.
=> Cleanup GetKingdomStartingResources

src/fheroes2/gui/interface_list.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom_overview.cpp
fix #4238
Also fix a crash due to a failed assertion when trying to view the Kingdom Overview for the second time after viewing an empty list of heroes or castles.
=> Fix an empty list of heroes in the Kingdom Overview after the dismissal or loss of a hero

src/fheroes2/heroes/heroes_base.cpp
In previous variant spell's move points requirement wasn't checked if `res` argument was omitted.
=> Flatten HeroBase::CanCastSpell and fix result without error output

src/fheroes2/heroes/heroes_spell.cpp
=> Unselect initial town in the Town Portal spell list

src/fheroes2/agg/agg_image.cpp, src/fheroes2/dialog/dialog_settings.cpp
=> Replace scrollbar in Experimental Settings dialog

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/heroes/heroes_spell.cpp
This fixes rendering of the list in Town Portal spell and Select
Hero/Skill/Army/Artifact/etc. lists in Battle-Only setup.
=> Fix scrollbar rendering in select lists

src/fheroes2/world/world.cpp
fix #4270
There is also a minor simplification of the code and style nits.
=> Do not place wandering troops on OBJ_COAST tile if there are no other OBJ_COAST tiles nearby

src/fheroes2/battle/battle_arena.h
This is how it looks before the change:
relates to #4208
=> Fix Resurrection spell regression

appveyor.yml, docs/README.txt
Related to #4307
* Don't pack `extract_homm2_dos_anim.*` files in a ZIP archive - animations can be extracted by the `extract_homm2_resources.bat` alone even if ZIP file will be extracted to the directory with the OG;
* Mention the `extract_homm2_resources.bat` in `README.txt`;
* Rephrase some sentences.
=> Minor improvements to installation scripts

src/fheroes2/game/game_startgame.cpp
=> Properly show the attack cursor when the attack square is located at the top of the castle sprite

src/engine/xmi2mid.cpp
=> xmi2mid: avoid possible reordering of MIDI commands with the same timestamp

src/fheroes2/system/settings.cpp
At the moment when `Settings::Read()` is called, `AGGInitializer` doesn't exist yet, so `isPriceOfLoyaltySupported()` always returns `false` and therefore `music = expansion` setting from the `fheroes2.cfg` is never read correctly.
=> Do not reset music type to MUSIC_MIDI_ORIGINAL too early

src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/buildinginfo.h, src/fheroes2/castle/castle.h, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/castle/castle_town.cpp, src/fheroes2/game/game_startgame.cpp
close #4335
Also reduce memory usage for castle window and fix swap and meeting buttons during hero fading animation.
This is how it looks:
=> Add buttons in castle construction window

src/fheroes2/battle/battle_interface.cpp
=> Always highlight the cell under the cursor in combat if the Shadow Cursor is enabled, even if this cell is not reachable by the current unit

src/fheroes2/agg/agg.cpp, src/fheroes2/agg/agg.h
ResetMixer is suffering from the same issues with music player:
for MIDI files, it will call SDL that will add a lag of 0.1 sec for every
action on MIDI files. This means that when calling ResetMixer during loading,
we waste 0.1 sec as well.
The fix is simply to have the call to Music::Reset be done in the
dedicated audio thread so it doesn't block the main thread.
We can put the "stop music" task into the stack of existing _musicTasks,
because it behaves the same way, ie the logic has to process in priority
the latest task and can discard all the previous ones.
fixes #4463
=> ResetMixer is async by default

src/fheroes2/dialog/dialog_system_options.cpp
Mouse wheel is enabled on the following options:
- Music
- Effects
- Hero Speed
- AI Speed
- Scroll Speed
Any adjustments made using the wheel do not wrap over max. value, as opposed
to clicking.  Clicking still works as before.
Also unify the value wrapping math.
=> Allow to use mouse wheel to change system options

src/fheroes2/agg/agg.cpp, src/fheroes2/agg/agg.h, src/fheroes2/game/game_startgame.cpp
Here's a tentative fix for #4557 which I couldn't reproduce
I think the issue is as follows:
before this PR, we call PlaySound() with aync = false
This forces a call to "sync()", which will remove all pending music tasks. I think at this point it can potentially cancel the "stop music" tasks generated by the call to Agg::ResetMixer that maybe was not dequeued yet
NB : it's unclear to me why AGG::PlaySound in synch mode will erase all pending async music tasks, seems incorrect IMO
=> Fix terrain music being played during battle

src/fheroes2/game/game_credits.cpp
Making this PR now since it makes the work with my other PR less cumbersome with regards to .pot merging.
This removes calls to gettext for the proper names in the NWC credits.
=> Don't translate the proper names in Original Team's credits

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_spell.cpp
Relates to #4567
I changed the logic a little:
- if enemy has already defense < 4, we reduce the score of disrupting ray
(really rare corner case)
- if we have a weak army, it means we will do weak direct damage, so
it reduces the usefulness of disrupting ray. In that case I reduce the
score
If I replay the fight of #4567 it will make the AI stop spamming DR
and cast lightning bolt on the titans
NB : in theory the "enemy strength" should take into account the actual
enemy defense, that would also get lower as we cast DR on the enemy.
But the logic change I'm doing is still valid IMO
=> Better heuristic for AI usage of Disrupting Ray

src/fheroes2/kingdom/kingdom.cpp
fix #4579
`std::vector::erase()` should not be called while walking over the vector using `std::for_each()` because it invalidates current iterator as well as pre-calculated `end()`.
=> Kingdom::LossPostActions(): don't (indirectly) call erase() in the std::for_each() functor

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_troop.cpp
Previously, updating the board state was done only when the animation was playing
this fixes #4568
=> Resurect spell updates the board even in no-UI mode

src/fheroes2/heroes/heroes.cpp
=> If a hero on the map has the custom empty army (OG editor bug/feature), give him a minimum army (one unit of level 1)

src/fheroes2/battle/battle_only.cpp, src/fheroes2/castle/castle_well.cpp
This first part currently only affects peasants since they are the only creatures where min damage is the same as max damage. In the fheroes2 monster info window their damage is already reported as just "1", so this also makes it more consistent.
OG:
fheroes2:
This is most likely why Damage is written "Damg" in OG:
OG:
fheroes2:
=> Well : Clean up, optimize and make consistent with OG

src/fheroes2/dialog/dialog_system_options.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
1. The max value is 10, but we were going only up to 9 previously.
2. Move min/max logic from dialog to settings (it was partially there already).
=> Fix max music/sound volume

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_spell.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h, src/fheroes2/kingdom/speed.cpp, src/fheroes2/kingdom/speed.h
I fixed a few bugs around speed computation, where enemy speed was
incorrectly computed. I also change the "average enemy speed" so it's weighted by monster
strength
I also changed the heuristic a bit so monster that are already slow/fast
don't really benefit that much from the spell
This should somehwat improve issue #4129 even though the problem will still
remain that enemy will cast a slow spell even though it has very low score,
if it's the only spell available
=> Fix heuristic for slow/haste spell in battle

fheroes2-vs2015.vcxproj, fheroes2-vs2019.vcxproj, src/engine/image.cpp, src/engine/image_palette.cpp, src/engine/image_palette.h, src/engine/image_tool.cpp, src/engine/screen.cpp, src/fheroes2/game/fheroes2.cpp, src/tools/icn2img-vs2015.vcxproj, src/tools/icn2img-vs2019.vcxproj, src/tools/icn2img.cpp
icn2img tool now requires original kb.pal file.
The solution is not ideal as Display class needs a valid palette at the initialization.
=> Load palette from AGG file

src/fheroes2/game/game_interface.h, src/fheroes2/gui/interface_events.cpp
fix #4653
fix #4659
fix #4660
fix #4661
fix #4662
=> Interface::Basic::EventDefaultAction(): the action object can alter the status of the hero, so forcibly redraw the hero icon panel

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/route.cpp, src/fheroes2/heroes/route.h, src/fheroes2/maps/ground.cpp, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h
fix #1986
fix #2200
fix #2583
fix #4510
Please note that, while this change applies to AI-controlled heroes too, sometimes AI uses the `AIWorldPathfinder` apart from the some specific hero (for some strategic planning I believe). In this case "last move" logic will not be used - due to natural reasons.
=> WorldPathfinder: implement "last move" logic, fix wrong penalty calculation algorithm

src/fheroes2/heroes/heroes_action.cpp
=> Always mark Artesian Spring as visited, even if the hero was not able to drink from it

files/lang/cs.po, files/lang/de.po, files/lang/es.po, files/lang/fr.po, files/lang/hu.po, files/lang/it.po, files/lang/lt.po, files/lang/nb.po, files/lang/nl.po, files/lang/pl.po, files/lang/pt.po, files/lang/ru.po, files/lang/sv.po, files/lang/tr.po, src/fheroes2/heroes/heroes_action.cpp
- added titles and fixed messages for Pyramid dialogs ( close #4615, close #4613 )
- added titles for Skeleton dialogs ( close #4612 )
- added titles for Abandoned Mine dialogs ( close #4614 )
- added titles for Wagon dialogs
=> Add title for most of dialogs from map's objects

src/fheroes2/army/army_bar.cpp, src/fheroes2/dialog/dialog_selectcount.cpp
Edit: the implemented algorithm is described in [the following comment](https://github.com/ihhub/fheroes2/pull/4211#issuecomment-965673032). 
-----
The army split logic after this change:
Case#1 splitting a troop into an empty slot -> the fhereoes2 moves a troop into the destination slot
(no change here)
Case#2 splitting troops into an empty slot -> by default, the fheroes2 proposes to split one troop into the destination slot (the main idea of the issue)
(before the change, the fheroes2 proposed "fast split" (divides troops equally into both slots)
Case#3 splitting troops into the same troop type -> by default system proposes "fast split" (divides troops equally into both slots)
(before the change, the fheroes2 moved one troop from the source slot to the destination slot)
The rest …
=> Troops split logic change

src/fheroes2/dialog/dialog_marketplace.cpp
This relates to discussion https://github.com/ihhub/fheroes2/discussions/4621.
This makes the gift button always available in the marketplace instead of conditionally hidden.
Code for updating the trade area had to be added to the gift condition to avoid being able to gift resources and then trade those already gifted resources again and therefore twice. Without the adjustments, this would be possible if you select two resources to trade right before you open the gift dialog.
=> Improve marketplace gift button placement

src/engine/image.cpp
close #4762
Within `makeButtonWithShadow` function we were calling **Crop** method which by default creates 2-layer image and calls **Copy** function. The last one copies only image layer from Display (as Display is a single-layer image) without touching transform layer. Newly created image has undefined values within transform layer leading to such bizarre output in debug mode.
=> Fix image Copy function

src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/gui/interface_buttons.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/kingdom/kingdom.cpp
fix #4764
~~I decided not to do this when moving the hero because currently the existing hero path is reset when the hero goes to the SLEEPER mode, so he can't have a paved path and be in the SLEEPER mode at the same time.~~
=> Don't reset the hero's path in SLEEPER mode, reset the SLEEPER mode only with the beginning of the hero's movement

src/fheroes2/game/game_mainmenu.cpp
Use the same hotkey as in "New Game" dialog.
Also rename the variable in the code (used to be called `resolutionArea`, as
this previously opened resolutions dialog).
Not sure why `T` is the default hotkey.  I would find `O` more logical, as:
1. It's already used for "Options" within game and battle.
2. It's the next letter in the word "Config" (`C` already stands for "Credits" or "Campaign", but `O` is not yet taken).
=> Add hotkey for settings in main menu

src/engine/screen.cpp
=> Fix crash due to out of memory boundary access during resolution change

src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp
The title and description of the Settings information window no longer correspond to the change possibilities.
Changed the description when right-clicking game settings to highlight all possibilities (#4788).
New: 
Old:
Project built and ran successfully.
=> Updated Settings description to cover all actions

src/engine/logging.cpp
Related to #4755
Before:
After:
Quick and dirty solution.
=> Windows: Try to set the console codepage to the system codepage

src/engine/audio.cpp
It is recommended by manual to use the `Mix_GetError()` to get the last SDL mixer error, not the `SDL_GetError()`.
=> Audio: replace SDL_GetError() by Mix_GetError()

src/fheroes2/dialog/dialog_language_selection.cpp
to avoid possible out of window cases.
Now it looks like this:
=> Show languages in vertical order rather than horizonal

src/fheroes2/heroes/route.cpp
=> Consider the protected tile as an obstacle when recalculating the hero's path

src/fheroes2/dialog/dialog_marketplace.cpp
closes #4805 
From what I can see the sprite was offset by ~1 pixel because of the rounding when dividing. 
@LeHerosInconnu, can you confirm that this change fixes the issue ?
=> Fixed sprite position in marketplace

src/fheroes2/game/game_interface.h, src/fheroes2/game/game_io.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/gui/interface_focus.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/heroes/route.cpp, src/fheroes2/heroes/route.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
fix #4838
Alternative approach to the #4839 (more risky in terms of possible breaking changes). Fixes also the following cases:
---
Before this change:
After this change:
---
Before this change:
After this change:
=> Rework the logic of re-calculating the paths of heroes on the adventure map

src/fheroes2/heroes/route.cpp
Another follow-up after #4846 and #4878
=> Route::Path::GetFrontDirection(): return Direction::UNKNOWN if path is empty and path destination is not valid

files/lang/fr.po
Fixes a small typo in the French translation where the word for "percent" was missing.
=> Adds missing "pourcent" in description of Golden Bow

src/dist/Makefile
Currently there is an issue with `make clean` command on Windows, which can be reproduced as follows:
- build the game with mingw32
- run `make clean`
- build the game with mingw64
The linker fails in the last step, because `src/resources/fheroes2.res` remains 32-bit and cannot be linked into a 64-bit executable. It is not rebuilt because the input file, `src/resources/fheroes2.rc`, is older, and `src/resources/fheroes2.res` doesn't get removed by `make clean`.
In fact, `make clean` tries to remove `*.rc *res` inside `src/dist`, but no such files exist. What's worse, `*.rc` files are git-tracked and should not be cleaned at all.
=> fix `make clean` to correctly remove fheroes2.res file

src/fheroes2/game/game.h
This should fix sound issues like this: [sound-after-battle-bug.zip](https://github.com/ihhub/fheroes2/files/7810935/sound-after-battle-bug.zip). Set the Battles to Auto Resolve and Music Type to External, skip the turn and press OKAY in the battle result window. You will hear the `MUS::BATTLELOSE` instead of `MUS::COMPUTER_TURN` while the AI hero gets into the boat.
=> MusicRestorer: prevent attempts to play the old music by new instances while the music being restored is starting in the background

src/fheroes2/heroes/route.cpp
Regression after #4878. The Whirlpools are not working now.
=> Fix the Whirlpools

docs/INSTALL.md
As GitHub does not provide macOS runners on the ARM platform, zip archives are not created for Apple Silicon chips. This patch clarifies that x86-64 binaries on MacOS will not run on ARM64 platform and points affected users to compatible installation methods.
=> Update documentation related to MacOS

docs/DEVELOPMENT.md, docs/INSTALL.md
Currently the link from the "macOS ZIP archive" section of the `INSTALL.md` to the "macOS and Linux" section of the `DEVELOPMENT.md` always leads to GitHub. This PR fixes this. You can try it out here:
https://github.com/oleg-derevenetz/fheroes2/blob/development-md-link-fix/docs/INSTALL.md#macos-zip-archive
https://oleg-derevenetz.github.io/fheroes2/INSTALL.html#macos-zip-archive
=> INSTALL.md: make the link to the section of the DEVELOPMENT.md universal

files/lang/Makefile, src/dist/Makefile
GNU `sed` is incompatible with BSD `sed` in this regard: the GNU `sed` has the `-i[SUFFIX]` syntax, while the BSD `sed` has the `-i extension` syntax, so we have undesirable behavior at least on the latest macOS (files like `fheroes2.pot-e` for example).
=> Fix sed -i behavior on some systems

.github/workflows/cmake.yml, .gitignore, CMakeLists.txt, src/dist/Makefile
* Now CMake is able to regenerate and install translation files (not the ideal solution I believe, because it uses custom targets to generate the `src/dist/fheroes2.pot` and run `make` in the `files/lang` to update existing `.po` files and generate `.mo` files, and changing anything in the source tree is bad manners for CMake), but it's better than nothing. Not supported on WIN32 though.
* Now CMake is able to install the `fheroes2.key`, what was previously overlooked.
=> CMake improvements

src/fheroes2/world/world_pathfinding.cpp
=> PlayerWorldPathfinder::processCurrentNode(): always check that the candidate tile is not blocked, even if it is guarded by a nearby monster

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_quantity.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/resource/artifact.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h, src/fheroes2/world/world_loadmap.cpp, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h, src/fheroes2/world/world_regions.cpp, src/fheroes2/world/world_regions.h
related to #4509
Continuation of #4894. That's how it currently works ([WRLTEST.ZIP](https://github.com/ihhub/fheroes2/files/7824054/WRLTEST.ZIP)):
The `AIWorldPathfinder::reEvaluateIfNeeded()` now has optional parameter `considerWhirlpools` (`false` by default).
The debugging principle is just like in #4894 (right-click by the mouse when debug hero is selected).
Please note that `World::GetWhirlpoolEndPoints()` has been rewritten and now it is perfectly deterministic, so it can be used just like `World::GetTeleportEndPoints()` in the AI-related code.
BTW one more funny note: since whirlpools are multi-tile objects, the pathfinder currently chooses the "best tile" of the whirlpool for diving and surfacing from the water.  This leads to the following trick: instead of going around the …
=> AIWorldPathfinder: add support for paving the way through Whirlpools

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/heroes/heroes_action.cpp
Minor improvements while I'm here:
* Make the `Troops::GetWeakestTroop()` `const`;
* Rewrite the `WhirlpoolTroopLoseEffect()` in the same manner as the `AIWhirlpoolTroopLoseEffect()` by changing variable names to more telling ones.
=> Rename WhirlpoolTroopLooseEffect() -> WhirlpoolTroopLoseEffect(), minor improvements

src/fheroes2/maps/maps_tiles.cpp
close #4348
close #4491
close #4389
close #4339
close #4344
relates to #4495
Yes, it's a voodoo magic how I came up with this solution. The idea is that if the current tile has nothing but a single object and the tile below isn't the same tileset then it must be considered as a separate object.
=> Fix most of still existing cases with passabilities

src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
Now it's a part of battle settings window and can be changed anytime during battle. The current unit has the same cycling color as the current monster. Moved creatures have grayed icons. Border of rectangles associates with the color of monsters.
Also drawings now are faster.
=> Modify army order setting

src/engine/image_palette.cpp
There is a race condition between the initialization of two global variables:
image_palette.cpp:42    PaletteHolder paletteHolder;
screen.cpp:184          const uint8_t * currentPalette = PALPalette();
If the compiler choses to initialize `currentPalette` first, it uses data from uninitialized `paletteHolder`, typically resulting in all-black palette. This is what happens e.g. with Mingw64 toolchain.
The proposed solution is to access `paletteHolder` via a singleton.
=> Fix race condition on initialization of paletteHolder

src/engine/rand.cpp, src/engine/rand.h, src/engine/tools.h, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_main.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/kingdom/week.cpp, src/fheroes2/kingdom/week.h, src/fheroes2/world/world.cpp
Currently there is some inconsistency: most of the `namespace Rand` use `uint32_t` seeds, while `DeterministicRandomGenerator` and `hashCombine()` use `size_t` seeds (I suppose that's because `std::hash<...>::operator()` returns `size_t`). This leads to numerous `static_casts` back and forth. I suggest using `uint32_t` everywhere.
Pros of `size_t`:
* ???
Cons of `size_t`:
* `size_t` is implementation-defined (its size can vary from 16 bits to infinity), so we can't reliably save it to the savefiles, we should convert it to some fixed type anyway;
* Most of the existing `Rand` library uses `uint32_t`.
=> Migrate seeds from size_t to uint32_t

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h
I chose black for Berserkers, but it's a matter of taste.
=> Fix the crash on an invalid assertion when the "Army order" setting is turned on and someone casts Berserker spell

fheroes2.key, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/game/game_hotkeys.cpp
That's what happens when I press the `ESC` key to close the hero dialog:
https://user-images.githubusercontent.com/32623900/152235272-91fb71b0-5b6b-47f3-8990-5f4e230de838.mp4
I propose to use the `KEY_r` instead by default.
=> Don't use ESC key as a retreat key during battle, because it conflicts with the hotkey that closes the hero dialog

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_interface.cpp
Unifies the spell logging format for all spells. Previously, a number of spells (for example, Summon Elemental, Teleport or Earthquake) were not logged at all.
Also fixes the following issues:
* Earthquake may "heal" castle walls (pay attention to the condition of the wall at the bottom right):
https://user-images.githubusercontent.com/32623900/152602691-8ac7968a-1c79-4c28-915b-b725b9619f2f.mp4
* Spells are incorrectly logged if they are applied to the tail cell of a wide unit:
https://user-images.githubusercontent.com/32623900/152602941-850cd40d-c214-4264-b759-27e77054893c.mp4
=> Change the way spell casts are logged

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h, src/fheroes2/heroes/heroes_move.cpp
fix #4978
https://user-images.githubusercontent.com/32623900/152430675-2cdcb988-20dd-4fe7-a601-53092cdf1429.mp4
---
Also this PR fixes additional issue when long distance attacks were not performed on retaliation. Before (note that the Dragons' retaliation strike does not affect Minotaurs):
https://user-images.githubusercontent.com/32623900/152445048-a750ad87-0e0e-4c06-84d6-ae2207ddb213.mp4
After:
https://user-images.githubusercontent.com/32623900/152445060-d8cccc6e-0e50-4e92-a055-7a720b3a189e.mp4
---
Also this PR fixes issue when units affected by Hypnotize or Berserk spells were able to shoot nearby units from their own army, which may lead to crash or freeze. Before:
https://user-images.githubusercontent.com/32623900/152456112-f8fe7434-7d75-48ce-bcb3-b44c305cbb1d.mp4 …
=> Improve attack handling by AI (and not only AI)

files/lang/cs.po, files/lang/de.po, files/lang/es.po, files/lang/fr.po, files/lang/hu.po, files/lang/it.po, files/lang/lt.po, files/lang/nb.po, files/lang/nl.po, files/lang/pl.po, files/lang/pt.po, files/lang/ru.po, files/lang/sv.po, files/lang/tr.po, src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h
The idea is to throw away that hacky approach with `Arena::BreakAutoBattle()` and use the "regular" approach with `Battle::Command`. Perhaps not the ideal approach, but I think it's less "hacky" and more "general" than the current one.
=> Improve the handling of auto battle on/off events and log them properly

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_spell.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_army.h, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_main.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/system/players.cpp, src/fheroes2/system/players.h
* Rename variables in the code related to the order of units in battle - for better clarity (all those `part1`, `part2` looks a bit clunky);
* Move this code from `Battle::Force` to the anonymous namespace in the `battle_arena.cpp`, because it doesn't have any dependencies on `Battle::Force`, is not relevant to it and is needed only in one place;
* Fix code smells related to the implicit slicing of `Force` to `Units` (most of remaining "bugs" from SonarCloud);
* Fix code smell related to the implicit slicing of `Players` to `std::vector<Player *>` (another "bug" from SonarCloud);
* Fix typo in debugging output.
=> Slightly refine the code

src/fheroes2/game/game_startgame.cpp
fix #4723
Just like in OG, disembarkation still won't work because it requires the `OBJ_COAST`.
=> Allow a boat to move near the coast above the center of a town

src/fheroes2/heroes/heroes.cpp
=> Heroes::GetRangeRouteDays(): remove the special logic related to the mechanics of the last step, because now pathfinder can handle it on its own

src/fheroes2/maps/maps_tiles_quantity.cpp
Fixes #4893 .
Currently if monster stack is smaller than 7 it won't grow at all. Adjusting the logic to follow the original.
=> Fix neutral monster growth formula

src/engine/logging.cpp, src/engine/system.cpp, src/engine/system.h, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/gui/ui_tool.cpp
At least in one place (`DEBUG_LOG` macro) `localtime()` could be called from the non-main thread (via `AGG::AsyncSoundManager`) - only being built with DEBUG, but nonetheless.
=> Use localtime_r() or localtime_s() instead of localtime()

src/fheroes2/world/world.cpp
Fixes #4427 .
Bring the monster minimum down to OG levels, reduce the primary count accordingly. Current values are a bit too much.
=> Adjust monthly monster spawn

src/engine/audio.cpp, src/engine/audio.h, src/fheroes2/agg/agg.cpp, src/fheroes2/agg/agg.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/game_loadgame.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_over.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/game/game_video.cpp, src/fheroes2/gui/interface_events.cpp
fix #4511
Also this fixes an issue with `Game::restoreSoundsForCurrentFocus()` in MIDI mode if there is no sound for the current terrain. Before (unmute the sound in this video):
https://user-images.githubusercontent.com/32623900/153728485-729adb0f-d4f3-4898-965b-f2dc9f65eb5b.mp4
After:
https://user-images.githubusercontent.com/32623900/153728488-16dd4c8c-9733-4256-9a46-210b65c98179.mp4
Also this PR removes the only asynchronous `AGG::ResetMixer()` call and reverts the commit that introduced asynchronous `AGG::ResetMixer()` variant because it's unreliable and it did work only because it was followed by the non-async `AGG::ResetMixer()` call in the `Interface::Basic::HumanTurn()` (now `Interface::Basic::StartGame()`).
=> Various sound-related fixes

src/fheroes2/agg/mus.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/system/settings.cpp
fix #4506
Also fixed an issue where the non-MIDI sounds of objects were not played when switching music from MIDI to external. Before (notice that there is no Wagon Camp sound when switching the music from the MIDI to External):
https://user-images.githubusercontent.com/32623900/153762849-73217ead-94dc-48d1-a14e-6e37e4b67cb1.mp4
After:
https://user-images.githubusercontent.com/32623900/153762813-d83cb770-2997-4e12-b437-b53ad1945d36.mp4
---
> Magic Garden has wrong sound. It should have the same to Wagon Camp.
https://user-images.githubusercontent.com/32623900/153765957-9962f2c2-537c-415f-8f45-727034f5d375.mp4
> Observation Tower is missing any sounds: There should be played sound same to Abandoned mine.
https://user-images.githubusercontent.com/32623900/153765987-5e50e4ff-15ae-45c3-9433-b0 …
=> Fix missing sounds for some objects

src/fheroes2/ai/ai.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/world/world_pathfinding.cpp
fix #5008
Also fully assign the assessment of the army defending the tile to the `AIWorldPathfinder::processCurrentNode()`.
=> Allow AI fog discovery only for teleport endpoints with reachability information

src/fheroes2/game/game_startgame.cpp
To avoid repeating the AI music for each AI player from scratch. I forgot about it.
Regression after #5007.
=> Reset environment sounds and music theme at the beginning and at the end of the human turn only

src/fheroes2/ai/normal/ai_normal_battle.cpp
Fixes #4386.
Blinded and paralyzed units are evaluated as strength 0, so AI was ignoring them. Every other enemy stack will be prioritized regardless.
=> Archers should not ignore blinded units

src/engine/translations.cpp, src/engine/translations.h, src/fheroes2/army/army.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/system/settings.cpp
This PR addresses three somewhat related problems regarding `StringLower` applied to translated strings, e.g. "Archers" -> "A few archers":
1. In German, nouns are always uppercase. There is no way to implement this feature via translation files, `StringLower` has to be aware of the language.
2. `StringLower` uses `std::tolower` which by default only works with ASCII. Letters from CP12XX codepages will remain uppercase, e.g. "Mało Łucznicy" in Polish or "Мало Стрелки" in Russian.
3. The variable `locale` in `translations.cpp` is only updated when the language is first loaded (via `bindDomain`), it will not change after successive calls. Changing from "Language 1" to "Language 2" and then back to "Language 1" in the game will result in some locale-specific rules from "Language 2" to be …
=> Fixes with lowercase conversion of translations

src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h
* Additional assertions to catch potential programming errors early;
* Extended check for potential pathfinding loops (only if built without `NDEBUG`, i.e. with assertions enabled). The previous check for loops was more simplistic;
* Early determination of whether there is a path to a given index instead of `clear()` call at the end.
=> Improve path calculation by WorldPathfinder & AIPathfinder

.github/workflows/sonarcloud.yml
I'm a bit tired of seeing a workflow failure notification after every fork sync :)
=> Run the SonarCloud Analyzer workflow only for the main repo, not for forks

src/fheroes2/campaign/campaign_scenariodata.cpp, src/fheroes2/maps/maps_fileinfo.cpp
Follow-up to #5012
* `Maps::FileInfo::ReadMP2()`: return false if map contains invalid list of kingdom colors instead of an assertion failure;
* `Campaign::ScenarioData::loadMap()`: validate result of the `ReadMP2()`.
=> Maps::FileInfo validation improvement

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/world/world_regions.cpp
This should fix the following crash due to the invalid assertion:
```
Assertion failed: (regionID < _regions.size()), function KingdomTurn, file ai_normal_kingdom.cpp, line 112.
```
How to reproduce:
1. Run fheroes2;
2. Load the following savefile: [!1.zip](https://github.com/ihhub/fheroes2/files/8089177/1.zip);
3. Load the following savefile: [!2.zip](https://github.com/ihhub/fheroes2/files/8089182/2.zip);
4. Skip the turn.
Maybe this can be fixed in some other way, perhaps @idshibanov will advise something.
=> World::ComputeStaticAnalysis(): reset the region information for all tiles at the very beginning

.clang-tidy
This diagnostic doesn't work reliably anyway because it will not be reported if function declaration (name/return type/arguments) is not changed as part of PR. It is better to use the SonarCloud for this.
=> Clang-Tidy: disable readability-function-cognitive-complexity

src/fheroes2/gui/interface_events.cpp
This should fix the issue where the sound of the terrain does not change when teleporting using Stone Liths with a space bar. Before:
https://user-images.githubusercontent.com/32623900/154559062-d52317b9-3020-49d3-8f8f-700623884a8b.mp4
After:
https://user-images.githubusercontent.com/32623900/154559089-6136ac21-181c-4526-8907-ef46fa6750a2.mp4
=> Interface::Basic::EventDefaultAction(): reset and redraw the focus after hero's action

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/world/world_pathfinding.cpp
=> Fix the logic of protecting tiles by neutral monsters

src/fheroes2/ai/ai.h, src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h
Fixes #4588 . Fixes #3300 .
Essentially if AI is left without castles and currently on timer it will take more risks and should focus on castle capture.
=> Make AI more aggressive in losing situation

src/fheroes2/monster/monster.cpp
Fixes #4591 .
GetAttack() or GetDefense() are overridden in derived classes and will account for army/combat bonuses automatically when called.
=> Fix monster strength heuristic regression

src/fheroes2/battle/battle_tower.cpp, src/fheroes2/battle/battle_tower.h, src/fheroes2/battle/battle_troop.h
In addition to already disabled copy (and therefore move) assignment for these classes. Current battle-related code in many places relies on the fact that all units are in heap and their addresses can be freely compared - so at least such a unit cannot be accidentally passed as a function argument via a copy (or move) instead of pointer or reference.
=> Explicitly disable copy (and therefore move) constructor of Battle::Unit and Battle::Tower

.github/workflows/cmake.yml, CMakeLists.txt, src/Makefile, src/Makefile.vita, src/engine/CMakeLists.txt, src/thirdparty/CMakeLists.txt, src/tools/Makefile
At least with GCC, `-pthread` implicitly adds `-D_REENTRANT`, which is the compile-time flag:
```
oleg@gentoo ~ $ gcc -dumpspecs | grep pthread
%{posix:-D_POSIX_SOURCE} %{pthread:-D_REENTRANT}
[...]
```
so using it just with linker is not enough (at least in general).
This issue came out when I tried to build fheroes2 as WASM using Emscripten (just out of curiosity). Emscripten was not able to link the final executable with `-pthread` if there were object files that used threads or atomics, but built without `-pthread`.
=> Compile with -pthread, not just link with it

files/lang/cs.po, files/lang/de.po, files/lang/es.po, files/lang/fr.po, files/lang/hu.po, files/lang/it.po, files/lang/lt.po, files/lang/nb.po, files/lang/nl.po, files/lang/pl.po, files/lang/pt.po, files/lang/ru.po, files/lang/sv.po, files/lang/tr.po, src/fheroes2/campaign/campaign_scenariodata.cpp
This is needed to support translations, such as Russian and German.
=> Allow a short name for all campaign bonus artifacts and spells

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/world/world_regions.cpp
Fixes #4566 .
Refactored recruitment decision logic to cover edge cases when there's more castles than heroes. Excluded patrol heroes from the list. Now AI should select a castle with most the army if multiple available.
Also fixed a minor issue with map region neighbors list.
=> Update AI hero recruitment logic

.github/workflows/pr_author_auto_assign.yml
It seems that this Action doesn't follow the [recommended versioning practice](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions), so specifying just a major version is not enough :(
=> Fix the versioning of toshimaru/auto-author-assign

src/engine/pal.cpp, src/engine/pal.h, src/fheroes2/agg/agg_image.cpp
No need to create a second copy of the same array. Plus add extra assertions.
=> Optimize memory usage for palettes

.github/workflows/clang_tidy.yml, .github/workflows/code_style_check.yml, script/tools/check_copyright_headers.py
These workflows access commits other than the current one (such as `HEAD^`) and default `fetch-depth` (1) is not enough for them.
P.S. I recommend to sync existing PRs with `master` after merging this one.
=> Increase the fetch-depth for clang_tidy.yml and code_style_check.yml workflows

src/fheroes2/battle/battle_interface.cpp
relates to #983
Because of this missing frame under normal speed we did not have 120 ms delay.
=> Show missing last frame of wince animation

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/heroes/heroes_action.cpp
- AI did not have any action while moving onto Sirens object while it should
- sirens must remove at least one unit from a stack which has more than 1 unit
- add experience UI element to Sirens dialog (close #4699 )
=> Fix Sirens logic, AI interaction and UI

src/fheroes2/game/game_campaign.cpp
close #5052
However, in the original game it is not possible to do so.
=> Allow selecting options while restarting a campaign scenario

src/fheroes2/game/game.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/game/game_scenarioinfo.cpp
Rendering of such screen sometimes takes more time than just to load a single map or save file.
=> Remove Map loading screen

src/fheroes2/campaign/campaign_data.cpp, src/fheroes2/campaign/campaign_data.h, src/fheroes2/campaign/campaign_scenariodata.cpp, src/fheroes2/campaign/campaign_scenariodata.h, src/fheroes2/game/game_campaign.cpp
- add popup windows for campaign awards and bonuses ( close #4501 )
- increase bonus name area name by 5 pixels to accommodate long names
- fix award name not being translated after language switching
=> Add popup windows for campaign awards and bonuses

.github/workflows/clang_tidy.yml, script/tools/check_code_format.sh, script/tools/check_copyright_headers.sh
Related to #5072
Previously, `git` failures in pipelines were not detected and everything went like the `git` output was just empty. Now such failures will be detected like [here](https://github.com/ihhub/fheroes2/runs/5439323484?check_suite_focus=true) and [here](https://github.com/ihhub/fheroes2/runs/5439323619?check_suite_focus=true) - just in case if `fetch-depth: 50` will not be deep enough.
=> Check for the git failures in pipelines

src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/agg/agg.cpp
This adds a search for FLAC files if Ogg files aren't found.  There don't seem to need to be any other changes, as SDL_mixer takes care of playback, though it does depend on SDL_mixer being compiled with FLAC support.
=> Added search for FLAC files if Ogg files aren't found

src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_levelup.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_meeting.cpp
- for hero level up window with no secondary skill display the primary skill icon ( close #5102 )
- for hero level up window with one secondary skill make the skill right clickable ( close #5099 )
- for Anduran assembly window show artifact name as a title ( close #5100 )
- fix Witch's Hut message body ( close #5097 )
- display experience amount for Tree of Knowledge ( close #5092 )
=> Fix some issues with UI windows

src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_dialogs.cpp
fix #5107
Currently the captain has the name of the castle instead of just "Captain". I like it better so I left it as it is.
=> Let the hero surrender to the captain during the siege

src/engine/agg_file.cpp, src/engine/agg_file.h, src/engine/audio.cpp, src/fheroes2/agg/agg.cpp, src/fheroes2/agg/agg.h, src/fheroes2/agg/bin_info.cpp, src/fheroes2/agg/mus.cpp, src/fheroes2/agg/mus.h
Reworked the way how we read music files. Previous implementation was slow and incorrect. We were expecting ogg files to be present while searching flac files.
Expanded the support of file types to MP3 ( close #5063 ).
=> Add MP3 file support

src/fheroes2/battle/battle_dialogs.cpp
=> Properly center the first sentence in the battle surrender dialog

src/fheroes2/game/game_video.cpp
We should not waste resources to do unnecessary work for rendering.
=> Do not render extra frame while playing an audio only video file

src/engine/smk_decoder.cpp
The heaviest video is for the Original Campaign. Based on my measurements the constructor of SMKVideoSequence class was taking ~270 ms to load INTRO.SMK file. The problem was in extra calls to smk library as well as too precise memory reallocation instead of using the default power of 2 approach. After these changes the constructor takes around 120 ms.
We can do further optimizations but at least we significantly reduced video loading times as of now.
=> Greatly speedup heavy video loading

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h
In OG:
https://user-images.githubusercontent.com/32623900/158616823-455eb4ea-af67-42de-acb2-be3cf1e9f166.mp4
Currently in fheroes2:
https://user-images.githubusercontent.com/32623900/158616907-a7fb812d-a61a-4829-94d9-c9f8ebaa4107.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/158617006-a2fdc1eb-3afd-46c2-bd37-b54dbb7db5ec.mp4
---
Also it seems that in OG defending unit doesn't turn to the attacker who has the "no enemy retaliation" ability:
https://user-images.githubusercontent.com/32623900/158617478-385c3ecf-76a6-4735-83c8-aa8ff0cfc299.mp4
Currently in fheroes2:
https://user-images.githubusercontent.com/32623900/158617557-16b3045b-f1b1-42b4-ace8-6c1641e6c7b5.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/158617606-f14fa725-9490-4f6f-9cfa-2e844bf …
=> Set the direction for attacking and defending units in battle in a more OG-like way

src/engine/image.cpp
close #5131
The original issue happens when a user resize the window leading the screen to have all 'skip' values in transform layer. `ApplyRawPalette` function did not take into account single-layer images. The issue was not observable without changing the resolution because of `fill()` method calls for Display object.
=> Fix incorrect logic for palette application function

VisualStudio/common.props, src/fheroes2/agg/agg.cpp, src/fheroes2/game/fheroes2.cpp, src/fheroes2/h2d/h2d.cpp, src/fheroes2/h2d/h2d.h
Since we want to bring the best experience to players and our h2d file contains some fixes over the original graphics we need to make h2d file presence to be mandatory in order to run the game. This approach will ensure that users will be using not a half-copied product.
=> Add mandatory requirement of h2d file being present

src/fheroes2/battle/battle_action.cpp
Follow-up to #5129
Related to the #5048
This PR implements proper animation when unit attacks from his tail cell. Before:
https://user-images.githubusercontent.com/32623900/159171242-12a5f990-c046-47d7-87d9-f2e9e79551e8.mp4
After:
https://user-images.githubusercontent.com/32623900/159171249-a2cc6be4-6e20-491a-830d-0c9ca6a9744e.mp4
=> Combat: calculate the position of the wide attacking unit based on the direction of attack

src/fheroes2/agg/agg.cpp
We were wasting memory resources by doing nothing. Now loading of resources on low-profile machines will be even faster.
=> Remove memory copy while reading data from AGG file

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_castle.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/world/world_regions.cpp
Fixes #5046 .
AI players will upgrade magic guild more often when there's heroes with appropriate Wisdom skill and current map region is considered to be safe.
Also includes bug fixes related to region generation and AI map scan at the beginning of the turn
=> Build player influence map to inform AI kingdom development decisions

src/fheroes2/ai/normal/ai_normal_hero.cpp
Adjust object values for fighter hero as of right now they are simply chasing monsters around the map/not even picking up artifacts at times.
=> Optimize fighter hero priorities

src/fheroes2/gui/interface_radar.cpp
Fixes #5152 .
Set white and green values to original color shades. Current green was also hard to see on the grassland terrain.
=> Update minimap colors

.github/workflows/clang_analyzer.yml, .github/workflows/clang_tidy.yml, .github/workflows/clang_tidy_comments.yml, .github/workflows/cmake.yml, .github/workflows/code_style_check.yml, .github/workflows/make.yml, .github/workflows/msvc.yml, .github/workflows/pr_author_auto_assign.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml, .github/workflows/sonarcloud.yml
Now we have a complex set of workflows with a couple dozen of jobs, and there are the following problems with them:
* Slow feedback. Quick but important checks (such as code style check or Clang-Tidy) may be started too late.
* Even if one of the essential checks fails, other workflows still continue to run, which is pointless.
* After updating the PR branch, the checks already running continue to run, which is pointless and slows down checks for the updated PR as well as other PRs.
This PR is designed to try to address these problems using the following techniques:
* Make feedback faster by running fast, but essential checks first, and failing fast the build in case of any issues.
* Automatically cancel already running workflows after updating the branch and before running a new workflow …
=> Optimize GitHub Actions workflows

src/engine/smk_decoder.cpp
Saves around 1.8 MB for intro video of the original campaign.
=> Avoid extra memory copy during video loading

src/fheroes2/army/army_troop.cpp, src/fheroes2/army/army_troop.h, src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_army.h, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h, src/fheroes2/monster/monster.cpp, src/fheroes2/monster/monster.h
fix #5168
Also fixed an issue when resurrected (not truly resurrected) units were taken into account when calculating the cost of surrender.
=> Fix the calculation of the cost of surrender

src/fheroes2/game/game_newgame.cpp
I noticed the VICTORY track getting called right after "choosing your lord" in the original campaigns for no apparent reason. You don't hear it getting played and it shouldn't be played here.
=> Remove unnecessary call to play VICTORY music during Campaign intro

src/engine/serialize.cpp
This significantly increases loading of translation files, save files and AGG files.
=> Avoid extra memory reallocations while handling stream buffers

src/engine/image.cpp, src/engine/serialize.cpp, src/engine/serialize.h
Reduce the amount of memory being used (especially within StreamFile::toStreamBuf method).
=> Use move operators for Stream Buffer

.github/workflows/make.yml, CMakeLists.txt, Makefile, files/lang/Makefile, src/CMakeLists.txt, src/Makefile, src/Makefile.all, src/Makefile.bsd, src/Makefile.mingw, src/Makefile.mingw32, src/Makefile.osx, src/Makefile.switch, src/Makefile.vita, src/dist/Makefile, src/engine/CMakeLists.txt, src/engine/Makefile, src/fheroes2/CMakeLists.txt, src/thirdparty/CMakeLists.txt, src/thirdparty/libsmacker/Makefile, src/tools/CMakeLists.txt, src/tools/Makefile
Make the build process a bit faster, disable some warnings specific for PSV and issued for the SDL library code, use `CCFLAGS` (Common CFLAGS) for both C and C++ compilers instead of using just `CFLAGS` and removing the C++ specific options via the `filter-out` construct, add copyright headers to makefiles.
Hi @ihhub could you please remove the Clang-Tidy from the list of required checks? It does not run if there is no changes in source files, like in this PR.
=> GitHub Actions: use shallow clone for VDPM, fix broken PSV build, improve Makefiles

src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/game_over.cpp, src/fheroes2/game/game_startgame.cpp
This plays the Victory theme when winning a scenario after the Dragon animation like OG, instead of the Main Menu theme like  it does currently, and it makes sure that the Main Menu theme continues to play if opening the High Score from the Main Menu, like in the original game.
This also future-proofs for when the Victory theme will be played while showing the Congratulations text behind the painting after the Dragon animation, but before the High Score menu is displayed.
=> Fix High Score Music after winning scenario

src/engine/image.cpp, src/fheroes2/battle/battle_interface.cpp
This fixes #5167 . Also for cases when the number of units to display is more than the screen the order is floating (relates to #5166 ) which means that the bar will show only limited number of units but shifts the order during the progression of the battle.
=> Fix army order option related crash

src/Makefile, src/Makefile.vita, src/fheroes2/army/army_bar.h, src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/castle/captain.cpp, src/fheroes2/dialog/dialog_marketplace.cpp, src/fheroes2/dialog/dialog_resolution.cpp, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/dialog/dialog_selectscenario.h, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game_campaign.cpp, src/fheroes2/gui/interface_icons.h, src/fheroes2/heroes/heroes_meeting.cpp, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/kingdom/color.cpp, src/fheroes2/kingdom/luck.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/monster/monster.cpp, src/fheroes2/objects/objcrck.cpp, src/fheroes2/resource/artifact.cpp, src/fheroes2/resource/artifact.h, src/fheroes2/spell/spell.cpp, src/tools/82m2wav.cpp
Also this PR fixes the build for PSV (once again).
In GCC, `-Weffc++` is broken and useless. For example, even the latest GCC [reports](https://godbolt.org/z/WdKKdsvWz) the following warning:
```
<source>: In constructor 'C::C()':
<source>:6:5: warning: 'C::s' should be initialized in the member initialization list [-Weffc++]
6 |     C() {};
|     ^
```
for the following code:
```cpp
#include <string>
class C
{
public:
C() {};
private:
std::string s;
};
int main()
{
C c;
}
```
despite the fact that `std::string` has perfectly safe default constructor.
=> Fix the build for PSV, add multiple warning-related compiler flags to the Makefile, remove useless -Weffc++ from the waiting list

.clang-tidy
Requested by @ihhub
Although `reinterpret_cast` conversion is dangerous in general, it's perfectly legal to use it in certain cases (for example, when accessing a byte representation of an object by casting a pointer to it to the `char *`).
=> Clang-Tidy: disable the cppcoreguidelines-pro-type-reinterpret-cast check

src/fheroes2/agg/agg.cpp
Case-sensitive filesystems do not support the current approach so we have to revert back to the original but with small modifications.
Regression of #5157 
Notes:
- h2d file related logic can remain as it is as we distribute the file and we know the actual name
- the same problem is present for music files but I'll fix it in a separate pull request.
=> Fix regression for AGG file search

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army_bar.cpp, src/fheroes2/army/army_troop.cpp, src/fheroes2/army/army_troop.h, src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h, src/fheroes2/castle/castle.cpp, src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/monster/monster.cpp, src/fheroes2/monster/monster.h
fix #5188
Regression after #5170
The problem is that currently in many relative classes (which inherit from each other) there are non-virtual methods that have the same names, but do different things that are not very compatible with each other. The previous approach was to make the `GetCost()` and `GetUpgradeCost()` `virtual` in related classes (such as `Monster`, `Troop` and `Battle::Unit`), but this may be error-prone in current circumstances, because the wrong method may be called easily (which is what in fact happened). This PR offers the second approach - I have changed the names of these methods to different ones, I hope that this approach is less error-prone.
=> Fix the calculation of the cost of upgrading troops

src/engine/image_tool.cpp, src/engine/image_tool.h, src/tools/icn2img.cpp, src/tools/til2img.cpp
WITH_IMAGE is used only for SDL 2 and it doesn't define the PNG format for SDL 1.
=> Fix incorrect WITH_IMAGE macro usage

.github/workflows/make.yml, CMakeLists.txt, Makefile, src/Makefile
I usually do this by patching the `Makefile`, so I decided to add options instead. [UBSAN](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)+[ASAN](https://clang.llvm.org/docs/AddressSanitizer.html) introduce relatively small runtime overhead (about 2x), so I use this combination on the everyday basis, while UBSAN+[TSAN](https://clang.llvm.org/docs/ThreadSanitizer.html) introduce significantly larger overhead (5x - 15x).
=> Makefile: add options to build the project with UBSAN, ASAN or TSAN

src/fheroes2/gui/interface_icons.cpp, src/fheroes2/gui/interface_icons.h, src/fheroes2/gui/interface_list.h
We don't need to draw the background for an icon as the icon has the same size as the background image.
Also use a range of background images for the icons. Previously we used only 1 image.
=> Speed up castle and hero icons rendering on adventure map

src/fheroes2/heroes/heroes_action.cpp
fix #5199
I have no idea why we played both `M82::TREASURE` and pickup sound in this case. Let's play just `M82::TREASURE`.
=> Play just the M82::TREASURE sound when we picked up an artifact due to an event

src/fheroes2/battle/battle_arena.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
It's logical that slowest units after waiting should go first. Also AI has no knowledge of such option.
=> Remove "battle: reverse wait order (fast, average, slow)" option

src/engine/screen.cpp
If we call `SDL_SetWindowSize()` before turning off the fullscreen mode, the size of the resulting window may be wrong. This issue may be observed not only in macOS, but on other systems where `SDL_WINDOW_FULLSCREEN_DESKTOP` is used (e.g. Linux).
Before:
https://user-images.githubusercontent.com/32623900/161860527-0295a3cc-4dbb-467d-826e-4536b9f5a4ca.mp4
After:
https://user-images.githubusercontent.com/32623900/161860814-1c36bf88-c006-43df-8b03-5120f136b88f.mp4
=> Fix switching fullscreen mode in macOS for certain resolutions

src/fheroes2/agg/agg_image.cpp
Relates to this: https://github.com/ihhub/fheroes2/issues/5114
Had to use some more letter spacing to avoid overlapping when pressing the button.
=> Generate Italian Battle Button

src/fheroes2/game/game_video.cpp
Previous approach was bug-prone as we assumed that file names are in all capital letters which might not be always true.
regression from #5125
=> Fix video file loading for case-sensitive filesystems

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/army/army.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
fix #5273
This issue may be observed not just with abandoned mines, but with all objects for which guardians may be set (as the result of the Haunt spell, as the result of the Set Guardian spell or by setting a guardian in case when the "world: allow to set guardian to objects" is enabled) when the attacking hero fails to defeat the guardians.
Also this PR fixes an issue when guardians were always controlled by AI even if they were set on the mines controlled by a human player (I thought I even saw the related issue, but I wasn't able to find one).
=> Properly work with guardians on the objects that can be captured

src/fheroes2/game/game_video.cpp
fix #5282
Mixer is usually used to play ambient sounds, which may have different volume depending on the distance. We should reset the volume of mixer channels to the default one before playing video soundtracks.
=> Reset the mixer volume before playing video soundtracks

.github/workflows/msvc.yml, script/windows/fheroes2.iss
Follow-up to #5231
Unfortunately replacing `GITHUB_RUN_NUMBER` with the `GITHUB_RUN_ID` did not bring the desired results, because, although `GITHUB_RUN_ID` is workflow-independent, it seems that there is no requirement for it to increase monotonically, so it is not suitable as the build number. I removed generation of the `FHEROES2_BUILD_NUMBER` from the MSVC workflow for a while and used the `ignoreversion` [flag](https://jrsoftware.org/ishelp/index.php?topic=filessection) in the Inno Setup instead. May be in future I'll come up with a better solution.
=> Fix versioning of MSVC builds

src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h
Added a new variable controlling how much spell points are reserved for adventure spells, half by default. Reset to 0 if there's nothing to do, so "stuck" heroes should teleport out.
=> Reserve half of spell points for dimension door

src/fheroes2/dialog/dialog_giftresources.cpp
This commit was written for issue #4804. It replaces the call to Game::GetStep4Player(...) with an inlined change that uses integer ceiling arithmetic to replace Game::GetStep4Player(...). The functional requirement was to ensure that the colored squares representing players would be evenly spaced was met.
=> Fix spacing of player squares in Select Recipients window and horiz. center resource icons for "Your Funds" and "Planned Gift"

src/fheroes2/battle/battle_only.cpp, src/fheroes2/battle/battle_only.h, src/fheroes2/resource/artifact.cpp
Currently it is possible:
This PR fixes this, and also the spell book will always be added to the first slot.
=> Do not allow a hero to have multiple spell books in the "Battle Only" mode

.github/workflows/sonarcloud.yml, sonar-project.properties
Thus, we only need to update the project version in two places: `version.h` and `version.txt`.
=> GitHub Actions: Automatically generate version information for SonarCloud

src/fheroes2/agg/agg_image.cpp
This addresses the French part of issue: https://github.com/ihhub/fheroes2/issues/5237
This makes a French 'Gift' button with the text 'Donner'. That's the word that was approved by French-speaking users.
The Gift button generated for English had to be moved to `generateEnglishSpecificImages()`, similar to what was done for the Battle Only button.
Added logic to fill with Evil button color to `getButtonFillingColor()`.
The current state of the generated buttons:
I had to refer to some different ICNs for the Evil button generation than than the Good, because the corresponding ones I used for the Good button didn't have the same background color as other evil ICNs (ex. campxtrg and campxtre).
There could be a reason to go back and make the Good button with the counterpart ICNs as the Evil …
=> Generate French 'GIFT' button

src/fheroes2/dialog/dialog_quickinfo.cpp
This addresses comment and part of issue: https://github.com/ihhub/fheroes2/issues/4797#issuecomment-1071123890
Use of `text.h` was replaced with `ui_text.h`.
Languages will need to be updated with this change since the original source string was changed.
=> Move statnumber column for hero quick info

src/engine/tools.cpp
We were not applying K and M for 1000 and 100000 values.
=> Fix 1000 and 100000 short values display

src/fheroes2/dialog/dialog_game_settings.cpp, src/fheroes2/dialog/dialog_system_options.cpp
This addresses one part of issue: https://github.com/ihhub/fheroes2/issues/5244
This also swaps position of "Settings" and "Experimental" in the main menu's system options since that fits in with the other headers: Language and Resolution.
Replaced use of `text.h` with `ui_text.h`.
=> Add double-lined headers to adventure map options.

src/fheroes2/ai/normal/ai_normal_hero.cpp
Current AI does fog discovery is nothing else to do which makes AI heroes to walk around visible territory and not to explore the map. This is a weak strategy as uncovering fog usually gives more resources and advantage. Now AI heroes have fog discovery value which is rated very low but still encourages them to explore.
With such change we can introduce a new type of AI heroes: explorers who would focus on fog discovery.
=> Encourage AI to explore more

src/fheroes2/agg/agg_image.cpp, src/fheroes2/game/game_logo.cpp, src/fheroes2/gui/text.cpp, src/fheroes2/gui/text.h, src/fheroes2/gui/ui_text.cpp, src/fheroes2/gui/ui_text.h
We need to transit to the new fheroes2::Text classes. Right now we are mixing both old and new text classes which confuses many developers.
=> Remove Large old Text usage

src/fheroes2/agg/agg.cpp, src/fheroes2/game/game_video.cpp
The same technique as for music files: we put directory where we find a current video file at the first place so for the subsequent runs we will search there.
Also avoid copying of strings where it is not necessary.
=> Improve search for video files

script/homm2/extract_homm2_resources.ps1, script/homm2/extract_homm2_resources.sh
They reside not in `ANIM` but (for some reason) in `HEROES2/ANIM`.
=> Properly extract animations from the GOG distribution of HoMM2 for Windows

src/fheroes2/campaign/campaign_data.cpp, src/fheroes2/game/game_campaign.cpp
Also fix invalid call leading to a cut of video playback.
=> Fix incorrect video playback on Descendants campaign, scenario 5

src/engine/localevent.cpp, src/engine/localevent.h, src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_only.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/castle_town.cpp, src/fheroes2/dialog/dialog_arena.cpp, src/fheroes2/dialog/dialog_buyboat.cpp, src/fheroes2/dialog/dialog_chest.cpp, src/fheroes2/dialog/dialog_levelup.cpp, src/fheroes2/dialog/dialog_message.cpp, src/fheroes2/dialog/dialog_recrut.cpp, src/fheroes2/dialog/dialog_resolution.cpp, src/fheroes2/dialog/dialog_selectcount.cpp, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_hotkeys.cpp, src/fheroes2/game/game_hotkeys.h, src/fheroes2/game/game_loadgame.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/ui_button.cpp, src/fheroes2/gui/ui_dialog.cpp, src/fheroes2/spell/spell_book.cpp
- interpret NumPad Enter as a normal Enter
- always save fheroes2.key file to have an updated list of hotkeys
- add hotkey for View Intro within campaign dialog
- rename KEY_RETURN into KEY_ENTER to be more understandable
- rename some hotkeys to be more understandable
- remove DEFAULT_LEFT and DEFAULT_RIGHT to do not confuse players as these hotkeys were not set at all
- add keys for moving corner movement related hotkeys
=> Polish HotKey related code

src/engine/screen.cpp
=> Fix a bug when a lowest resolution appears twice in a list

src/fheroes2/resource/artifact.cpp, src/fheroes2/resource/artifact.h
To fix the crash caused by an assertion failure.
=> Battle Only mode: always assign a random spell to the Spell Scroll

src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h
fix #5232
Previously, AI could in some situations "jump over" the levels of the Mage Guild during construction, which in turn led to unrecoverable violations of the requirements for the construction of buildings (like with Mausoleum in the related issue).
Related to #5263.
=> Do not allow higher-level Mage Guilds to be built if the previous-level Mage Guild has not been built yet

.github/workflows/clang_tidy.yml, .github/workflows/clang_tidy_comments.yml, .github/workflows/push.yml, .github/workflows/translation_update.yml, .gitignore
close #5383
Instead of forcing poor Windows developers to install Cygwin and `gettext`, deal with `bash`, `make`, and so on, I suggest just automatically regenerate `fheroes2.pot` and `*.po` on each push event. This will increase number of commits in log, though.
=> GitHub Actions: update translation files on push

src/engine/translations.cpp
This tidies up the Switch statement for gettext plural forms and reverts some changes to the order of cases. In other words I made the various locales use the same plural form as before, but I only checked the locales we currently have translation files for to see what plural expression they use.
Couldn't find a Locale for Hungarian even though a hungarian .po exists with quite a few translated strings.
These are used in cases like these for Russian so that the correct plural form is used:
Before this the Russian translation was using the Lithaunian plural form expression, which is not the same for Russian. Not sure if this was intentional.
=> Tidy up and fix gettext plural forms for languages

files/lang/Makefile, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_language.cpp, src/fheroes2/gui/ui_language.h
This  adds a Spanish language option to the game and font support.
The existing Spanish translation is 54 % complete.
Spanish uses CP1252 so I added its letters in a new function `generateCP1252Alphabet()`.
Tidied up so that German, Norwegian and Italian all use CP1252 too. French is supported by CP1252 as well, but the OG encoding does not support that. A decision on how to deal with this is necessary.
Some letter generation improvements to existing CP1252 letters like lowercase `ì`.
All Spanish characters have been implemented.
Current progress:
=> Add initial Spanish language support and move German, Norwegian and Italian to CP1252 generation function

src/engine/serialize.h
While all modern compilers I aware of fire this `static_assert()` immediately when compiling the template (what is in fact is needed here if there is no valid byte order info present), formally (according to the standard) the template for which no valid specialization can be generated is "ill-formed, no diagnostic required" (and, formally, no valid specialization can be generated for the template with `static_assert( false, ... )`). So let's just replace it with the `#error` preprocessor directive - just in case.
=> fheroes2::getLEValue(): replace static_assert() by #error

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/monster/monster.cpp, src/fheroes2/monster/monster.h, src/fheroes2/monster/monster_info.cpp, src/fheroes2/monster/monster_info.h
Calculation of army strength is a heavy operation and we should avoid calling it over and over again. However, caching should be error-prone to avoid incorrect estimations of strength by AI. close #3840 
Also this pull request fixes a case when AI was ignoring shrines with "View All" spell.
=> Cache AI hero's and neutral monsters' strength during AI turn

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_arena.cpp
fix #5342
Currently the logic is as follows:
* The limit is triggered if the number of dead in both armies does not change within 50 turns;
* The limit is applied only to the **_attacking AI-controlled army_** (the concept of "AI-controlled" in this particular case includes instant or auto battle mode). It is never applied to the defending army (it doesn't matter whether is controlled by AI or not), and also it is not applied to the attacking army if it is **_directly_** controlled by a human player at the moment (neither instant battle or auto battle are currently in effect);
* If the attacking army is controlled by AI player, and the limit of turns is exceeded, then the attacking hero will retreat (and lose his army);
* If the attacking army is controlled by human player, and there is …
=> Impose a limit of turns for an attacking AI-controlled hero

src/fheroes2/gui/interface_status.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
With recent changes for the past release AI became slower and it is noticeable on slower machines. Since we are going to add more logic to AI it is important to keep balance between performance and logic complexity. This pull request improves 2 places for AI turn:
- during `RedrawTurnProgress` method call render only status window instead of re-rendering the whole frame. It releases ~10% of overall AI turns
- `ClearFog` and `getFogTileCountToBeRevealed` where relying on an internal function which creates a vector, resize it due to item insertion and frees the memory. In particular `getFogTileCountToBeRevealed` can be called a lot of time during a single AI hero's movement calculation if there are many discovered cells.
=> Speed up AI turn

files/lang/Makefile, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_language.cpp, src/fheroes2/gui/ui_language.h
This replaces all special characters with their most similar latin counterpart.
These letters were added: `Ã, Â, Ç, Ê, Õ, Ô, ã, â, ç, ê, õ, ô`.
=> Add Portuguese language option and initial font generation

files/lang/Makefile, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_language.cpp, src/fheroes2/gui/ui_language.h
All necessary fonts were already present in CP1252.
Note that for some reason the person who made the current Swedish PO chose to replace all instances of special characters with similar latin characters. This would have to be fixed by someone competent in the language.
=> Add Swedish in-game option and font support

src/fheroes2/agg/m82.cpp, src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/castle/mageguild.cpp, src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/monster/monster_info.cpp, src/fheroes2/spell/spell.cpp, src/fheroes2/spell/spell.h
- return messages during battle should be based on monster's abilities
- monster quality and strength calculation depends purely on abilities
- do not show random spells in battle only mode
- rename Stone spell into Petrify spell to be consistent with its description
=> Unify code for monsters to avoid hardcoded monster types

files/lang/be.po, files/lang/bg.po, files/lang/cs.po, files/lang/de.po, files/lang/es.po, files/lang/fr.po, files/lang/hu.po, files/lang/it.po, files/lang/lt.po, files/lang/nb.po, files/lang/nl.po, files/lang/pl.po, files/lang/pt.po, files/lang/ru.po, files/lang/sv.po, files/lang/tr.po, files/lang/uk.po, src/fheroes2/resource/artifact_info.cpp, src/fheroes2/spell/spell_book.cpp
References #5437 
Currently, if the player tries to open his spell book and doesn't have one he will receive the message "No spell to cast.". This is true in most case, but misleading if the heroes has spell artifacts. So I changed the message from "No spell to cast." to "Spell book is not present."
Also, this text is already part of the game so it doesn't require any further work to translate it :
=> Improved error message if hero tries to open spell book and doesn't have one

src/fheroes2/maps/maps_tiles.cpp
close #5261
It is a regression from #4756. `OBJNTWRD` contains only one castle and one town entrance.
=> Fix incorrect tiles being marked as road

src/fheroes2/agg/agg_image.cpp
=> Generate missing parts of Red Tower sprite

CMakeLists.txt, docs/TRANSLATION.md, files/lang/Makefile
Source code should be unchanged after `make all; make clean`.
Currently .po files are changed on every rebuild. This PR fix it.
=> disable merging on every rebuild

src/engine/audio.cpp, src/fheroes2/agg/agg.cpp, src/fheroes2/agg/mus.h, src/fheroes2/game/fheroes2.cpp
- move `Audio::isValid()` checks to the appropriate places
- remove some invalid TODO comments
- remove useless audio related calls to slightly improve the performance
=> Cleanup of Audio related code

src/fheroes2/agg/agg_image.cpp
relates to #5490
The original assets include one pixel at the bottom of the image making it too huge in height.
Also a tiny speedup to use std::array over std::vector.
=> Fix Puzzle window exit button rendering

src/fheroes2/game/game_startgame.cpp
Currently game may be auto-saved in certain cases - for example, when player dismissed his last hero by hand, however it will not be auto-saved if player attacks by the same last hero and loses the battle. This seems a bit unfair. With this PR game will not be auto-saved at the end of the turn in all cases when player loses/vanquished on that turn. Let's give him another chance.
=> Do not auto-save at the end of a turn if the player has been vanquished on that turn

src/engine/audio.cpp, src/engine/audio.h, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_loadgame.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/gui/interface_focus.cpp
Follow-up to #5505
* If `playbackMode` is `CONTINUE_TO_PLAY_INFINITE`, but track type doesn't support the playback continuation, convert playbackMode to the `REWIND_AND_PLAY_INFINITE` just in case - to avoid the temptation of `replayCurrentMusic()` to restart it even if the track type is not restartable. Currently it shouldn't happen though, but `replayCurrentMusic()` doesn't check the track type, just the playback mode.
* Remove music fadeout support: first of all, it is unused, and also it deadlocks with the current approach by the following scheme:
1. `Music::Stop()` acquires `audioMutex`;
2. `Music::Stop()` calls `Mix_FadeOutMusic()`, which eventually (when the music is finally stopped) leads to the call of the `replayCurrentMusic()` from the different thread (thread started by the …
=> Minor fixes for the music continuation feature

src/engine/audio.cpp, src/engine/audio.h, src/engine/thread.cpp, src/engine/thread.h, src/fheroes2/audio/audio_manager.cpp
I believe that this is much more stable (and also a bit simpler I think) implementation, current implementation in `master` branch is  deadlock-prone because of acquiring audio mutexes in `SDL_Mixer` callbacks. Implementation from this PR doesn't acquire any mutexes in callbacks and, as far as I can tell, works well and is much more suitable for the new release - we don't want our users to suffer. But it still needs to be extensively tested, if possible.
Also I heeded to persistent recommendations from SonarCloud and replaced `std::lock_guard` by `std::scoped_lock` from C++17. Honestly, if there is no need to safely acquire multiple locks at the same time, I'd prefer old `std::lock_guard`, because due to the variadic nature of `scoped_lock`'s constructor you can easily make a mistake and …
=> Rework the music resume logic, replace std::lock_guard by std::scoped_lock

fheroes2-vs2017.vcxproj, fheroes2-vs2019.vcxproj, src/engine/image.cpp, src/engine/image.h, src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h, src/fheroes2/audio/audio_manager.cpp, src/fheroes2/dialog/dialog_audio.cpp, src/fheroes2/dialog/dialog_audio.h, src/fheroes2/dialog/dialog_game_settings.cpp, src/fheroes2/dialog/dialog_system_options.cpp
All Audio settings are moved to a separate window because we cannot have more than 9 options in a single window. Since we replaced 3 options by 1 I added Interface type and Battle Resolve options into Main Menu Settings and Cursor Type and HotKeys into Adventure System Options.
=> Rework settings and introduce 3D audio UI option

src/engine/audio.cpp, src/engine/thread.cpp, src/engine/thread.h, src/fheroes2/audio/audio_manager.cpp
The current approach with detached thread to restart the music is simple and works well enough, but it has one drawback - there is a possibility (although minimal) that eventually the detached thread will outlive the `main()`, which may lead to various issues, because when `main()` is exited, all global objects will be destroyed, and only then, during the process termination, other threads will be terminated, that is, there is always a possibility for a detached thread to access already destroyed object(s). BTW, `AsyncSoundManager` from the `AudioManager` module could suffer from this too, because its worker thread can outlive `main()` as well and can access global objects in other modules that are already destroyed while `g_asyncSoundManager` global object is not destroyed yet - since …
=> Multiple fixes for the AsyncManager, make it ready for use to restart the music in the RESUME_AND_PLAY_INFINITE mode

script/packaging/common/fheroes2.appdata.xml
Otherwise, the stores may not recognize the new version cleanly.
https://flathub.org/apps/details/io.github.ihhub.Fheroes2
Flathub still shows the old version in the info, although the new one is actually uploaded.
=> appdata.xml should be updated like this

src/engine/logging.cpp, src/engine/logging.h
While it is safe to concurrently [call](https://www.man7.org/linux/man-pages/man3/syslog.3.html#ATTRIBUTES) `syslog()` and [access](https://en.cppreference.com/w/cpp/io/cerr) `std::cout`/`std::cerr` from multiple threads simultaneously, it is still not safe to access Switch-specific `logFile` object this way.
=> Nintendo Switch: protect the logfile with mutex

src/fheroes2/maps/maps_tiles.cpp
fix #5538
However, I'm still not sure if it's worth doing a special fix for the sake of the single map generated by a buggy map editor...
=> Keep the object type and placeholder sprite index in sync on tiles with random monsters

src/fheroes2/audio/audio_manager.cpp, src/fheroes2/audio/audio_manager.h, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/game/game_loadgame.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_startgame.cpp
- fix cases when ambient sounds are still played while opening a castle's window
- fix incorrect order of music and sounds (pop call of std::queue actually removes front element, not back)
Note: video playback still uses Mixer::Stop() because it plays audio outside Audio Manager.
=> Reset sounds through Audio Manager

src/fheroes2/ai/normal/ai_normal_castle.cpp
Fixes #5162 .
Building wells only on last day of the week is unreliable. Do that only during the first week.
=> Fix the castle well build logic

src/fheroes2/ai/normal/ai_normal_kingdom.cpp
`availableHeroCount` wasn't incremented so AI could regularly buy 5 heroes on the first turn on large maps.
=> Fix AI hero recruiment limit

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Marking threatening enemy armies and friendly castles under attack as priority targets. AI heroes now have incentives to go to the castle to defend it and switch into sleeper mode to stay there as long as threat persists.
=> Improving AI castle defenses

src/fheroes2/audio/audio_manager.cpp, src/fheroes2/audio/audio_manager.h, src/fheroes2/game/game.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/heroes/heroes_move.cpp
First of all, this PR aims to fix the potential failure of `AudioManager` to stop the sound/music. In addition to making the `_taskToExecute` atomic (so it can be safely accessed by different threads without holding the same mutex), `executeTask()` now acquires `_resourceMutex` before checking the `_taskToExecute` (and for the entire duration of its execution) to avoid the scenario when `_taskToExecute` was checked and task is planned, then `_resourceMutex` was acquired by the main thread, which stops the music, but then the worker thread starts the music again.
Possible scenarios (at least essential ones):
* 1\. `stopSounds()`/`ResetAudio()` is called from the main thread (MT) when `prepareTask()` is executing on the worker thread (WT). `prepareTask()` holds the `_mutex`, …
=> Multiple AudioManager fixes

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_common.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/heroes/heroes.cpp
Fixes #5304 .
Now AI could leave some garrison (preferably slow units) behind when reinforcing the heroes if region is not completely safe.
Fighter heroes should be less likely to leave troops in town than regular ones to avoid players intentionally exploiting the feature by splitting the army on castle recaptures (common OG flaw).
=> AI should keep some creatures in reserve for castle defense

src/fheroes2/ai/normal/ai_normal_castle.cpp
Caused by oversight in #5570. AI currently wouldn't upgrade towns to castles because of the focus on the well.
=> Fix build order regression for AI towns

src/engine/audio.cpp, src/fheroes2/audio/audio_manager.cpp, src/fheroes2/audio/audio_manager.h, src/fheroes2/dialog/dialog_audio.cpp, src/fheroes2/dialog/dialog_audio.h, src/fheroes2/dialog/dialog_game_settings.cpp, src/fheroes2/dialog/dialog_system_options.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/gui/interface_focus.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/kingdom/puzzle.cpp
fix #5580
fix #5581
Scenario of the #5581 is as follows:
* The music type is changed for the first time, the current music is set to `MUS::UNKNOWN`, `MusicRestorer` started the preparation for the background music playback in the worker thread, BUT actual music playback is not started yet.
* The music type is quickly changed for the second time, BUT, since the actual music playback is still not started, the current music is still the `MUS::UNKNOWN`, so `MusicRestorer` has nothing to restore, and no music playback is planned for the worker thread.
* The previously planned music playback is actually started by the worker thread.
The proposed solution is to always start music playback in sync mode when changing the music type. There may be some minor delay if we are playing MIDI on Windows …
=> Fix multiple audio issues

src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_meeting.cpp, src/fheroes2/system/save_format_version.h, src/fheroes2/system/settings.cpp
Apparently this field was once used for some experimental functionality, but it's not the case anymore.
=> Remove unused field move_point_scale from the Heroes class

src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Setting the new Courier role to the most worthless AI hero (based on skills, not army) if hero pool is larger than 3. This new role should focus on bringing the army to others on the front line.
AI heroes on patrol are auto-assigned the Fighter role. Also bumped the threat lookup distance to 3000.
=> Implement AI courier hero role for better logistics

src/engine/audio.cpp
I have no idea why we need to reserve the channel 0.
=> Mixer::SetChannels(): don't call the Mix_ReserveChannels()

src/fheroes2/castle/castle_dialog.cpp
This is a regression from #5546
If you select Evil Interface, open a castle with no hero and then hire a hero you would notice that animation is not great.
=> Fix incorrect animation effect for castle's window

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/maps_tiles_quantity.cpp, src/fheroes2/maps/mp2.h
Add extra comments for the future Adventure Map rendering to be done in a correct way.
Also fixed invalid logic when neutral monsters whose number was set in the Editor did not grow at all.
=> Preparations for Adventure Map rendering

src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/army/army_ui_helper.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game.h, src/fheroes2/gui/interface_status.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps.h, src/fheroes2/world/world_regions.cpp
fix #1466
In the original game:
https://user-images.githubusercontent.com/32623900/177887700-aa85ac47-4400-4e59-9620-740ed7260736.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/177887727-5a151fc8-63d4-45d7-bdba-bba2248a3451.mp4
---
close #2570
Rework the "extended scouting" algorithm of neutral monster counting by excluding the random from it (a situation where the numbers are constantly changing looks weird). The proposed algorithm is as follows:
1. The range into which a given number of monsters falls (one of standard ranges, i.e. 1 - 5, 5 - 10, 10 - 20, 20 - 50, etc) is taken;
2. With basic scouting level, the range is divided in half and the part of the range into which the monster count falls is returned. For example, for 1 wolf and 2 wolves "1-3 wolves" will be …
=> When scouting, use a straight line distance instead of an approximate distance, rework the neutral monsters counting logic for the extended scouting

src/fheroes2/game/game_startgame.cpp
fix #5629
Regression after #5545
=> Fix redrawing of the status window in cases when the hero's army or the castle garrison change without changing focus

src/fheroes2/heroes/heroes.cpp
fix #5633
The issue scenario is as follows:
1. The game loads a hero with a specified portrait (Sir Gallant);
2. If this hero is already busy (already hired or jailed), the game tries to get a freeman hero and "remake" it into the right race and set a custom portrait;
3. If this freeman hero already have a spellbook because of his former race, and also he has a "custom" spellbook as an artifact, then the error from #5633 will be observed, because there will be an attempt to add the spellbook twice.
Also this PR fixes an issue when old default spell may remain after changing the hero's race for the custom hero, like here:
Custom Knight has the Stoneskin spell, "inherited" from the Wizard.
=> When adding a custom spellbook while loading a hero from MP2, check that the hero does not have it yet

src/engine/screen.cpp
to support wide screens without making the image too tiny.
The solution is not ideal but at least it gives more options for players without suffering with square or very high resolutions.
=> Add auto-calculated resolutions

src/fheroes2/army/army_troop.h
It is not overridden anywhere and only brings confusion.
=> Remove virtual from Troop::GetCount()

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp
Now AI should decide between gold or experience more carefully. Increases likelihood of meeting a strong AI hero.
=> Update treasure chest AI decision logic

script/windows/install_packages.bat, script/windows/setup_packages.bat, src/engine/audio.cpp, src/engine/screen.cpp
- update SDL library from 2.0.12 to 2.0.22 for Windows
- add more error checks for rendering
- add TODO comments for the future rendering enhancement
=> Update SDL to 2.0.22 version for Windows

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h
fix #5662
fix #5663
Related to #5651 (this PR does nothing with saving the number of ghosts after a battle, let's postpone it for a while because there is a topic for discussion).
Replaces the #5654.
=> Fix number of ghosts and splitting for Shipwreck, Haunt and Abandoned Mine cases

src/fheroes2/army/army.cpp
regression from #5668
close  #5681
The issue happens for AI calculating path through Shipwreck.
=> Fix an assertion crash for Shipwreck guardians

src/engine/xmi2mid.cpp
After fixing logs we can identify which instruments are missed. For example:
```bash
15:18:03: [DBG_ENGINE]  `anonymous-namespace'::LoadMID:  MIDI0008.XMI
15:18:03: [DBG_ENGINE]  MidiEvents::MidiEvents:  MID: channel 0, instrument ID 0: Acoustic Grand Piano
15:18:03: [DBG_ENGINE]  MidiEvents::MidiEvents:  MID: channel 1, instrument ID 72: Slap Bass 1
15:18:03: [DBG_ENGINE]  MidiEvents::MidiEvents:  MID: channel 2, instrument ID 71: FX 4 (atmosphere)
15:18:03: [DBG_ENGINE]  MidiEvents::MidiEvents:  MID: channel 3, instrument ID 49: Pad 1 (new age Fantasia)
15:18:03: [DBG_ENGINE]  MidiEvents::MidiEvents:  MID: channel 4, instrument ID 45: Lead 7 (fifths)
15:18:03: [DBG_ENGINE]  MidiEvents::MidiEvents:  MID: channel 5, instrument ID 44: Harmonica
15:18:03: [DBG_ENGINE] …
```
=> Update comments and logging for XMI conversion

VisualStudio/SDL1.props, VisualStudio/SDL2.props, VisualStudio/common.props, src/engine/audio.cpp, src/engine/dir.cpp, src/engine/logging.cpp, src/engine/system.cpp
With earlier Windows 8.1 SDK, `combaseapi.h` failed the build because it missed the `typename` in one place, so I used `WIN32_LEAN_AND_MEAN` to exclude COM from the `windows.h`.
Also I removed the MOD playback support. Are we really needed it for something? AFAIK there was no MOD music in any distributions of the original game.
Also I added an explicit initialization of `MID` module (MIDI) using the `MIX_INIT_MID`. Previously, it seemed to work without this, but this is necessary according to the documentation.
=> Fix build with earlier Windows SDKs, copy soundfonts and *.mo files (if they exist) to the $(OutDir)

src/engine/audio.cpp, src/engine/audio.h, src/engine/xmi2mid.cpp, src/fheroes2/audio/audio_manager.cpp
Fix the regressions after #5694
* It turns out that with ancient SDL_Mixer 1.x (used for SDL1 builds) `Mix_HookMusicFinished()`'s callback is not called if music is stopped using `Mix_HaltMusic()`, which causes the music cleanup process to fail;
* SDL_Mixer 1.x (at least 1.2.12) crashes somewhere inside its own music thread if `Mix_FreeMusic()` is called for an already inactive `Mix_Music` while playing another music track;
* Also this PR fixes MIDI instrument and drum descriptions which are currently messed up.
=> Fix issues with SDL_Mixer 1.x, as well as MIDI instrument and drum descriptions

src/fheroes2/campaign/campaign_savedata.cpp, src/fheroes2/campaign/campaign_savedata.h, src/fheroes2/game/game_io.cpp, src/fheroes2/kingdom/week.cpp, src/fheroes2/kingdom/week.h, src/fheroes2/system/save_format_version.h, src/fheroes2/world/world.cpp
=> Remove save format support older than 0.9.12

src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/gui/interface_events.cpp
The original Map Editor allows to place an Ultimate Artifact where it shouldn't be.
close #4298
=> Fix Ultimate Artifact digging conditions

src/fheroes2/gui/interface_gamearea.cpp
A boat or hero or a monster standing above or on the left side of the screen were not rendered properly. More specifically a part of them.
=> Fix out of view rendering of boats and heroes

src/fheroes2/army/army.cpp
fix #5726
Regression after #5703.
The crash due to an assertion failure was in the AI pathfinder because, due to this typo, the same AI-controlled hero with the same army on the same tile with the same guardians sometimes was able to defeat those guardians and sometimes (when guardians get the upgraded stack due to the non-deterministic random) he couldn't do it. This breaks the AI pathfinder logic because it always expects the same results of the `Army::GetStrength()` for the same army on the same tile.
=> Fix typo in Army::ArrangeForBattle()

script/windows/install_packages.bat
Changes in packages:
* fluidsynth: 2.2.6 -> 2.2.8
* glib (dependency): 2.70.5 -> 2.72.3
=> Update the dependency package hash for Windows

src/fheroes2/heroes/heroes.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/system/save_format_version.h, src/fheroes2/system/settings.cpp
We are reaching 1.0 release so we need to slowly kill support for older save file versions.
=> Remove older save formats before 0.9.16

.github/workflows/make.yml, Makefile, docs/INSTALL.md, script/packaging/debian/rules
Building translations by default allows running inplace fheroes2 with
languages enabled:
$ make
$ ./fheroes2
=> Makefile: build translations by default

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/system/bitmodes.h
fix #5745
Also minor style nits (curly braces added, some comments paraphrased), some checks are replaced by assertions, because what is being checked for should never happen.
=> Fix the battle order after bad morale events

.github/workflows/make.yml
This patch [is already in the SDL upstream](https://github.com/libsdl-org/SDL/pull/6086), but we need to apply it temporarily in our CI until the fixed version becomes available in the PSV SDK.
=> Fix build for PSV

src/fheroes2/army/army.cpp
fix #5763
Regression after #5703 - before that PR, `Troops::ArrangeForBattle()` always divided 100 units of any kind into 5 stacks, so it worked in the Graveyard by coincidence. Now the number of stacks is pseudo-random, so `ArrangeForBattle()` cannot be used for the Graveyard (where there should always be 5 stacks) anymore.
=> Fix the distribution of Mutant Zombies in the Graveyard

src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
The problem discussed in a discord chat
Incoming of a kingdom is doubled for human players if option `ExtWorldExtObjectsCaptured` enabled for `ExtObjects`
Save file: [Magic_Garden_Bug.zip](https://github.com/ihhub/fheroes2/files/9377255/Magic_Garden_Bug.zip)
to reproduce just memorize amount of resources then press end of the day and compare what messages write to you and how much you really get.
=> Fix doubling incoming for ExtWorldExtObjectsCaptured

.github/workflows/make.yml
Cached version already contains all necessary fixes, so there is no need to apply them once again.
=> Apply PSV paches only if the cached version has not been used

files/lang/be.po, files/lang/bg.po, files/lang/cs.po, files/lang/de.po, files/lang/es.po, files/lang/fr.po, files/lang/hu.po, files/lang/it.po, files/lang/lt.po, files/lang/nb.po, files/lang/nl.po, files/lang/pl.po, files/lang/pt.po, files/lang/ro.po, files/lang/ru.po, files/lang/sv.po, files/lang/tr.po, files/lang/uk.po, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
This option might actually lead to thinking that the engine is buggy for players who enable this option without checking it. We need to make the logic of focusing identical for every player.
As argument towards removing this option:
- focusing on a castle on a next turn is usually illogical as most of players start doing actions by heroes
- we allow player to put heroes asleep
close #3147
=> Remove "Remember last focus" option

src/fheroes2/game/game_campaign.cpp
closes #5620 
For some reasons the price of loyalty's icons do not follow the standard offset for the last 3 items. 
When comparing with any other menu we can clearly see that the icons are at the wrong location.
The workaround I found is to add a few pixels to the offset of those specific scenarios.
=> Added small offset to price of loyalty icons

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_command.cpp, src/fheroes2/battle/battle_command.h, src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/game/game_hotkeys.cpp, src/fheroes2/game/game_hotkeys.h
close #5626
Currently, only the hotkey can be used (`Q` by default - yes, just like in HoTA). There is no graphical button for this.
https://user-images.githubusercontent.com/32623900/185990658-f3099b04-7db1-4e0b-af83-760fa9d26b35.mp4
Currently, this works both in single-player and in hotseat mode, because, since now both human players are able to use the instant battle and auto combat, I do not see a reason to disable the instant finish in hotseat (and yes, it is convenient for debugging as well).
Also this PR fixes potential issues with non-deterministic random generator for Genie attack, Chain Lighting troop resistance and Earth Quake damage.
=> Implement the instant finish of the battle

src/fheroes2/game/game_over.h, src/fheroes2/kingdom/color.h, src/fheroes2/spell/spell_info.h
Without the change build fails on weekly `gcc-13` snapshot as:
../fheroes2/spell/spell_info.h:33:5: error: 'uint32_t' does not name a type
33 |     uint32_t getSpellDamage( const Spell & spell, const uint32_t spellPower, const HeroBase * hero );
|     ^~~~~~~~
../fheroes2/spell/spell_info.h:25:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
24 | #include <string>
+++ |+#include <cstdint>
=> gcc-13: add missing '#include <cstdint>'

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/mp2.cpp
fix for #5780
@oleg-derevenetz @ihhub @idshibanov, how do you see, guys, the proper way to move this condition:
```
if ( !isPuzzleDraw && mp2_object == MP2::OBJ_CAMPFIRE ) {
renderMainObject( dst, area, mp );
}
```
inside `isHiddenForPuzzle` function?
=> View Puzzle screen, wandering creatures and campfires should not be displayed

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/heroes/heroes_meeting.cpp
While watching [this](https://youtu.be/XckUhRMi3V0), I decided to propose this (debatable of course) PR, which is intended to make it easier for a player to exchange troops between heroes when performing typical PROgamer's 😎 tasks, such as:
* Creating hero chains in which you need to leave fast but relatively weak units to intermediate heroes:
https://user-images.githubusercontent.com/32623900/187012272-a2c47abd-2238-4454-af12-bf60f633462f.mp4
* Speeding heroes up, for which you need to leave just one fastest unit in hero's army:
https://user-images.githubusercontent.com/32623900/187012426-5e686413-232b-4fa3-8a02-a2f5f5c4115b.mp4
https://user-images.githubusercontent.com/32623900/187012432-f910fce7-eb39-4dc9-a9f2-ef3d74f27491.mp4
Hi @ihhub @Branikolog @LeHerosInconnu @zenseii thoughts are …
=> Implement some improvements when exchanging an army between heroes

src/fheroes2/agg/agg_image.cpp, src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/highscores.cpp, src/fheroes2/game/highscores.h
We added difficulty level for campaigns and we need to differentiate scores for them. The easiest way is to introduce rating like for single maps.
=> Include rating calculation for Campaign's high score

src/fheroes2/dialog/dialog_marketplace.cpp, src/fheroes2/gui/interface_radar.cpp
close #5843
This is because we were abusing the logic behind hide() and show() methods.
=> Fix crosshair rendering on Mini-map and missing selection in Marketplace

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h, src/fheroes2/game/game_campaign.cpp, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_text.cpp
This generates a default Gift button that is available for all languages and makes the letter G available for button generation.
Close https://github.com/ihhub/fheroes2/issues/5237
The generation of the Difficulty button was moved to image_agg.cpp.
An issue with two rows of missing pixels of the right side of the evil campaign screen's pressed buttons was addressed also:
=> Generate new default Gift button, move Difficulty button generation, fix pressed evil buttons

src/fheroes2/game/game.cpp, src/fheroes2/gui/player_info.cpp, src/fheroes2/system/players.cpp
Fix crash due to failed assertion when clicking on the handicap field for a player that can be controlled both by AI and a human player:
Such players have both the `CONTROL_HUMAN` and `CONTROL_AI` flags at the same time.
Also, this PR adds functionality to remember handicap settings when restarting the same map in the same circumstances, as it has already been done for other player settings.
=> Before setting a handicap for a player, make sure that this player cannot be controlled by AI

src/fheroes2/agg/agg_image.cpp, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_text.cpp
Close https://github.com/ihhub/fheroes2/issues/5234
With letter spacing fixed we can
close https://github.com/ihhub/fheroes2/issues/5858
The 'A' is different from the OG since the automatic shadowing etc is different and I had to add a pair of pixels to fill some gaps.
~~In the future it should be made possible to have the letter spacing be 2px smaller (i.e. 1px on each side of a letter) so that the buttons matche the OG main menu buttons:~~ This has been achieved in this PR.
Aligned and tighter Difficulty button:
=> Generate button letters A, B, E, H, P, R, S and new Battle Only button

README.md, docs/README.md
Current text:
```
You can find a complete list of all of our changes and enhancements in its own wiki page (with link to it).
```
The text will currently show up here since talk about enhancements are made there and we want users to see the enhancements so it's better to have on the top rather than further down in my opinion.
=> Add enhancements link to frontpage

src/fheroes2/gui/ui_font.cpp
This generates all the remaining letters of the latin alphabet plus the hyphen.
J and Z had to be invented since no buttons have them.
=> Generate J, Q, V, W, X, Z, -

src/fheroes2/army/army_bar.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/campaign/campaign_scenariodata.cpp, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/heroes/heroes_action.cpp
This puts creature names in lowercase in the same situations as the OG, which are:
* Army bar (Move, info, redistribute, recruit)
* Battle log
* Artifact creature encounters
In addition this adds lowercase to this:
* Campaign bonus right-click description
This does **not** lowercase creature names if they're in the header of a dialog.
Relates to:
Closed PR:https://github.com/ihhub/fheroes2/pull/5321
Issue: https://github.com/ihhub/fheroes2/issues/5246
=> Make creature names lowercased

src/fheroes2/battle/battle_interface.cpp
We still show coordinates in the battlefield but these values are useless.
=> Make logging for monster movement in battle more user-friendly

script/windows/install_packages.bat
Currently, this bat file always returns zero, which is inconvenient in scripts. Also, update the package hash due to the inclusion of `SDL*main.lib`.
=> install_packages.bat: return nonzero value on error, update package hash

src/engine/image.cpp, src/engine/image.h, src/fheroes2/gui/ui_font.cpp
This function is needed to avoid extra memory copies in few places, mostly font generation. It also improves performance of Adventure Map rendering.
relates to #5903
=> Add an overloaded Flip() function

src/engine/CMakeLists.txt
Fixes cmake error mensioned in :https://github.com/ihhub/fheroes2/pull/5139:  
```
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /worktmp/yaraslau/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /worktmp/yaraslau/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SDL2: /usr/lib64/libSDL2.so (found version "2.0.10") 
-- Found SDL2_mixer: /worktmp/yaraslau/lib/libSDL2_mixer.so (found version "2.6.2") 
-- Found ZLIB: /usr/lib64/libz.so …
```
=> Add check for SDL2MAIN_FOUND to prevent linking to library that was not found 

src/fheroes2/game/game_over.cpp
fix #5793
The wording was deliberately changed to look better with different composition of alliances.
=> Display detailed information about the composition of alliances in the scenario info window

src/fheroes2/castle/castle.cpp
The growth should not be affected by game's difficulty. close #5905
=> Fix neutral town unit growth

src/fheroes2/world/world_pathfinding.cpp
An artifact should be valid and this object must be pickup, otherwise a hero is not blocked while going through the object.
close #5920
=> Fix incorrect AI pathfinding for objects with artifacts

src/fheroes2/campaign/campaign_data.cpp
At least in Russian the existing translation for this string, which is
displayed in the battle summary, doesn't work in the context of the scenario
name.
=> Include translation context for the "Defender" scenario

.github/workflows/clang_analyzer.yml, .github/workflows/clang_tidy.yml, .github/workflows/clang_tidy_comments.yml, .github/workflows/cmake.yml, .github/workflows/code_style_check.yml, .github/workflows/make.yml, .github/workflows/msvc.yml, .github/workflows/pr_author_auto_assign.yml, .github/workflows/sonarcloud.yml, .github/workflows/translation_update.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
~The latest version of `microsoft/setup-msbuild` action still uses Node 12, hopefully Micro$oft will fix it in the foreseeable future.~ Already fixed.
=> Update workflows with latest versions of the actions which runs on Node 16

docs/TRANSLATION.md
This revises the translation guide to set the max amount of strings to 400 lines, reduced from 1000 strings, and it adds a minimum of 15 strings, but with an exception for translations that are borderline complete.
@ihhub and @oleg-derevenetz, I would like to have your opinion on the wording of this should you have the time to take a look at it. Thanks!
=> Translation guide: Reduce the max and add a minimum amount of strings per translation PR

.github/workflows/clang_analyzer.yml, .github/workflows/clang_tidy.yml, .github/workflows/code_style_check.yml
To better perform code diagnostics.
=> Use Clang 14 in Clang Analyzer, Clang-Tidy and Code style check workflows

src/fheroes2/game/game_over.cpp
I have no idea why I used `Translation::ngettext()` here while there is a much shorter widely used alternative.
=> Use _n() instead of Translation::ngettext()

.github/workflows/make.yml
PSV SDL2 package was apparently updated to the latest version, we don't need this patch anymore.
=> PS Vita: don't apply temporary patch to SDL2

src/fheroes2/audio/audio_manager.cpp
closes #5986
If for some reason someone deleted the files/soundfont directory (or does not have it). The music will fail to play because the SDL_Mixer won't be able to find any sound fonts. 
The SDL_Mixer libs seem to be using default paths that we don't want to overwrite when no sound fonts have been found. 
This PR adds a condition before calling the Mix_SetSoundFonts function to make sure that we don't overwrite the paths with an empty string.
=> Fixed issue where soundfonts are not found in the files directory

.clang-tidy
There are lots of valid and clear identifier names like `x`/`y`, `px`/`py`, `pt`, etc, etc.
=> Clang-Tidy: disable the readability-identifier-length check

README.md, docs/README.md
I don't know where exactly the previous badge URL came from, because I was not able to find it in the documentation. The documented badge URL syntax is as follows:
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
And the former URL doesn't work anymore (404 not found):
https://github.com/ihhub/fheroes2/workflows/GitHub%20Actions/badge.svg
Maybe it was a some legacy URL.
=> Fix the GitHub Actions status badge URL

.github/workflows/android.yml, .gitignore, script/android/README.md, script/android/install_packages.bat, script/android/install_packages.sh, script/demo/download_demo_version.sh, script/windows/README.md
Related to #6008
Also make `curl` call in the `download_demo_version.sh` a bit more sane.
=> Add scripts for Windows, Linux and macOS to install Android pre-built packages

src/fheroes2/castle/castle.cpp, src/fheroes2/resource/resource.h
Spells are valuable but they are useless if a hero does not have a magic book or cannot get one.
Also this pull request fixes incorrect evaluable of monsters to hire when a hero has no magic book. In `void Normal::reinforceHeroInCastle()` method we first buy a magic book and then buy monsters.
=> Take Magic Book into account while visiting a castle by an AI hero

src/engine/audio.cpp
I believe the root of the issue lies in SDL2 itself, but here's a workaround.
P.S. I just noticed that with `samples = 2048` there were excessive messages in the logcat like this:
```
D/AAudio: AAudioStream_requestPause(s#1) called
D/: PlayerBase::pause() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) called --------------
D/: PlayerBase::start() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) returned 0 ---------
D/AAudio: AAudioStream_requestPause(s#1) called
D/: PlayerBase::pause() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) called --------------
D/: PlayerBase::start() from IPlayer
D/AAudio: AAudioStream_requestStart(s#1) returned 0 ---------
D/AAudio: AAudioStream_requestPause(s#1) called
D/: PlayerBase::pause() from IPlayer
D/AAudio: …
```
=> Fix various audio distortions on Android

src/fheroes2/gui/ui_font.cpp
This adds a proper font with special letters to support CP1250 encoding. Full font support for Polish and Hungarian and some Czech characters (all except the ones with caron and the u with circle).
=> Add proper CP1250 font

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/values/strings.xml, android/app/src/main/res/xml/data_extraction_rules.xml, android/app/src/main/res/xml/full_backup_content.xml
Related to #6008
Without special configuration, Android will attempt to backup almost all files both from private and external app data directories (except caches), which is not desirable, because per-app backup storage is very limited (up to 25MB per app) and we shouldn't backup OG data files, maps, music, etc, etc. This PR configures backup rules for Android 11 and lower devices, as well as for Android 12+ devices.
=> Android: setup the backup rules

.github/workflows/msvc.yml
Fix current issues with MSVC build.
=> MSVC workflow: use cyg-get instead of broken "choco.exe install ... --source cygwin"

src/fheroes2/gui/ui_font.cpp
This adds the character Ц to the CP1251 button font as requested here: https://github.com/ihhub/fheroes2/issues/5969#issuecomment-1293376397
How does this look @Branikolog?
=> Add Cyrillic TSE to button font

src/fheroes2/agg/agg_image.cpp, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_font.h
This adds logic that will modify the base fonts on the fly.
The modifying logic was placed in `ui_font.cpp` to maintain current structure and because the function updating the font shadow is local to that file.
Lowercase k for both normal and small font have been edited as an example and these were also requested by many users.
This PR fixes other font issues like the `%` and `-`.
New `k`:
Fixed `%` sign:
Fixed hyphen `-` (only normal font has issues):
The Cyrillic `к` in CP1251 has been readjusted because it uses lowercase k for its generation.
Close #5514 
Close #4799
=> Modify and fix base font characters

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/battle/battle_main.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle_well.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp
- while hiring monsters in a castle put monsters to the slots with the same type of monsters
- while attending dwellings on map try to redistribute army before joining monsters
- add logic to hire some monsters from dwellings if they are payable
=> Update AI logic for monster distribution and recruitment

.github/workflows/msvc.yml
Recent version of `gettext-devel` (0.21.1-1) is linked against `cygunistring-5.dll`, while Cygwin has just `cygunistring-2.dll` (?), so let's ~~stick with older version of this package (0.21-1) for a while~~ install the `libunistring5` package to fix the broken dependency.
=> Fix the translation generation for MSVC workflow

files/lang/Makefile, src/fheroes2/gui/ui_font.cpp
This PR makes the French font generation use the CP1252 font generation and maintains compatibility with the original French custom encoding.
All French specific letters have been added as well as all characters with the tilde `~` accent for Portuguese support.
The MO makefile has been changed to use CP1252 encoding for French.
French has been set to use CP1252 for button font.
This PR will also add French quotation marks since they are part of CP1252.
Close #4882
=> Consolidate French and CP1252 font generation
