ihhub/fheroes2

src/fheroes2/world/world_loadmap.cpp
=> Add logging for Ultimate Artifact placement

src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/army/army.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/maps/maps_tiles.cpp
Added AI hero role to the debug output and reformatted the rest of it to make it a bit more concise.
Also the "has no parent tile" warning is my personal annoyance since it happens frequently and pollutes the log.
=> Update debug mode logging to include hero role

src/fheroes2/agg/agg_image.cpp, src/fheroes2/gui/player_info.cpp
=> Fixed missing column of pixels

src/fheroes2/agg/agg_image.cpp
=> Fix Campaign Window button flickering

src/fheroes2/dialog/dialog_file.cpp
=> Align File Options dialog position

src/fheroes2/castle/castle_town.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_dialog.cpp
=> Fix extra shadow being drawn for Hero Screen

src/fheroes2/heroes/heroes.cpp
=> Fix the class of a hero named Joseph

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h, src/fheroes2/game/game_campaign.cpp
=> Fix campaign button change regression

src/fheroes2/game/game_newgame.cpp
This will help to avoid any questions from players regarding missing campaigns.
=> Show a window stating about missing video files for campaigns

src/fheroes2/game/game_credits.cpp
=> Add The Price of Loyalty team to credits

src/fheroes2/ai/normal/ai_normal_hero.cpp
Fix the recently introduced code smell.
=> Remove the redundant cast

src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/dialog/dialog_file.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/maps/maps_actions.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/resource/artifact.cpp
Just a small code cleanup towards the new code.
=> Remove some usage of old Text classes

src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
=> Always ask about rewriting an existing save file

src/fheroes2/ai/normal/ai_normal_kingdom.cpp
close #5613
regression from #5583
=> Fix a crash when no AI heroes exist

src/fheroes2/heroes/heroes_spell.cpp
Caught during build with `NDEBUG`.
=> Remove unused variable

.github/workflows/cmake.yml, src/engine/audio.cpp, src/engine/audio.h, src/fheroes2/audio/audio_manager.cpp, src/fheroes2/audio/audio_manager.h, src/fheroes2/game/fheroes2.cpp
Prerequisite for #5628
Also minor style nits from the same #5628.
=> Add support for loading of MIDI sound fonts

src/engine/localevent.cpp, src/engine/localevent.h, src/engine/screen.cpp, src/fheroes2/game/fheroes2.cpp, src/fheroes2/game/game_logo.cpp, src/fheroes2/gui/ui_tool.cpp, src/fheroes2/kingdom/view_world.cpp
=> Color cycling code cleanup

src/engine/core.cpp, src/engine/xmi2mid.cpp, src/fheroes2/agg/agg_image.cpp, src/fheroes2/battle/battle_grave.h, src/fheroes2/battle/battle_troop.h, src/fheroes2/gui/text.cpp, src/fheroes2/gui/text.h
To reduce the number of warnings in SonarQube
=> Small code cleanup

docs/README.md
=> Update image sizes on the published web page

src/engine/screen.cpp
Also fixed missing resizing ability.
Apparently, the previous changes for resolutions are invalid as they do not add a truthful full screen mode.
=> Revert resolution changes and add checks for rendering

src/fheroes2/dialog/dialog_levelup.cpp
=> Add missing window frame for hero's dialog during level up

src/fheroes2/castle/castle.cpp
=> Fix incorrect castle's area leading to wrong castle's info

.github/workflows/make.yml
macOS 10.15 VM will be removed [soon](https://github.com/actions/virtual-environments/issues/5583).
=> Replace macos-10.15 by macos-11

src/fheroes2/battle/battle_interface.cpp
=> Fix missing retaliation delay after last animation frame

.github/workflows/msvc.yml
Fix persistent ZIP installation issues.
=> MSVC workflow: use 7zip instead of Info-ZIP

src/fheroes2/heroes/heroes_action.cpp
=> Fix experience from Tree of Knowledge

src/fheroes2/heroes/heroes.cpp
=> fix starting xp

.github/workflows/msvc.yml, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/heroes/heroes_action.cpp
=> Fix the pre-battle arrangement of neutral troops

src/fheroes2/gui/interface_gamearea.cpp
=> Do not draw objects over the map edge if they are in fog

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/world/world.cpp
=> Do not show digging holes on Puzzle Map

files/lang/be.po, files/lang/bg.po, files/lang/cs.po, files/lang/de.po, files/lang/es.po, files/lang/fr.po, files/lang/hu.po, files/lang/it.po, files/lang/lt.po, files/lang/nb.po, files/lang/nl.po, files/lang/pl.po, files/lang/pt.po, files/lang/ro.po, files/lang/ru.po, files/lang/sv.po, files/lang/tr.po, files/lang/uk.po, src/engine/screen.cpp, src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/gui/ui_castle.cpp, src/fheroes2/heroes/heroes_action.cpp
=> Address some TODO comments

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
Also removed useless checks to speed things up.
=> Fix missing shadows from path arrows when they are on the edge of screen

src/fheroes2/maps/maps_tiles.cpp
It is especially noticeable in debug mode with No Interface
=> Improve rendering of Radar area

src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h
=> AIPathfinder: make the cache of the tile army a static local variable, not a member of the class

.github/workflows/code_style_check.yml, .github/workflows/pr_author_auto_assign.yml, .github/workflows/translation_update.yml
30 minutes is too much for some jobs.
=> GitHub Actions: tune job timeouts

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
=> Fix tall object rendering

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/gui/interface_gamearea.h, src/fheroes2/gui/interface_radar.cpp, src/fheroes2/gui/interface_radar.h, src/fheroes2/kingdom/view_world.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h
close #4279
Also fixed #4200 by changing ROI calculations.
=> Fix rendering of towns for View Towns spell

src/fheroes2/maps/maps_tiles.cpp
close #4512
We need to take into account top (level 2) objects.
=> Fix Ultimate Artifact placement conditions

src/fheroes2/gui/interface_radar.cpp
=> Fix castle rendering on mini-map

src/fheroes2/gui/ui_dialog.cpp
=> Fix a crash in UI window

src/fheroes2/gui/interface_gamearea.cpp
=> Do not show boasts on puzzle image

src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/gui/interface_radar.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
Since we changed the way how we render mini-map it takes little more time than before so these changes are to address this performance drop.
=> Small optimization for Mini-map rendering

src/engine/tinyconfig.cpp, src/engine/tools.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_troop.h
Less warnings is always better.
=> Fix some compilation warnings

src/engine/system.cpp
Without the change `fheroes2` can start on NixOS for a few minutes.
It happens due to suboptimal interaction of NixOS flat directory layout:
/nix/store/...-fheroes2-${ver}/share/fheroes2/files/lang
/nix/store/...-other-package-1/...
/nix/store/...-other-package-2/...
...
/nix/store/...-other-package-10000/...
and of `bool System::GetCaseInsensitivePath(path, correctedPath)` function.
When `System::GetCaseInsensitivePath("/nix/store/...-fheroes2-${ver}/share/fheroes2/files/lang", out);`
is called `/nix/store` is fully expanded first to the list of file to look
up `...-fheroes2-${ver}` entry in a case insensitive manner.
My system happens to have 400_000 `/nix/store` entries and it takes tens
of seconds to match a file there.
The change adds an optimisitic direct entry lookup to avoid …
=> src/engine/system.cpp: speed up resolution of unmodified paths on unix

src/fheroes2/gui/interface_gamearea.cpp
=> Fix moving AI hero rendering

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
=> Fix rendering of Mine Guardians

src/engine/localevent.cpp, src/engine/localevent.h, src/fheroes2/army/army_bar.cpp, src/fheroes2/army/army_bar.h, src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/battle/battle_only.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/castle/castle_mageguild.cpp, src/fheroes2/dialog/dialog_guardian.cpp, src/fheroes2/gui/cursor.cpp, src/fheroes2/gui/cursor.h, src/fheroes2/gui/interface_itemsbar.h, src/fheroes2/gui/skill_bar.cpp, src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/heroes/heroes_meeting.cpp, src/fheroes2/kingdom/kingdom_overview.cpp, src/fheroes2/maps/maps_objects.h, src/fheroes2/resource/artifact.cpp, src/fheroes2/resource/artifact.h
As a part of migration to a newer UI element architecture. What was done:
- remove unused event handling by LocalEvent
- rework of ItemsBar class to avoid badly written code
- add setCustomImage() method for Cursor class which will be used for drag&drop ability
- remove default value for `Redraw` methods as in the future we might need to render on a separate image before rescaling on screen
- code readability improvements
=> UI elements code cleanup

src/fheroes2/kingdom/kingdom.cpp
relates to #5797
to be the way as in the OG which also eases AI on Easy and Normal difficulties.
=> Fix start resources for AI players

src/engine/smk_decoder.cpp, src/engine/smk_decoder.h, src/fheroes2/game/fheroes2.cpp, src/fheroes2/game/game_newgame.cpp
Also fix 2 issues with video playback:
- the number of audio channels was always set to 1
- add support for scaled video playback
=> Show intro videos like in the original game

src/fheroes2/game/game_campaign.cpp
=> Fix refresh of campaign window after choosing difficulty

src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/world/world_pathfinding.cpp, src/fheroes2/world/world_pathfinding.h
It is also much faster as we do not need to recalculate the map for a hero.
close #5650
=> Fix constantly moving AI heroes when they have nothing to do

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h, src/fheroes2/gui/ui_font.cpp
=> Generate MIN button based on newly added font

src/fheroes2/castle/castle_well.cpp
to make the interface uniform everywhere.
=> Add popup dialogs for Well's buttons

src/fheroes2/gui/cursor.cpp
=> Fix incorrectly rendered monochrome cursor for campaign selection window

src/fheroes2/heroes/heroes_action.cpp
=> Use sound volume when playing music for map objects

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/gui/ui_tool.cpp, src/fheroes2/gui/ui_tool.h
We had multiple places where rendering shouldn't be called for scrollbars but it was.
close #5333
=> Fix incorrect rendering calls being done by scrollbars

script/windows/install_packages.bat
Changes in packages:
* sdl2: 2.0.22 -> 2.24.0
=> Update the dependency package hash for Windows

src/fheroes2/heroes/heroes_action.cpp
=> Fix switching of terrain music in case of hero loss

src/engine/image.cpp, src/fheroes2/agg/agg_image.cpp, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_font.h, src/fheroes2/gui/ui_text.cpp
With these changes we can proceed to generate letters for other code pages as now the way to generate a letter is standartize and pretty straightforward. Also fix a crash in updateShadow() function.
=> Restructure button font generation code to support future code pages

src/fheroes2/ai/normal/ai_normal_hero.cpp
After we fixed pathfinding for heroes by using boats we did not remove checks for some objects not being available if a hero is a ship master. This explains a weird behavior when a hero moves from sea to land very often because priorities for his goals change drastically.
close #5881
=> Fix incorrect object evaluation for AI heroes on boats

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_pathfinding.cpp
fix #5859
https://user-images.githubusercontent.com/32623900/192784578-a37f93a8-b094-4c77-a7c6-abdcf9f66a70.mp4
Plus minor style nits (a few methods have been renamed).
=> AI battle pathfinder: fix logic of processing cells containing units available for possible attack

src/fheroes2/castle/castle.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h
The full explanation is in comments within the code to make sure that everyone in the future will understand magical numbers within the code.
This is subject to discussion and rejection so I'm marking this pull request without milestone for now.
relates to #5797
=> Decrease monster growth bonus for AI

src/fheroes2/castle/castle.cpp
=> Apply usual rules for unit growth in neutral towns/castles with custom troops

files/lang/Makefile
Forgot to add this when adding the language.
This fixes the build failing.
=> Add Turkish to the makefile

src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_language.cpp
This adds ISO8859-16 font used by Romanian and adds the language as a choice in the game.
Button fonts will be added in a later PR when we know what characters are needed.
=> Add Romanian font and language option

src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/highscores.cpp
=> Do not ask Player's name if the score is too low for High score board

src/fheroes2/gui/interface_events.cpp
=> Make sure that there is a place for the Ultimate Artifact in the artifact bag before trying to dig it out

src/engine/logging.cpp
This is useful for the future support of issues and logs provided by players.
=> Add date to logging

src/fheroes2/ai/normal/ai_normal_spell.cpp, src/fheroes2/heroes/heroes_base.cpp, src/fheroes2/heroes/heroes_base.h
Also heroes will have better army estimation. close #5930
=> AI heroes now use spells from scrolls

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h
=> Don't let the archers perform a double attack if they are out of ammo

files/lang/nl.po
Due to the 1000 changes limit for translations I've had to split the translations. This is the first part.
=> Add a part of the Dutch translations

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/heroes/heroes_base.h, src/fheroes2/resource/artifact.cpp, src/fheroes2/resource/artifact.h, src/fheroes2/resource/artifact_info.h
Add some basic checks for artifacts while exchanging them. More complex logic is required to make it more efficient but as of now this code works as a basis for the future improvements.
relates to #3718
=> Add proper logic for artifact exchange between AI heroes

src/fheroes2/audio/audio_manager.cpp, src/fheroes2/audio/audio_manager.h
fix #5941
Plus minor style nits.
=> MusicRestorer: always attempt to restore the music track last requested to be played

src/fheroes2/game/game_startgame.cpp
=> Recalculate the hero's path when the hero was selected with the mouse

src/fheroes2/agg/agg_image.cpp, src/fheroes2/gui/ui_font.cpp
Close #5960 
I also noticed that the Polish min button wasn't generated properly so I replaced it with the new button font generation.
=> Fix button font generation for original ICN

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/agg_image.h, src/fheroes2/gui/ui_language.cpp
=> Update language dependent resources while changing language

files/lang/Makefile, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_language.cpp, src/fheroes2/gui/ui_language.h
This adds Dutch as an option in the game, adds font support and adds it to the makefile. I couldn't find a clear source on what special characters there are in Dutch so I will need help from someone familiar with the language to tell me what diacritics/accents there are if any.
Also we should probably wait with this until we've decided on how to enlarge the language selection dialog.
=> Add Dutch font and language option

src/fheroes2/agg/agg_image.cpp
Fixes #5848 
I added checks when it seemed needed, the rest was already in bounds.
=> Add checks when the [] operator was used at risk

src/fheroes2/gui/ui_dialog.cpp, src/fheroes2/gui/ui_dialog.h
to avoid very complex code to be written for most of cases in the game.
relates to #5961
=> Add a simplified version of UI message dialog

src/fheroes2/castle/castle_dialog.cpp
=> Redraw the castle's resource panel when a hero purchases the spellbook

src/engine/logging.h, src/engine/system.cpp, src/fheroes2/h2d/h2d.cpp
This is minimum required code (besides commenting the whole audio-related code as I haven't figured out how to compile SDL Mixer) to run fheroes2 on an Android device.
=> Add Android specific code

src/fheroes2/gui/cursor.cpp
Close #4157
Close #1307
This needs to be verified by @LeHerosInconnu more knowledgeable, but i think now cursor is placed more or less in right place.
=> Hero fight cursor offset fix (#4157, #1307)

files/lang/Makefile, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_language.cpp, src/fheroes2/gui/ui_language.h
This adds Hungarian as an option in the game and adds replacement font using the closest Latin letter.
Hungarian is added to the language makefile.
Specific button fonts have not been added.
=> Add Hungarian language option and font replacements

src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/dialog/dialog_selectscenario.h, src/fheroes2/maps/maps.h
=> (#1240) Memorize Selected Scenario in Scenario Selection Window

src/fheroes2/gui/interface_radar.cpp
=> Fix terrain colors on the minimap

.gitignore
=> Ignore files from Android Studio

src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/dialog/dialog_selectscenario.h
close #6024
For your information @HaveFun91 (we missed this).
=> Fix a crash in scenario selection due to invalid pointer usage

android/app/jni/Android.mk, android/app/src/main/AndroidManifest.xml, src/engine/screen.cpp
Related to #6008
Hi @ihhub is this place "good enough" to set this hint, or is there some better place for this?
=> Android: lock the screen orientation to landscape

src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/highscores.cpp
=> Fix Campaign score sorting issue

script/android/install_packages.bat, script/android/install_packages.sh
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/19
=> Update the dependency package hash for Android

src/fheroes2/army/army_bar.cpp
Regression after #6016
See https://github.com/ihhub/fheroes2/issues/6008#issuecomment-1293007132 for issue details.
=> Fix the troop splitting logic

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, script/android/install_packages.bat, script/android/install_packages.sh
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/21 for details.
=> Android: remove the version info from the AndroidManifest.xml, set proper versionName in the build.gradle, update hash of the dependency package

src/fheroes2/kingdom/kingdom.cpp
=> Clear the kingdom's visited objects according to their lifetime, even if this kingdom has already been vanquished

src/fheroes2/gui/ui_font.cpp
By mistake the commit to add this was not added to https://github.com/ihhub/fheroes2/pull/6056
Close #4882 
We don't use any quotation marks in any smallfont strings so I didn't add these there.
=> Add CP1252 French quotation marks

src/fheroes2/castle/castle.cpp
=> Castle::isExactBuildingBuilt(): simplify logic, always check the sanity of building levels

src/fheroes2/game/game_campaign.cpp
=> Campaign difficulty window, text alignment

src/fheroes2/battle/battle_interface.cpp
=> Fix catapult's boulder animation

src/fheroes2/battle/battle_troop.cpp
fix #1701
This PR will correct issues from issue n°1701
https://github.com/ihhub/fheroes2/issues/1701
=> Correcting text errors

src/fheroes2/dialog/dialog_language_selection.cpp
This is definitely not a great solution due to code duplication but to reduce this it takes a lot of time.
close #6059
=> Change language selection window to support many languages

src/fheroes2/gui/interface_focus.cpp
=> Fix recently introduced code smell

src/fheroes2/game/game_campaign.cpp
=> Fix possible assertion hit for campaign scenario info dialog

src/fheroes2/kingdom/kingdom.cpp
=> Fix handicap income calculation

src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/army/army.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/monster/monster.cpp
=> Fix incorrect evaluation of army strength where hero's abilities should not be taken into account

src/fheroes2/campaign/campaign_data.cpp, src/fheroes2/campaign/campaign_data.h, src/fheroes2/game/game_campaign.cpp
=> Add missing alliance conditions for SW last scenarios

src/fheroes2/monster/monster.cpp
close #1322
I foresee some debates about this but this is how it works in the OG.
=> Fix monster upgrade cost formula

src/engine/system.cpp
Some kind of regression from a recent commit.
=> Fix Android filesystem related logic

src/fheroes2/battle/battle_tower.cpp, src/fheroes2/gui/ui_castle.cpp, src/fheroes2/monster/monster.cpp
Apparently, SonarCloud has updated the engine of its analyzer.
=> Fix bugs in the execution flow detected by SonarCloud

src/fheroes2/heroes/heroes.cpp
=> Do not show any hero status for AI heroes

src/fheroes2/dialog/dialog_graphics_settings.cpp
=> Correctly reflect the change of fullscreen mode in the graphics settings dialog when it was toggled using a hotkey

src/fheroes2/battle/battle_tower.cpp, src/fheroes2/battle/battle_tower.h
=> Tower::GetInfo(): correctly reflect the fact that the tower was destroyed during the battle

src/fheroes2/dialog/dialog_quickinfo.cpp
=> Fix UI elements for an unhired hero popup window

src/fheroes2/gui/ui_text.cpp, src/fheroes2/gui/ui_text.h
=> Always center text when a maximum width is provided

src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
=> Make the heroes: remember movement points when retreating or surrendering option by default

src/fheroes2/resource/artifact_ultimate.cpp
=> Always show the Ultimate Artifact behind one of the last four central pieces of the puzzle

src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/game/game_over.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
=> Remove the game: offer to continue the game after victory option

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/gui/ui_castle.cpp, src/fheroes2/gui/ui_castle.h
Mostly remove the unused code introduced by the latest changes.
=> Fix recent code smells

src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
=> Remove the heroes: allow buy a spellbook from Shrines option

src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/dialog/dialog_settings.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
=> Remove the world: Windmills, Water Wheels and Magic Gardens can be captured option

src/engine/core.cpp, src/engine/core.h, src/fheroes2/system/settings.cpp
To have better initial experience with the game.
relates to #6008
=> Make fullscreen mode as a default state for Android devices

src/fheroes2/battle/battle_interface.cpp
close  #1492
This PR:
Original game:
=> Change battlefield hexagon generation to match the original

src/fheroes2/dialog/dialog_gameinfo.cpp
=> Remove CONFIG button from scenario info dialog

src/engine/localevent.cpp, src/engine/localevent.h, src/fheroes2/dialog/dialog_selectcount.cpp, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/game/game.cpp, src/fheroes2/game/game_hotkeys.cpp, src/fheroes2/game/game_hotkeys.h
to avoid SDL dependency and make the code readable. Also reduced the scope of some functions.
=> Rework key modifiers logic

src/engine/core.cpp, src/engine/core.h, src/engine/localevent.cpp, src/engine/localevent.h, src/engine/system.cpp, src/engine/system.h, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/system/settings.cpp
* `LocalEvent`: make method naming more uniform;
* Move `isHandheldDevice()` from `core` to `system`: I think it's more suitable there (optional change).
=> Style nits

src/engine/screen.cpp
=> Fix inability to toggle V-Sync dynamically

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/dialog/dialog_arena.cpp, src/fheroes2/system/settings.h
=> Remove the heroes: allow to choose any primary skill in Arena option

src/fheroes2/dialog/dialog_gameinfo.cpp
=> Fix the scenario info dialog position

android/app/src/main/java/org/fheroes2/MainActivity.java
Not as useful as `const` in C++, but won't hurt. Plus make `MainActivity` the `final class` as well.
=> Java: use final where appropriate

.github/workflows/android.yml, docs/INSTALL.md, docs/README_android.md
This adds an Android installation guide to the repo, steps in the installation wiki and bundles the guide in the Android zip archive.
Close https://github.com/ihhub/fheroes2/issues/6174
=> Add Android installation and usage documentation

src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Also increase fog discovery value as it was very low and AI prefers to just stay in one place.
=> Introduce AI Scout role

src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
=> Add shadowing for fog in debug build

src/fheroes2/castle/castle.h, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/kingdom/kingdom.cpp
We don't support this feature anymore, but some leftovers are still there.
=> Remove some leftovers of support for visiting the allied castles

src/fheroes2/game/game_credits.cpp
A company name is not translatable in general.
=> Do not translate companies' names

src/fheroes2/battle/battle_interface.cpp
This PR changes the way the rainbow is drawn for the "good luck" event on the battlefield:
https://user-images.githubusercontent.com/113276641/204090850-53f04cc6-e391-43a2-bb5f-36271947d441.mp4
(In this video "good luck" is force set to 'true')
=> An attempt to recreate the original rainbow animation (battlefield)

src/fheroes2/castle/castle_building.cpp
=> Fix position of left barbarian's captain quarters part

src/engine/image.cpp
relates to #6303
I will need some time to rewrite the logic of the functions properly.
=> Revert back regression changes in Blit function

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h
close #6222 
close #3242
https://user-images.githubusercontent.com/113276641/205485764-20edabf9-387c-4e29-a52d-fd9394fa8dbd.mp4
=> Fix the smoke animation when demolishing a castle building (Battlefield).

.gitignore, android/app/src/main/res/xml/data_extraction_rules.xml, android/app/src/main/res/xml/full_backup_content.xml
This file is no longer in use and should not normally exist.
=> Android: do not backup fheroes2.bin

src/fheroes2/agg/bin_info.cpp
=> Fix Dwarves death animation

src/fheroes2/game/game_io.cpp, src/fheroes2/resource/resource.cpp
* Remove the redundant `if` clause detected as a bug by SonarCloud;
* Remove certain useless comments detected as a "commented out code" by SonarCloud.
=> Fix a few code smells and "bugs" detected by SonarCloud

docs/README_android.md, src/engine/localevent.cpp, src/engine/localevent.h, src/fheroes2/army/army_bar.cpp, src/fheroes2/gui/interface_buttons.cpp, src/fheroes2/gui/interface_itemsbar.h
The idea of the new simulation is as follows:
1. Place the first finger on the target object;
2. Place the second finger anywhere on the screen (not necessarily on the black bar);
3. Now you can remove the first finger from the screen.
This implementation looks more familiar and doesn't require to use black bars for the correct operation. ~It has one flaw though - it doesn't currently support the simulation of moving the mouse with the right button pressed, but, AFAIK, it's not used in the game anyway~ no longer true.
Also this implementation fixes the flaw in the logic of the current implementation I encountered. This logic:
https://github.com/ihhub/fheroes2/blob/1aa3c433b78eedf7c54d89aabb32c14e9019911b/src/engine/localevent.cpp#L1368-L1387
may not work in case of three (or more) fingers …
=> Rework the right mouse button simulation with touch events

src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_text.cpp
Adjust white space and Y, Q and V.
See explanation here: https://github.com/ihhub/fheroes2/issues/6194#issuecomment-1337429171
=> Adjust several button font characters

src/fheroes2/army/army_bar.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/gui/interface_itemsbar.h
=> Fix a few recently introduced code smells

src/engine/screen.h, src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_video.cpp
Reported by some users. I cannot replicate it but logically these are places to be fixed.
=> Fix black area not being rendering during video playback

src/engine/audio.cpp, src/engine/audio.h
=> Use logarithmic scale of sound volume

src/fheroes2/game/game_over.cpp, src/fheroes2/game/game_over.h, src/fheroes2/system/save_format_version.h
=> Remove the leftovers of the "Continue after victory" experimental setting

src/fheroes2/army/army.cpp
=> Fix a recently introduced code smell

src/fheroes2/gui/ui_text.cpp
This fixes Expansion Campaign button.
=> Fix rendering an extra empty line for specific texts

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_interface.cpp
close #6321
https://user-images.githubusercontent.com/113276641/207124866-dcd3954e-e4b7-43a1-8821-b2c97c878272.mp4
https://user-images.githubusercontent.com/113276641/207167267-f30f739b-f16f-4827-9a02-287b73d43d54.mp4
=> Do not mirror corpses of defeated troops (Battlefield)

src/fheroes2/dialog/dialog_recruit.cpp
This window was missing any popups in comparison with other windows.
=> Add popup windows for monster recruit dialog buttons

src/fheroes2/agg/bin_info.h, src/fheroes2/monster/monster_info.h
Hope they are not needed anymore.
=> Remove obsolete IWYU pragmas

src/engine/tinyconfig.cpp
=> Fix wrong usage of std::isspace() in TinyConfig

docs/README_android.md
To avoid countless questions how to get the game.
relates to #6008
=> Add a link to demo version within Android documentation

src/fheroes2/system/settings.cpp
=> Enable the instant battle (without the auto spell casting) by default

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_bridge.cpp, src/fheroes2/battle/battle_bridge.h, src/fheroes2/battle/battle_interface.cpp
Before this PR:
https://user-images.githubusercontent.com/32623900/208215297-a937516d-89cb-41c5-8564-9367dc27cce2.mp4
Now:
https://user-images.githubusercontent.com/32623900/208215374-7a51bcb7-23df-49be-b8fb-c547999a9134.mp4
Plus minor cleanup and simplification of overcomplicated castle bridge logic.
=> Fix bridge logic after morale event, simplify Bridge class, minor code cleanup

src/fheroes2/agg/agg_image.cpp
Italian is kept outside because the button font is bad and we don't have any players showing interest in this translation anyways.
=> Add French and German to use original assets for buttons

docs/INSTALL.md
SDL1 builds were removed from the 1.0.0 release.
=> INSTALL.md: remove SDL1 links

src/fheroes2/gui/ui_font.cpp
The accents are needed for the French buttons. Full stop is needed for several languages.
=> Add button font full stop and A and E with accents for CP1252

.github/workflows/cmake.yml, .github/workflows/make.yml
=> GitHub Actions: use ubuntu-20.04 image to build Linux x86-64 images using the Make workflow

script/packaging/common/fheroes2.appdata.xml
=> Add dev name to Flatpak package info

src/engine/screen.cpp
=> Fix screen flickering in SDL2

docs/fheroes2.6.in
- add info about files/soundfonts directory;
- rephrase a sentence about music.
=> update man page

src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/army/army.cpp, src/fheroes2/army/army_bar.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/campaign/campaign_scenariodata.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes_action.cpp
=> Don't lowercase creature name (or other string) when it is put first in phrase

docs/INSTALL.md, script/packaging/common/fheroes2.appdata.xml
=> Update docs and appdata (for flatpak)

src/resources/fheroes2.rc
Requested by our code style check machinery.
=> fheroes2.rc: update the copyright year

script/homm2/extract_homm2_resources.ps1, script/homm2/extract_homm2_resources.sh, script/homm2/extract_homm2_resources_for_app_bundle.sh
Ease of use for package maintainers and end users.
=> extract_homm2_resources.sh: add the innoextract support

src/engine/audio.cpp
=> Set audio frequency to 44100 on Windows

files/lang/pl.po
Update PL translation - fix wrong brackets
fixes #6456
=> Update PL translation - fix wrong brackets

src/fheroes2/battle/battle_interface.cpp
Follow-up to #6464 - just in case.
=> Battle::Interface::GetBattleCursor(): add the extra assertion

files/lang/pl.po
Fix few PL translations
fixes #6468
=> Fix few PL translations

android/app/src/main/res/values-de/strings.xml
German Translation of Toolset App.
If anyone wants to contribute other languages: feel free to attach xml file, then I'll expand the PR.
@oleg-derevenetz It should be enough to add the file, or is there more to be done?
=> Android Toolset Translation (German)

src/fheroes2/game/game_interface.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
=> Fix the Dimension Door shadow on resolutions 640+x480 & 640x480+, temporarily hide auxiliary panels in "no interface" mode

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/mp2.h, src/fheroes2/maps/mp2_helper.cpp, src/fheroes2/system/save_format_version.h, src/fheroes2/world/world.cpp
In preparation for the future Editor and to fully understand the current map format.
=> Code cleanup for terrain tile types

src/fheroes2/ai/normal/ai_normal_spell.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_grave.cpp, src/fheroes2/battle/battle_grave.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_troop.cpp
=> Fix the AI resurrect spell logic

src/fheroes2/heroes/heroes_move.cpp
=> Uncover the fog during the hero's instantaneous movement only if the hero is actually moving

src/fheroes2/game/game_campaign.cpp
=> Update spell points for campaign heroes at the start of a scenario

src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/dialog/dialog_adventure.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_over.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_buttons.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/resource/artifact.cpp
A cleanup phase towards a single Text class type code.
=> Reduce dependencies from old Text class

src/fheroes2/gui/interface_list.h, src/fheroes2/gui/ui_scrollbar.cpp
close #5840
This PR also makes the render of scrollbar only if scrollbar position was changed by mouse dragging to reduce FPS and CPU usage.
=> Fix scroll bar bottom position when dragging and fix high FPS rate when dragging scroll bar by mouse

android/app/src/main/res/values-ru/strings.xml
=> Android Toolset: add Russian translation

src/fheroes2/gui/statusbar.cpp
=> Fix incorrect status bar update call

src/fheroes2/game/game_credits.cpp
To appreciate @Districh-ru work.
=> Update team members in credits page

android/app/build.gradle, android/app/lint.xml, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, script/android/install_packages.bat, script/android/install_packages.sh, script/windows/install_packages.bat
Fixes the [issue](https://github.com/ihhub/fheroes2/pull/6564#issuecomment-1418096161) with libpng & sdl2_image.
=> Update Android & Windows dependencies, bump target Android API level to 33 (Android 13)

src/fheroes2/maps/maps_tiles.cpp
Follow-up to #6567 which fixed not all cases.
=> Fix saving of Maps::Tiles and Maps::TilesAddon enums

src/fheroes2/agg/m82.cpp, src/fheroes2/agg/m82.h
fix #6576
This sound is used also for Freeman's Foundry object in fheroes2, I decided not to change this.
=> Add the ambient sound for Abandoned Mine

.github/workflows/translation_update.yml, docs/TRANSLATION.md
close #6588
That's how it will look like:
https://oleg-derevenetz.github.io/fheroes2/TRANSLATION
The specific appearance, color scheme, etc., etc. are the subject of discussion.
=> Generate & display the current status of translations

src/engine/image_tool.cpp, src/engine/image_tool.h, src/fheroes2/agg/agg_image.cpp
=> Move TIL image decoding to a common place

files/lang/de.po
Fix for: https://github.com/ihhub/fheroes2/pull/6606
And test for 100% 😉
=> Fix title in German translation

.github/workflows/translation_update.yml
Hotfix for cases like this:
https://github.com/ihhub/fheroes2/actions/runs/4156983610/jobs/7191229979
=> Translation update workflow: hotfix for handling of partial msgfmt output

.github/workflows/sonarcloud.yml
https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache
=> SonarCloud: use newer syntax for the cfamily cache

src/engine/agg_file.h, src/fheroes2/agg/agg_image.cpp, src/tools/icn2img.cpp
=> Make ICNHeader::offsetX and ICNHeader::offsetY signed

src/fheroes2/campaign/campaign_scenariodata.cpp
=> Fix an invalid option for scenario 1 of Roland Campaign

script/agg/extract_agg.bat, script/agg/extract_agg.sh, script/android/install_packages.sh, script/demo/download_demo_version.sh, script/homm2/extract_homm2_resources.sh, src/engine/image_tool.cpp, src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/game/game_interface.h, src/fheroes2/gui/interface_events.cpp, src/tools/extractor.cpp, src/tools/pal2img.cpp
=> Run pal2img tool in extract_agg scripts, minor code cleanup

src/engine/image_tool.cpp
=> Add an ability to load 8-bit images

.github/workflows/make.yml, .github/workflows/msvc.yml, script/agg/extract_agg.bat, script/agg/extract_agg.sh, src/tools/extractor.cpp, src/tools/icn2img.cpp
This is based on the request from composers in Discord.
relates to #6568
=> Add sound related tools to tool package

src/fheroes2/agg/mus.cpp, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/heroes/heroes_action.cpp
fix #6633
fix #6634
fix #6637
fix #6647
Also I couldn't resist and did what I wanted for a long time - moved all auxiliary functions in `ai_hero_action.cpp` and `heroes_action.cpp` to the anonymous namespace.
=> Fix musical effects for various objects, move auxiliary functions to the anonymous namespace

src/fheroes2/kingdom/puzzle.cpp
=> Fix issue with the puzzle rendering

src/fheroes2/agg/m82.cpp, src/fheroes2/agg/m82.h, src/fheroes2/game/game.cpp
=> Fix volcano sounds

VisualStudio/common.props, src/CMakeLists.txt, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_quantity.cpp, src/thirdparty/libsmacker/smacker.c, src/tools/82m2wav.cpp, src/tools/bin2txt.cpp, src/tools/xmi2midi.cpp
=> Fix remaining MSVC warnings

src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/battle/battle_pathfinding.h
fix #6668
https://user-images.githubusercontent.com/32623900/219870371-f340d4be-e831-4f26-896a-61b758c734cd.mp4
https://user-images.githubusercontent.com/32623900/219870454-9fb186aa-e554-4a50-b61d-1b39d3bc790f.mp4
=> Track the board status while caching the battle pathfinder graph

src/fheroes2/kingdom/view_world.cpp, src/fheroes2/kingdom/view_world.h, src/fheroes2/system/settings.h
=> Memorize zoom level of the View World screen

src/fheroes2/maps/maps_tiles_quantity.cpp
Avoid & log potential overflows when manipulating the number of monsters on the tile (for example, during weekly/monthly growth).
=> Avoid overflow on manipulations with number of monsters on tile, remove static_cast

src/fheroes2/gui/interface_radar.cpp
=> Use an '^' operator for radar ROI with world intersection

src/fheroes2/CMakeLists.txt
Copy fheroes2 executable to project root when done building.
=> CMake to copy executable to project root

src/fheroes2/dialog/dialog_quickinfo.cpp
=> add a frame for a hero portrait on the quickinfo dialog

src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h
=> Remove unused functions

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/heroes/heroes_action.cpp
=> Tune sounds for guarded creature dwellings and streamline the logic

src/engine/zzlib.cpp
=> zzlib.cpp: avoid extra reinterpret_cast conversions, check the results of static_cast conversions

src/engine/zzlib.cpp
=> zzlib.cpp: avoid potential unsigned overflow when calculating the initial buffer size

files/lang/cs.po
Dwellings, Structures, Monsters
=> Czech translation Update

src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes_action.cpp
=> Fix crash at the start of every map

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h
close #6740
Hi @LeHerosInconnu could you please take a look at this implementation to find out whether it matches the expected logic?
=> Change the logic of reinforcement of the guest hero's army during the castle defense

src/fheroes2/ai/normal/ai_normal_hero.cpp
=> Handle tasks removed by another hero

src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h
=> Fix the battle casualty report when non-true Resurrect spell was used during battle

src/fheroes2/battle/battle_troop.cpp
=> Allow resurrected units to act on the current turn if they have not yet had their turn

script/android/install_packages.bat, script/android/install_packages.sh, script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/33 for details.
=> Update package hashes

docs/README_android.md
Information about minimum supported Android version
=> Update documentation about Android

src/fheroes2/gui/ui_dialog.cpp
fix #6838 
Now the '_hero' is passed in the 'draw()' 
* Have not checked if it has any impact on the overall code.
=> SP now calculated with SPR after mouse click on icon

src/fheroes2/battle/battle_action.cpp
=> Chain lightning blocked, if first target unit resists spell.

src/fheroes2/army/army_troop.cpp, src/fheroes2/army/army_troop.h, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/kingdom/speed.cpp, src/fheroes2/kingdom/speed.h
=> Added numeric speed of monsters to hero dialog fix #6526

docs/GRAPHICAL_ASSETS.md, src/engine/pal.cpp, src/tools/pal2img.cpp
=> Add cycling animation information into artist documentation

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/army/army.cpp, src/fheroes2/dialog/dialog_quickinfo.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_radar.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/kingdom/view_world.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/maps_tiles_quantity.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/monster/monster.cpp, src/fheroes2/system/save_format_version.h, src/fheroes2/world/world.cpp
=> Separate Abandoned and Haunted mines

src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/battle/battle_main.cpp
Number of skeletons is rounded down now.
Also unused code is cleaned. 
fix #6871
=> correct rounding of raising skeletons count

docs/TRANSLATION.md
Added info about where to find the flatpak installation.
=> Flatpak info translation page

src/fheroes2/army/army_bar.cpp
=> Fix a few more code smells

src/fheroes2/dialog/dialog_hotkeys.cpp, src/fheroes2/game/game_hotkeys.cpp, src/fheroes2/game/game_hotkeys.h
=> Make hotkey names translatable

src/fheroes2/battle/battle_interface.cpp
=> Show mirrored monster image in army order

src/fheroes2/maps/maps_objects.cpp, src/fheroes2/maps/maps_objects.h, src/fheroes2/maps/mp2.h, src/fheroes2/world/world_loadmap.cpp
- remove few unused structures from mp2.h file and add appropriate comments about them in the code
- add more checks while loading an MP2 file
=> Cleanup MP2 object loading code

src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h
We check more conditions under which Wells should be visited by AI heroes. The change covers only corner cases but it slightly improves AI logic.
relates to #6923
=> Reduce AI obsession with Wells

src/fheroes2/game/game_startgame.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/resource/resource.cpp, src/fheroes2/resource/resource.h
=> Adjusted number of resources subtracted in event messages.

src/fheroes2/dialog/dialog_quickinfo.cpp
=> Show approximate information about the mine guardians to a non-owner player

src/fheroes2/heroes/heroes_meeting.cpp
=> Hero info window frame is missing when checking through hero meeting window

.github/workflows/android.yml
=> Android: build AAB in addition to APK

files/lang/de.po
As requested by @ihhub for 1.0.3
=> Update German Translation

docs/PRIVACY_POLICY.md
It is required for Google Play Store. It is simple as we don't collect any personal information.
relates to #6822
=> Add a document for privacy policy for the project

script/packaging/common/fheroes2.appdata.xml
Add new links / adjust Links to "Github Pages" if possible.
By the way: The new Flathub Beta looks really nice. https://beta.flathub.org/de/apps/io.github.ihhub.Fheroes2
=> Flatpak Appdata update

src/fheroes2/game/game_startgame.cpp
Solves https://github.com/ihhub/fheroes2/issues/1582.
=> Add "New week!" title to dialog showing start of a new week

docs/INSTALL.md
close #6998
Also fix formatting for some links.
=> Add Google Play link to the INSTALL.md

script/android/install_packages.bat, script/android/install_packages.sh, script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/34 for details.
=> Update hashes for Windows and Android pre-built library packages

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_troop.cpp
fix #7036
fix #7037
Hi @LeHerosInconnu could you check this PR please?
=> Fix the behavior of Berserk and Hypnotize spells

src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_arena.h, src/fheroes2/battle/battle_dialogs.cpp
=> Catapult and castle towers should still act, even if there are no troops in the respective armies capable of taking any action

src/fheroes2/gui/interface_events.cpp
Solves https://github.com/ihhub/fheroes2/issues/1576.
=> Add "End Turn" title to dialog when heroes can move and you are ending your turn

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_common.cpp, src/fheroes2/ai/normal/ai_normal_battle.cpp
Fixes edge case when AI doesn't have a Castle building or gold in the bank to purchase.
=> AI should check for castles and funds before retreat

src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_castle.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/resource/resource.cpp, src/fheroes2/resource/resource.h
Adding a kingdom budget into consideration. AI heroes now should focus on collecting missing resources based on current castle build order.
=> Strategic AI economy update

docs/TRANSLATION.md
=> Add Vietnamese percentage icon to translation guide

src/engine/translations.cpp
Correct pointing to array positions - credits to Granfalegion
=> Slovak translation string pointing change

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/army/army.cpp, src/fheroes2/army/army.h, src/fheroes2/army/army_troop.h, src/fheroes2/battle/battle_army.cpp, src/fheroes2/castle/castle_town.cpp, src/fheroes2/heroes/heroes_dialog.cpp
fix #5523
fix #7063
Plus minor code modernization.
Case from #5523:
https://user-images.githubusercontent.com/32623900/234799576-f344d4e6-29cd-43fb-ae91-ede338204295.mp4
=> Fix calculation of castle towers strength for AI

docs/DEVELOPMENT.md
=> Add instructions for building the fheroes2 project for Android to DEVELOPMENT.md

src/engine/translations.cpp
=> Remove duplicate line in translations.cpp

src/fheroes2/dialog/dialog_armyinfo.cpp
To be consistent with the rest of the game.
=> Add popup windows for monster dialog buttons

src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_board.h
=> Create small and large obstacles on the battlefield at the same time.

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
=> Fix missing metadata conversion from old saves when a hero stands on an object

src/fheroes2/agg/agg_image.cpp, src/fheroes2/game/fheroes2.cpp
This causes all sorts of nasty rendering issues which we shouldn't take responsibility to fix.
=> Avoid pirated translation which are applied on English version of the game

src/fheroes2/battle/battle_army.cpp, src/fheroes2/battle/battle_army.h, src/fheroes2/battle/battle_interface.cpp
=> Fix creature idle animation freeze during Blind / Paralyze spell. Battlefield.

src/fheroes2/ai/normal/ai_normal_hero.cpp
relates to #5884
relates to #6923
Before the changes Dimension Door jump was always done once and then the target was re-evaluated. With these changes the behavior of an AI hero is the same as a normal walk: complete the full path without interruptions and changing mind.
=> Do not stop hero's movement after the first Dimension Door jump

src/fheroes2/dialog/dialog_selectcount.cpp, src/fheroes2/gui/ui_button.cpp, src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_keyboard.cpp, src/fheroes2/gui/ui_text.cpp
This was the easiest to do.
I might not have the latest translation files for Russian so buttons might be translated for users.
relates to #6924
=> Extra virtual keyboard language support for Russian

files/lang/bg.po, files/lang/de.po, files/lang/es.po, files/lang/fr.po, files/lang/hu.po, files/lang/it.po, files/lang/nb.po, files/lang/pl.po, files/lang/pt.po, files/lang/ru.po, files/lang/sv.po
Some strings have become outdated.
=> Remove unused translation texts

src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_keyboard.cpp
Polish has extra 9 characters on top of English alphabet.
relates to #6924
=> Add Polish to Virtual Keyboard

changelog.txt, script/packaging/common/fheroes2.appdata.xml
=> Fix incorrect changelog date

src/fheroes2/ai/normal/ai_normal_hero.cpp
=> Fix infinite loop while using Dimension Door spell by AI hero

script/windows/install_packages.bat
fix #7073
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/35 for details.
=> Update Windows dependencies

android/app/build.gradle, android/build.gradle
fix #7174
Plus various dependency updates. Tried this PR on Lenovo TAB 2 A10-70L with Android 6 and everything works fine.
=> Fix java.nio desugaring on Android 7 and below

src/fheroes2/gui/ui_font.cpp
Update of CP1250 font support for characters:
ľ, ĺ, ô, ŕ, ä (both uppercase and lowercase, normal and small font, extra character "â" added too).
ť (lowercase t with caron) fixed.
=> Update CP1250 font support - Slovak characters

src/fheroes2/audio/audio_manager.cpp, src/fheroes2/audio/audio_manager.h, src/fheroes2/heroes/heroes_action.cpp
=> MusicalEffectPlayer: do not change music volume if there is no music file for the corresponding effect, reduce I/O when searching for music files

files/lang/bg.po
My latest updates from Bulgarian translation. And I see one place where the buttons are not translated yet!
=> Update of Bulgarian translation

src/fheroes2/battle/battle_main.cpp, src/fheroes2/campaign/campaign_savedata.cpp, src/fheroes2/campaign/campaign_savedata.h, src/fheroes2/game/game_campaign.cpp, src/fheroes2/heroes/heroes_action.cpp
=> Fix logic for defeated heroes in campaign scenarios

src/fheroes2/maps/mp2.cpp
=> Fix the Skeleton passability

src/fheroes2/battle/battle_interface.cpp
=> Do not play same kill/wince sounds simultaneously

src/fheroes2/army/army.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes_base.cpp, src/fheroes2/spell/spell_book.cpp, src/fheroes2/system/players.cpp
=> Do not check whether a hero can cast a spell if spellcasting is prohibited in principle

src/fheroes2/battle/battle_dialogs.cpp
=> Fix okay button not being redrawn in battle options dialog

src/engine/image.cpp, src/fheroes2/gui/ui_keyboard.cpp
This PR adds shadows for the Virtual keyboard buttons
=> Add shadows for the Virtual Keyboard buttons

src/fheroes2/campaign/campaign_savedata.cpp, src/fheroes2/campaign/campaign_savedata.h, src/fheroes2/campaign/campaign_scenariodata.cpp, src/fheroes2/campaign/campaign_scenariodata.h, src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_helper.cpp, src/fheroes2/resource/artifact.cpp, src/fheroes2/system/save_format_version.h, src/fheroes2/world/world.cpp
=> Campaign scenario UI: show the currently selected bonus if the campaign scenario is already in progress

src/fheroes2/ai/normal/ai_normal_kingdom.cpp
close #7296
You can test the bug using this save file:
[The_Great_War_0069.zip](https://github.com/ihhub/fheroes2/files/11721685/The_Great_War_0069.zip)
End the turn and observe the behavior in debug mode.
=> Fix invalid AI castle reinforcement issue

script/homm2/extract_homm2_resources.ps1
=> extract_homm2_resources.ps1: add support for the Ubisoft digital HoMM2 version

src/fheroes2/agg/agg_image.cpp
Fix https://github.com/ihhub/fheroes2/issues/7227
Also fixed som leftovers of original text being present on the TOWNS/CASTLES button and the vertical misalignment of the guilds and well EXIT button.
=> Fixes to button text placements and smaller fixes

.github/workflows/android.yml
=> Android: put the AAB file to a separate ZIP archive

src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/dialog/dialog_selectcount.cpp, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/gui/ui_keyboard.cpp
Fix #7325
As `InsertString()` was used only for inserting a single character it is converted to `insertCharToString()`
=> Fix display of false symbols afer the blinking cursor

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/kingdom/kingdom_overview.cpp
Just a simple code cleanup to reduce the amount of useless work by CPU.
=> Reduce the number of calls to get a singleton instance

src/fheroes2/ai/ai.h, src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/heroes/heroes.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/world/world.cpp
close #7290
You can test this save file (see the difference in a Red AI hero):
[AI_fog_discvery.zip](https://github.com/ihhub/fheroes2/files/11800995/AI_fog_discvery.zip)
=> Make an AI hero to stop moving when a new action object is discovered

src/fheroes2/castle/mageguild.cpp, src/fheroes2/castle/mageguild.h, src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/spell/spell.cpp, src/fheroes2/spell/spell.h
fix #7117
fix #7127
Changes are made according to this description:
https://handbookhmm.ru/kakim-obrazom-zaklinaniya-popadayut-v-magicheskuyu-gildiyu.html
with the exception of "cheats" for AI-controlled castles, because our AI is different and I doubt that it needs to be strengthened in this way. Thus, AI plays in this PR by the same rules as a human player.
=> Rework the spell generation in castle's Mage Guilds

src/fheroes2/spell/spell.cpp
=> Spell::getAllSpellIdsSuitableForSpellBook(): minor optimization

src/fheroes2/ai/normal/ai_normal_hero.cpp
=> Fix crash while an AI hero captures a castle

.github/workflows/make.yml, src/Makefile.vita
See https://github.com/ihhub/fheroes2/pull/7376#issuecomment-1617564009 for details. Workaround in the `make.yml` is temporary until the https://github.com/vitasdk/vdpm/pull/101 will be merged.
=> Fix build for PS Vita

files/lang/Makefile
=> Pass --no-convert to msgfmt

.github/workflows/make.yml
https://github.com/vitasdk/vdpm/pull/101 has been merged.
=> PS Vita build: remove the temporary workaround

src/fheroes2/ai/normal/ai_normal_kingdom.cpp
=> Fix invalid Stone Liths after AI threat estimation

src/engine/image_tool.cpp
This PR is a part of #7233 and it makes ICN decode a bit faster (about 2-3 %).
=> Minor ICN decode speed-up

src/fheroes2/game/game_campaign.cpp
close #6922
This would help some players to succeed with their campaign.
=> Allow to lower difficulty down of campaign during gameplay

src/fheroes2/game/game_loadgame.cpp
close #7414
This is easily verified on the demo version of the game.
=> Disable Campaign button if no campaign resources are present

files/lang/sv.po
misc.
Changed Elemental from Ande to Väsen.
Changed Rogues from Skurkar to Rövare.
=> Update Swedish Translation

src/fheroes2/battle/battle_troop.cpp
=> Apply Cure & Mass Cure spells only if the target unit is either damaged or has negative magical effects

src/fheroes2/gui/interface_events.cpp
Solves https://github.com/ihhub/fheroes2/issues/1883.
=> Add "Quit" title to quit dialog

src/fheroes2/battle/battle_arena.cpp, src/fheroes2/dialog/dialog_game_settings.cpp, src/fheroes2/heroes/heroes_base.cpp
This changes some of the texts to be more correct in my opinion.
~~Boats can be summoned in lakes, which technically aren't oceans. Body of water sounds better to me than ocean location.~~
Nope, see discussion below.
=> Rephrase various game dialogs

files/lang/sv.po
=> Swedish translation update

.github/workflows/sonarcloud.yml
=> SonarCloud: fix the warning about the Java 11 deprecation

src/fheroes2/ai/normal/ai_normal_battle.cpp
Fixes #7498 . Fixes #7517 .
Tested on saves within respective tickets but might be useful to check few others.
=> Battle AI should switch to offense instead of passing

files/lang/dk.po
Focused mostly on oneliners in various contexts that has to do with the menu screens
=> Update danish translation (1133)

src/fheroes2/ai/ai.h, src/fheroes2/ai/ai_base.cpp, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/gui/interface_focus.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_move.cpp, src/fheroes2/heroes/heroes_spell.cpp, src/fheroes2/heroes/route.cpp, src/fheroes2/heroes/route.h, src/fheroes2/system/save_format_version.h
=> Fix issue when AI hero "jumps back" during the fog discovery, various fixes & improvements

android/app/build.gradle, android/build.gradle, android/gradle.properties, script/android/install_packages.bat, script/android/install_packages.sh, script/windows/install_packages.bat
* Update Android Gradle Plugin to 8.1.0 (should finally fix the https://issuetracker.google.com/issues/282544786);
* Bump Android & Windows dependencies (see https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/36 for details).
=> Update Android & Windows dependencies

src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/system/settings.h
Solves https://github.com/ihhub/fheroes2/issues/6888 by storing current map filter selection filter and applying it again when selection a scenario. Remember until you quit the game.
=> Remember map filter selection until you quit the game

src/fheroes2/game/game_over.cpp
=> Add "Victory!" title to victory dialog

src/fheroes2/game/game_startgame.cpp
=> Add "New Month!" title for new month

src/fheroes2/castle/castle_mageguild.cpp
=> Improve Mage guild status message for learnt spells

src/fheroes2/gui/ui_font.cpp
=> Fix size of the button letter Æ

CONTRIBUTING.md
Make the file to contain the same information as README.md to be consistent.
close #6603
=> Update Contributing file

src/fheroes2/dialog/dialog_quickinfo.cpp
close #2717
These are the longest texts:
=> Adjust text for Quick Info dialogs

src/fheroes2/gui/ui_button.cpp, src/fheroes2/gui/ui_button.h
Less memory usage and faster. A full power of C++11.
=> Avoid extra image copy while constructing specific buttons

src/fheroes2/dialog/dialog_armyinfo.cpp
=> Fix monster name in monster info dialog

src/fheroes2/army/army_ui_helper.cpp, src/fheroes2/battle/battle_only.cpp, src/fheroes2/castle/castle_mageguild.cpp, src/fheroes2/castle/castle_tavern.cpp, src/fheroes2/castle/castle_well.cpp, src/fheroes2/dialog/dialog_language_selection.cpp, src/fheroes2/dialog/dialog_recruit.cpp, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/game/game_credits.cpp, src/fheroes2/gui/ui_text.cpp, src/fheroes2/gui/ui_text.h
relates to #7497
Also small rendering optimization for text in multiple places to avoid extra memory copies.
=> Show ... in Load/Save File dialog for long names

src/fheroes2/battle/battle_dialogs.cpp
close #7324
You can test this save file:
[surrender_window.zip](https://github.com/ihhub/fheroes2/files/12444389/surrender_window.zip)
=> Shift text in Surrender window

src/fheroes2/game/game_mainmenu.cpp
=> Expand clickable area for settings in the Main Menu

src/fheroes2/castle/buildinginfo.cpp
=> Change Shipyard construction message

src/fheroes2/dialog/dialog_selectfile.cpp
=> Fix Load/Save file title position and color

src/engine/serialize.cpp, src/engine/serialize.h, src/engine/tinyconfig.cpp, src/engine/tools.cpp, src/engine/tools.h, src/engine/translations.cpp, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/game/game_io.h, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_fileinfo.h
relates to #6681
The slowest part - file reading from a storage, remains unchanged.
=> Speed up map, translation and save files loading

src/engine/tinyconfig.cpp, src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/maps/maps_fileinfo.cpp
Don't include `<locale>` twice and use `std::from_chars()` instead of fancy `GetInt()` (with UB).
=> Fix a few minor code issues

src/fheroes2/agg/agg_image.cpp
=> Fix foreign pixels on snow battlefield objects

src/fheroes2/dialog/dialog_file.cpp
=> File options menu disappears on cancelling load game dialog

src/fheroes2/agg/agg_image.cpp
=> Add Czech to original resource exceptions

src/engine/screen.h, src/engine/translations.cpp, src/fheroes2/gui/cursor.cpp, src/fheroes2/gui/cursor.h, src/fheroes2/gui/ui_dialog.cpp, src/fheroes2/gui/ui_dialog.h
plus small code cleanup.
regression from #7640
=> Fix SonarQube bugs and blocker issues

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/game/game_startgame.cpp
Because the method does the check internally.
=> Remove extra checks while setting cursor type

files/lang/sv.po
=> Update Swedish Translation (small fixes)

src/fheroes2/game/game_over.cpp
=> Show highscores after multiplayer game

src/fheroes2/ai/normal/ai_normal_battle.cpp
=> Fix some recently introduced code smells

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/dialog/dialog_selectitems.h, src/fheroes2/gui/skill_bar.cpp
=> Show only skills that the hero doesn't already have in battle only skill selection list;

src/fheroes2/gui/ui_text.cpp
=> Fix ? symbols appearing in single-line texts

src/fheroes2/castle/castle_mageguild.cpp, src/fheroes2/gui/ui_text.cpp, src/fheroes2/spell/spell_book.cpp
close #6885
close #7723
should be merged after #7724
=> Fix spell rendering issues when words are divided in the middle

src/fheroes2/battle/battle_troop.cpp, src/fheroes2/resource/artifact_info.cpp
=> Wand of Negation should grant immunity against the Mass Dispel spell

src/fheroes2/heroes/heroes_action.cpp
Just a minor improvement (rather cosmetic in nature).
=> ActionToStables(): remove redundant check

src/fheroes2/gui/interface_list.h
To quickly jump to the beginning or end of a list.
=> Use Home and End hotkeys to navigate among items within a list

files/lang/bg.po, files/lang/cs.po, files/lang/de.po, files/lang/dk.po, files/lang/es.po, files/lang/fr.po, files/lang/it.po, files/lang/nb.po, files/lang/pl.po, files/lang/ru.po, files/lang/sk.po, files/lang/sv.po, files/lang/vi.po
Leftovers after changing the code.
=> Remove unused texts from translations

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_castle.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h, src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_buttons.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/gui/interface_focus.cpp, src/fheroes2/gui/interface_icons.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_base.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/kingdom/kingdom_overview.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/spell/spell_info.cpp, src/fheroes2/system/save_format_version.h, src/fheroes2/world/world.cpp
- do not use empty structures **KingdomCastles** and **KingdomHeroes** as they were doing literally nothing. It is hard to handle different variable types.
- change gold income logic for AI. It is better to avoid any floating point calculation errors
- do some code clean up in Heroes class to make the code human readable
=> Hero related code cleanup

src/fheroes2/editor/editor_mainmenu.cpp
They were triggered for right click mouse event.
=> Fix Editor Main Menu hotkeys

files/lang/ru.po
- Removed `#, fuzzy` marks added after  #7755 because the translated text does not have double spaces.
- Corrected the translation for the Steelskin spell description.
- Updated the copyright year ... after 9 months. :)
=> Update Russian translation

src/fheroes2/battle/battle_troop.cpp
Since Ghosts have Soul Eater ability it is important to calculate the possible growth of their numbers after the attack.
close #7685
=> Improve AI behavior for Ghosts during battle

src/fheroes2/battle/battle_troop.cpp
relates to #7685
I realized that this is an absolutely invalid logic.
=> Revert Ghost estimation for the AI

src/fheroes2/dialog/dialog_armyinfo.cpp
relates to #5270
You can test the change using this save file:
[Broken_Alliance_0001.zip](https://github.com/ihhub/fheroes2/files/12707889/Broken_Alliance_0001.zip)
=> Update followers window to support text mode

src/fheroes2/dialog/dialog_selectscenario.cpp
=> Fix memorizing the position in the map list when changing the map size filter

src/fheroes2/gui/player_info.cpp, src/fheroes2/gui/text.cpp, src/fheroes2/gui/text.h
also remove the usage of the old class.
Before the changes (master branch) to display AAAAAAAAAA name:
After the changes:
=> Properly display player name in the New Game window

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h
AI was counting disabled shooters skewing battle estimations the wrong way.
=> Fix battle AI protecting paralyzed archers

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface_panel.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_helper.cpp, src/fheroes2/maps/maps_tiles_helper.h
Relates to #6845 
This PR implements streams placing on terrains.
The Erase tool will be improved in the next PR.
=> Implement streams placing in Editor

src/fheroes2/ai/normal/ai_normal_spell.cpp
=> Add a mirror image check during spell evaluation

src/fheroes2/ai/ai_common.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h
Might be up for discussion but removing the optimization should make battles easier. It will be a noticeable difference in behaviour between difficulties.
=> AI should avoid splitting troops on easy difficulty

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h
To address the complains of players about the harshness of the AI.
=> Restrict heroes meetings and army merging on Easy difficulty

src/fheroes2/editor/editor_interface_panel.cpp
Make the life of map makers easier.
=> Remember monster selection in the Editor

files/lang/de.po
Fix the German translation, Part 1 of 8
See also https://github.com/ihhub/fheroes2/issues/7860
And https://github.com/ihhub/fheroes2/pull/7865
=> Fix German translation No.1

src/fheroes2/editor/editor_mainmenu.cpp
This is not a part of the first stage so it is better not to tempt users.
=> Disable Random Map option in the Editor

files/lang/hu.po
More translations and corrections till "MIDI"
=> Hungarian translation update part 04

src/fheroes2/army/army_bar.cpp, src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/dialog/dialog_selectitems.h, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface_panel.cpp, src/fheroes2/maps/maps_tiles_helper.cpp, src/fheroes2/maps/maps_tiles_helper.h, src/fheroes2/maps/maps_tiles_render.cpp, src/fheroes2/monster/monster.cpp, src/fheroes2/monster/monster.h
https://github.com/ihhub/fheroes2/assets/19829520/05bc20ed-d0a1-4f85-847e-e4c40279f511
=> Add an ability to place Random Monsters in the Editor

src/fheroes2/heroes/heroes_base.cpp
=> Town Gate and Town Portal spells: use depersonalized wording

src/fheroes2/dialog/dialog_hotkeys.cpp
Fix #7829 
This PR makes Hot Keys dialog wider to fit most hot-key descriptions and adds support of evil interface.
=> Rework Hot Keys dialog to support flexible size and Evil interface

src/fheroes2/army/army_ui_helper.cpp
Fix the recently introduced code smell.
=> Use prefix decrement

src/fheroes2/maps/maps_tiles.cpp
=> Fix summon boat spell assertion

src/fheroes2/castle/castle_dialog.cpp
=> Fix the impossibility of actions in hero's army after recruitment

src/fheroes2/dialog/dialog_armyinfo.cpp
=> Display 0 shots during battle for archers

src/fheroes2/agg/agg_image.cpp, src/fheroes2/gui/interface_buttons.cpp, src/fheroes2/gui/ui_button.cpp, src/fheroes2/gui/ui_button.h
This PR adds an image for hero action button (relates to #7849)
https://github.com/ihhub/fheroes2/assets/113276641/fd60db58-985a-4c7d-b148-1e1aeabdb218
=> Add hero action button image

src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/castle/castle_building.cpp, src/fheroes2/maps/maps_tiles.cpp
=> Fix the logic of purchasing a boat in shipyard

src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_spell.cpp, src/fheroes2/battle/battle_action.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/battle/battle_troop.cpp, src/fheroes2/battle/battle_troop.h
fix #7996
https://github.com/ihhub/fheroes2/assets/32623900/a4cebf9b-46db-4151-83fc-19043ae676f1
https://github.com/ihhub/fheroes2/assets/32623900/bb0e9793-4508-46d1-a57d-2389ed79aaf4
Also I modernized code a bit.
=> AI: take into account the spell immunity when calculating the effectiveness of mass damage spells

src/fheroes2/agg/agg_image.cpp
A tiny performance improvement.
=> Speed up monochrome cursors loading

src/fheroes2/game/game_interface.h, src/fheroes2/gui/interface_events.cpp
- Fix #8030 (a regression after #8000).
=> Focus on the hero when he starts to move by the Move button press

files/lang/sv.po
Added translation into swedish for the newly added strings for the editor,
=> Swedish translation update (#8)

src/fheroes2/castle/castle.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
=> Shipyard: Treat water with an object's shadow as water free of objects

.github/dependabot.yml
To keep these actions up-to-date.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions
=> Enable Dependabot for actions from the GitHub Marketplace

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface_panel.h, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/map_object_info.h, src/fheroes2/maps/maps_tiles_helper.cpp
Also make top object parts do not have any layer as they should.
=> Group objects for the Editor into logical buckets

src/fheroes2/gui/ui_text.cpp
=> Fix multi-font text offset calculation

src/fheroes2/game/fheroes2.cpp
Based on the feedback from social media.
=> Allow application closure by close button if no resources available

src/fheroes2/game/game_scenarioinfo.cpp
A small performance improvement.
=> Speed up map loading for New Game

src/fheroes2/editor/editor_interface_panel.cpp, src/fheroes2/editor/editor_interface_panel.h
In the future we should use another cell highlighting color for tiles that are editable.
=> Add cell selection in Details mode for the Editor

android/app/build.gradle, android/build.gradle, script/android/install_packages.bat, script/android/install_packages.sh, script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/40 for details. Plus update of AGP and some Android dependencies.
=> Update hashes for Android & Windows dependency packages

src/fheroes2/dialog/dialog_selectfile.cpp
=> fix scroll location on file deletion

src/fheroes2/dialog/dialog_hotkeys.cpp, src/fheroes2/game/game_hotkeys.cpp, src/fheroes2/game/game_hotkeys.h
Based on the feedback from players.
=> Add Hotkeys categories for the future UI improvements

VisualStudio/fheroes2/sources.props, src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface_panel.h, src/fheroes2/editor/editor_mainmenu.cpp, src/fheroes2/heroes/heroes_base.cpp, src/fheroes2/heroes/heroes_base.h, src/fheroes2/maps/map_format_helper.cpp, src/fheroes2/maps/map_format_helper.h, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/map_object_info.h, src/fheroes2/maps/maps_tiles.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
This is a base map file format what will be modified in the future many times. However, this is a step stone towards a full editor.
To test map format saving you can add this code:
```cpp
StreamFile file;
file.open( "test.map", "wb" );
Maps::Map_Format::MapFormat map;
Maps::saveMapInEditor( map );
file << map;
file.close();
```
To test map format loading you can add this code:
```cpp
StreamFile file;
file.open( "test.map", "rb" );
Maps::Map_Format::MapFormat map;
file >> map;
Maps::readMapInEditor( map );
```
=> Add base map file format

files/lang/sv.po
The lastest newly added strings translated and a few small fixes.
=> Swedish translation update (#10)

src/fheroes2/gui/ui_text.cpp, src/fheroes2/gui/ui_text.h
relates to #8058,  #7491 and #1675
=> Add text rendering within a given ROI

src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle_building.cpp, src/fheroes2/castle/castle_building_info.cpp, src/fheroes2/castle/castle_town.cpp, src/fheroes2/dialog/dialog_gameinfo.cpp, src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_mainmenu.cpp, src/fheroes2/game/difficulty.h, src/fheroes2/game/game.cpp, src/fheroes2/game/game_highscores.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/gui/player_info.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/kingdom/color.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/view_world.cpp, src/fheroes2/maps/map_format_helper.cpp, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/map_object_info.h, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_fileinfo.h, src/fheroes2/resource/artifact.cpp, src/fheroes2/system/players.cpp, src/fheroes2/system/settings.h, src/fheroes2/world/world.cpp
- add a new map format entry - RESURRECTION and make the corresponding logic in the code
- rename some Settings class related methods
- add basic logic to load and save new maps
- expand new map format
- make code cleanup in `Maps::FileInfo` class
=> Add basic logic to load and save maps through UI

src/fheroes2/castle/castle.cpp
=> Fix a crash with castle overlapping inside a map

files/lang/hu.po
More fuzzy removals, monster names and their plurals corrected
=> Hungarian language update #10

src/fheroes2/editor/editor_interface.cpp
=> Set object ID for all object parts of town / castle

src/fheroes2/ai/normal/ai_normal_spell.cpp
fix #8162
https://github.com/ihhub/fheroes2/assets/32623900/74dc2461-f9ac-473f-82b3-457c473b3c8e
=> Fix the AI spell damage estimation logic for units immune to the given spell

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/maps/map_object_info.cpp
Campfire is a part of Adventure Treasures. Also, moved 2 functions to another location to follow the same order as the enumeration.
=> Add Campfire object in the Editor

files/lang/sv.po, src/fheroes2/army/army.cpp, src/fheroes2/castle/castle_building_info.cpp, src/fheroes2/heroes/skill.cpp, src/fheroes2/kingdom/luck.cpp, src/fheroes2/kingdom/morale.cpp
Relates to discussion here https://github.com/ihhub/fheroes2/discussions/6915
Changed the Attack, Defence, Knowledge and Spell Power so it refers to the hero and not your hero.
Spell power changed _length_ to _duration_ instead.
The same for secondary skills.
Changed Diplomacy from _group_ to _army._
Changed Morale and Luck to refer to the units/troops as units and not _armies_.
Changed the undead luck modifier to refer all of the heros units a an _army_ and not a _group_.
=> Update some descriptions

src/engine/translations.cpp
Related to #8168
https://github.com/ihhub/fheroes2/assets/32623900/56b79cb5-a0dc-4873-adcb-169f5ae35672
=> Add missing rules for the plural in Hungarian

src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_helper.cpp
=> Fix inaccurate Jail removal

src/fheroes2/heroes/heroes.cpp, src/fheroes2/system/save_format_version.h
=> Fix heroes with no names

src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_battle.cpp
=> AI: use the "cautious offensive" tactics only against melee-only armies without the distant attack potential (including damage spells)

src/fheroes2/agg/agg_image.h, src/fheroes2/gui/ui_language.h, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h
- add supported language (see comments in the code)
- add metadata structures for the objects. Castle metadata is not complete as we need to define what we want to store
=> Expand the map format

src/fheroes2/editor/editor_mainmenu.cpp
=> Reset object UID while creating a new map in the Editor

src/engine/screen.cpp, src/engine/translations.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_spell.cpp, src/fheroes2/campaign/campaign_data.cpp, src/fheroes2/castle/castle.h, src/fheroes2/castle/castle_building.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/system/gamedefs.h, src/fheroes2/system/settings.cpp
=> Fix several SonarQube smells

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h
=> Implement warning message in the Editor

src/fheroes2/editor/editor_interface_panel.cpp
Fix the code smell detected by SonarQube. My small contribution to reducing the number of code smells.
=> Remove redundant return type

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/dialog/dialog_selectitems.h, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface_panel.cpp, src/fheroes2/maps/map_object_info.cpp
I also added extra check for the objects.
=> Add dwellings into the Editor

src/engine/localevent.cpp
For now we do nothing but at least log an event.
=> Handle Low Memory event for Android and iOS

src/fheroes2/resource/resource.h
=> Remove unused macro

src/fheroes2/maps/map_object_info.h
relates to #8233
A simple trick of members position :)
=> Reduce object info structure size

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/ai/normal/ai_normal_kingdom.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/gui/interface_radar.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/view_world.cpp, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_helper.cpp, src/fheroes2/maps/maps_tiles_render.cpp, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world_loadmap.cpp, src/fheroes2/world/world_pathfinding.cpp
This has been annoying me for a very long time. This is a type of object for a single hero, not many standing at one tile.
=> Rename OBJ_HERO object

src/fheroes2/ai/normal/ai_normal_hero.cpp
This is to avoid waiting tactics from human players.
=> Make AI to attack human heroes with higher chance than AI heroes

src/fheroes2/ai/normal/ai_normal_hero.cpp
Making the AI less cheating since we've added more logic to it.
=> Make AI heroes do not know which spell a shrine has before visiting it

src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/skill.cpp, src/fheroes2/heroes/skill.h, src/fheroes2/kingdom/race.cpp, src/fheroes2/kingdom/race.h
=> Offer the Wisdom skill to the heroes of "magic" classes on a mandatory basis at least once every three level-ups

src/fheroes2/maps/map_object_info.cpp
Fix the top-2 code smell among the recently introduced ones.
=> Fix some recent code smells

files/lang/Makefile
=> Use CP1257 for Lithaunian

src/engine/image.cpp
=> Do not do operations with pointer to nullptr in image.cpp

src/fheroes2/army/army.cpp
=> Army::Reset(): the case of a hero without a race can sometimes be legitimate

src/engine/image.cpp
=> Revert changes for Resize() function

src/fheroes2/ai/normal/ai_normal.cpp, src/fheroes2/ai/normal/ai_normal.h, src/fheroes2/ai/normal/ai_normal_hero.cpp
=> Make the AI not to know what objects contain

src/fheroes2/dialog/dialog_interface_settings.cpp
=> Fix OKAY button translation for Interface Settings dialog after any setting change

src/fheroes2/editor/editor_interface.cpp
Update old functions `verifyObjectCondition` to `checkConditionForUsedTiles` and `checkConditionForOccupiedTiles`
=> Fix editor_interface.cpp compilation issues

src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/maps_tiles.cpp
=> Fix Oasis passability

src/engine/serialize.h, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/maps_tiles.cpp
=> Expand castle metadata and add hero metadata for the map format

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h
=> Limit the number of heroes being placed on map

src/fheroes2/ai/normal/ai_normal_hero.cpp
Since the AI doesn't have "eyes" so far we need to give him a power to see the visited status.
=> Fix incorrect Artesian Spring evaluation by AI

files/lang/pl.po
Change duplicate polish word for "swarm" to "mrowie".
=> Update the Polish translation

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/maps/map_format_helper.cpp, src/fheroes2/maps/map_format_helper.h, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/world/world_loadmap.cpp
- add logic to get available kingdom colors present on a map
- add logic to get races for each kingdom
- add logic to allow full map loading (random castles and heroes don't work yet and I'm sure many other things)
- fix town passability
=> Add basic map loading for gameplay

src/fheroes2/agg/agg_image.cpp, src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/dialog/dialog_system_options.cpp
UPGRADE, DISMISS, EXIT, TRADE, ACCEPT, DECLINE, RESET, START, RESTART
FIx #8335 
Relates to https://github.com/ihhub/fheroes2/issues/7548 , https://github.com/ihhub/fheroes2/pull/8173
=> Make several buttons text adapted and fix okay button redraw

src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/dialog/dialog_gameinfo.cpp, src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/game/game_campaign.cpp, src/fheroes2/gui/ui_text.cpp, src/fheroes2/gui/ui_text.h
=> Add a method to not align all text uniformly

src/fheroes2/agg/bin_info.cpp, src/fheroes2/agg/bin_info.h, src/fheroes2/game/fheroes2.cpp
We don't need this stage as we use caching mechanism in the game.
=> Speed up application loading by removing bin info caching stage

src/fheroes2/battle/battle_animation.cpp, src/fheroes2/battle/battle_animation.h
Code cleanup after the latest changes.
=> Remove the unused default constructor

src/fheroes2/agg/bin_info.cpp, src/fheroes2/game/fheroes2.cpp
Faster loading of the engine.
Plus small speed up for bin info file processing.
=> Do not do display zeroing twice during application startup

src/fheroes2/castle/castle_dialog.cpp
=> Update the resource panel immediately after a purchase.

src/fheroes2/maps/map_format_helper.cpp
=> Fix a crash while placing random castles in the Editor

src/fheroes2/maps/map_object_info.cpp
Fix castle's road overlapping. This is the same layer as in the OG.
=> Fix town road overlapping

src/fheroes2/battle/battle_board.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/campaign/campaign_data.cpp, src/fheroes2/campaign/campaign_scenariodata.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle_town.cpp, src/fheroes2/dialog/dialog_audio.cpp, src/fheroes2/dialog/dialog_graphics_settings.cpp, src/fheroes2/dialog/dialog_interface_settings.cpp, src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/dialog/dialog_system_options.cpp, src/fheroes2/game/game_campaign.cpp, src/fheroes2/game/game_hotkeys.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp, src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/gui/interface_buttons.cpp, src/fheroes2/gui/player_info.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/skill.cpp, src/fheroes2/kingdom/experience.cpp, src/fheroes2/kingdom/luck.cpp, src/fheroes2/kingdom/morale.cpp
Fix typos, add plural strings, paraphrase, add contexts.
Fix https://github.com/ihhub/fheroes2/issues/5992 
Fix https://github.com/ihhub/fheroes2/issues/5093
=> Fix a lot of English strings

src/engine/tools.cpp, src/engine/tools.h, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/buildinginfo.h
fix #8437
https://github.com/ihhub/fheroes2/assets/32623900/29f8d2a4-0b76-4fd1-b0a5-dc040ee26074
This PR:
https://github.com/ihhub/fheroes2/assets/32623900/10647ac2-cddd-44b5-b3c6-43d12b1be8d6
=> Kingdom Overview screen: automatically update status of castle dwellings that have just been built or upgraded

src/fheroes2/castle/buildinginfo.h
=> Fix the recently introduced code smell

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h
=> Fix a crash with AI hero animation

src/fheroes2/maps/map_object_info.cpp
close #6845
All these issues were detected by an algorithm which I will introduce in another pull request.
=> Fix multiple objects and add missing ones in the Editor

src/fheroes2/battle/battle_interface.cpp
Fix #8460 
This PR does `listlog` redraw and render it on the screen when it is needed.
=> Fix rendering flaws of battle journal when using scroll bar

src/fheroes2/kingdom/kingdom.cpp
`GetIncome()` already handles campaign awards!
=> fixed double daily resources award

src/fheroes2/game/fheroes2.cpp, src/fheroes2/game/game.h, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/game/game_newgame.cpp
Based on people misunderstanding that we are providing a game engine and not a game. This window will appear one time when a player opens "New game" dialog.
=> Add a window telling about demo version being used

src/fheroes2/game/game_credits.cpp
For the upcoming release to help translators to keep up with the changes.
=> Update credits page

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, script/android/install_packages.bat, script/android/install_packages.sh, script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/49 for details.
=> Update Windows & Android dependencies

files/lang/uk.po
Mostly checked orange colored text according to Zense's note.
=> Update the Ukrainian translation

src/fheroes2/heroes/heroes.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/map_object_info.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/system/save_format_version.h
To be able to include additional 127 objects in the future.
2 new objects were added:
- Swampy Lake
- Frozen Lake
=> Expand MapObjectType enumeration

src/fheroes2/ai/ai.h, src/fheroes2/castle/castle.h, src/fheroes2/gui/ui_castle.h, src/fheroes2/gui/ui_dialog.h, src/fheroes2/resource/resource.h
=> Make Funds as structure

docs/INSTALL.md
=> add info about install from Debian repository

src/fheroes2/dialog/dialog_marketplace.cpp, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/maps_objects.cpp, src/fheroes2/maps/maps_objects.h, src/fheroes2/resource/resource.cpp, src/fheroes2/resource/resource.h
I also did code cleanup for Resource and MapObject related files.
=> Add all required metadata structures for Adventure Map objects

src/fheroes2/resource/resource.cpp
=> Fix the typo in the Funds class constructor

Makefile, src/Makefile, src/dist/Makefile, src/engine/Makefile
to use system libsmacker instead bundled one.
=> add option FHEROES2_WITH_SYSTEM_SMACKER

files/lang/ro.po
Another batch of translations:
* Translates the *Load Game* parts of the menu.
* Translates the *New Game* parts of the menu -- this includes the races, which are mostly based on the French translation.
xref: #8519
=> Improve Romanian translations #3

src/engine/screen.cpp
=> Do not add scaled resolutions for PS Vita

src/engine/h2d_file.cpp, src/engine/serialize.cpp, src/engine/serialize.h, src/engine/zzlib.cpp, src/engine/zzlib.h, src/fheroes2/dialog/dialog_resolution.cpp, src/fheroes2/game/fheroes2.cpp, src/fheroes2/game/game_io.cpp, src/fheroes2/game/highscores.cpp, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h
=> Add compression step for the map format

src/fheroes2/heroes/heroes_dialog.cpp
=> Fix primary skill display in Hero dialog

src/fheroes2/army/army_bar.cpp, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/gui/player_info.cpp, src/fheroes2/gui/skill_bar.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/kingdom/race.cpp, src/fheroes2/kingdom/race.h, src/fheroes2/maps/map_format_helper.cpp, src/fheroes2/maps/map_format_helper.h, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/map_object_info.h, src/fheroes2/world/world_loadmap.cpp
Relates to #6845
This dialog is based on Hero Details dialog and allows to set the jailed hero race.
=> Add the jailed hero details dialog in Editor

src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/world/world_loadmap.cpp
=> Expand map format to support daily events

src/fheroes2/heroes/heroes.cpp
relates to https://github.com/ihhub/fheroes2/issues/6845#issuecomment-2051547045
=> Fix Artifact Spell Scroll read from hero metadata

src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/world/world_loadmap.cpp
Also, add extra logging for failures.
=> Add logic to handle victory and loss conditions for maps

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h, src/fheroes2/maps/map_format_helper.cpp, src/fheroes2/world/world_loadmap.cpp
- only one Random Ultimate artifact can be placed
- fix Spell Scroll artifact metadata
- each artifact now has its own metadata
=> Expand logic for artifact placement in the Editor

VisualStudio/fheroes2/sources.props, src/fheroes2/agg/agg_image.cpp, src/fheroes2/dialog/dialog_game_settings.cpp, src/fheroes2/dialog/dialog_language_selection.cpp, src/fheroes2/dialog/dialog_language_selection.h, src/fheroes2/dialog/dialog_system_options.cpp, src/fheroes2/editor/editor_options.cpp, src/fheroes2/game/game_hotkeys.cpp, src/fheroes2/game/game_language.h, src/fheroes2/game/highscores.cpp, src/fheroes2/gui/ui_font.h, src/fheroes2/gui/ui_keyboard.cpp, src/fheroes2/gui/ui_language.h, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h
As of now we just indicate that this is English language map.
=> Add language support for map format

src/fheroes2/editor/editor_interface.cpp
=> Allow river deltas to be placed anywhere

src/fheroes2/editor/editor_interface.cpp
=> Add code to modify Spell Scroll artifact

src/fheroes2/editor/editor_interface.cpp
=> Fix broken history manager while changing Editor options

src/fheroes2/maps/maps_tiles_helper.cpp
=> Fix spell scroll artifact spell being set for new game

src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h
=> Add artifact metadata for Sphinx and Event

src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_box.cpp, src/fheroes2/dialog/dialog_selectcount.cpp, src/fheroes2/editor/editor_interface.cpp
also, make monster count window to contain an image.
=> Add a window to enter Random Ultimate Artifact radius

src/fheroes2/game/game_hotkeys.cpp
=> Disable Editor hotkeys for non-POL resources

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/maps/maps_tiles_helper.cpp
=> Properly connect roads and castles in Editor

src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/world/world_loadmap.cpp
=> Add rumor support for the map format

files/lang/ro.po
This updates:
* The credits pages (didn't notice there were more of them last time).
* Various menus when starting a new game `New Game > Standard Game > Scenario Alteris`.
* Some additional strings here and there that had similar words in them.
xref: #8524.
=> Improve Romanian translations #4

src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h
- no need to expose stream operations
- add some basic checks for stream operations
=> Update code for map loading and saving

VisualStudio/fheroes2/sources.props, src/engine/system.cpp, src/engine/system.h, src/fheroes2/dialog/dialog_selectfile.cpp, src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/dialog/dialog_selectscenario.h, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h, src/fheroes2/editor/editor_mainmenu.cpp, src/fheroes2/editor/editor_save_map_window.cpp, src/fheroes2/editor/editor_save_map_window.h, src/fheroes2/game/game_scenarioinfo.cpp, src/fheroes2/maps/maps_fileinfo.cpp
relates to https://github.com/ihhub/fheroes2/issues/6845
This dialog allows:
- setting file name;
- changing map name;
- deleting the existing map file.
=> Implement simple Save Map dialog for Editor

src/fheroes2/dialog/dialog_selectscenario.cpp
=> Fix the flickering of the map filter buttons in the map selection dialog

src/fheroes2/heroes/heroes.cpp
This is what was introduced within the Editor.
=> Change a message while trying to get another Magic Book

VisualStudio/fheroes2/sources.props, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_sphinx_window.cpp, src/fheroes2/editor/editor_sphinx_window.h, src/fheroes2/gui/interface_list.h, src/fheroes2/gui/ui_scrollbar.cpp, src/fheroes2/gui/ui_scrollbar.h, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/maps_objects.cpp, src/fheroes2/maps/maps_objects.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/world/world_loadmap.cpp
- update logic for Sphinx and Event metadata reading
- add a UI window to setup Sphinx properties
=> Add UI window to edit Sphinx properties

VisualStudio/fheroes2/sources.props, src/fheroes2/agg/agg_image.cpp, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h, src/fheroes2/editor/editor_interface_panel.cpp, src/fheroes2/editor/editor_map_specs_window.cpp, src/fheroes2/editor/editor_map_specs_window.h, src/fheroes2/maps/map_format_info.h
relates to https://github.com/ihhub/fheroes2/issues/6845
Currently the Victory / Loss conditions cannot be changed. It will be done later.
=> Implement base functions of Map Specifications dialog for Editor

src/fheroes2/editor/editor_interface.cpp
=> Remove not needed scenario info window for game's Adventure Map

src/fheroes2/editor/editor_interface_panel.cpp
=> Make Editor panel buttons change good/evil interface during current run

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h, src/fheroes2/editor/editor_interface.cpp
This adds Evil generated buttons too.
=> Add generated buttons for map file dialog

VisualStudio/fheroes2/sources.props, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_battle.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/battle/battle_grave.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_pathfinding.cpp, src/fheroes2/editor/editor_castle_details_window.cpp, src/fheroes2/editor/editor_event_details_window.cpp, src/fheroes2/editor/editor_event_details_window.h, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_sphinx_window.cpp, src/fheroes2/editor/editor_ui_helper.cpp, src/fheroes2/editor/editor_ui_helper.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/map_format_helper.cpp, src/fheroes2/maps/maps_objects.cpp, src/fheroes2/maps/maps_objects.h, src/fheroes2/world/world.cpp, src/fheroes2/world/world_loadmap.cpp
=> Event details window implementation

src/fheroes2/editor/editor.h, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface_panel.cpp, src/fheroes2/editor/editor_mainmenu.cpp, src/fheroes2/game/game_mainmenu.cpp
=> Hide selection of map types in the Editor

src/fheroes2/editor/editor_interface.cpp
=> Remove unused hotkey events for the Editor

src/fheroes2/editor/editor_castle_details_window.cpp
Because the logic hasn't been implemented.
=> Temporary remove town restrict building UI

src/fheroes2/resource/artifact.cpp
=> Remove random spells from Spell Scroll within Hero dialog and show message about Magic Book duplication

src/fheroes2/editor/editor_interface.cpp
=> Add a general window for action objects with no metadata

src/fheroes2/editor/editor_interface.cpp
No need to update map information for each town and hero.
=> Speed up object erasure in the Editor

src/fheroes2/editor/editor_interface.cpp
=> Use the same hotkey for Scenario specification dialog

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/maps/maps_tiles_helper.cpp
=> Show a warning message that streams and roads cannot be placed on water

src/fheroes2/editor/editor_interface.cpp
=> Show a warning message for no modification of normal artifacts

src/fheroes2/army/army_bar.cpp, src/fheroes2/editor/editor_interface.cpp
=> Show the same monster window setup within Town as for Monster on map

src/fheroes2/editor/editor_interface_panel.cpp, src/fheroes2/gui/ui_map_object.cpp, src/fheroes2/maps/map_format_info.h
based on the feedback
Also, change some comments.
https://github.com/ihhub/fheroes2/assets/19829520/9b247a7b-e0f8-4ffd-b5f0-41632853623f
=> Show mines and towns over water

src/fheroes2/maps/maps_tiles_helper.cpp
https://github.com/ihhub/fheroes2/assets/19829520/c389336a-2b5d-4ed5-b4fd-d8363fe735d9
=> Fix Eraser not being able to erase object on background layer

src/fheroes2/resource/artifact_info.cpp
Update the Magic Book pick-up story:
https://github.com/ihhub/fheroes2/pull/8664#discussion_r1605733227
=> Update Magic Book pick-up story

src/fheroes2/editor/editor_interface_panel.cpp
=> Change Detail Mode description to reflect the correct purpose

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/gui/interface_gamearea.cpp, src/fheroes2/gui/interface_gamearea.h
=> Use golden color to highlight cells that are sometimes possible to edit

src/fheroes2/editor/editor_interface.cpp
close #8732
We forgot to add check for this group of objects.
=> Add missing checks for Miscellaneous objects

src/fheroes2/editor/editor_interface_panel.cpp
=> Fix Editor instruments buttons rendering

src/fheroes2/maps/map_object_info.cpp
based on https://github.com/ihhub/fheroes2/pull/8751#issuecomment-2135152669
=> Fix random artifact types

src/fheroes2/editor/editor_interface.cpp
Hero color must be set at first.
=> Fix hero editing assertion

src/fheroes2/gui/ui_scrollbar.cpp
=> Limit the minimum slider length by 15 pixels

src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_fileinfo.h, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/resource/artifact.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h, src/fheroes2/world/world_loadmap.cpp
- add more checks for map loading logic
- move the code for map loading into separate functions that we will use separately for fh2m file loading as we won't need the code to set metadata
- rename certain functions to show their purpose. Many of them are being used only for MP2 map format
- fix invalid logic for setting random artifacts
=> Code cleanup for the future changes of map loading with more functionality

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h
If the same object is being placed then move the existing one on top of all other objects.
=> Move an existing object in front while trying to place an exact one on the same tile

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/normal/ai_normal_hero.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/kingdom/payment.cpp, src/fheroes2/kingdom/payment.h
=> Avoid hardcoded values for Magellans' Maps visit object

src/fheroes2/game/game_mainmenu.cpp
Reported by some users who cannot access the Editor but they see the button in the Main Menu which is not interactive.
=> Properly check the PoL resources in order to enable the Editor

src/fheroes2/gui/ui_keyboard.cpp
=> Add '?' symbol to Virtual Keyboard

src/engine/localevent.cpp, src/engine/screen.cpp
To make sure that we properly handle everything and to avoid infinite loops in cases of error.
=> Add more checks for SDL functions

src/fheroes2/maps/maps_tiles_helper.cpp
Based on the map makers' feedback.
=> Fix Magic Garden being shown without animation within the Editor

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h
=> Fix castle and hero radar rendering in the Editor

src/fheroes2/dialog/dialog_selectitems.cpp
=> Update hero selection dialog in the Editor

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_interface.h, src/fheroes2/maps/map_format_helper.cpp
The problem was occurring during terrain placement. This is more generalized solution to avoid anymore similar places.
=> Fix radar rendering within the Editor

docs/DEVELOPMENT.md
Add step in Windows to ensure the user clones the project before proceeding onto next steps.
=> Update development instructions

src/fheroes2/dialog/dialog_selectscenario.cpp
=> Update map type popup message by right click to include Resurrection maps

src/fheroes2/dialog/dialog_selectitems.cpp
=> Reduce castle ROI for mouse right clicking inside Editor's castle selection window

src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/maps/map_object_info.cpp
=> Add color names to Traveller's Tent and Barrier objects within object selection window

src/fheroes2/editor/editor_map_specs_window.cpp, src/fheroes2/gui/ui_dialog.cpp, src/fheroes2/gui/ui_dialog.h, src/fheroes2/maps/maps_fileinfo.cpp
relates to #8717
Implement Gold Accumulation Victory condition and Run of Time Loss condition.
Please take a note that this is a basic version at the moment. We are going to improve the UI later.
=> Add first special map conditions within the Editor

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/gui/interface_events.cpp, src/fheroes2/heroes/heroes_base.cpp, src/fheroes2/heroes/heroes_base.h, src/fheroes2/resource/artifact.cpp, src/fheroes2/spell/spell_book.cpp, src/fheroes2/spell/spell_book.h
=> Magic Book window: show the maximum number of spell points

src/fheroes2/battle/battle_dialogs.cpp
fix #8844
Although there is nothing particularly wrong with a comparison using addresses of artifact names' strings, I still changed the comparisons to use artifact IDs.
=> Fix the display of identical artifacts captured in battle

src/fheroes2/gui/ui_text.cpp
=> Set the space width as a maximum word width if the text contains only spaces

src/fheroes2/editor/editor_map_specs_window.cpp
=> Show Day, Week and Month for Out of time loss condition

src/fheroes2/editor/editor_interface.cpp
=> Restrict obelisk placement to 48 objects

src/fheroes2/editor/editor_map_specs_window.cpp
=> Add popup messages for right clicking on special map conditions

src/fheroes2/editor/editor_daily_event_spec_window.cpp, src/fheroes2/editor/editor_map_specs_window.cpp, src/fheroes2/editor/editor_ui_helper.cpp, src/fheroes2/editor/editor_ui_helper.h
=> Show date description for daily events

src/fheroes2/castle/castle.cpp
=> Fix the logic of processing the castle construction ban for MP2/MX2 maps

src/fheroes2/editor/editor_interface.cpp
See https://github.com/ihhub/fheroes2/actions/runs/9771857348/job/26975277607#step:8:157 for details.
=> Fix the unused variable warning in release builds

src/fheroes2/editor/editor_daily_events_window.cpp, src/fheroes2/editor/editor_rumor_window.cpp, src/fheroes2/editor/editor_sphinx_window.cpp
To make the life of map makers easier.
=> Add support for double click within Sphinx, Daily Events and Rumors lists

files/lang/sv.po
Mostly translated new strings added related to the editor.
=> Swedish Translation Update (#19)

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h
ICNs RECR2BKG_EVIL and RECRBKG_EVIL are not used anymore because now we generate these dialogs using StandardWindow class.
=> Remove the unused extra ICNs

src/engine/localevent.cpp
=> Fix an assertion when pressing an unknown mouse button

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h
No need to keep unused code and waste resources.
=> Remove unused ICN resources being generated by the engine

src/fheroes2/maps/maps_fileinfo.cpp
=> Fix "Accumulate gold" condition logic

src/fheroes2/maps/map_object_info.cpp
To make sure that the data is valid.
=> Add extra checks for verify objects' information

src/fheroes2/editor/editor_map_specs_window.cpp, src/fheroes2/maps/maps_tiles.h
=> Address recently added SonarQube issues

files/lang/uk.po
=> Update of Ukrainian Translation

src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h
Fix the recently introduced code smell.
=> Kingdoms::AddCastles(): bring the const back

src/fheroes2/agg/agg_image.cpp, src/fheroes2/editor/editor_interface.cpp, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_helper.cpp, src/fheroes2/maps/maps_tiles_helper.h
=> Add new River Deltas objects

src/engine/localevent.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/maps/maps.cpp, src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/maps/mp2.h, src/fheroes2/maps/mp2_helper.cpp, src/fheroes2/maps/mp2_helper.h, src/fheroes2/world/world_loadmap.cpp
=> Fix several SonarQube code smells

src/fheroes2/dialog/dialog_selectitems.cpp
=> Fix diacritical marks remove in mine selection dialog in the editor

src/fheroes2/spell/spell.cpp
Fixed issue https://github.com/ihhub/fheroes2/issues/8968
=> fix Anti-Magic spell description #8968

src/fheroes2/editor/editor_interface.cpp
=> Editor: take into account the arbitrary case of the map directory name

src/fheroes2/gui/ui_font.cpp, src/fheroes2/gui/ui_keyboard.cpp
=> Add Ukrainian language virtual keyboard

src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_object_info.cpp
=> Add missed Small Cliff (Dirt terrain) to the Landscape Miscellaneous objects in Editor

src/fheroes2/editor/editor_daily_event_spec_window.cpp, src/fheroes2/editor/editor_event_details_window.cpp, src/fheroes2/editor/editor_map_specs_window.cpp, src/fheroes2/editor/editor_ui_helper.cpp, src/fheroes2/editor/editor_ui_helper.h, src/fheroes2/maps/map_format_helper.cpp
=> Implement alliances in editor

src/engine/localevent.cpp
=> Do not immediately handle the intermediate events of some types

src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/kingdom/payment.cpp, src/fheroes2/kingdom/profit.cpp, src/fheroes2/monster/monster_info.h, src/fheroes2/resource/resource.cpp, src/fheroes2/resource/resource.h
The `_t` suffix is reserved by POSIX for their own identifiers.
=> Rename cost_t to Cost

src/fheroes2/agg/agg_image.cpp
Fix #7666 
Master build:
This PR:
=> Fix Cliff Nest glowing pixel

src/fheroes2/castle/castle_building.cpp
fix #9039
https://github.com/user-attachments/assets/c113c83d-3186-4a6d-ac6f-36745bf66417
=> Fix the rendering of the Mage Guild upgrade animation

src/fheroes2/castle/castle_building.cpp
SonarQube [doesn't like](https://sonarcloud.io/project/issues?rules=cpp%3AS1751&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=ihhub_fheroes2&open=AZFCJSTmSxIIFSdlQeRC) my creative.
=> Transform the single-iteration loop into the lambda

src/fheroes2/ai/ai_planner.h, src/fheroes2/ai/ai_planner_kingdom.cpp, src/fheroes2/castle/castle.cpp
=> Use the castle owner's point of view for the threat assessment algorithm for castles

files/lang/sv.po
Som newly added strings translated.
=> Swedish Translation Update (#21)

src/fheroes2/dialog/dialog_levelup.cpp
Fix https://github.com/ihhub/fheroes2/issues/9071
=> Move skill amount info up

src/engine/serialize.cpp, src/engine/serialize.h, src/engine/zzlib.cpp, src/engine/zzlib.h, src/fheroes2/game/game_io.cpp, src/fheroes2/game/highscores.cpp, src/fheroes2/maps/map_format_info.cpp
=> Generalize the zzlib functions

src/fheroes2/editor/editor_interface.cpp
To improve performance of the Editor.
=> Speed up Map Specification Window closure if no changes are being done

src/fheroes2/resource/artifact.cpp
=> Preserve the order of artifacts when adding the Spell Book to the artifacts bag

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.cpp, src/fheroes2/agg/icn.h, src/fheroes2/battle/battle_dialogs.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/captain.cpp, src/fheroes2/castle/castle_building.cpp, src/fheroes2/castle/castle_well.cpp, src/fheroes2/editor/editor_castle_details_window.cpp, src/fheroes2/editor/editor_map_specs_window.cpp, src/fheroes2/game/game_mainmenu.cpp, src/fheroes2/gui/ui_campaign.cpp, src/fheroes2/gui/ui_dialog.cpp, src/fheroes2/gui/ui_language.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles_render.cpp
This PR updates the function names in `icn.h`.
=> Minor code clean-up in icn.h/.cpp

src/engine/dir.cpp, src/engine/system.cpp, src/engine/translations.cpp
=> Fix a few recently introduced (or updated) code smells

src/fheroes2/dialog/dialog_resolution.cpp
=> Add a popup dialog to the list of resolutions

src/fheroes2/battle/battle_interface.cpp
Initialize vectors with the known constants instead of using `.push_back()` in a loop from a const array (and then never used) to a vector.
=> getHeroAnimation() function minor code clean-up

src/engine/audio.cpp, src/engine/dir.cpp, src/engine/image_tool.cpp, src/engine/screen.cpp, src/engine/system.cpp, src/engine/system.h
=> Fix the UTF-16 -> CP_ACP conversion issues on Windows

src/fheroes2/battle/battle_army.h, src/fheroes2/castle/buildinginfo.h, src/fheroes2/gui/interface_itemsbar.h, src/fheroes2/gui/skill_bar.h
This PR mostly fixes the code smells related to the cases when non-final virtual methods are called from the constructor, as well as a few other minor code smells.
=> Fix a few code smells

src/fheroes2/game/game_startgame.cpp, src/fheroes2/gui/interface_gamearea.cpp
=> Fix the triggering of invalid drag events for the game area in certain cases

src/fheroes2/editor/editor_interface.cpp
=> Fix blinking arrow cursor during scrolling in Editor

src/engine/pal.cpp, src/engine/smk_decoder.cpp, src/fheroes2/agg/agg_image.cpp, src/fheroes2/ai/ai_common.cpp, src/fheroes2/battle/battle_arena.cpp, src/fheroes2/gui/ui_button.cpp, src/fheroes2/gui/ui_dialog.cpp, src/fheroes2/gui/ui_dialog.h, src/fheroes2/gui/ui_keyboard.cpp, src/fheroes2/maps/map_object_info.h
Use const reference to Point, Size and Rect in function arguments, use array instead of vector
=> Some code optimizations

src/fheroes2/ai/ai_planner_hero.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/maps/visit.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
=> Fix the recently introduced code smells

.github/workflows/cmake.yml
See https://github.com/microsoft/vcpkg/issues/41199#issuecomment-2378255699 for details.
=> Add the temporary workaround to fix the Windows CMake build

src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/castle/castle_building_info.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/maps/map_object_info.cpp, src/fheroes2/world/world.cpp, src/fheroes2/world/world.h, src/fheroes2/world/world_loadmap.cpp
Partially based on #9151 and should be merged after it.
=> Migrate AllCastles and AllHeroes to std::unique_ptr

src/fheroes2/castle/castle.h, src/fheroes2/heroes/heroes.h
Fix a couple of code smells introduced in #9153.
=> Specify the pointer part of the type outside of auto

src/fheroes2/castle/buildinginfo.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/castle/castle_mageguild.cpp, src/fheroes2/castle/castle_tavern.cpp, src/fheroes2/castle/castle_town.cpp, src/fheroes2/castle/castle_well.cpp
This PR updates `Castle` class' private methods naming, makes methods' arguments `const` where needed and makes some methods inline (code moved from castle.cpp to castle.h).
=> Small code clean in Castle class

src/fheroes2/game/game_interface.h
Fix the recently introduced code smell.
=> Remove the unused function

src/fheroes2/agg/agg_image.cpp
=> Center Magic Book artifact on the Adventure Map

src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/icn.h, src/fheroes2/dialog/dialog_gameinfo.cpp
=> Add support of Evil interface for Scenario Information dialog

src/fheroes2/dialog/dialog_selectscenario.cpp, src/fheroes2/editor/editor_mainmenu.cpp, src/fheroes2/game/game_over.h, src/fheroes2/game/highscores.cpp, src/fheroes2/game/highscores.h, src/fheroes2/kingdom/week.cpp, src/fheroes2/kingdom/week.h, src/fheroes2/maps/maps.h, src/fheroes2/monster/monster.h
Also this PR simplifies and modernizes the `HighScoreDataContainer::getMonsterByDay()` and `HighScoreDataContainer::getMonsterByRating()`.
=> Rename or remove some more reserved type/enum names (ending in _t)

src/fheroes2/maps/maps_tiles.cpp
These changes do not affect any passabilities but make the code way more readable. It is still far from a perfect code but we are getting closer.
=> Code cleanup for tile passability calculations

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/maps/map_format_helper.cpp, src/fheroes2/maps/map_format_helper.h, src/fheroes2/maps/maps_tiles_helper.cpp, src/fheroes2/maps/maps_tiles_helper.h
Relates to #8589
This PR updates Streams placing, removing and connecting with river deltas in Editor.
=> Move Streams handling in Editor from "world" tiles to "Map_Format"

src/fheroes2/editor/editor_interface.cpp
=> Fix LANDSCAPE_MISCELLANEOUS objects erasure in editor

src/fheroes2/dialog/dialog_recruit.cpp
close #9298
https://github.com/user-attachments/assets/82fc6397-2f6c-4d61-8eab-c65425042abb
=> Enable the number input dialog for the recruitment window

src/fheroes2/gui/ui_font.cpp
=> Add missing CP1254 button letters for Turkish

src/fheroes2/heroes/heroes_indicator.cpp
=> Add range values for default experience

docs/README_android.md
Related to #8464
We forgot to document this handy touchscreen mechanic anywhere. The wording can be adjusted if there are appropriate proposals.
=> Document the mechanics of "drawing the angle of attack" in the README_android.md

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/maps/map_format_info.cpp, src/fheroes2/maps/map_format_info.h, src/fheroes2/maps/maps_tiles_helper.cpp, src/fheroes2/world/world_loadmap.cpp
=> Add ability to edit spells in Pyramid inside the Editor

src/fheroes2/gui/ui_dialog.cpp
fix #9365
See the discussion in #9365 regarding this PR.
=> Fix the spell cost displayed in the quick info window when hero has artifact that reduces this cost

files/lang/sv.po
Updated some recently changed strings.
=> Swedish Translation Update (#24)

files/lang/cs.po
Updated Czech translation with newly added strings
=> Updated Czech translation

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h
Not sure what was it for but in the original game the passability doesn't change.
=> Remove the logic to update Troll's Bridge passability after visiting it

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h
=> Fix the issue with the status of the pressed buttons on the battle screen

src/fheroes2/army/army.cpp, src/fheroes2/army/army.h
=> Fix the Hideous Mask behavior when neutral units never flee

src/fheroes2/kingdom/view_world.cpp, src/fheroes2/kingdom/view_world.h
Also, make zoom x1 available for the Editor.
=> Fix a crash in View World mode for the Editor

src/fheroes2/editor/editor_interface.cpp
as it is still hard to remember what a particular artifact does.
=> Show Artifact description window for clicking on it in the Editor

src/fheroes2/editor/editor_interface.cpp, src/fheroes2/editor/editor_object_popup_window.cpp, src/fheroes2/editor/editor_object_popup_window.h
To make map makers' life easier. Relates to #8589
=> Display resource count if set for right click popup info in the Editor

src/fheroes2/agg/agg_image.cpp, src/fheroes2/dialog/dialog_selectitems.cpp, src/fheroes2/gui/ui_button.cpp
=> Use a single button to switch between castle and town in the Editor dialog

src/engine/image_tool.cpp, src/engine/image_tool.h, src/fheroes2/agg/agg_image.cpp, src/fheroes2/agg/agg_image.h, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/gui/ui_text.cpp
`agg_image.cpp` has become too big and it lost its original purpose: to return an image. We need to remove non-related code from this file.
=> Small code restructure for agg_image.cpp|h files

src/fheroes2/dialog/dialog_interface_settings.cpp, src/fheroes2/editor/editor_options.cpp, src/fheroes2/gui/ui_option_item.cpp, src/fheroes2/gui/ui_option_item.h
=> Add more game options for the Editor

src/fheroes2/editor/editor_object_popup_window.cpp
=> Display monster count for monster object for the Editor

src/fheroes2/world/world.cpp, src/fheroes2/world/world.h
=> MonthOfMonstersAction(): make the generator dependent not just on the map seed, but also on the current month

src/fheroes2/editor/editor_castle_details_window.cpp, src/fheroes2/editor/editor_event_details_window.cpp, src/fheroes2/editor/editor_map_specs_window.cpp, src/fheroes2/editor/editor_ui_helper.cpp, src/fheroes2/editor/editor_ui_helper.h
=> Impose checkbox text width limit

script/homm2/extract_homm2_resources_from_cd_image.sh
I've verified that this extracts music and resources from my old Succession Wars and Price of Loyalty CDs.
=> Add script to extract resources from CD images

src/fheroes2/editor/editor_interface.cpp
=> Show total obelisk number while clicking on the corresponding Adventure Map object

src/fheroes2/gui/ui_dialog.cpp
=> Show a range of available values for an input value dialog

src/fheroes2/dialog/dialog_audio.cpp
=> Show an appropriate icon for music and audio settings when they are off

src/fheroes2/game/game_over.cpp
=> Check Loss conditions before Victory conditions

src/fheroes2/dialog/dialog_selectcount.cpp
=> Replace "max" text with MIN and MAX buttons for integer input dialog

src/fheroes2/dialog/dialog_giftresources.cpp
=> Fix marketplace resource type string replace

src/fheroes2/maps/maps_objects.cpp
=> Invalid serialization for save files

src/fheroes2/editor/editor_interface.cpp
Before the changes:
https://github.com/user-attachments/assets/02010f6d-9c2d-4d4c-b965-10080bf1b619
After the changes:
https://github.com/user-attachments/assets/de627128-7172-4b14-b784-8fbe409b7ba8
=> Fix Ultimate Artifact being erased for any action done on a map

src/fheroes2/army/army.cpp
=> Fix invalid undead army check for an empty army

src/fheroes2/agg/agg_image.cpp
=> Fix Russian resources' max button and empty guild/well button

files/lang/sv.po
Another small update for the swedish translation.
No major changes.
=> Swedish Translation Update (#26)

src/fheroes2/gui/ui_button.cpp, src/fheroes2/gui/ui_button.h, src/fheroes2/gui/ui_option_item.cpp, src/fheroes2/gui/ui_option_item.h, src/fheroes2/gui/ui_tool.h, src/fheroes2/heroes/heroes_dialog.cpp, src/fheroes2/system/settings.cpp, src/fheroes2/system/settings.h
To hit 777 code smells number :)
=> Fix few SonarCloud code smells

src/fheroes2/gui/ui_keyboard.cpp
This will fix https://github.com/ihhub/fheroes2/issues/9609
=> Allow activate Czech virtual keyboard

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/kingdom/kingdom.cpp, src/fheroes2/kingdom/kingdom.h, src/fheroes2/maps/mp2.cpp, src/fheroes2/maps/mp2.h, src/fheroes2/maps/visit.cpp, src/fheroes2/maps/visit.h, src/fheroes2/world/world.cpp
I have no idea why castles were marked as monthly objects. Also, the AI was marking castles as visited which makes no sense as this status is being ignored completely.
=> Remove unused logic for monthly castle visited status

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/ai_planner.h, src/fheroes2/ai/ai_planner_hero.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h
You can throw rocks at me but the AI should use the spell if it can :)
Parameters and conditions are open for discussions.
=> Make the AI use Guardian spells

src/fheroes2/ai/ai_hero_action.cpp
=> Allow the AI to cast Guardian spell after capturing an Abandoned Mine

src/fheroes2/ai/ai_common.cpp, src/fheroes2/ai/ai_common.h, src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/game/difficulty.cpp, src/fheroes2/game/difficulty.h
This is a very tiny improvement for the AI but within the limits of the game and without cheating.
=> Make the AI share visit info about some objects

src/fheroes2/dialog/dialog_armyinfo.cpp
Credit to @Districh-ru for the fix
Fix #9621
=> Fix creature info dialog shadow draw on right click

src/fheroes2/maps/maps_tiles.cpp
=> Fix an assertion crash for hacked mines on old saves

src/fheroes2/game/game_startgame.cpp
Fixes: https://github.com/ihhub/fheroes2/issues/9522
=> Fix reseting heroes icons focus after oppening Castle (#9522)

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/ai/ai_planner_hero.cpp, src/fheroes2/castle/castle.cpp, src/fheroes2/castle/castle.h, src/fheroes2/castle/castle_dialog.cpp, src/fheroes2/castle/mageguild.cpp, src/fheroes2/castle/mageguild.h, src/fheroes2/heroes/heroes.cpp, src/fheroes2/heroes/heroes.h, src/fheroes2/heroes/heroes_action.cpp, src/fheroes2/heroes/heroes_spell.cpp
Fun fact: I found a commit from 2021 with this exact change but I don't think it was ever merged into main.
Test using Knight/Barbarian heroes.
=> AI heroes should buy spellbook if there isn't one

src/fheroes2/battle/battle_interface.cpp
fixes: https://github.com/ihhub/fheroes2/issues/6572
=> Add shadow to Battle::PopupDamageInfo

src/fheroes2/ai/ai_hero_action.cpp, src/fheroes2/campaign/campaign_savedata.cpp, src/fheroes2/campaign/campaign_savedata.h, src/fheroes2/game/game_campaign.cpp, src/fheroes2/system/save_format_version.h
=> Campaign: allow to raise the game difficulty during the campaign

.github/workflows/codechecker.yml, src/engine/serialize.cpp
New version of Code Checker reports another false positive.
=> Silence the CodeChecker false positives

.github/workflows/cmake.yml
=> vcpkg update: don't pull the feature branches

src/fheroes2/gui/interface_events.cpp
Since #9661 causes a lot of controversy, I would like to merge at least the part of it that modernizes the code (limits the scope of certain variables and avoids calling the same functions multiple times) in any case.
=> Modernize some parts of the interface event handling code

src/fheroes2/castle/castle.cpp, src/fheroes2/castle/mageguild.cpp, src/fheroes2/heroes/heroes.cpp, src/fheroes2/kingdom/kingdom.cpp
=> If the hero was moved to the castle when loading the map, then train him in the Mage Guild

src/fheroes2/game/game_startgame.cpp
=> Fix the scroll bar behavior after visiting a castle

src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h
=> Do not ask for additional confirmation if Auto Combat or Quick Combat have been started from the GUI dialog

docs/INSTALL.md
Addresses https://github.com/ihhub/fheroes2/pull/9718#discussion_r2030241245
=> Remove alert to fix github pages rendering

docs/INSTALL.md
=> INSTALL.md: properly align the tables and text

src/fheroes2/gui/ui_keyboard.cpp
These actions are handled immediately and should not be propagated outside.
=> Virtual keyboard: remove unused actions

src/fheroes2/gui/ui_keyboard.cpp
Fix the code smell introduced in #9733.
=> Replace switch statement by if statement

docs/.gitignore, docs/fheroes2.6.in
* Mention the contents of the `files/timidity` directory;
* Mention the `files/save` directory;
* Present some fragments in clearer language.
This is how it looks like now in text format (variant for Linux):
```
fheroes2(6)                       Games Manual                      fheroes2(6)
NAME
fheroes2 - free remake of the Heroes of Might and Magic II game engine
SYNOPSIS
fheroes2
DESCRIPTION
fheroes2  is  a  free implementation of the Heroes of Might and Magic II
game engine, a classic turn‐based strategy game,  with  significant  im‐
provements  in gameplay, graphics and logic (including support for high‐
resolution graphics, improved AI, numerous fixes and UI improvements).
To play the game, the assets from the demo version or the  full  version
of the original Heroes of Might and …
```
=> Update the fheroes2 manual page

README.md, docs/README.md
=> Add sections to differentiate website from the game engine

src/fheroes2/battle/battle_cell.cpp, src/fheroes2/battle/battle_cell.h
This PR caches some calculations of battlefield cells coordinates and inline some `Cell` class methods.
=> Minor "battle_cell" optimizations

src/fheroes2/gui/ui_dialog.cpp, src/fheroes2/gui/ui_dialog.h
This PR adds `DEFAULT_UP` and `DEFAULT_DOWN` hotkeys processing to `ValueSelectionDialogElement` class that is used for value input fields in dialogs.
=> Allow to use Up and Down hotkeys to change the value in value input dialogs

src/fheroes2/world/world.cpp
fix #9825
A regression after #9766
=> Fix Capturable Objects related regression

src/fheroes2/ai/ai_hero_action.cpp
regression from #9778
Thanks @usidedown for spotting it!
=> Compilation fix

docs/README_PSV.md, docs/README_android.md, docs/README_switch.md, src/fheroes2/ai/ai_planner_hero.cpp, src/fheroes2/battle/battle_interface.cpp, src/fheroes2/battle/battle_interface.h, src/fheroes2/world/world_loadmap.cpp
I have found some small typos in the code and docs. These were corrected in this pull request.
=> Fix code typos in documentation and in code

src/fheroes2/gui/player_info.cpp
Fix #9863
Fix regression after #9758
An incorrect condition (human players count != 1) was added to `player_info.cpp` (https://github.com/ihhub/fheroes2/commit/a3827e02c44a1059d3a43a2598fdeaf76c971e75#diff-496b0af0656e53fa40740b54b5eee25a47adc74675409ea5e2da13cfa30baa91R357 )
This PR updates variables naming and allows to select player when selected human player in the singleplayer game is 1 and otherwise it dos nothing (an assertion added) because there can be only 1 human player.
=> Fix regression: unable to change player color in single-player game

files/lang/uk.po
New lines translated and few minor corrections to old ones.
=> Update of Ukrainian Translation June 2025

src/fheroes2/agg/agg_image.cpp
Ref https://github.com/ihhub/fheroes2/pull/9902#discussion_r2148873850
=> Lower case the first letter of a string context

src/fheroes2/battle/battle_interface.cpp
See https://github.com/ihhub/fheroes2/pull/9847#issuecomment-2999324068 for the issue details.
Also fixes the following issue in `master`:
https://github.com/user-attachments/assets/c6fe3b1d-96cf-4aef-9b1e-dc3222fca697
With this PR:
https://github.com/user-attachments/assets/f46793e3-3a1b-4ab9-8a36-c9d5d7bd8c49
=> Fix the position adjustment logic in case of a tail attack

src/fheroes2/maps/map_object_info.cpp
close #9447
To be consistent with the original game.
=> Fix passability issue for a mountain

src/fheroes2/maps/maps_fileinfo.cpp, src/fheroes2/maps/maps_tiles.cpp, src/fheroes2/maps/maps_tiles.h, src/fheroes2/world/world_loadmap.cpp
The current Tile class is too huge and hard to maintain. We need to do some cleanup before we proceed with further changes.
partially related to #6681
=> Simplify MP2 format info parsing

src/fheroes2/game/game.h, src/fheroes2/game/game_newgame.cpp
=> Fix the choice of the number of players for multiplayer maps

src/fheroes2/heroes/heroes_action.cpp
fix #9979
Regression after #9607.
=> Show the proper message for an empty water chest

script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/64 and https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/65 for details.
=> Update the hash for Windows dependency package

.github/workflows/codechecker.yml, .github/workflows/iwyu.yml, .github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml
=> Do not run the SonarCloud workflow if only files related to translations have changed

src/fheroes2/dialog/dialog_selectcount.cpp
=> Add popup messages for button in the Count Selection dialog

src/fheroes2/army/army.h, src/fheroes2/army/army_bar.h, src/fheroes2/battle/battle_catapult.h, src/fheroes2/battle/battle_cell.h, src/fheroes2/battle/battle_interface.h, src/fheroes2/battle/battle_only.h, src/fheroes2/battle/battle_tower.h, src/fheroes2/campaign/campaign_data.h, src/fheroes2/campaign/campaign_scenariodata.h, src/fheroes2/castle/buildinginfo.h, src/fheroes2/system/bitmodes.h
Better to be safe than sorry. Undefined behavior alert!
This pull request does not cover every single structure so do not consider this as a full-scale change.
=> Set default initialization values for many members of classes and structures

src/fheroes2/maps/maps_tiles.cpp
relates to https://github.com/ihhub/fheroes2/pull/10052#issuecomment-3145653037
=> Fix incorrect boat setting logic on a map tile

src/fheroes2/heroes/heroes_dialog.cpp
To align with other places in the game.
close #8557
=> Rename strings in the Editor to use "class" instead of "race"

src/fheroes2/game/game_campaign.cpp
=> Add a popup window for clicking on scenario title in the campaign window

android/app/build.gradle, android/app/jni/Application.mk, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, script/android/install_packages.bat, script/android/install_packages.sh
See https://developer.android.com/guide/practices/page-sizes?hl=en and https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/66 for details. Tested on emulator with pre-release 16 KB page size image.
=> Android: support 16 KB page sizes

src/fheroes2/game/game_io.cpp
To make it easier to maintain. Plus tiny optimizations.
=> Code cleanup for the save handling code

files/lang/hu.po
Translations of the latest modifications.
=> Hungarian language updates

src/fheroes2/dialog/dialog_armyinfo.cpp, src/fheroes2/game/game_startgame.cpp
=> Show the creature image in the "Week of..." and "Month of..." dialog windows

src/fheroes2/dialog/dialog_selectitems.cpp
=> Fix logic for hero selection window in the Editor

files/lang/hu.po
Some translations on class and populations
=> Small Hungarian language update

src/fheroes2/dialog/dialog_selectitems.cpp
The message was copy-pasted from another place.
=> Fix incorrect sentence for Mines and Observation Tower popup message for OKAY button

src/fheroes2/editor/editor_interface_panel.cpp
=> Fix invalid cursor while choosing an object in the Editor

src/fheroes2/editor/editor_map_specs_window.cpp
This is the correct way of saying it.
=> Grammar fix for winning condition

src/fheroes2/gui/ui_window.cpp, src/fheroes2/gui/ui_window.h
=> Remove unused method

src/fheroes2/dialog/dialog_selectcount.cpp, src/fheroes2/gui/ui_tool.cpp, src/fheroes2/gui/ui_tool.h
close #9985
https://github.com/user-attachments/assets/b1e32d0a-0b9a-465f-bdd2-99121b1b274e
=> Set a limit on multi-line text input to avoid going beyond the dialog

src/fheroes2/kingdom/puzzle.cpp
=> Add missing popup dialog for Exit button in the Puzzle dialog

src/fheroes2/heroes/heroes_meeting.cpp
=> Add missing popups for all buttons in the Hero Meeting dialog

src/engine/localevent.h, src/fheroes2/gui/ui_keyboard.cpp
close #8918
https://github.com/user-attachments/assets/da802f54-7882-46a4-ad1b-9782380dfec4
=> Allow to hold a button to repeat an action in the Virtual Keyboard

src/fheroes2/world/world_loadmap.cpp
This is only applicable for Resurrection maps.
relates to #8766
=> Remove dangling shadow part of the Ultimate Artifact

src/fheroes2/game/game_logo.cpp
As trivial as it seems.
relates to #5270
=> Add startup text mode message

src/fheroes2/dialog/dialog.h, src/fheroes2/dialog/dialog_giftresources.cpp, src/fheroes2/dialog/dialog_marketplace.cpp
close #4751
https://github.com/user-attachments/assets/a2198be4-817e-496e-a07f-fe3e8d4568f1
=> Do not cancel Marketplace resource selection if no gift was made
