ihhub/fheroes2

.travis.yml
src/engine/system.cpp

Add MacOS support for Travis-CI

---

src/Makefile
src/engine/serialize.cpp

Add compilation flags

---

.travis.yml

Add compilation with SDL 2

---

src/engine/dir.cpp
src/engine/system.cpp
src/engine/thread.h
src/fheroes2/maps/maps_fileinfo.cpp

Fix Windows build

---

README.md

Add relevant information to readme file

---

README.md
appveyor.yml
fheroes2.vcxproj
src/engine/audio_mixer.cpp
src/engine/translations.cpp
src/fheroes2/game/fheroes2.cpp
src/fheroes2/heroes/heroes_base.cpp

Add Visual Studio build based on AppVeyor

---

fheroes2.vcxproj
src/engine/serialize.cpp
src/engine/serialize.h
src/engine/surface.cpp
src/fheroes2/agg/agg.cpp
src/fheroes2/army/army.cpp
src/fheroes2/army/army.h
src/fheroes2/gui/interface_list.h

multiple crashes fixes and add audio support

Windows fix

---

src/fheroes2/system/settings.cpp

relates to #25 
relates to #12

Display in 640x480 with music for first run without configuration file

---

.travis.yml

Add cppclean as static analysis job for Travis-CI

---

script/demo/README.md
script/demo/demo.sh

Add a script to download demo version of the original game for Unix

---

src/fheroes2/gui/interface_buttons.cpp
src/fheroes2/gui/interface_buttons.h
src/fheroes2/gui/interface_focus.cpp

Show disable continue movement button for castle

---

.gitignore
fheroes2.vcxproj

Set files from original game to be ignored by git to avoid committing
them by mistakes

Add auto file copy from original game to simplify developer work

---

fheroes2.vcxproj
src/fheroes2/gui/interface_focus.cpp
src/fheroes2/gui/text.cpp
src/fheroes2/maps/maps_tiles_quantity.cpp
src/fheroes2/maps/mp2.cpp
src/fheroes2/monster/monster.cpp
src/fheroes2/system/settings.cpp

set warning level to 4 for Visual Studio

Fix compilation warnings

---

appveyor.yml

Add Appveyor deployment

---

.travis.yml
appveyor.yml

Add exception branches for Travis

---

.travis.yml

Add Unix OS deployment on Travis-CI

---

README.md

Add an information about compiled game downloading

---

.travis.yml

Add file zipping for test deployment

---

appveyor.yml

Add Appveyor deployment message

---

src/engine/font.cpp
src/engine/sprites.cpp
src/engine/system.cpp
src/engine/tools.cpp
src/fheroes2/resource/artifact_ultimate.h
src/fheroes2/system/players.cpp
src/fheroes2/system/settings.cpp

Code cleanup

---

appveyor.yml

relates to #67 
relates to #68

Add license and script to download demo version of the game for deployment

---

src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_only.cpp
src/fheroes2/battle/battle_tower.cpp
src/fheroes2/heroes/route.cpp
src/fheroes2/heroes/skill.cpp
src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/kingdom/world.cpp
src/fheroes2/monster/monster.cpp

Remove duplicated header file inclusion

---

src/fheroes2/kingdom/luck.cpp
src/fheroes2/kingdom/luck.h

Ref: https://github.com/ihhub/fheroes2/issues/90
Did the required modifications and compiled successfully.

Modify Luck::String() and Luck::Description() functions to do not recreate objects for every call

---

src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game.cpp
src/fheroes2/pocketpc/pocketpc_mainmenu.cpp

Renamed 'Free Heroes II' to 'Free Heroes of Might and Magic II'

---

src/fheroes2/castle/buildinginfo.cpp

Fix incorrect image for Captains Quarters (#109)

---

src/fheroes2/castle/buildinginfo.cpp

Changes to building dialog (#110)

---

.travis.yml

Do not populate GitHub releases with new versions for Travis-CI

---

.travis.yml

Travis deployment fix

---

appveyor.yml

AppVeyor deployment fix

---

src/fheroes2/castle/buildinginfo.cpp

Required buildings are listed in separate lines

---

src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/kingdom/kingdom.h

Change LastLoseHero structure

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fixed redrawing grid during battle

---

Makefile

changed ai to simple
relates to #146

Change AI state from empty to simple in makefile

---

src/fheroes2/castle/buildinginfo.cpp

fixed a bug with duplication of text
Fixes #122

Incorrect message for Shipyard by right click

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Hide dismiss button

---

.travis.yml

Try to fix Travis-CI build for MacOS

---

src/fheroes2/battle/battle_cell.cpp
src/fheroes2/battle/battle_cell.h
src/fheroes2/battle/battle_interface.cpp

Change battle cells net

---

src/fheroes2/kingdom/kingdom.cpp

Fix save loading

---

src/fheroes2/kingdom/world_loadmap.cpp

clang format is not done because it is changing many files if I run that command
relates to #188

Tavern info updated

---

README.md
script/demo/demo.bat
script/windows/install_packages.bat

Didn't knew about prerequisites(7zip), so had a lot of problem setting up.
Not a change in binary but hope its worth. (I don't think a seperate "Issue" need to be raised for this small change, my apologies for not obeying CONTRIBUTING.md)

Added setup instructions for win system in README.md

---

src/fheroes2/agg/agg.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h
src/fheroes2/castle/castle.cpp
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/gui/interface_icons.cpp
src/fheroes2/gui/interface_radar.cpp
src/fheroes2/gui/interface_status.cpp
src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/resource/artifact.cpp

Fix #158 shadowing of variables

---

src/fheroes2/dialog/dialog_system.cpp

Addressing #31 
I changed the file to spaces only.

Split settings labels above and below icon

---

src/fheroes2/ai/simple/ai_castle.cpp
src/fheroes2/castle/castle.cpp

- AI is able to build Black Dragons
- AI prioritizes dwellings of higher level to be built first
- AI doesn't build useless for him buildings
- AI builds some buildings only having certain amount of resources
- AI doesn't develop castle if no creatures inside and an enemy is nearby
- AI builds Well only on 7th day (no need to build before)
- AI builds tent into castle under more conditions
relates to #209

Change logic for AI castle development

---

VisualStudio/SDL1.props
VisualStudio/SDL2.props
VisualStudio/common.props
src/fheroes2/dialog/dialog_system.cpp

No sound win sdl1

---

src/fheroes2/game/fheroes2.cpp

Save configuration file is none is present

---

src/fheroes2/dialog/dialog_recrut.cpp

relates to #33 
Not a perfect solution as it's not exactly the same as in original game

Add monster information dialog by right mouse click

---

src/engine/display.cpp

It's some kind of hack but at least it works
relates to #232

Fix window position in SDL 2 for Windows

---

src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/dialog/dialog_system.cpp
src/fheroes2/system/settings.cpp

This PR is rework of #178, #182.
It also fixes #175.

AI speed, Hero speed and Battle speed must take values from 1 to 10

---

src/fheroes2/game/game.cpp

Fix credits

---

src/fheroes2/system/settings.cpp

This option doesn't make any impact on game but makes it a little more
comfortable

Make "Buy from well" as default option

---

src/engine/sprites.cpp
src/engine/sprites.h
src/fheroes2/dialog/dialog_recrut.cpp

relates to #251 
This is a look of window after the change:

Fix dwelling info dialog position

---

src/fheroes2/battle/battle_dialogs.cpp

Fix shadowing in hero's option dialog

---

src/engine/display.cpp

for SDL 2 only
relates to #248

Fix missing window title after starting new game

---

src/fheroes2/dialog/dialog_quickinfo.cpp

Fix resource displaying popup

---

src/fheroes2/battle/battle_dialogs.cpp

Fix battle option missing titles

---

src/fheroes2/heroes/heroes.cpp

Fix hero path cursor display

---

src/fheroes2/dialog/dialog_recrut.cpp

Fix crystal resource position

---

src/fheroes2/game/game_newgame.cpp

Add initial campaign button

---

src/fheroes2/dialog/dialog_selectscenario.cpp
src/fheroes2/game/game_newgame.cpp
src/fheroes2/gui/interface_border.cpp

Make Roland campaign UI appear for New Campaign option

---

src/fheroes2/game/game_newgame.cpp

Fix campaign crash on OKAY button press

---

src/engine/surface.cpp

Make 32 bit depth as default depth

---

.travis.yml

relates to #300 
relates to #73

Add ARM compilation support

---

.travis.yml

Add ZIP support for ARM build

---

src/engine/serialize.h

minus 2000 lines of compilation log in Travis-CI

Fix compilation warning

---

src/engine/audio.h
src/engine/sprites.cpp
src/engine/sprites.h
src/fheroes2/battle/battle.h
src/fheroes2/battle/battle_arena.h
src/fheroes2/battle/battle_only.cpp
src/fheroes2/dialog/dialog_selectitems.cpp
src/fheroes2/dialog/dialog_selectitems.h
src/fheroes2/gui/interface_status.h
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/skill.h
src/fheroes2/kingdom/kingdom.h
src/fheroes2/maps/ground.h
src/fheroes2/maps/maps.h
src/fheroes2/maps/maps_actions.h
src/fheroes2/maps/maps_tiles.h
src/fheroes2/system/players.h

Static analysis fixes

---

appveyor.yml

Use caching for packages

---

.travis.yml
editor/CMakeLists.txt
editor/dialogs.h
editor/fh2editor.pro

Compile Editor on OSX with Qt

---

.clang-format
src/engine/IMG_savepng.cpp
src/engine/audio.h
src/engine/system.cpp
src/engine/types.h
src/fheroes2/game/difficulty.cpp
src/fheroes2/game/difficulty.h
src/fheroes2/kingdom/color.cpp
src/fheroes2/kingdom/color.h
src/fheroes2/kingdom/luck.cpp
src/fheroes2/kingdom/luck.h
src/fheroes2/kingdom/morale.cpp
src/fheroes2/kingdom/morale.h
src/fheroes2/kingdom/race.cpp
src/fheroes2/kingdom/race.h
src/fheroes2/kingdom/speed.cpp
src/fheroes2/kingdom/speed.h
src/tools/extractor.cpp
src/tools/til2img.cpp

Code style formatting

---

VisualStudio/Release.props

It should vastly improve compilation speed on servers

Disable VS linker optimizations

---

src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/castle_town.cpp

Do not show a Tavern in Necromancer's castle

---

src/fheroes2/battle/battle_main.cpp

Do not show Necromancy window for 0 skeletons

---

editor/dialogs.cpp
editor/dialogs.h
editor/engine.cpp
editor/engine.h
editor/global.cpp
editor/global.h
editor/mainwindow.cpp
editor/mainwindow.h
editor/mapdata.cpp
editor/mapdata.h
editor/mapwindow.cpp
editor/mapwindow.h
editor/program.cpp
editor/program.h

Format code style for Editor

---

src/fheroes2/gui/interface_buttons.cpp

Do not do anything for disabled spell cast button

---

.travis.yml

We save 3 seconds by not doing this

Do not install gettext for OSX jobs

---

.travis.yml

We want to do not waste time for package installations

Try to cache Homebrew

---

src/fheroes2/gui/interface_radar.cpp

Fix resizing of minimap in fixed interface mode

---

src/fheroes2/agg/agg.cpp
src/fheroes2/agg/sprite.cpp
src/fheroes2/agg/sprite.h

Show movement arrow icons with proper colors

---

src/fheroes2/castle/castle_well.cpp

Castle well ui fixes

---

src/fheroes2/castle/castle_well.cpp
src/fheroes2/dialog/dialog_recrut.cpp

Display recruit monster window even for 0 creatures

---

src/engine/display.cpp
src/engine/display.h
src/fheroes2/game/game_interface.cpp
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_gamearea.cpp

Fix scrolling behaviour and add diagonal scrolling

---

src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/game/game_delays.cpp

and fix post battle animation loop
relates to #287 
relates to #108

Set correct animation speed

---

src/fheroes2/battle/battle.h
src/fheroes2/battle/battle_army.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h
src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_well.cpp
src/fheroes2/monster/monster.cpp
src/fheroes2/monster/monster.h

Add monster animation to castle's well

---

src/fheroes2/game/game_interface.cpp
src/fheroes2/game/game_startgame.cpp

Tune parameters for scrolling

---

src/fheroes2/game/game_startgame.cpp

Update cursor while stopping hero's movement

---

src/fheroes2/resource/artifact.cpp

Fix https://github.com/ihhub/fheroes2/issues/111

Dont allow to move artifacts for not hired heroes (#111)

---

script/demo/demo_windows.bat

Add Wing32.dll download for Windows demo

---

src/fheroes2/agg/icn.cpp

Fix blurred advanture buttons https://github.com/ihhub/fheroes2/issues/273

Fix blurred adventure buttons (#273)

---

src/engine/dir.cpp
src/engine/dir.h
src/fheroes2/dialog/dialog_file.cpp
src/fheroes2/game/game_mainmenu.cpp
src/fheroes2/pocketpc/pocketpc_mainmenu.cpp

Fix issue https://github.com/ihhub/fheroes2/issues/372

Don't show file save loading dialog if no saves exist

---

src/fheroes2/game/game_startgame.cpp

Fix https://github.com/ihhub/fheroes2/issues/322

Human turn always first (#322)

---

src/fheroes2/game/game.cpp
src/fheroes2/game/game.h
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/heroes/heroes_action.cpp

Fix https://github.com/ihhub/fheroes2/issues/234
Initial solution, I think we can make some improvements. Instead of deleted fork.

Fix game freezes during animation of resources collection (#234)

---

src/fheroes2/monster/monster.cpp
src/fheroes2/monster/monster.h

Suggestion to fix https://github.com/ihhub/fheroes2/issues/57

Monster::Rand optimisation (#57)

---

src/fheroes2/ai/ai_action.cpp
src/fheroes2/army/army.cpp
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/heroes/heroes_spell.cpp

Never use static_cast where dynamic_cast should be
relates to #392

Fix map object casting

---

src/fheroes2/battle/battle_cell.cpp
src/fheroes2/battle/battle_cell.h
src/fheroes2/battle/battle_interface.cpp

Fix battle grid drawings

---

src/fheroes2/dialog/dialog_selectscenario.cpp
src/fheroes2/dialog/dialog_selectscenario.h
src/fheroes2/game/game_scenarioinfo.cpp
src/fheroes2/gui/interface_list.h

and fix incorrect position in map list after restarting

Fix incorrect scrolling in dialogs

---

src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_events.cpp

No jumping back
relates to #218

Complete hero's movement if user stops it

---

src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_radar.cpp
src/fheroes2/maps/maps.cpp
src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h

Add an edge of world map

---

src/fheroes2/game/game_startgame.cpp

Stop hero's movement if any button is pressed

---

src/fheroes2/battle/battle_dialogs.cpp

Add double quotes to surrender dialog

---

src/engine/display.cpp
src/engine/display.h
src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/game/fheroes2.cpp

also small drawing speed up
relates to #417

Fix application crash at exit in SDL 1

---

src/fheroes2/heroes/heroes_dialog.cpp

Do not show text for hidden Dismiss button

---

src/Makefile

We want to squeeze all juices from source code to have as fast as possible application

Use O3 flag to optimize code even more

---

src/engine/display.cpp
src/engine/display.h
src/engine/rect.cpp
src/engine/rect.h
src/fheroes2/agg/agg.cpp
src/fheroes2/agg/agg.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_only.cpp
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/castle/castle_mageguild.cpp
src/fheroes2/castle/castle_town.cpp
src/fheroes2/castle/castle_well.cpp
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/dialog/dialog_thievesguild.cpp
src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game_loadgame.cpp
src/fheroes2/game/game_mainmenu.cpp
src/fheroes2/game/game_newgame.cpp
src/fheroes2/game/game_scenarioinfo.cpp
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_border.cpp
src/fheroes2/heroes/heroes_dialog.cpp
src/fheroes2/kingdom/kingdom_overview.cpp
src/fheroes2/kingdom/puzzle.cpp
src/fheroes2/system/settings.cpp

- replace many hardcoded values
- make "World: show visited content" as default option
- fix application crash at exit for SDL 1
relates to #286 
relates to #293

Add scalable Sprites support

---

src/fheroes2/dialog/dialog_file.cpp
src/fheroes2/gui/interface_events.cpp

Fixes: #369 
added little bit extra comments to `src/fheroes2/game/fheroes2.cpp` that explains `NEWGAME` handling

Add quit dialog popup window and change File Options dialog behavior

---

src/tools/bin2txt.cpp

Update bin2txt tool

---

src/engine/dir.cpp
src/engine/system.cpp
src/engine/system.h

Adds case insensitive file access on *nix systems
Closes #429

*nix case insensitive file access

---

src/fheroes2/battle/battle_troop.cpp
src/fheroes2/game/game_static.cpp

Getting moat penalty right, adding extra elemental damage and correcting the defense formula.

Fix unit damage formula

---

src/fheroes2/agg/bin_info.cpp
src/fheroes2/agg/bin_info.h
src/fheroes2/battle/battle_animation.cpp
src/fheroes2/battle/battle_animation.h
src/fheroes2/monster/monster.cpp
src/fheroes2/monster/monster.h
src/fheroes2/monster/monster_info.h

also make some code decoupling
relates to #351

Update well animation based on latest BIN file changes

---

src/fheroes2/agg/bin_info.cpp
src/fheroes2/agg/bin_info.h
src/fheroes2/battle/battle_animation.cpp
src/fheroes2/battle/battle_animation.h
src/fheroes2/castle/castle_well.cpp
src/fheroes2/monster/monster.cpp
src/fheroes2/monster/monster.h

Add movement animation in Well

---

src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_well.cpp
src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/monster/monster.cpp
src/fheroes2/monster/monster.h

Add monster animation in army's info dialog

---

src/fheroes2/battle/battle_interface.cpp

Correct hero position in battle

---

src/fheroes2/battle/battle_interface.cpp

Fix hero animation in battle

---

src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fix surrender action during battle

---

src/fheroes2/dialog/dialog_settings.cpp

Set a correct position for buttons in Configuration dialog

---

src/fheroes2/castle/castle_town.cpp

Fix EXIT button position in casle options

---

src/fheroes2/monster/monster.cpp

Fix Phoenixes naming

---

src/fheroes2/agg/bin_info.cpp
src/fheroes2/castle/castle_well.cpp
src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/monster/monster.cpp

Fix Golem and Swordsman animation shift

---

src/fheroes2/game/game_highscores.cpp

Draw main menu as a background for High Score window

---

src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/resource/resource.cpp
src/fheroes2/resource/resource.h

Fix negative resources in kingdom posession

---

src/fheroes2/dialog/dialog_recrut.cpp

Fix shifted monster position in recruit window

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix alignment of text in monster info dialog

---

src/engine/display.cpp
src/engine/display.h
src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h

Fixes this: https://github.com/ihhub/fheroes2/issues/416

Add optional aspect ratio correction in fullscreen mode.

---

src/fheroes2/battle/battle_arena.cpp

Fix memory leak for arena

---

src/fheroes2/dialog/dialog_quickinfo.cpp

Fix display info of resources with scouting

---

src/fheroes2/gui/interface_radar.cpp

This was bothering me for a while.. literally every color on the radar minimap was wrong.
Before:
After:

Fix minimap colors

---

src/fheroes2/dialog/dialog_recrut.cpp

also remove duplicated code
relates to #531

Set correct position of monster in dwelling info

---

src/fheroes2/agg/bin_info.cpp
src/fheroes2/army/army.cpp
src/fheroes2/army/army.h
src/fheroes2/game/game_interface.cpp
src/fheroes2/gui/text.cpp
src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h
src/fheroes2/objects/objtown.cpp
src/fheroes2/system/settings.cpp
src/xmlccwrap/tinyxml.h
src/xmlccwrap/tinyxmlparser.cpp

It caught a critical typo in `settings.cpp` and `text.cpp`. `Troops` class allocates memory so it needs an explicit assignment operator.
Also fixing the straightforward warnings around the project.
https://lgtm.com/projects/g/ihhub/fheroes2/alerts/?mode=list&severity=

Fix bugs and warnings caught by lgtm

---

.github/workflows/github_actions.yml
appveyor.yml
script/tools/check_code_format.sh
src/Makefile

Add GitHub Actions builds

---

.travis.yml

We run this on GitHub Actions from now

Remove clang-format from Travis-CI

---

src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/maps/maps.cpp

relates to #434
relates to #411

Fix cursor behavior beyond world edge

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix speel icon size and position for monster's info

---

src/fheroes2/spell/spell.cpp

Fix Mass Cure spell icon

---

src/fheroes2/spell/spell_book.cpp

Fix incorrect mixed spells for hero's book

---

src/fheroes2/heroes/heroes_action.cpp

Attack a monster after landing from a ship

---

src/fheroes2/heroes/heroes_spell.cpp

Fix invisible hero's path after Dimension Door spell

---

src/engine/display.cpp
src/engine/display.h
src/fheroes2/game/game_interface.cpp

relates to #461
Now it looks like this:

Limit Dimension Door spell range

---

src/engine/display.cpp
src/fheroes2/battle/battle_interface.cpp

Add fading animation after battle

---

src/fheroes2/system/settings.cpp

relates #238
we had an option for this

Fixed a monster attrack an the start of a new game

---

src/fheroes2/gui/interface_events.cpp

Show a message if not enough points for digging

---

src/fheroes2/resource/artifact.cpp

Fix inability to move artifacts

---

src/fheroes2/battle/battle_interface.cpp

Use shadowing for end movement cell

---

src/fheroes2/heroes/heroes_action.cpp

Do not move a hero over a portal above another hero

---

src/fheroes2/heroes/heroes.cpp

Remove tiny ship icon

---

src/fheroes2/heroes/heroes_spell.cpp

Fix an ability to continue movement after Town portal spell

---

src/fheroes2/castle/castle_building.cpp

Fix building a new dwelling animation

---

src/fheroes2/battle/battle_interface.cpp

Fix incorrect position of a stunned monster

---

src/fheroes2/heroes/heroes_action.cpp

Play animation of treasure chest after collection

---

src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/dialog/dialog_recrut.cpp
src/fheroes2/dialog/dialog_selectfile.cpp
src/fheroes2/game/game_scenarioinfo.cpp

Add shadows to most of dialogs

---

src/fheroes2/heroes/heroes_spell.cpp

Fix Haunt spell incorrect behavior

---

src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/dialog/dialog_recrut.cpp
src/fheroes2/dialog/dialog_selectfile.cpp
src/fheroes2/game/game_scenarioinfo.cpp

Fix incremental growth of shadows of dialogs

---

src/engine/surface.cpp

Fix gradual shadowing in SDL2

---

src/fheroes2/battle/battle_arena.cpp

Give a control to an opponent over a hypnotized monster

---

src/fheroes2/heroes/heroes_dialog.cpp

Show disable Dismiss button for a hero in a castle

---

src/fheroes2/heroes/heroes_spell.cpp

Fix 0 monster count for Visions spell

---

src/fheroes2/dialog/dialog.h
src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_icons.cpp
src/fheroes2/heroes/heroes_dialog.cpp
src/fheroes2/heroes/heroes_spell.cpp
src/fheroes2/kingdom/kingdom_overview.cpp

relates to #618
relates to #619

Fix Identify Hero spell behavior

---

src/fheroes2/heroes/heroes_spell.cpp

Fix the logic for Summon Boat spell

---

src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_troop.cpp

Fix Archmage dispel post attack effect

---

src/fheroes2/gui/interface_list.h

this has been bothering me for a very long time

Fix many warnings

---

src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_interface.cpp

Fix Lich animation

---

.travis.yml

Use parallelization of jobs at maximum

Speed up Travis-CI

---

src/fheroes2/resource/artifact.cpp

Remove an ability to add an artifact for a hero

---

.github/workflows/clang_format.yml
.github/workflows/static_analysis.yml
.travis.yml

Travis-Ci is overloaded with jobs

Move static analysis job to GitHub Actions

---

src/fheroes2/battle/battle_interface.cpp

Fix hero position in battle

---

src/fheroes2/heroes/heroes_action.cpp

Play resource collection and sound after reading a dialog

---

src/fheroes2/battle/battle_interface.cpp

Fix inability to cast another spell upon cancellation teleport spell

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fix hero's flag position in battle

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/agg/agg.cpp
src/fheroes2/agg/sprite.cpp
src/fheroes2/agg/sprite.h

Hi @idshibanov , could you please check this function with your future color changes updates? I am not 100% sure about the correct logic for this function. The original function checks a pixel values from the input image and then put a pixels value on output image. In my opinion this logic seems incorrect so I changed ti to be only output image. `GetSurface` function should return an identical copy of input image.

Speed up rendering

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/dialog/dialog_marketplace.cpp
src/fheroes2/dialog/dialog_selectscenario.cpp
src/fheroes2/pocketpc/pocketpc_selectscenario.cpp

Fix few bugs found by SonarCloud

---

src/fheroes2/agg/agg.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

relates to #482
plus a small fix for MIN button

Fix hero's offset in battle for high resolutions

---

src/fheroes2/dialog/dialog_selectcount.cpp

Add min and max buttons for troop separation dialog

---

src/fheroes2/game/game_startgame.cpp

Fix hot seat no info situation

---

src/fheroes2/game/game_startgame.cpp

Fix incorrect dialog display for non-hot seat mode

---

src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_move.cpp

relates to #220
relates to #592

Fix hero fading animation

---

src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/game/game_delays.cpp

Set correct post battle video sequence

---

src/fheroes2/battle/battle_action.cpp

Ignore bad spell status for Archmage attack

---

src/engine/localevent.cpp
src/engine/localevent.h
src/fheroes2/game/game_interface.h
src/fheroes2/game/game_mainmenu.cpp
src/fheroes2/game/game_scenarioinfo.cpp
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_icons.cpp

plus add Alt+F4 support on SDL 2

Fix application exiting behavior

---

src/fheroes2/battle/battle_troop.cpp

Fix defence formula for monster during battle

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Sort spell icons by duration in monster statistics window

---

src/fheroes2/battle/battle_interface.cpp

Fix teleport delay in animation

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/gui/interface_cpanel.cpp

Fix blurred buttons in Adventure Panel

---

src/fheroes2/heroes/heroes_spell.cpp

Update sounds and music upon teleport spell usage

---

src/fheroes2/game/game_interface.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_gamearea.h
src/fheroes2/gui/interface_radar.cpp

Add exit button during Dimension Door spell

---

src/fheroes2/gui/interface_status.cpp

Make interface background more uniform

---

src/fheroes2/gui/interface_icons.cpp

Do not move screen to current hero after closing hero's stats window

---

src/fheroes2/dialog/dialog.h
src/fheroes2/dialog/dialog_box.cpp

Make non-fixed framebox for the future changes

---

src/fheroes2/battle/battle_bridge.cpp
src/fheroes2/battle/battle_bridge.h
src/fheroes2/battle/battle_troop.cpp

hi @shprotru , this condition will never be true as for now attacking unit cannot stand on moat cell before bridge.

Add a condition to check down bridge for unit defence calculation

---

src/fheroes2/game/game_startgame.cpp

Update focus after hero's dismiss

---

src/fheroes2/battle/battle_interface.cpp

Add a log message for flying monsters

---

src/fheroes2/heroes/heroes_action.cpp

Make hero's path visible after using a portal

---

src/fheroes2/game/game_interface.cpp

relates to #699
also fix some incorrect drawing upon cancellation of the spell

Show adventure map quick info by right click for dimension door spell

---

src/fheroes2/battle/battle_troop.cpp

Griffins would retaliate even under the effect or paralysis.

Fix retaliation condition logic

---

src/engine/rand.cpp
src/engine/serialize.cpp
src/engine/serialize.h
src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle.h
src/fheroes2/monster/monster.cpp
src/fheroes2/resource/resource.cpp
src/fheroes2/system/players.cpp

Minor issues/low hanging fruits. You can look at every commit for specific warnings.
For the most of the 'blocker' ones it really wants C++11 functionality for time and random.

Fix sonarcloud warnings/issues

---

src/fheroes2/gui/interface_list.h
src/fheroes2/kingdom/kingdom_overview.cpp

relates to #700
We need an extensive testing of these changes!

Fix a crash during hero's dismiss

---

files/lang/cs.po
files/lang/es.po
files/lang/fheroes2.pot
files/lang/fr.po
files/lang/hu.po
files/lang/lt.po
files/lang/nl.po
files/lang/pl.po
files/lang/pt.po
files/lang/ru.po
files/lang/sv.po
files/lang/tr.po
src/fheroes2/heroes/heroes_spell.cpp

Fix message content and scrollbar for Town Portal spell

---

src/fheroes2/battle/battle_arena.cpp
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/system/players.cpp

Fix code regression

---

src/engine/display.cpp
src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/agg/agg.cpp
src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/castle/castle_building.cpp
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/gui/interface_cpanel.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/heroes/heroes_move.cpp
src/fheroes2/kingdom/puzzle.cpp
src/fheroes2/pocketpc/pocketpc_dialog.cpp
src/fheroes2/test/test.cpp

relates to #729
Fixed transparent hero and its flag on World Map
Fixed Teleport spell during battle for many cases

Fix transparency on World Map and during Battle

---

src/engine/localevent.cpp
src/engine/localevent.h
src/fheroes2/gui/interface_list.h

Fix for issue #368 and fix a bug with ListBox crashing the app when having less than four items (out of bound seeking in a vector).

Fix scrollwheel and lists

---

src/fheroes2/battle/battle_interface.cpp

to match sounds on animation speed 1 at least

Make animation of teleport spell slower

---

src/fheroes2/game/game_startgame.cpp

Hide World Map for next turn in hot seat mode

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/heroes/heroes_move.cpp

relates to #696
relates to #671
relates to #550

Fix many places with shadows while using alpha blending in SDL 1

---

.travis.yml

no need to waste resources on other branches

Run SonarCloud only on master branch

---

src/fheroes2/battle/battle_board.cpp

Corrected obstacle to terrain mapping, more variety will be available. Updated random selection to make sure only one of a kind appear at the same time.
Tech debt: replace `std::random_shuffle` with `std::shuffle` once we move to C++11.

Improved battle obstacle selection

---

src/fheroes2/battle/battle_interface.cpp

Fix dimming post battle screen under cursor

---

src/fheroes2/agg/agg.cpp

Fix small yellow font

---

fheroes2.vcxproj

relates to #192
only for 64-bit for now

Compile without Visual Studio dependency

---

src/fheroes2/army/army.cpp

Fixes #726 .
Better count for power ratio plus fixing logic flow

Fix join and flee condition

---

src/fheroes2/kingdom/puzzle.cpp

Fix puzzle view on high resolutions

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/agg/agg.cpp
src/fheroes2/agg/agg.h
src/fheroes2/agg/icn.h
src/fheroes2/agg/pal.cpp
src/fheroes2/agg/pal.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h
src/fheroes2/gui/text.cpp
src/fheroes2/gui/text.h
src/fheroes2/spell/spell_book.cpp

- added mirror image rendering ( #555 )
- fixed incorrect stoned state rendering
- partially fixed blood lust based on #738 (SDL 1 still has problems) ( #754 )
- added gray font support
- set correct yellow and white font
- show gray text for spells which need more than currect hero spell
amount ( #759  )

Add a support of palette changing technique

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Use palette instead of map of colors

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/agg/pal.cpp
src/fheroes2/battle/battle_interface.cpp

relates to #715
relates to #613

Fix BloodLust animation

---

src/engine/rect.cpp
src/engine/rect.h
src/engine/surface.cpp
src/fheroes2/battle/battle_interface.cpp

Fix Armageddon and Earthquake animations

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fix Resurrect spell

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Add Stunning animation

---

src/fheroes2/battle/battle_interface.cpp

and fix teleporting stunned creature

Add color cycling effect on mirrored creature

---

src/fheroes2/battle/battle_interface.cpp

Fix missing effects on cloned creature

---

src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_gamearea.h
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_move.cpp

relates to #412
relates to #443
relates to #347

Add smooth screen movement during hero's walk

---

src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_board.cpp
src/fheroes2/battle/battle_interface.cpp

also fixed animation of clonning

Fix Mirror Image clone place

---

src/fheroes2/game/game_startgame.cpp

Fixing unresponsive screen after hero's fleeing

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/agg/pal.cpp
src/fheroes2/agg/pal.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/game/game_delays.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_gamearea.h
src/fheroes2/maps/maps_tiles.cpp

relates to #289
This is a initial solution towards cycling of colors on World Map.

Add initial implementation of color cycling on tiles

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/ai/simple/ai_simple.cpp
src/fheroes2/ai/simple/ai_simple.h
src/fheroes2/ai/simple/ai_simple_heroes.cpp
src/fheroes2/ai/simple/ai_simple_kingdom.cpp
src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/gui/interface_events.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/heroes/route.cpp
src/fheroes2/heroes/route.h
src/fheroes2/heroes/route_pathfind.cpp
src/fheroes2/maps/ground.cpp

The goal is to improve pathfinding and make AI more decisive. Sorting tasks by distance, optimizing algorithms a bit. This won't make the current version magically smart though; new AI from scratch is in the works for 0.9.
- Significantly lower turn time on large maps.
- Removed AI stutter stepping (stopping/re-pathing in the middle of the move).
- Better efficiency in first month (tested on large map Good vs Evil, impossible difficulty).
Renamed `Hero::isVisited()` to `isObjectTypeVisited()` to avoid confusion. Fixed a related bug in AI code where it would get stuck on the obelisk.

Simple AI strategic updates

---

src/fheroes2/maps/maps_tiles.cpp

relates to #803
Before:
After:
Before:
After:
Before:
After:

Fix fog drawings

---

src/fheroes2/heroes/skill.cpp

Add missing Skill word

---

src/fheroes2/battle/battle_interface.cpp

Add magic resist sound

---

src/fheroes2/gui/interface_events.cpp

Fix incorrect cursor during hero's movement by keyboard

---

src/fheroes2/castle/castle_dialog.cpp

relates to #819
relates to #820

Fix hero hiring animation position

---

src/fheroes2/castle/buildinginfo.cpp

Make yellow frame for not available building info

---

src/fheroes2/dialog/dialog_box.cpp
src/fheroes2/dialog/dialog_marketplace.cpp
src/fheroes2/dialog/dialog_resourceinfo.cpp
src/fheroes2/kingdom/kingdom_overview.cpp

fixes #818
fixes #532
Before:
After:
Before:
After:
Before:
After:
Before:
After:

Fix incorrect drawings for many dialogs

---

src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/monster/monster.cpp
src/fheroes2/monster/monster.h

Fix monster shifting inside monster info dialog

---

src/fheroes2/agg/icn.cpp
src/fheroes2/agg/icn.h
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/captain.cpp

Add a flag to castle's captain

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Draw post attack animation in parallel

---

src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/heroes/heroes_dialog.cpp

It's really annoying that you cannot use keyboard left/right buttons to navigate between castles

Add keyboard support for navigating between castles and heroes

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/agg/agg.cpp
src/fheroes2/agg/agg.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h

relates to #653
Also our contour generation image has become faster.

Fix creature contour drawing

---

src/fheroes2/dialog/dialog_marketplace.cpp

Fix marketplace window UI issues

---

src/fheroes2/battle/battle_army.cpp
src/fheroes2/battle/battle_army.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Do not run idle animation at every human's turn

---

src/engine/rect.cpp
src/engine/rect.h
src/fheroes2/battle/battle_interface.cpp

relates to #215
not the same as in the original but pretty good

Add base lightning animation

---

src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/castle/castle_mageguild.cpp

Display different message if no hero's in castle

---

src/fheroes2/spell/spell_book.cpp

Add keyboard support for navigation in spell book

---

src/fheroes2/heroes/heroes_move.cpp

also no froth when no movement
relates to #833

Fix ship shifting upon boarding it

---

src/fheroes2/battle/battle_interface.cpp

now it looks more to real lightning (in Heroes world of course)

Make lightning animation improvement

---

src/fheroes2/gui/interface_gamearea.cpp

Fix hero movement jump near left and top edges

---

src/engine/display.cpp

Fix fullscreen behavior in SDL 2

---

src/fheroes2/battle/battle_interface.cpp

when we move them from left to right

Fix extra shifting upon landing for wide flying monsters

---

src/fheroes2/gui/interface_buttons.cpp

Make "Next hero" button disable when no heroes exist

---

src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_gamearea.h

Update cursor while pointing on an empty interface area

---

src/fheroes2/battle/battle_interface.cpp

Fix last unit being hit 1 frame missing animation

---

src/fheroes2/gui/interface_status.cpp

Show a proper status window message depending on resolution

---

src/fheroes2/heroes/heroes_move.cpp

Make hero's movement smoother

---

src/fheroes2/game/game_delays.cpp

Fixes #483 . Self-explanatory.

Adjust flags animation with battle speed

---

src/fheroes2/heroes/heroes_move.cpp

relates to #931
relates to #934

Fix incorrect hero's interaction with objects during movement

---

README.md

Update README to reflect more accurate information

---

src/engine/surface.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h

Add base code for contour color cycling

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/battle/battle_interface.cpp

Add simplified lightning animation

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Add Chain Lightning animation

---

src/fheroes2/heroes/heroes_dialog.cpp

Fix hero's status bar item locations

---

src/fheroes2/castle/castle_mageguild.cpp

Fix mage guild background

---

src/fheroes2/battle/battle_interface.cpp

Set monster to static state after receiving a hit

---

src/fheroes2/game/game_highscores.cpp

Add frame border to highscore screen

---

src/fheroes2/agg/agg.cpp
src/fheroes2/spell/spell.cpp
src/fheroes2/spell/spell_book.cpp

relates to #554
every mass spell except Mass Dispel which requires an extra attention in the future

Change mass spell icons

---

src/fheroes2/battle/battle_interface.cpp

Fixes #969. Related to #973.
Small and self-explanatory pull request. Tested on both SDL1 and SDL2 debug builds.

Add lightning flash and delay

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/game/game_startgame.cpp

Update camera logic for AI moving out of the fog

---

src/engine/display.cpp

relates to #919 , #921 and #887

Use only screen supported resolutions for the game

---

src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/maps/maps_tiles_quantity.cpp

Fix Shipwreck empty battle

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_move.cpp

relates to #980
relates to #990

Correct AI movements

---

src/engine/display.h
src/engine/localevent.h
src/fheroes2/gui/interface_list.h

Fix enormous warning generation on Unix builds

---

src/fheroes2/gui/interface_list.h
src/fheroes2/gui/text.h

we have too much of them and our compilation log is too huge

Fix more warnings

---

src/fheroes2/battle/battle_interface.cpp

Update elemental storm spell

---

src/fheroes2/battle/battle_interface.cpp

Fix irresponsive battle log

---

src/fheroes2/ai/simple/ai_simple_battle.cpp
src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_board.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h

relates to #808
relates to #809 
relates to #810

Fix Hypnotyze and Berserk spell behaviors

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/agg/m82.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fixes #704 .
Notice difference between Ripple and Wave:

Death wave/ripple spell effect implementation

---

src/fheroes2/game/fheroes2.cpp

Try to apply mass spell on 10 creatures in the battle and notice that
not all of them have a hit/death sound

Increase the amount of sound channels to 16

---

src/engine/surface.cpp
src/engine/surface.h
src/engine/tools.cpp
src/engine/tools.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fixes #888 . 
Small interface things drawn on the side are explained in another issue. Existing UI bug.

Holy Shout blur effect

---

src/fheroes2/game/game_interface.cpp

relates to #1035
relates to #1040

Fix dimension door range and drawings

---

src/fheroes2/castle/castle.cpp

Add additional buildings to the cycling list

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fixes #1042.
Water, lava and castle moat.

Add cycling animation to the battlefield

---

src/fheroes2/game/game_interface.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/heroes/heroes_spell.cpp

relates to #1061
relates to #1060

Fix screen centering and dimension door spell

---

src/fheroes2/battle/battle_interface.cpp

Fix chain lightning start point

---

src/fheroes2/battle/battle_main.cpp

Reset sound only if battle is shown

---

src/fheroes2/dialog/dialog_system.cpp

relates to #1059
relates to #1066

Fix system menu OKAY button

---

src/engine/smk_decoder.cpp
src/fheroes2/game/game_video.cpp

Used EVIL08.SMK to test it, has video, voice audio channel and music channel. Result looks good to me.
Looping video/sound tested on CHOOSE.SMK

Add SMK audio playback

---

src/fheroes2/battle/battle_interface.cpp

Fixes #975 . 
Making sure luck animations are fully displayed even in the top row. I missed this one last time :)

Fix luck animation offset

---

src/fheroes2/dialog/dialog_levelup.cpp

Fix hero's level up window with single secondary skill

---

src/fheroes2/battle/battle_interface.cpp

Fix delayed mouse click on a cell during battle

---

src/engine/localevent.cpp
src/engine/localevent.h
src/fheroes2/heroes/heroes_dialog.cpp

Fix incorrect popping window in tavern

---

src/fheroes2/gui/cursor.cpp

Update current cursor first before deleting old one for SDL 2

---

src/fheroes2/game/game_startgame.cpp

Fix cursor for empty enemy castle

---

src/fheroes2/agg/agg.cpp
src/fheroes2/agg/agg.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/dialog/dialog_selectcount.cpp
src/fheroes2/dialog/dialog_thievesguild.cpp
src/fheroes2/game/game_loadgame.cpp
src/fheroes2/game/game_mainmenu.cpp
src/fheroes2/game/game_newgame.cpp
src/fheroes2/game/game_scenarioinfo.cpp
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_events.cpp
src/fheroes2/gui/text.h
src/fheroes2/heroes/heroes_dialog.cpp
src/fheroes2/heroes/heroes_meeting.cpp
src/fheroes2/objects/objtown.cpp
src/fheroes2/pocketpc/pocketpc_dialog.cpp

Remove PocketPC related code and fix some compilation warnings

---

src/engine/localevent.cpp
src/engine/localevent.h

Don't play sounds in castle's window when restoring the application

---

src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/castle/castle_town.cpp

Use correct sprite for castle's exit button

---

src/fheroes2/heroes/heroes_move.cpp

Display froth sprite only if away from the coast

---

src/fheroes2/agg/agg.cpp

Fix wolf's low attack animation

---

src/fheroes2/game/game.cpp
src/fheroes2/game/game.h
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/heroes/heroes_spell.cpp

Fixes #1043 .
Refactored RemoveAnimation struct to support both add and remove actions.

Add boat summoning animation

---

src/fheroes2/gui/interface_gamearea.cpp

Fix fading animation on the World Map

---

src/fheroes2/agg/agg.cpp
src/fheroes2/agg/bin_info.cpp

Fix wolves attack animation

---

src/engine/audio_music.cpp

Don't run useless code

---

src/fheroes2/game/game_interface.cpp

Add evil interface support for Dimension Door spell

---

src/fheroes2/heroes/heroes_spell.cpp

Fix missing music after Dimension Door

---

src/fheroes2/maps/maps_tiles.cpp

Fix attacking monster sprite on the World Map

---

src/fheroes2/game/game_startgame.cpp

Fix attack cursor while pointing a monster

---

src/fheroes2/maps/maps_tiles.cpp

Fix attacking monster sprite conditions

---

src/fheroes2/agg/bin_info.cpp

Fix elves lower shooting start position

---

src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/resource/artifact.h

Fix flickering of status bar in castle

---

fheroes2.vcxproj
src/engine/display.cpp
src/engine/display.h
src/fheroes2/dialog/dialog_resolution.cpp
src/fheroes2/dialog/dialog_resolution.h
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/game/game_mainmenu.cpp

Add resolution change in-game option

---

src/fheroes2/agg/bin_info.cpp

Fix last shooting angle missile sprite

---

src/fheroes2/game/game_mainmenu.cpp

Reset game interface when resolution changes

---

src/engine/display.cpp

Filter resolutions if they are bigger than default

---

src/engine/display.cpp

Add extra conditions for SDL2 resolution retrieval

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fixes #1114 .
Also swamp battle background needed water animation.

Add swamp and necromancer cycling animations

---

src/fheroes2/dialog/dialog_resolution.cpp

Fix inability to choose similar resolution

---

src/fheroes2/game/game_interface.cpp
src/fheroes2/game/game_interface.h
src/fheroes2/game/game_mainmenu.cpp

Fix incorrect scrolling area for new resolution

---

src/fheroes2/gui/interface_focus.cpp
src/fheroes2/heroes/heroes_spell.cpp

Fix Dimension Door crash

---

src/fheroes2/gui/interface_events.cpp

Skip heroes who dont have move points for move or sleep

---

src/fheroes2/dialog/dialog_system.cpp

fix #1155. Button icon was hardcoded

fix hardcoded icon

---

src/engine/audio_mixer.h
src/engine/audio_music.cpp
src/engine/font.h
src/engine/sdlnet.h
src/engine/surface.cpp
src/engine/thread.h

As some users are having problems with compilation on Linux

Use global file inclusion for SDL files

---

src/fheroes2/heroes/heroes_spell.cpp

Fix for #1115 
Only teleport to the nearest town if no guest hero.
Idk must I update *.po files or not?

Fix logic of Town Gate spell

---

src/fheroes2/castle/castle_building.cpp

relates to #459
and the drawings now are slightly faster :)

Don't draw tent images in the castle window at all

---

src/fheroes2/castle/castle_well.cpp

Add logic to handle inability to buy monsters in well

---

src/fheroes2/army/army_bar.cpp

Remove black background over army counter

---

src/Makefile
src/fheroes2/ai/simple/ai_simple_battle.cpp
src/fheroes2/ai/simple/ai_simple_kingdom.cpp
src/fheroes2/army/army.cpp
src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_army.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/castle/castle.cpp
src/fheroes2/gui/interface_focus.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/kingdom/world.cpp
src/fheroes2/system/players.cpp
src/thirdparty/libsmacker/Makefile

Add C++11 support

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix EXIT button position in creature window

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.cpp

 Skip turn of resurrected troop

---

src/fheroes2/gui/button.cpp

Fix an ability to skip button state by using keyboard

---

src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h
src/fheroes2/spell/spell.cpp

Apply Chain Lightning damage on allies as well

---

src/fheroes2/resource/artifact.cpp

Don't display artifact dialog for unknown artifact

---

src/fheroes2/castle/castle_dialog.cpp

Show a dialog if a hero has no space for Spell Book

---

src/fheroes2/dialog/dialog_marketplace.cpp

Fix marketplace text

---

src/fheroes2/heroes/heroes_action.cpp

Fix graveyard message

---

src/fheroes2/heroes/heroes_action.cpp

Add missing title for graveyard message

---

src/fheroes2/heroes/heroes_dialog.cpp

Fix Dismiss button position in Hero's dialog

---

src/fheroes2/maps/mp2.cpp

Fix lighthouse spelling

---

src/fheroes2/agg/agg.cpp

Polish battle only button

---

src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes_indicator.cpp

Modify Graveyard robber message

---

src/fheroes2/heroes/heroes_action.cpp

Fix Sphinx message

---

src/fheroes2/gui/cursor.cpp

Fix cursor position for SDL 1

---

src/fheroes2/dialog/dialog_selectfile.cpp

Fix file save always disabled button

---

src/fheroes2/game/game_startgame.cpp
src/fheroes2/maps/mp2.cpp
src/fheroes2/maps/mp2.h

Fix abandonded mine cursor

---

src/fheroes2/heroes/heroes_action.cpp

Don't show diplomacy even when not enough gold

---

src/fheroes2/game/game_newgame.cpp

Disable Campaign button if no files present

---

src/fheroes2/game/game_highscores.cpp

Make Disabled Campaign button in High Score board

---

src/fheroes2/game/game_startgame.cpp

Don't refocus after exiting castle's window

---

src/fheroes2/dialog/dialog_system.cpp

Reset interface while changing its type

---

src/fheroes2/dialog/dialog_settings.cpp

Use proper config background image

---

src/fheroes2/dialog/dialog_selectscenario.cpp

Fix map difficulty text and its position

---

src/fheroes2/game/game_scenarioinfo.cpp

Always center scenario window position

---

src/fheroes2/game/game_startgame.cpp

Add dot at the end of player's turn text

---

src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/heroes/heroes_action.cpp

Always show diplomacy window and fix marketplace button

---

src/fheroes2/game/game_scenarioinfo.cpp

The game crashes for unknown map extension

Incorrect map extension crash

---

src/fheroes2/game/game_startgame.cpp

Update interface after exiting hero dialog

---

src/fheroes2/battle/battle_interface.cpp

Fix Armageddon animation

---

src/fheroes2/dialog/dialog_system.cpp
src/fheroes2/gui/interface_events.cpp
src/fheroes2/gui/interface_radar.cpp

Fix shift after opening and closing system options dialog

---

src/engine/display.cpp
src/engine/display.h
src/fheroes2/agg/agg.cpp
src/fheroes2/agg/agg.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game_hotkeys.cpp
src/fheroes2/system/settings.cpp

no need to even compile the old code

Old engine code cleanup

---

src/fheroes2/agg/agg.cpp

Add missing config button

---

src/fheroes2/dialog/dialog_box.cpp

Fix message dialog shadow

---

src/fheroes2/gui/interface_cpanel.cpp

Fix button drawing for no interface

---

src/engine/smk_decoder.cpp
src/fheroes2/agg/agg.cpp
src/fheroes2/agg/agg.h
src/fheroes2/agg/bin_info.cpp
src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.h
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/castle.h
src/fheroes2/dialog/dialog_resolution.cpp
src/fheroes2/game/game_interface.h
src/fheroes2/game/game_video.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_itemsbar.h
src/fheroes2/gui/interface_list.h
src/fheroes2/gui/ui_button.cpp
src/fheroes2/kingdom/world.h
src/fheroes2/pocketpc/pocketpc_dialog.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h

plus a huge chunk of code cleanup

Save all battle options in global configuration file

---

src/fheroes2/game/game_mainmenu.cpp

Save configuration file after resolution change

---

src/fheroes2/castle/castle_building.cpp

relates to #1305
and it's faster now :)

Draw only current level of mage guild

---

src/fheroes2/gui/interface_icons.cpp

relates to #1462
relates to #1463

Fix castle mini status icon

---

src/fheroes2/castle/captain.cpp
src/fheroes2/heroes/heroes.cpp

Set minimum Spell Power to be 1

---

src/fheroes2/gui/interface_events.cpp

Set focus on a hero while opening spell book

---

src/engine/localevent.cpp
src/engine/localevent.h
src/engine/screen.cpp
src/engine/screen.h
src/engine/smk_decoder.cpp
src/engine/smk_decoder.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/dialog/dialog_resolution.cpp
src/fheroes2/dialog/dialog_selectfile.cpp
src/fheroes2/dialog/dialog_selectitems.cpp
src/fheroes2/dialog/dialog_selectscenario.cpp
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game_video.cpp
src/fheroes2/gui/interface_icons.cpp
src/fheroes2/gui/interface_list.h
src/fheroes2/gui/ui_tool.cpp
src/fheroes2/gui/ui_tool.h
src/fheroes2/heroes/heroes_spell.cpp
src/fheroes2/kingdom/kingdom_overview.cpp

Play video intro at the opening

---

src/engine/image.cpp
src/engine/image.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/gui/interface_border.cpp
src/fheroes2/gui/interface_radar.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h

and remove show SDL logo configuration setting

Add different type of border

---

changelog.txt
src/fheroes2/system/gamedefs.h
src/fheroes2/system/settings.cpp

Update version to 0.8.1

---

src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_troop.cpp

Fix Resurrection animation frame and moving dead units

---

src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/buildinginfo.h
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/castle/castle_town.cpp
src/fheroes2/gui/ui_button.cpp
src/fheroes2/gui/ui_button.h

Make Exit button disabled for popup windows in castle

---

src/fheroes2/dialog/dialog_box.cpp

Fix generated window position

---

src/fheroes2/gui/interface_status.cpp

Fix sky view status

---

src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h

it's an imbalance thing for the game

Remove "castle: allow recruits special/expansion heroes" option

---

src/fheroes2/game/game_newgame.cpp

Fix New Game window UI

---

src/fheroes2/dialog/dialog_selectscenario.cpp
src/fheroes2/gui/ui_button.cpp
src/fheroes2/gui/ui_button.h

Fix map size button state selection

---

src/fheroes2/game/game_video.cpp

don't idle when we can crunch some data

Optimise video playback

---

src/fheroes2/game/game_newgame.cpp
src/fheroes2/game/game_scenarioinfo.cpp

Fix few UI issues

---

src/engine/image.cpp
src/engine/image.h
src/engine/math_base.h
src/fheroes2/castle/castle_well.cpp
src/fheroes2/dialog/dialog_armyinfo.cpp

relates to #1095
also changed fheroes2::Size type and fheroes2::Rect classes
Now it's slightly faster :)

Draw monster animation within specified ROI

---

src/engine/image.cpp
src/engine/image.h
src/fheroes2/agg/agg.cpp

It's present even in the original game
relates to #1408

Fix graphical issues in big text font

---

src/fheroes2/game/game_newgame.cpp

Fix multiplayer player count window position

---

src/fheroes2/gui/interface_buttons.cpp

Disable Next Hero button if none of heroes can move

---

src/fheroes2/agg/agg.cpp
src/fheroes2/dialog/dialog_gameinfo.cpp

relates to #1482
relates to #1481

Fix game info buttons

---

src/fheroes2/battle/battle_interface.cpp

Make scroolbar more user friendly in battle log

---

src/fheroes2/agg/agg.cpp

Fix few Phoenix frames

---

src/fheroes2/gui/interface_events.cpp

Add a dot at the end of Ultimate Artifact message

---

src/engine/screen.cpp

Fix missing resolutions and black screen for SDL 1

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Fix `battle: show damage info` option

---

src/fheroes2/agg/agg.cpp
src/fheroes2/agg/mus.cpp
src/fheroes2/agg/mus.h
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/dialog/dialog_system.cpp
src/fheroes2/game/game_newgame.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h

- support for Windows and DOS versions
- if no external music present then fall back to MIDI
- we can switch between 3 types of music

Add external music support by default

---

src/fheroes2/game/game_newgame.cpp
src/fheroes2/gui/ui_button.cpp
src/fheroes2/gui/ui_button.h

Add button choice support for campaign

---

src/engine/screen.cpp
src/engine/screen.h
src/fheroes2/agg/agg.cpp
src/fheroes2/agg/agg.h
src/fheroes2/army/army_bar.cpp
src/fheroes2/army/army_bar.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/buildinginfo.h
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/cursor.cpp
src/fheroes2/gui/cursor.h
src/fheroes2/kingdom/kingdom_overview.cpp
src/fheroes2/test/test_monstersprite.cpp

and make old code cleanup
It should be faster and the game will eat less resources

Add proper Cursor class

---

src/engine/image.cpp
src/fheroes2/agg/agg.cpp

relates to #1384
this is a part of image decoding algorithm

Fix creature shadow contour issue

---

src/fheroes2/game/game_over.cpp

I1648 added word player

---

src/fheroes2/heroes/heroes_indicator.cpp

Center spell point text in hero's dialog

---

src/fheroes2/heroes/heroes_dialog.cpp

Fix some icon positions in hero's dialog

---

src/fheroes2/battle/battle_interface.cpp

Remove extra wince animation for cold ray spell

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix monster info shadow position

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix text color for joining window

---

src/fheroes2/dialog/dialog_file.cpp

Fix File Options window position

---

src/fheroes2/battle/battle_dialogs.cpp

Fix victory message in battle

---

src/fheroes2/spell/spell.cpp

Fix Blind spell name

---

src/fheroes2/heroes/heroes_action.cpp

Fix Daemon Cave incorrect window

---

src/fheroes2/game/game_startgame.cpp

Reset music after exiting a castle

---

src/fheroes2/battle/battle_troop.cpp

Fix a crash for Mirror image creature

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix hero button position for joining window

---

src/fheroes2/battle/battle_dialogs.cpp

Add missing dot for a victory text

---

src/fheroes2/maps/maps_tiles_quantity.cpp

Display Liches for the City of the Dead

---

src/fheroes2/spell/spell_book.cpp

Display spell points in magic book from bottom to top

---

src/fheroes2/battle/battle_dialogs.cpp

Center Hero's Options dialog

---

src/fheroes2/game/game.cpp

Add proper credits

---

README.md
src/engine/image.cpp
src/engine/screen.cpp
src/fheroes2/agg/agg.cpp
src/fheroes2/gui/cursor.cpp

Readme and code cleanup

---

src/fheroes2/gui/skill_bar.cpp
src/fheroes2/heroes/heroes_dialog.cpp
src/fheroes2/heroes/heroes_indicator.cpp
src/fheroes2/heroes/skill.cpp

relates to #1676
relates to #1678
relates to #1679
relates to #1680
relates to #1681
relates to #1682
relates to #1685

Fix multiple UI issues in Hero's Screen

---

src/fheroes2/battle/battle_action.cpp

Check magic resistance against Chain Lighting spell

---

src/fheroes2/game/game_startgame.cpp

Focus on a new hired hero in a castle

---

src/fheroes2/heroes/heroes.cpp

Reset dimissed hero's army

---

src/fheroes2/gui/interface_list.h

Fix bottom-to-top scrolling issue by keyboard key

---

src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/castle/castle_town.cpp

Castle construction screen, add the Income information window

---

src/fheroes2/army/army_bar.cpp
src/fheroes2/dialog/dialog_selectcount.cpp
src/fheroes2/resource/artifact.cpp

relates to #1718
relates to #1719

Change color for item selection

---

src/fheroes2/battle/battle_interface.cpp

Change unit movement speed in battle under spells

---

src/fheroes2/castle/castle_town.cpp

Shift second hero's portrait in town

---

src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game.h
src/fheroes2/game/game_highscores.cpp
src/fheroes2/game/game_over.cpp

The main menu should be in the best condition

Don't shift High Score background for high resolutions

---

src/fheroes2/dialog/dialog_settings.cpp

relates to #1509
relates to #1421

Use single OKAY button for Config window

---

src/fheroes2/castle/castle_town.cpp

Added dot to the end of hero description

---

src/fheroes2/dialog/dialog_settings.cpp

Fix scrollbar in Settings window

---

src/fheroes2/game/game_startgame.cpp

Fix cursor for Abandoned mine protected by monsters

---

src/fheroes2/spell/spell_book.cpp

relates to #1285
relates to #1087

Fix popup windows for Spell Book

---

src/fheroes2/dialog/dialog_file.cpp

Add Information window by right click in File dialog

---

src/fheroes2/dialog/dialog_recrut.cpp

Fix text poistion in creature recruit window

---

src/fheroes2/spell/spell_book.cpp

Fix bookmark positions in Spell Book

---

src/fheroes2/battle/battle_main.cpp
src/fheroes2/spell/spell_book.cpp

relates to #1499
relates to #1694

Add missing dots for messages

---

src/fheroes2/dialog/dialog.h
src/fheroes2/dialog/dialog_box.cpp

Fix dialog frame drawing

---

src/fheroes2/heroes/heroes_meeting.cpp

Allow to open hero's dialog during meeting

---

src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_arena.h
src/fheroes2/battle/battle_grave.cpp
src/fheroes2/battle/battle_grave.h
src/fheroes2/battle/battle_interface.cpp

Draw all dead troops on the battlefield

---

src/fheroes2/heroes/heroes.cpp

Fix hero's names

---

src/fheroes2/ai/normal/ai_normal_battle.cpp

Adding protective mode for the units (ranged unit protection) including castle defense.
Small fixes here and there.

Combat AI: enable defensive tactics

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Amount of creatures moved down by 1 pixel in DrawMonsterInfo

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_events.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/heroes/direction.cpp
src/fheroes2/heroes/direction.h
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_move.cpp
src/fheroes2/heroes/route.cpp
src/fheroes2/heroes/route.h
src/fheroes2/maps/maps.cpp
src/fheroes2/world/world_pathfinding.cpp

Fixes #1145 . Fixes #1703 .
Fixed penalty calculation logic as well as minor refactoring there.

Allow hero to make last diagonal move

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_pathfinding.cpp
src/fheroes2/game/game_newgame.cpp
src/fheroes2/world/world_pathfinding.cpp
src/fheroes2/world/world_pathfinding.h

Remove unused variables

---

src/fheroes2/heroes/heroes_action.cpp

Always reduce moral for visited Graveyard and Ship Wreck

---

src/fheroes2/ai/ai.h
src/fheroes2/ai/ai_common.cpp
src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/ai/normal/ai_normal.h
src/fheroes2/ai/normal/ai_normal_hero.cpp
src/fheroes2/ai/normal/ai_normal_kingdom.cpp
src/fheroes2/army/army.cpp
src/fheroes2/army/army.h
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/castle/castle_well.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/maps/ground.h
src/fheroes2/maps/mp2.cpp
src/fheroes2/maps/mp2.h
src/fheroes2/resource/artifact.cpp
src/fheroes2/resource/artifact.h
src/fheroes2/resource/resource.cpp
src/fheroes2/resource/resource.h

Skeleton code and preparation for future changes.
More sophisticated map heuristic value will be added later.
No priority management from the AI kingdom yet, each hero acts on its own.

Strategic AI: handle hero movement

---

src/engine/rand.cpp
src/engine/rand.h
src/fheroes2/game/fheroes2.cpp

Use a proper randomizer

---

README.md

By Monu Update README.md

---

src/fheroes2/ai/normal/ai_normal_kingdom.cpp

Calculates the threat of nearby enemy armies and runs a defensive CastleTurn (includes recruiting armies and building fortifications).

Strategic AI: build up castle defenses

---

src/fheroes2/battle/battle_action.cpp

Fix second attack for blinded creatures

---

src/fheroes2/battle/battle_interface.cpp

Don't show journal scrollbar when it's not open

---

src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h

Forgot to update old code dealing with the issue.

Fix price of loyalty map objects

---

src/fheroes2/dialog/dialog_box.cpp

Fix missing dialog box in some rare cases

---

src/fheroes2/maps/maps_tiles_quantity.cpp

Fix monthly monster placement

---

src/fheroes2/gui/interface_gamearea.cpp

Updating draw priority for map objects (done in separate loop so it won't be drawn on top of others).

Fix monster shadows

---

src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/kingdom/kingdom.h
src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h
src/fheroes2/maps/maps_tiles_quantity.cpp
src/fheroes2/maps/mp2.cpp

Fixed color set for each tent/barrier pair
Fixed barrier pass-through logic (bitwise sets)
Also removed a bunch of unused code.

Fix tents/barriers from Price of Loyalty

---

src/fheroes2/maps/mp2.cpp

Fix event cursor type

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/game/game.h
src/fheroes2/game/game_delays.cpp
src/fheroes2/game/game_startgame.cpp

Also speed 10 is an instant speed.

Fix hero's movement speed

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/game/game_delays.cpp
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/heroes/heroes_move.cpp

also adjust default speed animation

Make boarding/off-boarding boat animation dependent

---

src/fheroes2/dialog/dialog_adventure.cpp

Center Adventure Options window

---

files/lang/cs.po
files/lang/es.po
files/lang/fheroes2.pot
files/lang/fr.po
files/lang/hu.po
files/lang/lt.po
files/lang/nl.po
files/lang/pl.po
files/lang/pt.po
files/lang/ru.po
files/lang/sv.po
files/lang/tr.po
src/fheroes2/army/army_bar.cpp
src/fheroes2/dialog/dialog_selectcount.cpp

this pr is supposed to replace my previous pr "Modify messages for splitting army window #1897"
relates to #1887

Modify messages for splitting army window - fixed issue #1887

---

src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/castle.cpp
src/fheroes2/dialog/dialog_selectscenario.cpp
src/fheroes2/resource/artifact.cpp

fix issue #1884 
fix issue #1885
fix issue #1886 
fix issue #1888

Fix some text issues

---

src/fheroes2/heroes/heroes.cpp

I1858 fix CanMove method

---

src/engine/image.cpp
src/engine/rect.cpp
src/engine/rect.h
src/engine/smk_decoder.cpp
src/engine/smk_decoder.h
src/engine/surface.cpp
src/engine/surface.h
src/engine/thread.cpp
src/engine/thread.h
src/fheroes2/agg/agg.cpp
src/fheroes2/ai/ai.h
src/fheroes2/dialog/dialog.h
src/fheroes2/dialog/dialog_frameborder.cpp
src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game_interface.cpp
src/fheroes2/gui/interface_list.h
src/fheroes2/gui/splitter.h
src/fheroes2/heroes/heroes.h
src/fheroes2/system/settings.cpp
src/fheroes2/world/world_regions.cpp

as a part of code enhancements

Source code cleanup

---

src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/captain.cpp
src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_well.cpp
src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/dialog/dialog_system.cpp
src/fheroes2/game/game.h
src/fheroes2/game/game_delays.cpp
src/fheroes2/game/game_video.cpp
src/fheroes2/gui/interface_border.cpp
src/fheroes2/heroes/heroes_spell.cpp
src/fheroes2/spell/spell_book.cpp

Fix multiple compilation warnings

---

src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/maps/maps.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h
src/fheroes2/world/world.cpp

Remove "allow pickup objects for patrol"

---

src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/pocketpc/pocketpc_dialog.cpp

never ending task for the perfection of the code

Usual code cleanup

---

src/fheroes2/agg/agg.cpp
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/castle/buildinginfo.h
src/fheroes2/dialog/dialog_giftresources.cpp
src/fheroes2/game/game.cpp
src/fheroes2/game/game.h
src/fheroes2/system/players.cpp

Another compilation warning reduction

---

src/engine/localevent.cpp
src/engine/rect.cpp
src/engine/rect.h
src/fheroes2/agg/agg.cpp
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_main.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle_building.cpp
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/dialog/dialog_message.cpp
src/fheroes2/dialog/dialog_resolution.cpp
src/fheroes2/dialog/dialog_selectfile.cpp
src/fheroes2/dialog/dialog_selectitems.cpp
src/fheroes2/dialog/dialog_selectscenario.cpp
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/game/game_interface.cpp
src/fheroes2/gui/interface_icons.cpp
src/fheroes2/gui/interface_itemsbar.h
src/fheroes2/gui/interface_list.h
src/fheroes2/gui/player_info.cpp
src/fheroes2/gui/ui_button.cpp
src/fheroes2/heroes/direction.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes_base.cpp
src/fheroes2/heroes/heroes_spell.cpp
src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/kingdom/kingdom_overview.cpp
src/fheroes2/maps/maps_objects.cpp
src/fheroes2/pocketpc/pocketpc_dialog.cpp

Fix many compilation warnings

---

src/fheroes2/ai/ai_hero_action.cpp

Add fading animation for defeated AI hero

---

src/fheroes2/battle/battle_only.cpp
src/fheroes2/kingdom/kingdom.cpp

Remove scrollbars from interface in battle only mode

---

src/fheroes2/dialog/dialog_system.cpp

relates to #1908
relates to #1909
relates to #1910

Fix system options dialog

---

src/fheroes2/game/game_scenarioinfo.cpp
src/fheroes2/gui/player_info.cpp
src/fheroes2/gui/player_info.h

Honour player count for Hot Seat mode

---

src/fheroes2/battle/battle_army.cpp
src/fheroes2/battle/battle_army.h
src/fheroes2/battle/battle_main.cpp

Fix incorrect resurrected troops after battle

---

src/fheroes2/ai/normal/ai_normal_battle.cpp

Show skip turn message during AI turns

---

src/fheroes2/dialog/dialog_selectcount.cpp
src/fheroes2/gui/player_info.cpp
src/fheroes2/gui/text.cpp
src/fheroes2/gui/text.h

relates to #1309
also fixed input text position

Limit text within given input box

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h

Fix visibility of AI hero moving close to fog

---

src/fheroes2/dialog/dialog_thievesguild.cpp

Fix Theves Guild background

---

src/fheroes2/battle/battle_interface.cpp

Combat screen, logs list, quantity text "one" instead of "1"

---

src/fheroes2/battle/battle_arena.cpp

Battle doesn't stop, after AI kills the last creature

---

src/fheroes2/resource/resource.cpp

Fix income window drawings

---

src/fheroes2/heroes/heroes_action.cpp

Play flotsam disappearing sound after closing the window

---

src/fheroes2/heroes/heroes.cpp
src/fheroes2/maps/mp2.cpp

replace "Ship Wreck" with "Shipwreck"

---

src/fheroes2/battle/battle_army.cpp

The growth of ghosts after battle

---

src/fheroes2/army/army.cpp
src/fheroes2/army/army.h
src/fheroes2/heroes/heroes.cpp

Fix non-necro undead units decreasing morale in an all-undead army

---

src/engine/thread.cpp
src/engine/thread.h

to fix compilation on other systems

Revert back some cleanup changes

---

src/fheroes2/battle/battle_board.cpp

Remove mud pool from obstacle list

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/castle/castle.cpp
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/heroes/heroes_spell.cpp
src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h
src/fheroes2/maps/maps_tiles_quantity.cpp
src/fheroes2/maps/mp2.cpp

Save boat direction when disembarking 

---

src/fheroes2/heroes/heroes_action.cpp

Disable spell animation after mine was cleared

---

src/fheroes2/game/game_io.cpp
src/fheroes2/game/game_startgame.cpp

Make autosave with capital letters

---

src/fheroes2/dialog/dialog_file.cpp

Change main menu popup window descriptions

---

src/engine/image.cpp
src/engine/image.h
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/maps/maps_tiles.cpp

Make small code optimizations

---

src/fheroes2/agg/agg.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_gamearea.h
src/fheroes2/world/world.cpp
src/fheroes2/world/world.h

Make small speedups for drawings

---

src/fheroes2/ai/normal/ai_normal_hero.cpp
src/fheroes2/army/army.cpp
src/fheroes2/army/army_troop.cpp
src/fheroes2/army/army_troop.h
src/fheroes2/monster/monster.cpp
src/fheroes2/monster/monster.h
src/fheroes2/world/world_pathfinding.h

Army::GetStrength() is twice as fast on average.

Cache hero bonus when calculating army strength

---

src/fheroes2/battle/battle_interface.cpp

Adjust post battle shadowing

---

src/fheroes2/battle/battle_dialogs.cpp

Fix battle option text overlapping

---

src/fheroes2/dialog/dialog_resolution.cpp

Adjust few elements in resolution window

---

fheroes2.vcxproj
src/fheroes2/ai/normal/ai_normal_castle.cpp
src/fheroes2/ai/normal/ai_normal_hero.cpp
src/fheroes2/world/world.h
src/fheroes2/world/world_regions.cpp
src/fheroes2/world/world_regions.h

Refactored and cleaned up map region code to be referenced by outside code. Removed unused values (region border nodes) and added new metrics instead. Data is now stored as a part of World class.
Using new values to make better decisions during AI turns. More usage (for hero recruit and role decisions) will be added in future PRs.

Use map region tools in AI code

---

src/engine/pathfinding.h
src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/ai/normal/ai_normal.h
src/fheroes2/ai/normal/ai_normal_hero.cpp
src/fheroes2/ai/normal/ai_normal_kingdom.cpp
src/fheroes2/battle/battle_pathfinding.cpp
src/fheroes2/battle/battle_pathfinding.h
src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/kingdom/kingdom.h
src/fheroes2/maps/maps.cpp
src/fheroes2/world/world_pathfinding.cpp
src/fheroes2/world/world_pathfinding.h

AI path optimization: get things on the way to make sure hero have something to do once he reaches target.
General fixes to AI action object selection.

Hero AI: value objects on the way to target

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix OK button in joining army window

---

src/fheroes2/castle/mageguild.cpp
src/fheroes2/spell/spell.cpp
src/fheroes2/spell/spell.h
src/fheroes2/spell/spell_storage.cpp
src/fheroes2/spell/spell_storage.h

Give every magic guild a guaranteed damage and non-damage spell

---

src/fheroes2/dialog/dialog_arena.cpp
src/fheroes2/gui/text.cpp

Fix Knowledge message in arena

---

src/fheroes2/castle/buildinginfo.cpp

Always show building requirements even if the building is already built

---

src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/castle/castle_town.cpp

Spelling in castle dialog

---

src/fheroes2/game/game_mainmenu.cpp

Add game resolution popup window

---

src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/world/world.cpp
src/fheroes2/world/world.h

Fix #1866 
Center camera on eye and add delay for this event. Moved one-use function from world.cpp to heroes action.

Change Hut of the Magi behavior

---

.gitignore
src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_arena.h

Hello!
Please, review my PR for #117 
I couldn't find out what do magic numbers 8, 29, 73, 96 mean. If everything else is ok, i think it's worth making constants for them to increase readability.

Use hero spell power when applying Earthquake

---

src/fheroes2/battle/battle_interface.cpp

Fix redraw order for unit count

---

src/fheroes2/game/game_over.cpp

Add after play animation

---

src/fheroes2/battle/battle_interface.cpp

Fix troop counter window position

---

src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_building.cpp
src/fheroes2/castle/castle_dialog.cpp

relates to #2059
relates to #1310

Fix boat animation and castle building rendering

---

src/fheroes2/castle/castle_well.cpp

Fix town population status text position

---

src/fheroes2/castle/castle_town.cpp

Fix Hero's portrait in hiring window

---

src/fheroes2/heroes/heroes.cpp

Change Pyramid Bad Luck message

---

src/fheroes2/heroes/heroes_meeting.cpp

Fix Hero meeting screen title position

---

src/fheroes2/heroes/heroes_dialog.cpp

Fix Hero screen status bar message position

---

src/fheroes2/battle/battle_main.cpp

Give at least 1 skeleton via necromancy after victory

---

src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_gamearea.h
src/fheroes2/maps/maps_tiles.cpp

Speed up drawings for World Map

---

src/fheroes2/agg/agg.cpp
src/fheroes2/gui/interface_gamearea.cpp

Small optimizations by caching some data

---

src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/dialog/dialog_file.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/system/players.cpp
src/fheroes2/world/world.cpp

relates to #1342
and fix some compilation warnings

Fix lighthouse missing movement bonus

---

src/engine/image.cpp
src/fheroes2/castle/castle_building.cpp
src/fheroes2/game/game_interface.cpp
src/fheroes2/gui/interface_cpanel.cpp
src/fheroes2/gui/interface_radar.cpp
src/fheroes2/maps/maps_tiles.cpp

small speedups to make the game even faster

Code speedup and Blit function correction

---

src/fheroes2/heroes/heroes_move.cpp

Show boat froth sprite when stationary

---

src/fheroes2/ai/normal/ai_normal_battle.cpp
src/fheroes2/battle/battle_board.cpp
src/fheroes2/battle/battle_pathfinding.cpp

Refactored the offensive action logic so they will try to block multiple archers if possible.
Also fixed a flying unit bug that kept them from acting in some situations.

Battle AI: teach units to block enemy archers

---

src/fheroes2/ai/normal/ai_normal_kingdom.cpp

Caught a silly bug where AI would see a threat to a castle from wrong player army. This could lead to stunting castle growth.

Fix castle defense trigger condition

---

src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_building.cpp
src/fheroes2/castle/castle_dialog.cpp

also fixed crystal garden in Sorceress castle
relates to #2059

Add road connection drawings for Barbarian castle

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/ai/normal/ai_normal_hero.cpp
src/fheroes2/ai/normal/ai_normal_kingdom.cpp
src/fheroes2/army/army.cpp
src/fheroes2/army/army.h
src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle.h
src/fheroes2/castle/mageguild.cpp
src/fheroes2/castle/mageguild.h
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/skill.cpp
src/fheroes2/heroes/skill.h
src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/maps/mp2.cpp
src/fheroes2/resource/artifact.cpp
src/fheroes2/resource/artifact.h

Now we can evaluate and compare army reinforcements, castle buildings, heroes, skills, spells and artifacts to make more accurate strategic decisions in the future.
Taught AI heroes to exchange armies and artifacts.
Added a few additional validation checks to avoid heroes getting stuck on each other.
Made few improvements based on newly implemented tools (castle/hero priority for example).

Strategic AI: cooperating heroes and improved estimates

---

src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/heroes/heroes_spell.cpp

Fix boat summoning animation

---

src/fheroes2/castle/castle_building.cpp
src/fheroes2/castle/castle_dialog.cpp

Fix mage guild dialog message

---

src/fheroes2/agg/agg.cpp

Fix Cavalry sprite

---

src/fheroes2/heroes/heroes_action.cpp

Hi!
This one fixes #1971. There are also changes for inspections in corresponding funciton.

Play sound on shipwreck pickup

---

src/engine/smk_decoder.cpp
src/fheroes2/game/game_video.cpp

also don't show a message from smk library when a file doesn't exist

Speed up video loading

---

src/fheroes2/agg/agg.cpp

Fix few castle icons

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Fix Monster Info dialog in evil interface

---

src/fheroes2/battle/battle_cell.cpp
src/fheroes2/battle/battle_cell.h
src/fheroes2/battle/battle_interface.cpp

Fixes #2029 . One of the battle animation glitches that have been happening recently.

Fix glitched flying animation when unit has to turn to attack

---

src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle.h
src/fheroes2/heroes/heroes_spell.cpp

relates to #1184
special thanks to @ghostBot
Town Portal before:
Town Portal after:
@LeHerosInconnu could you please give your opinion as well?

Update Town Portal dialog

---

src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle.h
src/fheroes2/castle/castle_well.cpp

`RecruitBestAvailable` now able to dismiss the weakest monster in the garrison, improving average AI army quality.
Refactored RecruitMonster/RecruitMonsterFromDwelling functions to remove duplicated code; added extra validation and deleted unused function.

Improvements for castle monster recruitment

---

src/fheroes2/spell/spell_book.cpp

Fix missing spell point digits

---

src/fheroes2/agg/agg.cpp

Fix Sorceress castle background image

---

src/fheroes2/ai/ai_hero_action.cpp

fix changing boat direction by AI at boarding

---

src/fheroes2/ai/normal/ai_normal_kingdom.cpp

Fix a bug added during a recent review. Causes AI to not defend castles..

Fix enemy army threat check

---

src/fheroes2/agg/agg.cpp

Fix normal moral icon

---

src/engine/pal.cpp
src/engine/surface.cpp
src/engine/surface.h
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/heroes/heroes.cpp

Show hero's name in magic book related windows

---

src/fheroes2/heroes/heroes_meeting.cpp

close #1711
close #1712
close #1713
close #1714
close #1716
close #1717

Fix drawings for meeting hero dialog

---

src/fheroes2/battle/battle_interface.cpp

Fix battle false hex shadow

---

src/fheroes2/dialog/dialog_armyinfo.cpp

Add a title for joining army dialog

---

src/fheroes2/heroes/heroes_meeting.cpp

Fix primary skill frame color in hero meering dialog

---

src/fheroes2/dialog/dialog_selectscenario.cpp

relates to #1241
relates to #1243

Change map size popup window text

---

src/fheroes2/kingdom/kingdom.cpp

Place a hero into castle at the start of game

---

src/fheroes2/heroes/heroes_meeting.cpp

Assemble Battle Garb of Anduran artifact for hero meeting

---

src/fheroes2/heroes/heroes_action.cpp

Fix Alchemist Tower artifact manipulation logic

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h

Artesian spring logic

---

src/fheroes2/spell/spell_book.cpp

Fix spell order in magic book

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

Increase Meteor Shower spell animation

---

src/engine/audio_mixer.cpp

Remove last occurence of std::mem_fun_ref

---

src/fheroes2/dialog/dialog_settings.cpp
src/fheroes2/system/settings.cpp
src/fheroes2/system/settings.h

Remove "pocketpc: low memory" option

---

src/fheroes2/gui/interface_events.cpp

fix next hero focusing the first hero if used when the focus is on a castle

---

src/fheroes2/heroes/heroes_action.cpp

Crossing barrier (#2232)

---

src/fheroes2/battle/battle_interface.cpp

Armageddon spell is too powerfull. It crash the game with sigsegv while using.

fix stack overflow when using armageddon spell

---

src/fheroes2/castle/castle_town.cpp

Don't show army formation with no captain

---

src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h

Draw boat shadow (#1290)

---

src/fheroes2/game/game_startgame.cpp
src/fheroes2/gui/interface_buttons.cpp
src/fheroes2/gui/interface_buttons.h

Reset buttons when cursor move out (#387)

---

src/fheroes2/dialog/dialog.h
src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/kingdom/kingdom.cpp

Mine info dialog near hero (#2170)

---

src/fheroes2/kingdom/kingdom.cpp

Don't reset army while moving a hero to castle

---

src/fheroes2/game/game_over.cpp

Fix post game conditions

---

src/fheroes2/battle/battle_interface.cpp

fix battle log text layout

---

src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/maps/mp2.cpp

Fix for #2245, #2246, #1341, #1340 and #1339

Adventure map, Freeman's Foundry window, wrong title and wrong text

---

src/fheroes2/game/game_newgame.cpp

related issues #2241, #2243, #2244.
After:

fix layout for campaign selection window

---

src/fheroes2/army/army.cpp
src/fheroes2/army/army.h
src/fheroes2/castle/castle.cpp
src/fheroes2/castle/castle.h
src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/game/game.cpp
src/fheroes2/game/game.h
src/fheroes2/kingdom/kingdom.cpp
src/fheroes2/kingdom/kingdom.h

Solves #366.
Probably doing more than required for specifically this issue, but I think the changes to drawing the army monsters overall are needed so that I don't make almost identical functions for doing it based on thieves guild count

Enemy castle view based on Thieves Guild count

---

src/fheroes2/agg/agg.cpp
src/fheroes2/agg/icn.h
src/fheroes2/heroes/heroes_spell.cpp

"Town portal" spell window should have evil UI elements

---

src/engine/localevent.cpp

Use keypad Enter as a normal one

---

src/fheroes2/spell/spell_book.cpp

Add popup messages for next/previous pages

---

src/fheroes2/resource/artifact.cpp

Add missing Info word for artifact status bar

---

src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_arena.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h
src/fheroes2/battle/battle_main.cpp

Clear message log for retreat case

---

src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/heroes/heroes_dialog.cpp

Remove spaces for Level messages

---

src/fheroes2/dialog/dialog_armyinfo.cpp
src/fheroes2/dialog/dialog_levelup.cpp

Add a popup message for View Hero button

---

src/fheroes2/heroes/heroes_action.cpp

Fix Pyramid bad luck position

---

src/fheroes2/heroes/heroes_action.cpp

Adventure map, no sound should be played until the hero gets the artifact

---

src/fheroes2/gui/interface_list.h
src/fheroes2/kingdom/kingdom_overview.cpp

Fix castle and hero interaction with mouse in Kingdom Overview

---

src/fheroes2/heroes/heroes_action.cpp

Fix Wagon sounds

---

.github/workflows/osx_pull_request.yml
.github/workflows/osx_release.yml
.travis.yml
Makefile
src/Makefile
src/dist/Makefile

- add -Werror for SDL2 build;
- enable echoing for fheroes2 directory build. It's usefull for building linters and visual control.
related issue #2294

some improvements for Makefile

---

src/fheroes2/battle/battle_army.cpp
src/fheroes2/battle/battle_army.h

fix surrending cost

---

src/fheroes2/battle/battle_dialogs.cpp

resolve issue #2263 
Horizontal segment of shadow sprite has height 15.

fix shadow under battle summary dialog

---

src/fheroes2/battle/battle_dialogs.cpp

fix elements layout for surrending dialog

---

src/engine/localevent.cpp
src/engine/localevent.h
src/engine/screen.cpp
src/engine/screen.h

This pr was tested for SDL2 Linux build (with fake fullscreen).
relates to #1091
relates to #900

Fix rendering and mouse behavior for SDL2

---

src/fheroes2/castle/castle_tavern.cpp

Castle screen, Tavern window, wrong title color

---

.github/workflows/osx_pull_request.yml
.github/workflows/osx_release.yml

in a hope that GitHub Actions team fixed the issue

Simplify macOS builds

---

src/fheroes2/castle/castle_dialog.cpp

fix info for exit button at castle screen

---

src/fheroes2/dialog/dialog_armyinfo.cpp

fix joining message for 1 monster

---

src/fheroes2/heroes/heroes_spell.cpp

fix defect after close town portal dialog

---

src/engine/image.cpp
src/engine/image.h
src/fheroes2/heroes/heroes_meeting.cpp

fix graphic defect after exit meeting dialog

---

src/engine/image.h
src/fheroes2/agg/agg.cpp

Speed up generation of few images

---

src/fheroes2/heroes/heroes_spell.cpp

and also cache some calculations to be faster
close #2318

Fix incorrect town frames for evil town portal UI

---

src/fheroes2/dialog/dialog_quickinfo.cpp

Fix road penalty text

---

src/engine/sdlnet.cpp
src/engine/sdlnet.h
src/engine/serialize.cpp
src/engine/serialize.h
src/engine/tools.cpp
src/engine/types.h
src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_command.cpp
src/fheroes2/battle/battle_command.h
src/fheroes2/dialog/dialog_giftresources.cpp
src/fheroes2/dialog/dialog_guardian.cpp
src/fheroes2/dialog/dialog_marketplace.cpp
src/fheroes2/dialog/dialog_selectitems.cpp
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/maps/maps.cpp
src/fheroes2/maps/maps_tiles.cpp

The application then eats less memory

Do not use const reference for POD types

---

src/fheroes2/game/game.cpp
src/fheroes2/game/game.h
src/fheroes2/game/game_scenarioinfo.cpp
src/fheroes2/system/players.cpp
src/fheroes2/system/players.h

Keep random race (#265)

---

src/fheroes2/army/army.cpp

Previous version is failling because Assign() does nothing on empty Troops instance.
I also added comments about the behavior of this method

Fix Armmy::getReinforcementValue

---

src/fheroes2/game/game_over.cpp

Game doesn't show a message, when AI player was vanished

---

src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_move.cpp

Code improvement for `Heroes` class, added `Heroes::IsInROI` method

Implement IsInROI method for Heroes class

---

src/fheroes2/maps/mp2.cpp

Fix interaction with skeleton on map

---

src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/heroes/heroes_move.cpp

Fix empty castle capture behavior

---

src/fheroes2/dialog/dialog_marketplace.cpp

Disable gift button for a single player

---

src/fheroes2/game/game_interface.cpp

Ignore fog for dimension door

---

src/fheroes2/game/game_over.cpp

Fix singleplayer game conditions

---

src/fheroes2/battle/battle_arena.cpp

Fix Resurrect logic

---

src/fheroes2/dialog/dialog_skillinfo.cpp

Add an option to reveal secondary skill info by right click

---

src/fheroes2/army/army_troop.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/castle/buildinginfo.cpp
src/fheroes2/gui/interface_list.h
src/fheroes2/gui/splitter.cpp
src/fheroes2/gui/splitter.h

close #716
aslo fixed some compilation warnings

Implement smooth slider

---

src/fheroes2/heroes/heroes_dialog.cpp
src/fheroes2/resource/artifact.cpp

Fix Transcribing spell scrolls logic and UI

---

src/fheroes2/game/game_scenarioinfo.cpp
src/fheroes2/gui/player_info.cpp
src/fheroes2/gui/player_info.h

Fix a crash in multiplayer game selection

---

src/fheroes2/heroes/skill.cpp
src/fheroes2/heroes/skill.h
src/fheroes2/kingdom/kingdom_overview.cpp

Kingdom Overview screen, Towns/Castles Overview screen, wrong numbers displayed for heroes' primary skills

---

src/engine/image.cpp
src/engine/image.h
src/engine/localevent.h
src/fheroes2/agg/bin_info.h
src/fheroes2/agg/icn.cpp
src/fheroes2/agg/icn.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/dialog/dialog_selectitems.cpp
src/fheroes2/gui/interface_icons.h
src/fheroes2/gui/interface_itemsbar.h
src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h
src/fheroes2/maps/visit.cpp
src/fheroes2/resource/artifact_ultimate.h
src/fheroes2/world/world.h
src/fheroes2/world/world_pathfinding.cpp
src/fheroes2/world/world_regions.cpp

- compilation warning fixes
- reduce structure sizes
- optimize the code
- remove unused code

Code improvements

---

src/fheroes2/ai/ai_hero_action.cpp

Fix empty castle capture by AI

---

src/fheroes2/heroes/heroes_meeting.cpp

Fix meeting hero update after exiting hero's dialog

---

src/fheroes2/heroes/heroes_action.cpp

Fix impassable barrier

---

src/fheroes2/battle/battle_arena.h
src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/battle/battle_main.cpp

Show correct artifact transfer dialog after battle

---

src/fheroes2/game/game_startgame.cpp

Fix Hide interface reset issue

---

src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/skill.cpp

Make a proper calculation of movement points

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_interface.h

close #1494
close #1493
close #1490

Fix positions of monsters in battle

---

src/fheroes2/game/game_scenarioinfo.cpp

Fix Select button movement in Scenario window

---

src/fheroes2/dialog/dialog_quickinfo.cpp

Fix popup message for Abandoned Mine

---

src/fheroes2/heroes/heroes_spell.cpp
src/fheroes2/maps/maps.cpp

Fix Summon boat logic

---

src/fheroes2/game/game_startgame.cpp
src/fheroes2/heroes/heroes_spell.cpp
src/fheroes2/maps/maps_tiles.cpp
src/fheroes2/maps/maps_tiles.h

Fix Summon Boat animation

---

src/fheroes2/gui/interface_status.cpp

Fix cursor disappearance during resource collection on SDL 1

---

src/fheroes2/dialog/dialog_settings.cpp

Gray elements for inactive game settings

---

src/fheroes2/castle/castle_dialog.cpp

remove click area around "exit" button

---

src/fheroes2/heroes/heroes_spell.cpp

No monster attack using Dimension Door

---

src/fheroes2/army/army_bar.cpp

Solves #2389 (partially, just the shift part), and #2390.
Made a smaller PR because the changes needed for #2391 became much bigger than expected, so it's better if we can first ensure the smaller changes are working first.

Fix split logics for #2389 (partially) and #2390

---

src/fheroes2/dialog/dialog_armyinfo.cpp

related issues #1200, #1773, #1927

Fix elements' layout at monster info dialog

---

src/fheroes2/game/game_mainmenu.cpp

Add extra info in first game message about F4 key

---

src/engine/endian.h
src/engine/endian_h2.h
src/engine/serialize.cpp
src/engine/serialize.h

IO is independent from SDL now

Remove SDL dependency for IO classes (serialize.cpp)

---

src/fheroes2/gui/interface_list.h

Fix list scrolling by keyboard

---

src/fheroes2/battle/battle_board.cpp
src/fheroes2/battle/battle_board.h

Correct wide creatures back movement

---

src/engine/screen.cpp
src/engine/screen.h
src/fheroes2/gui/cursor.cpp

needed in order to support controllers properly

Add software emulation support for cursor

---

src/fheroes2/maps/maps.cpp
src/fheroes2/maps/maps.h
src/fheroes2/world/world.cpp

- removed unused method
- fix bug in GetObjectsPositions
- removed GetAllIndexes, replaced calling code with a method that
doesn't need to generate all tiles at each call

Cleanup maps file

---

src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_board.cpp
src/fheroes2/battle/battle_board.h

Fix path calculation for wide creatures

---

src/fheroes2/gui/interface_icons.cpp

Fix clickable area for Heroes and Castles in their lists

---

src/engine/localevent.cpp
src/engine/localevent.h
src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game_interface.cpp
src/fheroes2/game/game_interface.h
src/fheroes2/gui/ui_tool.cpp
src/fheroes2/gui/ui_tool.h

Add FPS display support

---

src/fheroes2/battle/battle_only.cpp
src/fheroes2/battle/battle_only.h
src/fheroes2/game/game_interface.cpp
src/fheroes2/game/game_interface.h
src/fheroes2/game/game_newgame.cpp

relates to #2122
and also some code cleanup

Fix Battle Only mode

---

src/Makefile.switch
src/engine/endian_h2.h
src/engine/system.cpp

Here's a minimal change set which allows the master branch to be built using devkitPro toolchain targeting Nintendo Switch. The build is currently non-playable due to the missing touchscreen/gamepad support, but there are pull requests already open for that.

Initial Nintendo Switch support

---

src/fheroes2/kingdom/kingdom.cpp

Add spells into Hero's book at the start of a map

---

src/fheroes2/castle/castle_town.cpp

fix income info click area at castle options window

---

src/fheroes2/battle/battle_board.cpp

Fix Hydra's movement during battle

---

fheroes2.vcxproj
src/engine/localevent.cpp
src/engine/localevent.h
src/engine/thread.cpp
src/engine/timing.cpp
src/engine/timing.h
src/fheroes2/game/game_delays.cpp
src/fheroes2/game/game_delays.h
src/fheroes2/gui/interface_gamearea.cpp
src/fheroes2/gui/interface_gamearea.h

More precise measurements - more stable game

Replace SDL Time by std time

---

src/engine/image.cpp
src/engine/image.h
src/engine/screen.cpp

Add support for pseudo-single images

---

src/fheroes2/castle/captain.cpp
src/fheroes2/castle/captain.h
src/fheroes2/gui/interface_border.cpp
src/fheroes2/gui/interface_icons.cpp
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h

Speed up interface drawings for World map

---

src/fheroes2/heroes/heroes_action.cpp

Fix empty enemy castle capture action

---

src/engine/math_base.h
src/engine/rect.cpp
src/engine/rect.h
src/fheroes2/battle/battle_interface.cpp

and also move slowly from old code structures

Fix Earthquake spell animation

---

src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game_newgame.cpp
src/fheroes2/game/game_over.cpp
src/fheroes2/game/game_video.cpp
src/fheroes2/game/game_video.h

Add Gold version support for video

---

src/fheroes2/dialog/dialog_thievesguild.cpp

Fix Player Rankings message bar

---

src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h

Always display the correct monster combat speed

---

src/engine/localevent.cpp
src/engine/timing.h

thanks @Northfear for pointing this out

Fix controller support

---

src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_only.cpp
src/fheroes2/castle/captain.cpp
src/fheroes2/castle/captain.h
src/fheroes2/castle/castle_dialog.cpp
src/fheroes2/dialog/dialog_guardian.cpp
src/fheroes2/dialog/dialog_quickinfo.cpp
src/fheroes2/dialog/dialog_selectcount.cpp
src/fheroes2/dialog/dialog_selectitems.cpp
src/fheroes2/dialog/dialog_spriteinfo.cpp
src/fheroes2/dialog/dialog_thievesguild.cpp
src/fheroes2/game/difficulty.cpp
src/fheroes2/gui/interface_cpanel.h
src/fheroes2/heroes/heroes.cpp
src/fheroes2/heroes/heroes.h
src/fheroes2/heroes/heroes_base.h
src/fheroes2/heroes/heroes_meeting.cpp

Fix multiple SonarCloud bugs

---

.github/workflows/scan-build.yml
src/fheroes2/agg/agg.cpp
src/fheroes2/ai/ai_hero_action.cpp
src/fheroes2/ai/normal/ai_normal_battle.cpp
src/fheroes2/battle/battle_action.cpp
src/fheroes2/battle/battle_bridge.cpp
src/fheroes2/battle/battle_catapult.cpp
src/fheroes2/battle/battle_dialogs.cpp
src/fheroes2/battle/battle_only.cpp
src/fheroes2/game/fheroes2.cpp
src/fheroes2/game/game_interface.cpp
src/fheroes2/game/game_newgame.cpp
src/fheroes2/gui/interface_events.cpp
src/fheroes2/gui/player_info.cpp
src/fheroes2/gui/text.cpp
src/fheroes2/heroes/heroes_action.cpp
src/fheroes2/heroes/heroes_indicator.cpp
src/fheroes2/maps/maps_fileinfo.cpp
src/fheroes2/maps/maps_tiles.cpp
src/thirdparty/libsmacker/smk_hufftree.c

Fix all scan-build warnings

---

src/fheroes2/gui/interface_events.cpp

Fix mouse cursor switching while navigating on hero or castle panel

---

src/fheroes2/heroes/heroes_meeting.cpp

Meeting screen, morale and luck sprites positioning

---

src/engine/screen.cpp

potential speed up for video cards with such support

Add palette support for SDL2

---

.travis.yml
src/Makefile
src/engine/rect.cpp
src/engine/tools.cpp
src/fheroes2/agg/bin_info.cpp
src/fheroes2/agg/bin_info.h
src/fheroes2/army/army.cpp
src/fheroes2/battle/battle_animation.cpp
src/fheroes2/battle/battle_animation.h
src/fheroes2/battle/battle_interface.cpp
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h
src/fheroes2/castle/castle.cpp
src/fheroes2/dialog/dialog_thievesguild.cpp
src/fheroes2/game/game_mainmenu.cpp
src/fheroes2/heroes/heroes_move.cpp
src/fheroes2/kingdom/kingdom.cpp

Add -Wfloat-conversion compilation flag

---

src/fheroes2/battle/battle_arena.cpp
src/fheroes2/battle/battle_arena.h
src/fheroes2/battle/battle_troop.cpp
src/fheroes2/battle/battle_troop.h

Bone Dragon morale malus shows in battle and in dialog window

---

.github/workflows/osx_pull_request.yml
.github/workflows/osx_release.yml
.github/workflows/scan-build.yml
.travis.yml
Makefile
README.md
src/Makefile
src/tools/Makefile

Make SDL2 as default option for makefile

---

src/fheroes2/battle/battle_interface.cpp

Fix object drawings on battlefield

---

src/fheroes2/battle/battle_interface.cpp

Display battle grid for whole battlefield

---

src/fheroes2/battle/battle_interface.cpp

Fix a log message when a tower kill one creature

---

src/fheroes2/battle/battle_interface.cpp

close #2190
close #1617
close #1505

Always draw troop counter at the top of monster sprites

---

src/fheroes2/battle/battle_dialogs.cpp

Hide Marketplace button for Surrender window

---

src/fheroes2/battle/battle_board.h
src/fheroes2/battle/battle_interface.cpp

Fix castle's battlefield drawings

---

src/fheroes2/battle/battle_dialogs.cpp

Fix marketplace button in Surrender window

---

src/fheroes2/game/game_io.cpp
src/fheroes2/gui/interface_events.cpp

Do not close File Save window while cancelling file overriding
