ihhub/fheroes2

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/castle/castle.cpp
close #6076
Also fix the `Army::ArrangeForWhirlpool()`: it seems that "weakest stack" for whirlpool should be selected based on the unit's battle value, not HP.
> Rework the troops arrangement mechanics for the castle defense

- src/fheroes2/gui/interface_gamearea.cpp
fix #6085
This was the regression after the #5692 - while reviewing, I forgot that when leaving the road, we still need to show a short "road arrow" even though the road penalty is not actually applied (it is applied only when moving from a road tile to a road tile), and I didn't notice that `tileTo` should be replaced by `tileFrom` in one more place (in fact, due to the "road issue" mentioned earlier, we don't need to use the `tileTo` at all).
> Draw the correct arrows for the paths on the adventure map

- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_focus.cpp
When loading a save file, the current focus was being overwritten by the first hero. This PR changes this default behavior.
closes #5898
> Don't overwrite focus on game load

- fheroes2-vs2017.vcxproj
- fheroes2-vs2019.vcxproj
- src/fheroes2/dialog/dialog_audio.cpp
- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_graphics_settings.cpp
- src/fheroes2/dialog/dialog_graphics_settings.h
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/dialog/dialog_system_options.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/gui/ui_option_item.cpp
- src/fheroes2/gui/ui_option_item.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
The new window includes resolution, fullscreen / windowed modes (very useful for devices with no keyboard support, relates to #6008), v-sync option and system information. Besides this this pull request does:
- update fresh start window text: the settings can be changed by pressing a button and remove F4 mentioning as it is not true for all devices
- standartize all options within every dialog: we were rendering text differently for some dialogs
- simplify code for popup windows
**Note**: names and sentences are subject of changes so feel free to proposed better ones.
> Add a separate graphics options window

- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
close #5298 & fix #1724
Added the ability to view quick info about the castle captain in the castle and quick info about the hero for the hero meeting dialog, hero recruit dialog, castle dilaog.
Have not made quick info for heroes in Thieves guid and in Oasis.
upd.:
Quick info for Recruit hero dialog is now without flags:
> Add right click quick info in more dialogs for hero and castle captain

- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
~~The idea is to calculate costs using the method in which the previous steps have more weight than the subsequent ones. However, this method has limitations, since the order of magnitude of costs increases significantly (at least when working with integers, because in this case the minimum coefficient for the previous steps (without rounding errors) is 2, so we have the 2^N coefficient for the first step after the Nth step). Using the `uint64_t` to represent the progressive costs, this method may be applied to at least a few dozens of initial steps in the path (for subsequent steps the regular summing algorithm will be applied to avoid the unsigned overflow), which should be enough for real applications, because on the next day hero paths will be recalculated anyway.~~
This approach …
> Adventure map pathfinding: minor optimizations

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
Previously the hero meeting flag was reset for cases when it was needed or it wasn't reset at all like after levelling up.
> Reset hero meeting flag every time if hero's strength has changed

- iwyu.map
Both `#include <cmath>` and `#include <cstdlib>` [should be fine](https://en.cppreference.com/w/cpp/numeric/math/abs) for the `std::abs()`. Before this PR, there was only alias for the `<cstdlib>`.
> IWYU: add <cmath> as another alias for std::abs()'s internal header

- docs/INSTALL.md
File naming scheme was changed after #6040, now they are in release, so we need to update the download links.
> Fix download links after 0.9.21

- src/fheroes2/battle/battle_tower.cpp
Follow-up to the #6173. Overlooked the opportunity to add `const` when refactoring old code.
> Tower::GetInfo(): add const

- src/fheroes2/castle/captain.cpp
- src/fheroes2/castle/castle.cpp
Close #6132 
This PR adds setting captain's Spell Points to max on map load for castles where the Captain's Quarters is already built and when building the Captain's Quarters in a castle. It also removes the pre-battle setting max Spell Points setting.
Since the intialization of 'captain' is different for random and non-random races, this operation cannot be performed in 'captain' class constructor and in the 'LoadDefaults' function.
> Update captain's mana on map load and when building the Captain's Quarters

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/army/army_ui_helper.cpp
- src/fheroes2/army/army_ui_helper.h
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/dialog/dialog_settings.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game.h
- src/fheroes2/gui/interface_status.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
Related to #6161
The previous logic was somewhat overcomplicated and confusing due to the need to focus on the scouting skill level in lots of places, I hope I didn't miss anything. It would be good to additionally test the new logic in different situations with artifacts that affect object info visibility (Crystal Ball?) to ensure that I didn't miss something in the mechanics.
> Remove the world: Scouting skill shows extended content info option

- iwyu.map
- src/engine/audio.cpp
- src/engine/localevent.cpp
- src/engine/localevent.h
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_hotkeys.h
Technically `SDLCALL` usually expands either to `__cdecl` or to an empty string, but not always. Also SDL_mixer 1.x doesn't require its callbacks to be `SDLCALL`, while SDL_mixer 2.x does.
Also I noticed that `SDL_SetEventFilter()` is used. Please do not ever use it - as rightly [stated in the documentation](https://wiki.libsdl.org/SDL_SetEventFilter), the callback function set by `SDL_SetEventFilter()` has the same issues as any other SDL callbacks - it might be called from an internal SDL thread! (remember SDL_mixer callbacks). So we can't reliably use it to redraw software cursor or switch the fullscreen mode. The only thing you can do safely in it is filter an event out from the event queue by returning 0, that's what this function is designed for. You can't access or alter any …
> Add SDLCALL to callbacks used by SDL, remove the SDL_SetEventFilter()

- src/engine/tools.cpp
- src/engine/tools.h
- src/fheroes2/battle/battle_interface.cpp
close #6079 
I changed the catapult stone trajectory calculation function to calculate a ballistic parabolic trajectory:
https://user-images.githubusercontent.com/113276641/201529496-6eb15855-f046-44c3-97c7-4de6194c04b6.mp4
It calculates the porabolic trajectory for the same target height as the height of the catapult. And for aiming at a specific target, a linear trajectory has been added.
PS
There is one more issue left (not fixed in this PR): the wall (or tower) disappears (destroys) only after the smoke animation, and should disapper in the middle of this animation.
I can call `break;` in the middle of the smoke cloud animation and call a new function to end the smoke animation after the wall is set to destroyed state. But this will duplicate the smoke animation code and I don't think …
> Use parabolic catapult projectile flight trajectory

- src/engine/core.cpp
- src/engine/localevent.cpp
- src/engine/localevent.h
- src/engine/screen.cpp
- src/engine/screen.h
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/system/settings.cpp
The current implementation of SDL events is a complete mess. We do not even handle most of events and these should be disabled to avoid extra processing. Proper separation of SDL1 and SDL 2 allows us to support the code without mind-bending hacks. The place where initialization of event types is initiated should be within core initialization code as it belongs there.
Moreover, I fixed the place where we update cursor before we even initialize the system.
> Rework SDL events handling

- src/fheroes2/dialog/dialog_system_options.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
Make it as an option. Also change magic values of scrolling into more human readable strings.
> Disable Adventure Map scrolling for handheld devices by default

- src/engine/dir.cpp
- src/engine/logging.cpp
- src/engine/logging.h
- src/engine/rand.cpp
- src/engine/system.cpp
- src/engine/system.h
- src/fheroes2/audio/audio_manager.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_io.cpp
- src/fheroes2/game/game_video.cpp
- src/fheroes2/h2d/h2d.cpp
- src/fheroes2/system/save_format_version.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
- src/fheroes2/world/world.cpp
- src/tools/extractor.cpp
- src/tools/icn2img.cpp
- src/tools/til2img.cpp
While I'm here:
1. `System::MakeDirectory()` returned 1 (`true`) on Windows, but 0 (`false`) on other systems upon successful directory creation;
2. `System::Unlink()` returned 0 upon successful file/directory removal, which was counterintuitive;
3. Renamed `ConcatePath()` to `concatPath()` (I've been dreaming of doing this for a long time);
4. Fixed an issue that caused `fheroes2.log` not to be created when the game was started for the first time;
5. `System::GetConfigDirectory()`, `System::GetDataDirectory()`: use the current directory as a fallback instead of an empty string. The previous behavior leads to attempts to create a log file, config file, etc. in the root directory, which is hopeless.
6. `GetDirname()` was not quite POSIX-compliant:
| Argument | Old `GetDirname()` | POSIX …
> Fix multiple issues with auxiliary functions from the engine

- .github/workflows/iwyu.yml
- iwyu.map
- src/fheroes2/agg/bin_info.h
- src/fheroes2/monster/monster_info.h
- src/fheroes2/resource/artifact_info.cpp
- src/fheroes2/resource/artifact_info.h
Fix migration of Ubuntu 22.04 image from 20221027.1 to 20221119.2 with the newer compiler.
See [this run](https://github.com/ihhub/fheroes2/actions/runs/3525606072/jobs/5912534513) and [this comment](https://github.com/ihhub/fheroes2/pull/5983#issuecomment-1324094001) for details.
> iwyu.map: add new private header mappings for newer Ubuntu image version, speed up IWYU workflow a bit

- android/app/build.gradle
Related to #6008
* Apache commons-io 2.11.0 did not work with Android 6 due to the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.fheroes2, PID: 8710
java.lang.NoClassDefFoundError: org.apache.commons.io.IOUtils$$ExternalSyntheticLambda2
at org.apache.commons.io.IOUtils.<clinit>(IOUtils.java:183)
at org.fheroes2.MainActivity.extractAssets(MainActivity.java:86)
at org.fheroes2.MainActivity.onCreate(MainActivity.java:40)
at android.app.Activity.performCreate(Activity.java:6309)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2530)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
at …
```
> Set the minimum supported version to Android 6.0

- .github/workflows/android.yml
- .github/workflows/clang_analyzer.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/clang_tidy_comments.yml
- .github/workflows/cmake.yml
- .github/workflows/code_style_check.yml
- .github/workflows/iwyu.yml
- .github/workflows/make.yml
- .github/workflows/msvc.yml
- .github/workflows/pr_author_auto_assign.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/translation_update.yml
The reason for this change is as follows: while `bash` is in fact used on *nix OS images if shell is not specified, it is [used with relaxed parameters ](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell)that doesn't include `-o pipefail`. I was forced to add `set -o pipefail` in place, which is actually unreliable and may be overlooked or forgotten.
> Use explicit shell: bash in GitHub Actions scripts

- files/lang/Makefile
- src/fheroes2/agg/agg_image.cpp
Due to changes from this PR https://github.com/ihhub/fheroes2/pull/6056 when you have the French original assets you will not get the French special characters.
In addition while I was at it I added support for Italian characters too.
> Fix French and Italian characters not being shown with their assets

- script/android/install_packages.bat
- script/android/install_packages.sh
- script/windows/install_packages.bat
Update details: https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/23. Nothing critical, no updates for libs - I'll delay them until the 1.0 will be released.
> Update the dependency package hashes for Android & Windows

- src/engine/audio.cpp
- src/engine/localevent.cpp
- src/engine/localevent.h
- src/engine/screen.cpp
- src/engine/screen.h
- src/engine/timing.cpp
- src/engine/timing.h
- src/engine/tools.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/gui/cursor.cpp
- src/fheroes2/gui/cursor.h
In the global event loop we have 2 sources of performance drops:
- sleep event which is executed if no immediate return from events is required and no color cycling event occurs
- call of rendering when mouse or touchscreen position changes with cursor software rendering option being on. Mouse and touchscreen events can occur multiple times per single global event loop function call.
These 2 places connect to each other leading to obvious slowdowns with enabled V-Sync option. The correct way is to check whether sleeping is allowed. If it is not then we shouldn't render within the global event loop but only update rendering area for the upcoming rendering event outside the loop. If there is a time to sleep we should render only once.
close #6252
> Improve rendering speed with software cursor rendering

- src/fheroes2/gui/ui_font.cpp
- src/fheroes2/gui/ui_language.cpp
- src/fheroes2/gui/ui_language.h
This adds Danish as an option and includes it in the CP1252 font.
Relates to https://github.com/ihhub/fheroes2/pull/6237
> Add Danish language option and font

- README.md
- docs/README.md
LGTM will shut down in December 2022.
The social networks are sorted according to their appearance in the text above.
> Remove LGTM badge and minor adjustments to the frontpage

- VisualStudio/Debug.props
Follow-up to #6267
There is no need to define `_DEBUG` by hand because it's [automatically defined](https://learn.microsoft.com/en-us/cpp/c-runtime-library/debug?view=msvc-170) when we set the `RuntimeLibrary` to any of the debug versions, which is what we are doing one line above.
> MSVC: do not define _DEBUG by hand

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
In addition to #6216: made generation of two hexagon shadows.
- shadow that fits the grid
-  shadow with 3px space between hexagons for use without grid
(Cursor shadow size is set to fit the grid.)
> Hexagon shading improvement (Battlefield)

- src/engine/screen.cpp
- src/engine/screen.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
With introduction of "fake" full screen mode for Windows it is visible that the picture is blurred with linear mode. To cover needs of everyone we are adding a new configuration option to choose pixelated image or blurred. By default it is linear.
relates to #5373
relates to #2238
relates to #4946
> Make an option to toggle screen scaling type

- src/fheroes2/battle/battle_interface.cpp
> Fix incorrect cursor shadow position at the creature's turn start

- .github/workflows/msvc.yml
- docs/README.txt
- script/windows/fheroes2.iss
Related to #6276
I also switched this workflow from Cygwin to the pre-installed MSYS2, this somewhat accelerated the build - from 6-8 minutes to 4-6 minutes.
I have a few notes though:
1. ~We download the redistributable package installer [from the MS website](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) via a permalink without any verification. Hash verification is useless here, because we don't control "the other side" and I suspect that there will be silent regular updates for that package, but maybe we can use at least the digital signature verification. We can try to figure this out.~ Implemented the mandatory signature verification using the `signtool.exe`.
2. ~When `vcredist.exe` updates libraries in `SYSTEM32`, Inno Setup detects this and …
> Install the latest Microsoft Visual C++ Redistributable package using Inno Setup

- src/fheroes2/gui/ui_text.cpp
close #6288
relates to #6165 
before: ![translation 1](https://user-images.githubusercontent.com/113276641/205437205-78ae717f-bd1c-4983-9fe1-0873781e5e75.png)   after: ![translation 2](https://user-images.githubusercontent.com/113276641/205454069-52e98e00-c422-4416-9181-0f10e3dd6a50.png)
> Fix multiline word splitting for short phrases with a long first word

- src/engine/image.cpp
- src/fheroes2/maps/maps_tiles.cpp
`redrawBottomLayerObjects()` method is called a lot of times while rendering a frame of Adventure Map. Using a container based on heap memory is not an optimal from performance point of view approach.
Also fix incorrect logic for `Blit()` and `AlphaBlit()` functions where we might read invalid data.
> Avoid using memory on heap for rendering methods

- src/fheroes2/game/game_interface.cpp
- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_gamearea.cpp
We were generating but not rendering multiple frames of Adventure Map while a hero was moving. This was a waste of resources by doing nothing from the perspective of players. This change is not ideal as I wanted to avoid making heavy changes. Also the change should potentially reduce fluctuations in FPS as these "extra" frames were rendered only when a hero moves to another tile.
Looks like we have exactly the same problem for Adventure Map rendering like we did for localevent: too many useless rendering calls. To prove it I cite a message from Discord about performance drop on PS Vita:
```
30% is just during map scrolling. Performance drop during hero movement on the world map is closer to 50%-55%
```
which means that we really do something extra while a hero is moving.
> Do not draw multiple frames of Adventure Map

- src/fheroes2/dialog/dialog_armyinfo.cpp
fix #6323
Looks like the regression after #5671.
> Display the amount of gold in the diplomacy dialog

- src/fheroes2/battle/battle_interface.cpp
close #5764
The problem was that the SetPosition method makes a copy of the image part where the popup image will be placed. After drawing the popup, this part of the image is recovered. And sometimes, when the creature moves, this recovery occurs before drawing a new popup.
Since the battlefield is dynamically updated, the restored part does not always correspond to the current state of the battlefield.
The change in the drawing method (made in this PR) caused the part of the popup that was outside the battlefield image to remain permanently. So now it is always displayed inside the battlefield.
> Fix incorrect battlefield image restoration in the place of the previous damage popup

- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/dialog/dialog_audio.cpp
- src/fheroes2/dialog/dialog_game_settings.cpp
- src/fheroes2/dialog/dialog_graphics_settings.cpp
- src/fheroes2/dialog/dialog_system_options.cpp
- src/fheroes2/gui/ui_option_item.cpp
- src/fheroes2/gui/ui_option_item.h
The settings dialogs have different spacing between elements: in audio and graphics settings there is more space than in other configuration dialogs. So for these two dialogs the maximum text width can be set higher to allow use of longer phrases (especially for translations).
This PR adds the ability to set per element (per icon) the maximum text width for configuration dialogs. In this PR maximum width is set to `( distance_between_elements - 5px )`.
> Add the ability to set the maximum text width for each icon in settings dialogs

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_status.cpp
- src/fheroes2/gui/interface_status.h
If AI movement is not shown or AI heroes are hidden by fog Adventure Map is not updated so all objects become frozen. The changes allow to continue animation of objects for such cases.
Progress bar for AI turn is updated based on heroes' turns. It also renders when Adventure Map objects require an update so we do not waste time for rendering a frame just to indicate some progress and then few nanoseconds later we do the same.
> Do not stop object animation during AI turn

- src/engine/audio.cpp
As mentioned in the [documentation](https://wiki.libsdl.org/SDL_mixer/Mix_Volume), the default volume for the newly allocated channels is `MIX_MAX_VOLUME`. We should remember the correct volume for the newly allocated channels when audio is muted, otherwise there is a discrepancy in behavior when audio is muted and when it is not muted.
There was the correct logic initially, but it was changed for some reason in #5486.
> The newly allocated channels have a default volume of MIX_MAX_VOLUME

- src/fheroes2/ai/normal/ai_normal_hero.cpp
Plus AI heroes shouldn't waste last resources for a level up in Tree of Knowledge.
> Reduce priority for bottles in sea for AI

- src/fheroes2/battle/battle_interface.cpp
close #6343 
The rainbow endpoint calculation now uses 'width' and 'height' from the `GetRectPosition()` method.
> Fix rainbow endpoint calculation (Battlefield)

- src/fheroes2/battle/battle_animation.cpp
- src/fheroes2/battle/battle_animation.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
- src/fheroes2/monster/monster_anim.h
Close #5701 and close #1041.
Relates to #1229.
Redone the animation sequence for Death Wave, Death Ripple, Holy Word and Holy Shout shout.
Now the flame animation (after the spell animation) is made only after applying damage from the spell. And during this flame animation the death animation and the wince animation is applied to the corresponding creatures.
To do this I had to make a copy of part of the code from `RedrawActionWincesKills` method. :(
To reduce the size of this duplication a new (small) method was made.
fheroes2 Death Death Ripple and Death Wave animations:
https://user-images.githubusercontent.com/113276641/206888610-90a2e068-487d-49cc-9e8a-469f80a587c5.mp4
Original game Death Ripple and Death Wave animations:
https://user-images.githubusercontent.com/113276641/206887219-4 …
> Death Wave spell animation fix (Battlefield)

- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/campaign/campaign_scenariodata.h
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/ui_campaign.cpp
- src/fheroes2/gui/ui_castle.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/system/save_format_version.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/world/world_loadmap.cpp
fix #6027
Currently (before this PR) campaign bonuses and awards are applied to the "best hero of the kingdom", which usually means "hero with the most powerful army". This PR introduces some sort of "infrastructure" to set the specific hero to get these bonuses & awards (with the fallback to the old behavior if no hero specified or found). After a quick run through the campaigns I found the following places (and fixed these places in this PR):
* Roland's campaign, mission "Defender" - there are two heroes, and Sorceress should get the bonus spell;
* Roland's campaign, mission "Final Justice" - there are multiple heroes, and Roland should get the bonus artifact, as well as army from "The Gauntlet";
* Archibald's campaign, mission "Apocalypse" - there are multiple heroes, and Archibald …
> Implement the infrastructure to apply campaign bonuses and awards to a specific hero, multiple campaign-related fixes

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game.h
- src/fheroes2/game/game_interface.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_status.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/maps/maps_tiles.cpp
This is a leftover code and regression from #6319 which was forgotten to be addressed:
- do not update progress status for AI if it isn't changed. Every movement for hero was updating the status bar
- remove one extra frame rendering upon calling `DrawAITurnProgress()` method
- code cleanup to avoid weird reference increment code
> Fix extra frame rendering for status update during AI turn

- src/fheroes2/dialog/dialog_marketplace.cpp
The problem was that the `buttonTrade` was always interpreted as `isEnabled()`.
Fix #6369
> Disable Trade button in Marketplace when appropriate

- src/fheroes2/battle/battle_dialogs.cpp
Added enough slack for neither the attacker's nor defender's row of monsters to ever vertically overlap with either text label. This is probably as good as it gets without shuffling the other labels around.
> [#5240] Adjusted "Battlefield Casualties" vertical position of MonsterLines.

- src/fheroes2/maps/maps_tiles_quantity.cpp
close #6393
This change must be thoughtfully tested on many maps to make sure that we don't break anything. The test scope should be done on maps with "bad" resources as well as any normal resources.
> Fix incorrect resource placements on certain maps

- .github/workflows/make.yml
- docs/INSTALL.md
Because now we have ARM64 builds.
Hi @ihhub could you please postpone the release creation until this PR will be merged since the names of x86-64 linux ZIP archives have been changed?
> Add links to download the ARM64 Linux build, distinguish the archive names between x86-64 and ARM64

- src/engine/screen.cpp
- avoid calling **copyImageToSurface()** within `render()` method if it's not necessary (use side-by-side comparison to see that the code is mostly untouched)
- use `SDL_SetRenderTarget()` function only once as we don't change the destination of rendering
- find the most suitable driver as the first driver might not be the correct one (never happened before but just in case)
> Update SDL 2 rendering code

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
Reworked the rendering of the Death Wave spell effect. Now the game only renders the part of the screen where the effect is located.
Also in this PR before the spell effect, all creatures are now forced to stop their `IDLE` animation and their unit counter is now turned off, as it is not so aesthetic when the creature freezes in some `IDLE` pose during the spell animation and when the unit counters, that are part of the user interface , are distorted by the spell. The same applies to the Holy Shout spell.
<details><summary>A video of the Death Wave spell effect</summary>
https://user-images.githubusercontent.com/113276641/209446836-30a4f65d-3acd-4739-ba2d-0040ca8fde31.mp4
</details>
> Optimize Death Wave spell effect rendering. Battlefield.

- script/tools/check_copyright_headers.py
Improved support of command line arguments. It allows to simplify future changes and adds auto formatting of usage messages.
Now error message will look like this:
```
usage: check_copyright_headers.py [-h] full_header_file header_template_file source_file [source_file ...]
check_copyright_headers.py: error: the following arguments are required: full_header_file, header_template_file, source_file
```
> Better support of commandline arguments to check_copyright_headers

- src/fheroes2/battle/battle_troop.cpp
close #6399
It seems that the problem was that while creature does its non `STATIC`/`IDLE` animation (attack, wince, moving) the delay till the next `IDLE` animation passes and after switching to `STATIC` animation the game automatically switches the creature to `IDLE` animation. So the creature could start its `IDLE` animation after wince, instead if `STATIC`, which changes to attack animation in the middle of `IDLE`.
> Fix forced IDLE animation after switching to STATIC animation. (Battlefield)

- src/fheroes2/maps/maps_tiles_quantity.cpp
close #6378
We were comparing `objectTileset` with value 48 which is not true for all cases as first 2 bits of this value do not belong to tileset.
> Fix incorrect logic for monster placement on Adventure Map

- src/engine/system.cpp
fix #6434
Previous implementation always added `./` to the beginning of relative paths, even if they already begin with `./`, which was TECHICALLY correct (because `MUSIC`, `./MUSIC` and `././MUSIC` are in fact the same paths), but the logic of `findMusicFile()` in the `audio_manager.cpp` compares paths literally, so it was not able to find the music file.
> System::GetCaseInsensitivePath(): remove the addition of an extra "./" for relative paths

- .github/workflows/translation_update.yml
- script/android/install_packages.sh
- script/demo/download_demo_version.sh
- script/homm2/extract_homm2_resources.sh
On certain systems (including the modern macOS versions) there may be only `python3` binary available.
> extract_homm2_resources.sh: detect multiple Python versions

- src/fheroes2/dialog/dialog_language_selection.cpp
close #6445
Do not call `setGameLanguage` on every loop, do it only if `chosenLanguage` was changed.
> Reduce CPU usage in Select Language dialog

- changelog.txt
- script/packaging/common/fheroes2.appdata.xml
- script/tools/changelog_update_appdata.py
Script for parsing the `changelog.txt` into `*.appdata.xml`. Copies the whole changlog (except the oldest entry) in the appdata.xml.
Appdata can be updated after changelog update by executing `python3 script/tools/changelog_update_appdata.py changelog.txt script/packaging/common/fheroes2.appdata.xml`.
@ihhub Do you think that's a good idea, or should we rather discard it?
Furthermore I have also added the donate link.
Changelogs looks like this in the software center (sorry for german):
> Changelog in appdata.xml

- docs/INSTALL.md
After going through the installation process for MacOS, I wanted to contribute some installation pointers back to the docs. This PR addresses
* ensuring that every Mac installation path includes the last step of gathering game resources
* adding a link to a helpful library to open a self-extracting exe without having to install Windows emulation software on a unix-based machine
* can also add this to the linux instructions, should I also create a similar section there?
* adding the path to the scripts when using the homebrew installation for Mac
> Streamlining MacOS installation instructions

- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/maps/mp2.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
This is a preparation step towards building the future Editor. Right now the code related to object loading and handling on Adventure Map is a complete mess. This pull request is targeted to cleanup the code and make it more or less readable. The list of changes:
- rename `uniq, level, object and index` of **TilesAddon** structure and `uniq, objectTileset, objectIndex and _level` of class **Tiles** into `_uid, _layerType, _objectType and _imageIndex` to have the same member names as these variables are exactly the same for both classes. In the future class **Tiles** will have only one stack of objects.
- add **ObjectIcnType** enumeration and replace many hardcoded values by entries from the enumeration
- add multiple TODO comments for the future changes (I wanted to keep this pull request …
> Prepare code for the future Editor

- src/fheroes2/battle/battle_interface.cpp
Reverted the hiding the unit counters before Death Wave or Holy Shout spells animation made in #6413.
> Revert the unit counter display while Death Wave or Holy Shout spell effect animation. Battlefield.

- src/engine/timing.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/dialog/dialog_recruit.cpp
- src/fheroes2/game/game_credits.cpp
- src/fheroes2/game/game_delays.cpp
- src/fheroes2/game/game_delays.h
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/game_interface.cpp
- src/fheroes2/game/game_logo.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_video.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/ui_tool.cpp
- all event loops during battle animations did not check whether it is allowed to do rendering within handle event loop
- custom delays were not reset properly causing slight delays in first frame to be rendered. Video playback was affected the most
- avoid excessive rendering for multiple windows. Render only the area which was changed
- add todo comments for the future changes
- some animations during battle did not play the last frame like monster animation, hero's animation and hero's flag animation
- small code cleanup
> Optimize multiple places for rendering

- sonar-project.properties
Currently SonarCloud [fails the analysis](https://github.com/ihhub/fheroes2/actions/runs/3842572586/jobs/6544128440) because project now includes multiple Java files (for Android) and they are not compiled in the SonarCloud workflow. While in theory we can try to build Android project for SonarCloud, this means that we will not build some other parts of the project (for example, tools), and also this will be slower than just build the Linux project, so I decided to just exclude Java files from SonarCloud analysis.
> Exclude Java files from SonarCloud analysis

- src/fheroes2/battle/battle_bridge.cpp
- src/fheroes2/battle/battle_bridge.h
fix #6471
Also make the cell enum naming more uniform.
Before this PR:
https://user-images.githubusercontent.com/32623900/211209379-c29388e7-209c-42e8-ab93-79211d30dfc8.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/211209393-df7cf67e-78f4-4f0e-82e2-e5c30fb758cc.mp4
In OG:
https://user-images.githubusercontent.com/32623900/211211064-bc21a864-28d3-4fbd-a887-e43fb1942d9d.mp4
> Fix the bridge operation when a wide friendly unit steps on it from the moat

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/interface_gamearea.h
Currently, when you start dragging the adventure map with the mouse, the engine starts to render the adventure map and radar continuously, even if the mouse is not moving.
This PR makes that the requests for rendering (`isDragScroll()`) are set only if the map is moved with the mouse.
> Removed redundant redraws when dragging an adventure map with the mouse

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/maps/mp2.h
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
- convert Thatched Hut into Peasant Hut as this is exactly the same object, only different names. Moreover, when a Peasant Hut was marked as Thatched Hut no sounds appear from this dwelling on Adventure Map
- remap PoL objects to follow the same logic as other objects
- simplify many places for logic, in some functions sort objects per their names
- add Mossy Rock object which appears only on Swamp terrain. In the original game this object has no name but it has passability as any terrain non-action object
> Finalize object tile types

- src/fheroes2/battle/battle_interface.cpp
close #6482
I changed the logic for checking that Lich cloud animation is finished.
> Fix an infinite loop in the RedrawActionWincesKills() on Lich attack

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_army.h
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
- src/fheroes2/battle/battle_cell.cpp
- src/fheroes2/battle/battle_cell.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_pathfinding.cpp
- src/fheroes2/battle/battle_pathfinding.h
- src/fheroes2/battle/battle_troop.h
close #6291
<details>
<summary>Issue from #6291</summary>
https://user-images.githubusercontent.com/32623900/211691123-993c013c-1ddf-400d-8ab9-98d5372d2d95.mp4
This PR:
https://user-images.githubusercontent.com/32623900/211688066-6eca86c3-2d1d-4216-a71a-06ff6f6c9b32.mp4
https://user-images.githubusercontent.com/32623900/211687971-377623be-02d0-46c5-a5a3-38b389674a9c.mp4
</details>
<details>
<summary>Famous issue with wide units retreating one step back diagonally</summary>
https://user-images.githubusercontent.com/32623900/211690219-2ef3687f-9a8e-4a7a-bc1b-82503464c8a8.mp4
This PR:
https://user-images.githubusercontent.com/32623900/211688089-e640f2db-2d39-4f44-b886-425062ddc225.mp4
https://user-images.githubusercontent.com/32623900/211688110-7712c9a2-1cfc- …
> Rework the battle pathfinding

- .github/workflows/sonarcloud.yml
- sonar-project.properties
Speed up the analysis, because now we do not need to perform a full build beforehand.
> SonarCloud: use the compile_commands.json instead of build wrapper

- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
Players should not rename maps as they want. If people want to play PoL maps they must own this version of the game.
This is a very basic check but it works on most of maps.
relates to #6047
> Add checks to identify MX2 being loaded as MP2

- script/packaging/common/fheroes2.appdata.xml
Fix small error which which prevents the successful build process of flatpak.
I have also added all three links.
See here: https://github.com/flathub/io.github.ihhub.Fheroes2/pull/16
> [Fix] Appdata: correct & extend donation link

- src/fheroes2/battle/battle_pathfinding.cpp
* Don't call redundant `operator=()`;
* In C++17 `operator[]()` is [guaranteed](https://en.cppreference.com/w/cpp/container/unordered_map/operator_at) to be the same as the `try_emplace().first->second`, but the former looks shorter.
> BattlePathfinder::evaluateForUnit(): minor polishing

- src/fheroes2/gui/interface_events.cpp
- the change for the original issue is to add `!ultimateArtifact.isFound()` condition (close #6486)
- `EventDigArtifact()` method's code restructure to avoid nested if-conditions
- replace **Dialog::Message()** calls with **fheroes2::showStandardTextMessage()** as a part of migration to the new text related code
> Do not allow to dig for Ultimate Artifact second time

- src/fheroes2/battle/battle_interface.cpp
close #6465 
This PR fixes the after attack (melee or distance) animation.
Before this PR the engine did the change of the current frame to the next one (or changed the animation if it is finished) and then made a render. Now it first renders and then changes the frame/animation.
Also in this PR the redundant check for need of render at the start of the loop was removed as it is checked at the end of the loop.
> Fix loss of the first frame in the after attack unit animation. Battlefield.

- src/fheroes2/castle/castle.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps_objects.cpp
- src/fheroes2/maps/maps_objects.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/maps/mp2.h
- src/fheroes2/resource/resource.cpp
- src/fheroes2/resource/resource.h
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
- remove **mp2riddle_t** structure and add appropriate comments into `MapSphinx::LoadFromMP2()` method
- rename **_objectType** member into **_objectIcnType** and make it as `MP2::ObjectIcnType` to avoid confusion from `MapObjectType` enumeration
- move multiple static methods from `Tiles` class into anonymous namespace to reduce the complexity of the class
- rename **mp2_object** member of `Tiles` class into **_mainObjectType** to make it clear what it is
- rename all **tileset** usages into **objectIcnType**
- remove all usages of bitwise shift operations on objectIcnTypes (except where we read data from an MP2 file). This was an ultimate goal of the changes as the code was a complete mess and not sustainable to be supported
- fix multiple compilation warnings
~~- add …
> Rework the way how object ICN types are used

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
- src/fheroes2/battle/battle_cell.cpp
- src/fheroes2/battle/battle_cell.h
- src/fheroes2/battle/battle_pathfinding.cpp
- src/fheroes2/battle/battle_pathfinding.h
- src/fheroes2/battle/battle_tower.h
- src/fheroes2/maps/maps.h
Related to #6527
Currently battle pathfinding cache is built once per turn (well, not quite, but close enough) for the particular "current" unit (the one whose turn has come). This is inconvenient in cases where you need to quickly recalculate the cache for another arbitrary unit, so with this PR cache will be rebuilt on demand.
> Rebuild the battle pathfinding cache dynamically if necessary

- src/fheroes2/game/game_io.cpp
We should not allow to do that as some objects will be absent on the Adventure Map.
relates to #6047
> Do not allow to load saves from a PoL map if PoL expansion isn't present

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/agg/bin_info.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_interface.cpp
This PR adds using of sprite `x` and `y` data to adjust the projectile render position.
This PR:
https://user-images.githubusercontent.com/113276641/212488158-278cb45b-7ef7-4621-bdd8-8a3344753733.mp4
<details><summary>Video of shooting from right to left</summary>
https://user-images.githubusercontent.com/113276641/212488789-0af4edb0-838e-4d60-bfe4-96c51a92dd6c.mp4
</details>
Currently in fheroes2 the archers arrows are shifted in direction from archers so the last animation frame renders the arrow behind the target:
<details><summary>Video</summary>
https://user-images.githubusercontent.com/113276641/212488176-d472dc9f-62e1-4127-8549-61231bfb18d1.mp4
</details>
> Fix shooters projectile position. Battlefield.

- docs/README_PSV.md
- src/engine/localevent.cpp
- src/engine/localevent.h
- src/engine/screen.cpp
Bunch of fixes related to PS Vita
- Disabled rear touchpad
- Added gamepad mapping for cursor speedup
- Fixed fullscreen/windowed toggle in display options
> PS Vita fixes and gamepad mapping improvements

- src/fheroes2/agg/bin_info.cpp
Relates to #6491
<details><summary>
_Originally posted by @Branikolog:
</summary>
https://github.com/ihhub/fheroes2/issues/6491#issuecomment-1410243613
Every creature except druids seem to have proper projectile animation now.
Issue is valid only for such shooting angle:
https://user-images.githubusercontent.com/55348946/215755877-2c450ab1-558c-4699-81b6-10f73a7aabdd.mp4
</details>
This PR:
https://user-images.githubusercontent.com/113276641/215776135-b895a0a2-08e8-4b7d-acf5-3613d4595c09.mp4
> Fix Druid projectile start position for shooting up (Battlefield)

- src/fheroes2/gui/ui_font.cpp
relates to #6335
This PR makes Cyrillic characters more narrow to be able to write long words on buttons.
But some buttons are still narrow for the translated words :(
Suggestions and comments are welcome.
Language file with alphabet in first two main menu buttons: [ru.zip](https://github.com/ihhub/fheroes2/files/10501113/ru.zip)
> Make a narrower button font for cp-1251 (Cyrillic) characters

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
- android/app/src/main/res/layout/activity_save_file_manager.xml
- android/app/src/main/res/layout/activity_toolset.xml
- android/app/src/main/res/values-de/strings.xml
- android/app/src/main/res/values/strings.xml
Requested by @Branikolog in #6505
It is possible to filter standard, campaign and multiplayer save files in various combinations as desired.
> Android Save File Manager: implement filtering of save files by type

- src/fheroes2/kingdom/kingdom.cpp
If one of resources has negative value per day then the original formula was just increasing it. This is how it was before the fix:
and this is how it should be (after the fix):
> Fix invalid Kingdom income calculation

- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/gui/statusbar.cpp
- src/fheroes2/gui/statusbar.h
There is a lag in the status window. It is updated only due to cycling animation. This is how it looks:
https://user-images.githubusercontent.com/19829520/216804492-3051429d-4d60-446f-ab16-36d4dc2e13bb.mp4
Plus a very tiny optimization.
> Instantly update status bar in battle for hero's dialog options

- src/fheroes2/maps/maps_tiles.cpp
This is a possible for some corrupted save files introduced by #6502. We need to explicitly cast enumeration entries to prevent possible corruption.
This is a save file which might be created because of latest changes:
[Artifact_Isle_gazebo.zip](https://github.com/ihhub/fheroes2/files/10610242/Artifact_Isle_gazebo.zip)
> Fix possibly corrupted save format

- .clang-format
Inspired by questions in #6590
Example (headers from hypothetical `core.cpp`):
```cpp
#include <assert.h>
#include <cstdint>
#include <stdexcept>
#include <SDL.h>
#include <SDL_error.h>
#include <SDL_version.h>
#include "audio.h"
#include "core.h"
#include "localevent.h"
#include "logging.h"
```
will be reformatted as:
```cpp
#include "core.h"
#include <cstdint>
#include <stdexcept>
#include <assert.h>
#include <SDL.h>
#include <SDL_error.h>
#include <SDL_version.h>
#include "audio.h"
#include "localevent.h"
#include "logging.h"
```
> clang-format: force reordering of header groups

- docs/INSTALL.md
close #6592
I decided to reorder the installation instructions according to the popularity, package repositories going first, options related to building from sources going last. I'm not really sure about the order of popularity of Linux package repos though.
> Improve installation documentation

- src/engine/tools.cpp
- src/engine/tools.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
As mentioned in #1625, the super helpful damage info tooltip that shows the range of damage when attacking the enemy troop does not show anything when using spells. When using a single-target damage spell such as a Lightning Bolt, Arrow, or Coldray, the spell in the magic book shows you the exact damage it would deal, but when hovering over an enemy troop, you have to cancel the spell, check the troop's health to calculate how many troops will perish, and then go back to using the spell again. Additionally, the spellbook does not show the spell adjustments you might encounter when targeting special troops, for example when using a cold ray on an Air Elemental (cold spells have 2x damage on air type monsters).
This damage tooltip, however, will ignore defending hero's artifacts - if the …
> Combat, Adding tooltip damage info for single target attack spells

- script/agg/extract_agg.bat
- script/agg/extract_agg.sh
- src/tools/extractor.cpp
Related to #6553
It [turns out](https://github.com/ihhub/fheroes2/issues/6553#issuecomment-1428380378) that `HEROES2.AGG` and `HEROES2X.AGG` may contain items with the same names, thus, extracting both of these files to the same directory is undesirable.
> extractor tool: extract each AGG file to a separate subdir

- VisualStudio/tools/xmi2midi/sources.props
Related to #6652
This removes extra DLL dependencies for the `xmi2midi` tool to run.
> Tune MSVC dependencies for xmi2midi tool

- src/engine/smk_decoder.cpp
NWCLOGO.SMK constains stereo audio track that isn't played. The game puts "[ERROR]    playSound:  Failed to create an audio chunk from memory. The error: Unsupported block alignment " message.
> fix stereo audio playing in SMK files

- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/kingdom.cpp
Fix an issue, found by **Dmytr01** (on Discord):
The color of enemy objects (mines) was not reset on Mini-map after enemy vanquish.
This archive contains two saves I used to check the fix (capture an enemy castle, defeat an enemy hero): [saves.zip](https://github.com/ihhub/fheroes2/files/10746348/saves.zip)
> Fix Mini-map reset of enemy object colors after enemy vanquish

- docs/GRAPHICAL_ASSETS.md
This fixes missing line breaks for the links to the precompiled tools and puts 32-bit Windows first:
https://github.com/zenseii/fheroes2/blob/fix-graphical-artist-guide/docs/GRAPHICAL_ASSETS.md
This is how it looks in master currently:
> Fix line breaks in Graphical Artist Guide

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_only.cpp
- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/gui/ui_window.cpp
- src/fheroes2/gui/ui_window.h
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
- src/fheroes2/kingdom/puzzle.cpp
fix #6547
relates to #6391
Made rendering of a Standard window using game resources and connecting them by using simple transition pattern: 
Also added ability not to render the window background if only the borders are needed (in example for Castle, Battle dialogs).
<details><summary>Standard Window for Evil interface with and without background</summary>
</details>
> Rewrite standard window generation code

- VisualStudio/Release.props
This slows down the build somewhat in release mode, but performs various useful [optimizations](https://learn.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=msvc-160), including cross-module inlining.
> MSVC: enable link-time optimization in release mode

- src/fheroes2/army/army_bar.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/dialog/dialog_recruit.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
This PR fixes the following issues:
1. CPU hog when viewing quick info on a unit using the right mouse button. How to reproduce:
1.1. Open hero window or any other window where you can view quick info on the unit;
1.2. Hover the mouse over the unit, press and hold the right mouse button;
1.3. Observe the 100% CPU load in Task Manager.
2. Hero is able to upgrade troops during the battle if he is defending a castle, this castle has an upgraded dwelling and there is non-upgraded unit from that dwelling in hero's army. How to reproduce:
https://user-images.githubusercontent.com/32623900/219902090-cf8cb47f-c721-47ef-9681-30083451ede8.mp4
Also I moved all auxiliary functions in the `dialog_armyinfo.cpp` to the anonymous namespace.
> Fix multiple issues in the Dialog::ArmyInfo()

- src/fheroes2/kingdom/puzzle.cpp
This is my first PR. Puzzle window is centered nicely in game area after this change.
fixes: #6657
> Puzzle map window is not centered on the screen

- src/fheroes2/maps/maps_tiles_quantity.cpp
fix #6676
Previously, the spell id of a spell scroll was not truncated to its lower 8 bits while loading it from MP2 and therefore may have invalid values, which is wrong. This now has been caught by an assertion.
> Fix the spell id calculation for a spell scroll

- src/engine/dir.cpp
Use `FindFirstFileEx()` with accelerating flags instead of old `FindFirstFile()`. However, there is unlikely to be a strong accelerating effect in the case of map files (especially at the first run), because we need to open each map file separately to read its header. This operation is instant on my Windows (on SSD and even on 7200RPM HDD) as well as on macOS and Ubuntu (running in VM), but on configurations with a slower HDD, it still can take time.
> Speed up the creation of a file list in Windows

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/payment.cpp
- src/fheroes2/kingdom/payment.h
- src/fheroes2/maps/maps_tiles.cpp
fix #6685
Currently, these tiles are inaccessible "at the logical level", i.e. they cannot be chosen as a destination by a human player or AI. However, if they were already chosen before they become occupied by an ally, adventure map pathfinder has no idea that something is wrong and doesn't recalculate the path.
> Make tiles with allied heroes or castles inaccessible at the pathfinder level

- src/fheroes2/kingdom/kingdom_overview.cpp
Fixes https://github.com/ihhub/fheroes2/issues/6557. Now show kingdom income when left or right clicked on the gold income per day box.
> Show kingdom income when gold per day income is clicked

- src/fheroes2/kingdom/kingdom_overview.cpp
> Render background between HEROES and TOWSN/CASTLES buttons in Kingdom Overview window

- src/fheroes2/battle/battle_dialogs.cpp
> Properly restore the screen after closing the hero dialog during combat

- src/fheroes2/battle/battle_pathfinding.cpp
An alternative approach to #6717
fix #6715
https://user-images.githubusercontent.com/32623900/221380571-9d719000-c63a-4e10-ae90-6b5e53cfbb15.mp4
```
26.02.2023 00:32:35: [DBG_BATTLE]       AI::BattlePlanner::meleeUnitDefense:  Hydras protecting friendly archer, moving to 12
26.02.2023 00:32:35: [DBG_BATTLE]       AI::BattlePlanner::planUnitTurn:  Hydras melee phase end, target cell is 12
26.02.2023 00:32:35: [DBG_BATTLE]       AI::BattlePlanner::planUnitTurn:  Hydras moving to cell 12
```
> Battle pathfinder: auto-fix the cropped paths for AI-controlled wide units

- src/fheroes2/maps/maps_tiles.cpp
> Fix fog rendering horizontal offset. Adventure map.

- src/fheroes2/battle/battle_board.cpp
> Battle::Board::GetDistanceIndexes(): results should not include the center

- src/engine/zzlib.cpp
- src/engine/zzlib.h
- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/castle/castle_building.cpp
- src/fheroes2/dialog/dialog_file.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game.h
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/game_io.cpp
- src/fheroes2/game/game_io.h
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_over.cpp
- src/fheroes2/game/highscores.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_fileinfo.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/system/players.cpp
- src/fheroes2/system/save_format_version.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
- src/fheroes2/world/world.cpp
Implement the proposal from #6707
There were two main problems because of which it was impossible to make a "naive" implementation and which caused refactoring:
1. The world date is stored in the zipped part of the save file, so we can't just seek & read a few bytes, we should unzip this part first, which is relatively slow;
2. There was no infrastructure to use the save file version in the `struct Maps::FileInfo`, so it was impossible to just add a couple of fields there.
> Display the world date for save files, refactor the game I/O a bit

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes.cpp
At the time #5697 fixed the experience calculation only for human-controlled heroes, but not for AI-controlled ones.
This change was originally the part of #6737, but since the another part of that PR is questionable, I moved the bugfix to the separate PR (this one).
> Tree of Knowledge: fix the experience calculation for AI-controlled heroes

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
fix #6733
Not limited to Magellan's Maps only:
https://user-images.githubusercontent.com/32623900/221958406-8aa72aa5-0187-4906-ae06-4d14e6ed52c6.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/221958518-8d701784-f0c9-420e-ab93-ccafab78ba1f.mp4
> Reset the world pathfinder(s) on fog reveal operations

- src/fheroes2/ai/normal/ai_normal_battle.cpp
Currently AI sitting in a castle defensively when enemy's archer ratio is too low. Aggressive behaviour should be the default stance and during castle siege AI should stay within the wall only if archers are stronger rather than looking at the ratios in the first place.
Also reducing walls archer penalty because strength isn't all about the damage dealt.
> Fix battle AI tactics estimation

- src/engine/audio.cpp
Remove the last TODOs in the `engine/audio.cpp`.
> Cleanup the SDL Mixer initialization

- src/fheroes2/game/game_delays.cpp
If you set the Battle speed to 10 and start a battle with Zombies or Genies or Ghosts you can notice the high CPU usage on master build.
This PR makes the maximum Battle speed (10th) to use the half of 9th speed delays.
The custom unit movement delay is capped at 1 ms from the bottom.
Visually the battle movement preserves the same as before the PR.
> Fix zero delays for Battlefield animations to reduce CPU usage at 10th battle speed

- src/fheroes2/ai/normal/ai_normal_hero.cpp
We missed this on a recent refactor. Currently AI hero gets stuck in a loop if such object is on the map.
> Fix AI being stuck on watering hole

- src/fheroes2/gui/ui_font.cpp
Relates to #6750 
The added symbols: 7 8 9 ! " # % & ' ( ) * + , / : ; < = > ? [ \ ] ^ _ 
A Caps Lock symbol (▲) temporary replaces currently unused `|` character:
Backspace symbol (<x]) temporary replaces the currently unused tilde character (~):
The need of temporary Caps Lock and Backspace symbols and what ASCII character might be replaced by them can be discussed.
> Add symbols to button font (ASCII)

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
relates to #6744
The "AI auto control mode" is currently available only in debug version of fheroes2 for AI debugging purposes.
For human player we made special mini-map updates after some actions, which does not include hero movement as the player can do this action and then wants to overview the world and think about the next action. AI don't do this. So mini-map update is needed only after hero move.
The `.SetRedraw( Interface::REDRAW_RADAR )` for "AI auto control mode" player is called from `Heroes::Scoute(()` method.
It could possibly be placed in `Maps::ClearFog()`, for example, but to do this we have to transfer there the player/hero ID and to mix different logic.
> Rework the radar (mini-map) update calls for AI auto controlled player

- src/fheroes2/ai/ai.h
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Currently AI could rush to castle defence even if enemy hero threatening it was taken out. Adding more information to track & finally taking advantage of attack tasks.
> Clean up AI priority tasks if attacker was killed

- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/spell/spell_book.cpp
- src/fheroes2/spell/spell_info.cpp
- src/fheroes2/spell/spell_info.h
Solves https://github.com/ihhub/fheroes2/issues/5822 by graying Town Gate and Town Portal spells instead of not showing them in the spell book while onboard. Also changes Summon Boat spell to gray out when not near water.
> Gray out summon boat, town gate and town portal spells

- docs/TRANSLATION.md
This should hopefully relieve us of some headaches.
Max 30 lines for translations of new languages that don't already exist in the project.
> Add max lines of translations for new languages

- src/fheroes2/heroes/heroes_action.cpp
In original game a hero has to fight the guardians only once per map. After this any player can recruit troops from this dwelling without fighting the guardians.
After defeating the player who has first captured these dwellings any one can continue visiting them without fighting the guardians.
In fheroes2 the player who has first captured the dwelling gets it to his own (by color), but any other player can recruit creatures without a fight with guardians. But if the owner is vanquished the next hero has to fight the guardians to be able to recruit troops.
This PR makes the dwelling to act like in original game by setting the ownership to the Neutral (gray) player.
This affects City of the Dead, Troll Bridge and Dragon City.
> Make dwellings act like in OG: fight the guardians only once per map

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/monster/monster_info.cpp
- src/fheroes2/spell/spell.cpp
- src/fheroes2/spell/spell.h
fix #6784
Resurrect is allowed only while at least one elemental from the stack is still alive.
> Allow to resurrect Elementals

- src/fheroes2/dialog/dialog_game_settings.cpp
No use to translate strings which are used only in English.
> Remove unneeded translations

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
This PR fixes the absence of mini-map update before entering a Teleport or Whirlpool.
The condition used to check if Hero has moved to a Teleport does not work properly so I moved the mini-map redraw after every hero move to `heroes_move.cpp`.
fheroes2:
https://user-images.githubusercontent.com/113276641/223682822-7c3bd128-9f65-442b-825d-48ab74be2f2f.mp4
This PR:
https://user-images.githubusercontent.com/113276641/223691078-1787beca-26b3-4073-bbe3-bf4c622e1a0b.mp4
UPD:
This PR also makes mini-map to update right after hero move in hero scout area.
If hero action leads to mini-map objects change then mini-map is updated only in the area of changed objects (capture of mine, resource or artifact, defeat a hero).
Previously the mini-map update was made only after hero move and action assuming …
> Fix mini-map update when interacting with map objects (Teleport, Artifact, Mine, Resource, Hero)

- script/packaging/common/fheroes2.appdata.xml
As Flatpak only shows the last link as a donation link.
> Keep only Patreon link for FlatPak

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/heroes/heroes_move.cpp
Close #3015
Relates to #5716
This PR makes render of shadows, corresponding to hero animation:
- fixed Hero shadow ID calculation;
- corrected shadow sprite shift.
In fheroes2:  ![fheroes2 2023-03-13 20-48-43-199](https://user-images.githubusercontent.com/113276641/224788889-b2796a7c-bc8e-4dc0-93da-549b8849b9ff.gif)  This PR:  ![fheroes2 2023-03-13 20-44-42-025](https://user-images.githubusercontent.com/113276641/224788930-730c9d00-3bdd-46ef-b2c6-f51c27693638.gif)
This PR also fixes not properly updated hero shadow during move when hero speed is set to 10.
> Fix Hero shadow render on Adventure Map

- src/fheroes2/maps/maps_tiles_quantity.cpp
fix #6377 
Relates to #5716 
This PR preserves object sprite Layer Type when pushing it to Addons on monster placing. The previously forced set of Layer Type to `OBJECT_LAYER` made roads parts to be rendered by the engine above hero sprite and possible some other sprites: https://github.com/ihhub/fheroes2/issues/5716#issuecomment-1473823066
```
--------- Level 1 --------
UID             : 5318
ICN object type : 30 (ROAD.ICN)
layer type      : 0 (0) - Object layer <-- Initially it was: 3 - Terrain layer
```
This PR also implements setting a unique UID for the placed monster.
The changes of this PR don't affect existing save files. The fix is only for newly placed monsters (at the end of the month).
I checked this change on a couple of maps by forcing `MonthOfMonstersAction()` on every day …
> Preserve existing object sprite Layer Type on monster spawning. Adventure map.

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_quickinfo.cpp
In fheroes2 when you try to get quick info for an object whose action (main) tile is under the fog you get the "Uncharted Territory" instead of the object info:
In original game you are able to get object quick info if its action (main) tile is under the fog.
This PR makes the fog check to be done only for the tile under the cursor and if it is the non-action tile then get info from the action tile of this object:
This PR also slightly reworks the code for all quick info text strings.
> Fix quick info for non-action objects when their action tile is under the fog. Adventure map.

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/heroes/heroes_action.cpp
fix #6862
This situation is properly handled for a human-controlled hero, but not for an AI-controlled hero.
This PR also implements the following changes:
<details><summary>Now, if a group of wandering monsters has an upgraded stack, and only this stack is left alive after the hero is defeated, this is handled properly.</summary>
In the `master` branch:
https://user-images.githubusercontent.com/32623900/226147178-adcbbd5c-4c4b-4f52-a050-7fec87ddd410.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/226147190-7156bdc0-1933-4600-be54-303319e4482c.mp4
</details>
<details><summary>Now protection of guarded objects is removed if guardians and attacking hero eliminate each other. </summary>
Human player:
https://user-images.githubusercontent.com/32623900/226208755-da152059-86 …
> Properly handle the situation when wandering monsters and a hero controlled by AI eliminate each other

- src/fheroes2/army/army_bar.cpp
- src/fheroes2/army/army_bar.h
- src/fheroes2/castle/buildinginfo.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
Solves https://github.com/ihhub/fheroes2/issues/4749. The recruitment windows is lowered 2 pixels on castle well view and in kingdom overview centered over top part of the window.
> Adjust recruitment window position on castle well and kingdom overview

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/mp2.cpp
fix #6897
Unlike using Stone Liths or Whirlpool, AI hero can cast Dimension Door or Town Portal (or get on board the boat) right at the beginning of his turn without any previous movement, so we need to focus on the corresponding tile first to display the fade-out animation.
> Focus on the AI hero before he disappears due to boarding a boat or using a Dimension Door or Town Portal spell

- src/fheroes2/game/game_static.cpp
- src/fheroes2/heroes/skill.cpp
fix #6903
Since the original description of the Mysticism skill is really a bit misleading, I decided to change it a bit. Suggestions are welcome.
> Fix the number of regenerated spell points with the Mysticism skill

- src/fheroes2/castle/castle_building_info.cpp
Missing in the OG game also, but no point of keeping the misstakes and typos of the OG.
> Added gold missing in statue building description

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
All tiles covered by fog can be divided into 2 categories:
- tiles which are neighboring passable tiles. These tiles most likely be passable and might have some valuable objects
- tiles which are not reachable. These tiles are usually useless unless they are on another part of land / sea separated by impassable objects
In the majority of situations uncovering passable tiles is the best strategy and this is what actually most of human players do. With the proposed changes AI heroes tend to uncover "proper" tiles by expanding the territory which they can access.
> Improve AI fog discovery logic

- src/fheroes2/castle/castle_building_info.cpp
Missing in the OG game also, but gold is clearly missing and every other description in game uses "per" and not "/".
> Added missing gold in Dungeon description

- src/fheroes2/gui/interface_gamearea.cpp
This fix was made in #6809, but was accidentally lost in that PR.
Path icon is removed after a hero/boat makes a turn (relates to [#5716](https://github.com/ihhub/fheroes2/issues/5716)):
> Remove path icon after a hero/boat makes a turn, not before

- src/fheroes2/ai/normal/ai_normal_hero.cpp
Right now all objects decrease their value over distance to a hero. Logically it works fine but not always accurate. There are objects on maps which still should have high enough value over distance. For instance, a mine has a value of 2000. When an AI hero stands just 7 tiles away (700 move points) this value drops to ~0. For comparison, a resource located 3 tiles away (300 move points) will still have value 100. The formula should be adjusted for some objects so they don't loose their value drastically. On the other hand, some objects should not be worth visiting if they are far away like Luck modifiers.
relates to #3589, #5307
> Consider object type while calculating object value over distances for AI heroes

- src/fheroes2/battle/battle_interface.cpp
Close #6687
This PR makes the arrow not to be rendered going through the creature.
The last render position is shifted by the half of arrow size so it is rendered hitting the target and does not disappear before the target (like in original game).
https://user-images.githubusercontent.com/113276641/229307566-d10f1b76-756c-4999-92d5-bc8ce9857b0b.mp4
> Fix projectile render position when hitting the target creature. Battlefiled.

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps_objects.cpp
- src/fheroes2/maps/maps_objects.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_quantity.cpp
- src/fheroes2/maps/mp2.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
- src/fheroes2/world/world_pathfinding.cpp
- remove the remaining unused structures in `mp2.h` file
- move several methods out of Maps::Tiles class as they don't belong there being too specific to certain object types. Not all methods were moved to keep this pull request relatively small.
> Cleanup MP2 format and Maps::Tiles class

- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/gui/ui_button.cpp
- src/fheroes2/gui/ui_button.h
- src/fheroes2/gui/ui_keyboard.cpp
This PR adds the button "..." to dialogs with editable fields:
- Save Game dialog;
- Player Name.
This button will allow to open the Virtual keyboard on any system.
This PR also fixes high CPU usage in name input dialog.
> Add Virtual Keyboard open button to Save Game and Player Name dialogs

- src/fheroes2/world/world_pathfinding.cpp
Related to #6959
Should fix an inability to access some tiles that require to stand in front of them (i.e. overprotected tiles that has too strong army of wandering monsters on them). "Too strong army" is detected using the same rules as `AIWorldPathfinder` uses for the "normal" movement. This change still allows to "steal" pickupable objects from under the nose of guardians:
https://user-images.githubusercontent.com/32623900/230740334-0f082bff-f1e7-4319-b39b-a3227ed05f80.mp4
Hi @ihhub could you please verify this change in regard to #6959? Does it resolve the corresponding issues?
> Do not allow to access overprotected tiles using the Dimension Door spell

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
close #6941
Also, this PR fixes the issue when cells are highlighted, even if the current spell does not apply to units on these cells. Currently on the `master` branch:
https://user-images.githubusercontent.com/32623900/229931766-7bfca010-d673-42ae-8d60-fa9bcf6f06e4.mp4
With this PR:
https://user-images.githubusercontent.com/32623900/229931819-4463921c-0218-46c8-96b6-364beba7429d.mp4
This change may be controversial, but I believe that since we do not highlight the cells with dragons in this video, we should not also highlight the cells with other units on which this spell does not work. Empty cells will continue to be highlighted as before.
> Improve the destination indication for Teleport spell

- android/app/src/main/res/values-pl/strings.xml
Demo version URL is marked as non-translatable and is not need to be translated.
> Android: remove non-translatable string from Polish localization

- src/engine/audio.cpp
- src/fheroes2/maps/maps_tiles.cpp
Fix the warning:
```
/home/runner/work/fheroes2/fheroes2/android/app/jni/main/../../../../src/fheroes2/maps/maps_tiles.cpp:2506:19: warning: unused variable 'centerfogDataIndexLimit' [-Wunused-variable]
const int32_t centerfogDataIndexLimit = fogDataSize + topLeftDirectionOffset;
^
```
when app was built with the `NDEBUG` macro defined.
> Fix the "unused variable" warning on release builds

- src/fheroes2/gui/interface_gamearea.cpp
This PR fixes a bug of hero/boat rendering over the bottom map border.
Current master build:
This PR:
> Do not render hero/boat over the bottom map border. Adventure map.

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/world/world.cpp
> Redraw the status window after the amount of kingdom resources has changed at the beginning of the day, fix recurring events

- src/fheroes2/battle/battle_interface.cpp
The bug was found by **drevoborod** on Discord.
If your cursor pointer is not _WAR_NONE_ (X) and you call the Spell Book by hotkey ("C") and try to use the **Teleport** spell you will encounter an assertion that checks that the cursor type is not _WAR_NONE_ or _SP_TELEPORT_.
You can just simple point your creature and call the Spell Book:
This happens as the cursor position and type were not updated from the state before opening the Spell Book.
This PR resets the battlefield cursor position on battlefield after using the Spell Book.
> Reset battlefield grid cursor position after using the Spell Book

- src/engine/screen.cpp
- src/engine/screen.h
- src/engine/tinyconfig.cpp
- src/engine/tinyconfig.h
- src/fheroes2/dialog/dialog_graphics_settings.cpp
- src/fheroes2/dialog/dialog_resolution.cpp
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/system/settings.cpp
Add a special resolution for devices to support wide screens which are prevalent in modern devices. Only for SDL 2. The newly added resolution is extremely useful for mobile phones where we have to keep resolution as low as possible but avoid the game being rendered only on half of the phone's screen. This resolution is set by default for the first application run.
relates to #5373
I am open for suggestions, corrections how to improve user experience in this field.
> Expand wide screen support

- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/highscores.cpp
- src/fheroes2/game/highscores.h
close #6970
We save highscores file only when a player complete a single map / campaign. This is done to save data using the same language user chosen to use.
> Add language support for highscores

- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
We don't want people to use demo version of the game to play The Price of Loyalty maps without owning a full game.
> Add extra checks to prevent loading renamed MX2 maps on demo version

- src/engine/screen.cpp
Related to #7046
Use the reverse logic to search the available scaled resolutions: do not search for bigger resolutions for existing smaller ones (640x480 -> 1280x960) but add lower "pseudo-resolutions" for existing bigger resolutions instead (1280x1024 -> 640x512x2).
> Rework the search algorithm for available scaled resolutions

- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
This PR adds
- events handling during fade animations (i.e. at the end of battle). This fixes soft rendered cursor freezes.
- fade animations synchronization by "CustomAnimationDelay" instead of `delayforMs()`.
Also a small code clean-up was made in this PR.
> Handle events during fade animations, sync rendering by "CustomAnimationDelay"

- .clang-format
- .github/workflows/android.yml
- android/app/build.gradle
- android/app/src/main/java/org/fheroes2/GameActivity.java
- android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
- android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
- android/app/src/main/java/org/fheroes2/ToolsetActivity.java
- android/isotools/LICENSE
- android/isotools/build.gradle
- android/isotools/src/main/AndroidManifest.xml
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/api/FileEntry.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/api/FileSystem.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/api/LoopFileSystemException.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Constants.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/EntryInputStream.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/EntryIterator.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Iso9660FileEntry.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Iso9660FileSystem.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Iso9660VolumeDescriptorSet.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Util.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/AbstractBlockFileSystem.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/AbstractFileSystem.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/SeekableInput.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/SeekableInputFile.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/VolumeDescriptorSet.java
- android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/util/LittleEndian.java
- android/settings.gradle
If `HOMM2.GOG` is present in a ZIP archive with HoMM2 assets. On request from people writing reviews on Google Play.
ISO9660 module was mostly taken from [stephenc/java-iso-tools](https://github.com/stephenc/java-iso-tools) repo (LGPL license, currently unmaintained). I removed a lot of unnecessary code that did nothing useful for us but require unnecessary dependencies (including natural monsters like [Apache Hadoop](https://github.com/stephenc/java-iso-tools/blob/334caa435f58ebaa8a5f69eefc2e5ac247c0d6c2/loop-fs-spi/pom.xml#L50-L54)), fixed a few bugs (for instance, the original code treated files with the `Hidden` attribute in the ISO image as directories and caused a crash), modernized the original code a bit, formatted it according to our standards and added our copyright strings …
> Android Toolset: implement animation extraction from HOMM2.GOG

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/kingdom/kingdom.cpp
Currently in `master` branch only patrol distance ("square") is printed, but not the patrol center. A number of clumsily named variables have also been renamed.
> Print more detailed information about the hero patrol settings in debug mode

- src/fheroes2/game/game.h
- src/fheroes2/game/game_over.cpp
- src/fheroes2/game/game_startgame.cpp
Solves https://github.com/ihhub/fheroes2/issues/1561 and https://github.com/ihhub/fheroes2/issues/1649. Add title to following dialogs
This one you can see when it's your last day and you end you turn manually.
This one can been seen when you have more than one castle and then they are taken from you. When it's your turn and you end your turn manually.
> Improve dialog titles related to losing the game

- src/fheroes2/heroes/heroes_base.cpp
- src/fheroes2/spell/spell_book.cpp
Solves https://github.com/ihhub/fheroes2/issues/5259 by changing the message to "You have no mana..." when hero has 0 mana points.
> Adust spell info message when hero has zero (0) mana

- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/system/players.cpp
- src/fheroes2/system/players.h
- src/fheroes2/system/settings.h
The issue was found by **Stisen11** on Discord channel: "When I restart Good Campaign level 2, the adventure map is ALL black! That is until I click and move a hero. Then the fog of war renders wierdly..."
This PR does these fixes:
- do not force set player color to -1 when you end current player turn not by "ending" it (i.e. restarting a campaign scenario);
- set the the only human player color before updating adventure map fog directions for Single player games;
- rework of `Players::FriendColors()` to return return current friends player colors, if player does not exist - return 0.
> Fix adventure map fog reveal on campaign scenario restart and when loading a Hot Seat save made in the first game day.

- src/engine/serialize.h
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/view_world.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_helper.h
- src/fheroes2/maps/mp2.cpp
- src/fheroes2/maps/mp2.h
- src/fheroes2/maps/pairs.h
- src/fheroes2/resource/resource.cpp
- src/fheroes2/resource/resource.h
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
- src/fheroes2/world/world_pathfinding.cpp
- remove cryptic quantity1 and quantity2 values everywhere in the code and replace them with human-readable **metadata** array
- avoid hardcoded values for many object conditions like Artifact, Daemon Cave or Shipwreck
- fix AI pathfinding when Spell Scroll was considered as an artifact which requires to defeat an army
- fix Shipwreck Survivor bonuses. It always contained artifact of level 1
- add many checks in the code to prevent calling functions for unsupported objects
- add specialized functions to get information about objects. We have to avoid generic functions
relates to #6845 
**ATTENTION**
This pull request changes almost every object interaction on Adventure Map in relation to conditions and resources. Also I added a conversion code from old save format to a new one. As a …
> Standartize metadata for all objects on Adventure Map

- src/fheroes2/system/players.cpp
relates to #7109
This PR fixes loading a save made at the end of a campaign scenario.
Such old saves store '-1' as the current player color.
Recently we decided not to use negative numbers for player colors as in some cases it produces bugs.
All places in the engine that were setting player color to '-1' were changed to 'Color::NONE' in https://github.com/ihhub/fheroes2/pull/7080
> Fix loading campaign save made at the end of scenario

- src/fheroes2/game/game_mainmenu.cpp
> Fix not returning to load menu while switching between campaign scenarios

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/game/game_loadgame.cpp
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/game/game_mainmenu_ui.cpp
- src/fheroes2/game/game_mainmenu_ui.h
- src/fheroes2/game/game_newgame.cpp
This change might be not the best approach we could do but it does not stretch the main menu, avoiding button shifting issues and also serves as an indicator for widscreen resolutions.
close #7045
close #7014
relates to #4384
> Fill main menu with background when we do not stretch the main menu main image

- src/fheroes2/battle/battle_interface.cpp
This PR fixes the freeze of Battlefield animations after finishing rainbow animation and until Good Lock sound is over.
This PR also removes waiting for Good Luck sound if sound volume is set to 0.
> Fix Battlefield animations freeze while waiting for Good Luck sound to end

- src/fheroes2/audio/audio_manager.cpp
- src/fheroes2/audio/audio_manager.h
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
This PR adds the ability to skip waiting for pre-battle sound to over and start the battle by pressing ESC, right mouse or middle mouse button. This does not interrupt the pre-battle sound playback.
> Add the ability to cancel waiting for the end of the pre-battle sound

- src/fheroes2/battle/battle_interface.cpp
This PR fixes the idle animation lag while hero is moving his arm to cast a spell and after casting it.
Master build:
https://user-images.githubusercontent.com/113276641/236998990-31d6ec52-2c9c-4b0d-b455-edf2b1529c7b.mp4
This PR:
https://user-images.githubusercontent.com/113276641/236998614-e8abdea6-9390-4497-aeec-3842c2c5ae2e.mp4
> Fix idle animation lag while casting a spell on the Battlefield

- src/fheroes2/battle/battle_interface.cpp
fix #7150 
This PR:
https://github.com/ihhub/fheroes2/assets/113276641/adc58ef8-2c82-4e3b-9319-ef01c4a91f9f
> Fix absence of delay after creature wincing animation. Battlefield.

- android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
- android/app/src/main/java/org/fheroes2/ToolsetActivity.java
* Enforce check for ongoing background operation in `ViewModel` methods to better prevent potential race conditions. Currently, this prevention is performed using only the UI logic (by disabling/enabling UI controls), so it's better to be safe than sorry;
* Removed some single-line methods and short private methods that are used only in one place.
> Android Toolset: minor cleanup

- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_focus.cpp
- src/fheroes2/gui/interface_icons.cpp
- src/fheroes2/gui/interface_icons.h
- src/fheroes2/heroes/heroes_action.cpp
Solves https://github.com/ihhub/fheroes2/issues/6837. Now both castles and heroes scrollbars positions are retained when hero moves. Previously both of them were modified. Castle scrollbar always goes to the top and heroes scrollbar is either placed to the top or bottom of the scrollbar view depending on the hero's position on the list.
> Do not reset castle or heroes scrollbars when hero moves

- src/fheroes2/gui/ui_font.cpp
Relates to #7180
Add diacritic signs to CP-1250 button font characters:
Š Ś Ť Ž Ź Ł Ą Ş Ż
Ľ Ŕ Á Â Ă Ä Ĺ Ć
Ç Č É Ę Ë Ě Í Î Ď Đ
Ń Ň Ó Ô Ő Ö Ř Ů
Ú Ű Ü Ý Ţ
I'm not familiar with these letters so comments are welcome.
> Add diacritic signs to CP-1250 button font

- src/engine/audio.cpp
Fix #7176
On the battlefield on high speed the move sound is played for every cell move which ends in multiple simultaneous sound playbacks. The PS Vita sound resampler loads the CPU to resample and play these sounds. This result in game lags and jerky animation.
> Use 22050 sound sample rate for PS Vita to fix high CPU load

- src/fheroes2/ai/normal/ai_normal.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
std::binary_search works only if an array is partially sorted in respect to value - https://en.cppreference.com/w/cpp/algorithm/binary_search
~~Since **getObjectsOnTheWay()** method returns unsorted array we have to sort it in order to fulfill binary search requirements.~~
**_mapObjects** wasn't been completely sorted during fog revealing events.
> Fix cases when AI ignores some objects during path evaluation

- android/app/build.gradle
- android/build.gradle
fix #7187
https://issuetracker.google.com/issues/279034662
https://issuetracker.google.com/issues/282544786
This issue was introduced in the Android Gradle Plugin 8.0 and should be fixed in 8.1 (currently in beta, will be available along with the new version of Android Studio). As a workaround, I rolled back to an older AGP version (7.4.2). With older AGP version, there are warnings during the desugaring stage:
```
Warning: Desugared library: Cannot amend library reference java.nio.file.Path java.nio.file.Path.of(java.net.URI) because the holder is not a library class.
Warning: Desugared library: Cannot amend library reference java.nio.file.Path java.nio.file.Path.of(java.lang.String, java.lang.String[]) because the holder is not a library class.
```
but it seems that everything works …
> Use an older version of the Android Gradle Plugin

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_move.cpp
Apparently this parameter was used in the past when it was possible to pave the way through the whirlpool, but with the current passability rules it is not needed (and even harmful: if `AIAutoControlMode` is turned off on the current turn, semi-AI-controlled heroes are not able to use Whirlpool until the next turn).
This change needs to be properly tested (with different whirlpool usage, movement in jump and normal mode, etc) and it should not be merged before the upcoming 1.0.4 release.
> Remove obsolete parameter of Heroes::Action()

- src/fheroes2/audio/audio_manager.cpp
Fix minor code smells recently introduced by #7183.
> Use try_emplace() from C++17 instead of emplace()

- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/spell/spell.cpp
> Resurrection spells are not a subset of restoration spells

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
This PR relates to #7176 issue and optimizes the Battlefield render:
- render Battlefield background only when it is changed (grid on/off) and cache it;
- use `fheroes2::Copy()` instead of `fheroes2::Blit()` where possible:
- when preparing the Battlefield background;
- on every render when drawing the rectangle images without transparency (count background, status bar background, ...);
- during DeathWave and EarthQuake spell effects.
Full render time for the Castle battlefield: 1.5 -> 0.85 ms
Full render time for the "Ship" battlefield, used in Battle only" mode: 1.0 -> 0.6 ms. 
<details><summary>Render time for optimized parts for the "Ship" battlefield</summary> 
```
RedrawCoverStatic render time:   0.2916 ms. -> 0.0443 ms.
RedrawPartialFinish render time: 0.1684 ms. -> 0.0142 ms. …
```
> Optimize CPU load while Battlefield rendering

- files/lang/ru.po
These are distinct words and they shouldn't be used one instead of another for the translation being accurate.
> Translation ru: Correct the translation of `halfling` as `полурослик`, not `hobbit` (`хоббит`).

- src/fheroes2/battle/battle_interface.cpp
Regression after #7209, minor (copy+paste?) typo.
This PR:
> Fix the rendering of the number of units during the castle siege

- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_loadgame.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/gui/interface_events.cpp
Remove fade when switching between the scenarios in campaign scenario info dialog.
master build:
https://github.com/ihhub/fheroes2/assets/113276641/652090e5-f8e9-434e-8e59-7ae2bf8f07c3
this PR:
https://github.com/ihhub/fheroes2/assets/113276641/07a243f3-fd6a-4001-87a8-000dea6bfee6
> Do not use fade effect when switching campaign scenario

- .github/workflows/msvc.yml
AGG tools depend on zlib after #7196.
> Add zlib1.dll to the tools package on Windows

- src/fheroes2/battle/battle_interface.cpp
fix #7236 - the regression after #7208
Before:
After:
> Fix not rendering big objects on the Battlefield

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/maps/maps_tiles_helper.cpp
Fix #7245
In master build it possible that AI captures the Dragon City (or Troll Bridge, or City of Dead), byes all creatures and is vanquished. So the dwelling's color is reset to NONE and we have 0 creatures count.
This PR makes AI logic as for non-AI heroes: Set ownership of the dwelling to a Neutral (gray) player.
Also to fix such cases (with 0 creatures and NONE color after AI vanquish) the dwelling population is increased like the dwelling was captured.
> Fix AI capturing a dwelling protected by monsters

- src/fheroes2/kingdom/kingdom_overview.cpp
Fix extra fade-in and redundant Castle `row.Init()` in Kingdom Overview dialog when clicking on an empty hero or castle captain icon.
Master build:
https://github.com/ihhub/fheroes2/assets/113276641/6c78a0ee-c788-4fef-b947-eeb6b1e6e0cd
In this PR the first 3 extra fades (when no new dialog is not opened) are disabled.
> Remove extra fade-in and redundant Castle row 'Init()' in Kingdom Overview

- src/fheroes2/game/difficulty.cpp
Since the AI is smarter and we want to give less bonuses to it, we are reducing the unit growth for AI within castles and towns.
> Reduce unit growth bonus for AI

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal.cpp
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/world/world.cpp
- we did not update map object cache when a hero moves so other heroes were using the old cached data and failed to find the hero if there is a need to meet each other. Such behavior is really hard to catch so you can use this save to test the master branch and this branch (green AI hero moves to a castle and another hero ignores him in master branch):
[Great_War_II_0018_hero_inte.zip](https://github.com/ihhub/fheroes2/files/11612281/Great_War_II_0018_hero_inte.zip)
- fix Magellan's Maps visit by AI heroes when discovered objects were not being added for exploration
- fix duplication of object information from the fog discovery event when AI uses "View All" spell.
- reduce the amount of objects being processed for a possible movement. Only action objects should be considered as useful for …
> Fix missing logic for AI heroes to meet each other in the middle of a turn

- src/fheroes2/army/army.cpp
close #6095
We should not calculate commander magical impact if an army does not have any creatures.
> Fix AI heroes behavior ignoring empty castles with commanders

- src/fheroes2/gui/interface_focus.cpp
Fix issue observed after #7228 on debug builds when a developer grants AI temporary control over a human-controlled player. Here is a save file:
[AI_Crash.zip](https://github.com/ihhub/fheroes2/files/11625209/AI_Crash.zip)
On this video game crashes on failed assertion in the `AIToTeleports()` because the hero's path is not empty on the teleport tile, which should not be under normal conditions:
https://github.com/ihhub/fheroes2/assets/32623900/a1c23b54-c261-41e3-810b-433945d90ac9
Usually, `SetFocus()` should be called for a human-controlled player only, but in debug builds we have `AIAutoControlMode` and `SetFocus()` may be called for a hero in this mode - for example, it is called on the teleport tile before performing the action, which leads to invalid hero's path due to its …
> Do not recalculate the hero path on focus change if player is controlled by AI

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
fix #7255
This PR also fixes a bug when dismissing hero after opening hero dialog from the castle:
https://github.com/ihhub/fheroes2/assets/113276641/9ad6ce7b-623b-44f3-86ad-d90adfb3aad1
> Fix extra fade when switching heroes by interface buttons, fix hero dismiss UI bugs

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/army/army_bar.cpp
- src/fheroes2/army/army_troop.h
- src/fheroes2/castle/castle.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/monster/monster.cpp
- src/fheroes2/monster/monster.h
Previously `GetUpgradeCost()` method was returning a normal cost of a monster if no upgrade is available. This causes a problem in `Troops::UpgradeTroops()` method which was deducting resources from the kingdom but no upgrade was done. On top of this the method didn't even have a check whether the monster can be upgraded.
During AI turn when a hero is in a castle we execute `reinforceHeroInCastle()` function which internally executes the code to upgrade monsters. This of course didn't work for monsters like Wolves which don't even have any upgrades.
This is a save file where a Yellow player has a hero in a castle and their money just disappear every turn because the "upgrade" of Wolves costs 1200 gold while the kingdom has only 1250 per day leaving the AI with 50 gold (on **master** …
> Fix monster upgrade logic when AI was wasting resources for nothing

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
There are situations when AI heroes have literally nothing to do. If it is a last day of week then it is wise to move to objects which will give something on the next day.
This is a save file where Yellow player heroes have no tasks so it is wise to move one of them to the castle for reinforcement. This save is done on day 6 so see what happens on day 7.
[AI_does_not_merge_army.zip](https://github.com/ihhub/fheroes2/files/11641662/AI_does_not_merge_army.zip)
> Move jobless AI heroes into castles on a last day of a week

- src/fheroes2/gui/interface_focus.cpp
fix #7271
This method can also be called in the "AI auto control mode".
> Fix assertion in the Interface::Basic::SetFocus( Castle * )

- src/fheroes2/ai/normal/ai_normal_castle.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
The current AI behavior does not cover possible scenarios:
- army is not distributed evenly after visiting by a hero. In most cases a hero grabs the most of the army and leaves just one stack of weak monsters. There is no perfect rule how to distribute an army of weak monsters but it is proven that having 5 stacks of monsters is better than 1 stack as there is a higher chance of shooting towers
- monsters were not upgraded if they were initially in a castle (use [AI_does_not_merge_army.zip](https://github.com/ihhub/fheroes2/files/11666182/AI_does_not_merge_army.zip) save, wait for the 7th day when a Yellow hero moves to the castle)
- if monsters are present in the castle no army shuffling was done (use [ai_castle_army_distribution.zip](https://github.com/ihhub/fheroes2/files/11666209/ai_ca …
> Improve army distribution in castles for AI players

- src/fheroes2/game/game_campaign.cpp
This PR fixes wrong display of Rating in congratulations text shown in WIN video. In 'master' build it was calculated without taking into account of campaign difficulty.
> Fix rating in campaign congratulations text in win video

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/army/army.h
This pull request fixes multiple things in AI behavior:
- move to a castle and stay there the hero cannot defeat the treat (close #7082). This is important to stay in the castle if the hero is too weak
- capture empty castles even if the area is under treat (close #7193). Also be afraid only of heroes which are really more powerful that the hero
> Improve AI heroes interaction with castles and heroes in dangerous areas

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
fix #7298 
This PR fixes the army troops strength calculation while AI performing the army split by explicitly calling the static function 'GetStrength()' from the corresponding class.
The incorrect army strength calculation sometimes led to the dismissal of the only unit in the hero's army: [troopSplitAssertion.zip](https://github.com/ihhub/fheroes2/files/11719315/troopSplitAssertion.zip)
> Explicitly call static function 'GetStrength()' to resolve the ambiguity between 'Army::GetStrength()' and 'Troops::GetStrength()'

- docs/TRANSLATION.md
A step to update the TRANSLATION.md file.
The idea behind this change is to slightly reorganise the file into the following sections:
- Intro
- Current status
- Adding new translations/localizations
- Editing translations - Before you start
- Editing translations - Your first or next translation
- Other topics (currently Updating PO templates and translatable strings in PO files)
The second idea is to add few high-level instructions on cooperating and using the Github.
This change tackles (but does not resolve) second topic of #7089.
> Update the translation documentation

- src/fheroes2/game/game.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_credits.cpp
- src/fheroes2/game/game_credits.h
Close #7303
This PR keeps the aspect ratio if game credits and removes redundant resize on every render loop and render of an image when it is in NO_ACTION state (showing page for some time without any effects).
This PR also reworks the code to reduce code repeating and not to use legacy 'Text' class.
> Rework game credits to keep aspect ratio

- src/fheroes2/game/game_startgame.cpp
> Properly restore environment sounds and terrain music after opening a castle dialog from the Kingdom Overview screen

- src/engine/image_tool.cpp
- src/tools/h2dmgr.cpp
- src/tools/pal2img.cpp
> h2dmgr: extract images as BMP/PNG files, fix color format of images loaded from BMP/PNG files (SDL2 only)

- src/fheroes2/kingdom/view_world.cpp
fix #7328
`Display::screenSize()` is the "physical" dimensions of the screen, and we need to operate in "logical" dimensions.
> Fix the fade effect on the "View World" screen

- src/fheroes2/game/game_mainmenu.cpp
> Do Main Menu fade-in before showing first game run messages, not after

- src/fheroes2/maps/maps_tiles.cpp
This PR fixes this issue: https://github.com/ihhub/fheroes2/issues/5716#issuecomment-1601480162
It makes engine to update the Abandoned Mine right sprite even if its tile object type is not `MP2::OBJ_NON_ACTION_ABANDONED_MINE`.
Master build:
The save file with the issue: [ghostmine_capture_sprit_bug.zip](https://github.com/ihhub/fheroes2/files/11823903/ghostmine_capture_sprit_bug.zip)
This PR:
> Fix Abandoned Mine right sprite update

- src/engine/image_tool.cpp
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_interface.cpp
This PR contains changes made in #7233
While working on #7233 there were made some necessary for that PR changes in the code, but PR became very big. To reduce the size of that PR and to properly test and merge some changes this PR is made. It contains:
- rework of **decodeICNSprite()** function to gain 1-30% speed-up while decoding ICN images;
- clean-up of `agg_image.cpp` to make Clang-Tidy a little happier;
- fix of  some images which were containing invalid transparent pixels (pixel count starts from 0x0 - upper left corner):
- mini portraits of PoL heroes (ICN::**MINIPORT**):
- Solmyr (ICN id 60, pixels 5x0, 10x10, 28x11,4x14),
-  Danwin (ICN id 61, pixels 21x1, 20x2, 21x2, 23x2, 25x14),
-  Gallavant (ICN id 65, pixels 19x16, 2x20, 1x21),
-  Ceallach (ICN id 67, pixel 12x1);
- …
> Redo ICN decode code and agg_image.cpp code clean-up

- src/fheroes2/spell/spell.cpp
This pull request fixes 2 cases:
1) Town Portal and Town Gate were not considered as valued spells for visiting castles or shrines.
2) Summoning spells were overestimated causing AI heroes to attack too powerful neutral monsters.
close #7194
Moreover, this is a save file when an AI hero attacks Druids having an idea in mind that Summoning spells are too powerful (hit F8 in debug mode for this):
[AI_army_overestimation.zip](https://github.com/ihhub/fheroes2/files/11928748/AI_army_overestimation.zip)
> Correct spell value estimation for AI heroes

- src/fheroes2/ai/normal/ai_normal_hero.cpp
Fix the assertion failure in the `master` branch on this line:
https://github.com/ihhub/fheroes2/blob/96a1ef0d61cad88760bb48dd93cfc6086f4d31e5/src/fheroes2/ai/normal/ai_normal_hero.cpp#L1673
How to reproduce:
1. Load the attached save file using the debug build;
2. Press F8 to transfer the control to AI;
3. Wait until the blue Wizard Caerlyn begins to attack the Necromancer's castle Chandler.
[Crash.zip](https://github.com/ihhub/fheroes2/files/11931896/Crash.zip)
> Fix the object cache update when AI-controlled hero uses the Dimension Door spell

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/kingdom/kingdom.cpp
This pull request fixes multiple issues with AI behavior on the Adventure Map:
1) before the changes AI heroes "knew" if any Shrine contains "useless" spell after visiting a single Shrine on the map. Now AI heroes should visit a Shrine in order to "know" the spell there.
2) Arena was still considered as a valuable object to visit even after visiting one. Arena can be visited only once per map even if there are multiple Arenas on the map.
3) expand the list of spells the AI currently does not know how to use:
- Earthquake
- Haunt
- Identify Hero
- Set Air Elemental
- Set Earth Elemental
- Set Fire Elemental
- Set Water Elemental
- Teleport (don't mix with Dimension Door)
- View Artifacts
- View Heroes
- View Mines
- View Resources
- View Towns
- Visions
So in this case there is no need to …
> Fix AI logic for visiting Shrines and Arena

- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
This pull request fixed multiple issues with evaluation objects on the Adventure Map for AI heroes:
1) pathfinding for couriers was not taking into an account possible Dimension Door spell usage.
2) for some objects (Oasis, Watering Hole, Magic Well and Stables) we use distance from a hero in order to analyze whether it is worth to visit the object. However, previously we did not take into account a situation when a hero could have Dimension Door spell. This was making AI heroes to use Dimension Door to reach objects which are less valuable than others.
> Add checks for object reachability when calculating their value for AI heroes

- src/engine/image.cpp
- src/engine/image.h
This PR contains changes made in https://github.com/ihhub/fheroes2/pull/7233
While working on https://github.com/ihhub/fheroes2/pull/7233 there were made some necessary for that PR changes in the code, but PR became very big. To reduce the size of that PR and to properly test and merge some changes this PR is made. It contains:
- improved image processing logic for single-layer images: currently (in master build) some functions analyze and change the 'transform' layer of single-layer images which is not correct (wastes resources and in some places may give unpredictable result);
- clean up `image.h` and `image.cpp` code to make Clang-Tidy a little happier.
> Improve image processing logic for single-layer images

- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_hotkeys.h
- src/fheroes2/heroes/heroes_dialog.cpp
This makes it possible to press the Dismiss hotkey in the hero screen, by default "D".
Additionally it was discovered that the last hotkey didn't show up in the hotkey dialog due to both the call to `reserve()` and the for loop in `Game::getAllHotKeyEvents()`.
> Add Dismiss hotkey to hero screen and fix last hotkey not showing up in the hotkey dialog

- src/fheroes2/battle/battle_only.cpp
> Fix missing redraw in Battle Only dialog after cancelling hero selection

- src/fheroes2/game/game_highscores.cpp
This PR reworks the High Score screen render: cache background with the static part of animation and update only this part of screen while rendering next monsters animation frame.
> Avoid redrawing the whole High Score screen while performing monsters animation to reduce CPU usage

- android/app/src/main/java/org/fheroes2/ToolsetActivity.java
- android/app/src/main/res/values-ru/strings.xml
- android/app/src/main/res/values/strings.xml
> Android Toolset: handle potential errors when trying to launch an external activity to download the HoMM2 demo

- src/fheroes2/dialog/dialog_thievesguild.cpp
This makes the thieves guild show with evil stone background if that interface type is chosen.
When visiting the oracle the good interface will always show because the Oracle isn't playing on your team and should therefore not change their interface according to your alignment.
> Make thieves guild adapt background to chosen interface

- VisualStudio/fheroes2/sources.props
- src/engine/exception.h
- src/engine/smk_decoder.cpp
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/agg/agg_image.h
- src/fheroes2/game/fheroes2.cpp
close #5741
We shouldn't handle corrupted resources.
> Avoid engine execution with corrupted video files

- src/fheroes2/kingdom/puzzle.cpp
> Fix puzzle screen exit button theme

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/game/game_delays.cpp
fix #1057
This PR changes `BATTLE_OPPONENTS_DELAY` to be much less dependent on the battle speed setting and have lower delay values to be closer to the original game.
This PR changes only the animation speed of heroes before and after casting a spell.
https://github.com/ihhub/fheroes2/assets/113276641/83597066-7c70-41ea-a7cc-097eb5148307
> Change heroes animation speed (before and after casting a spell) on the battlefield, fix lack of the first (and sometimes only) animation frame.

- src/engine/h2d_file.cpp
- src/engine/image_tool.cpp
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/ui_tool.cpp
This PR is a part of #7233
This PR disables `transform()` layer for images that have no transparent (or shadow/bright transform) pixels:
- during ICN load;
- for battle arena fade effect (after the battle);
- for spell effects:
- Death Wave;
- Holy Shout;
- Earthquake;
- Armageddon;
- for Puzzle map.
Doing this will save some computation resources while processing these images: no operations with the transform layer would be performed.
This PR changes properties of many loaded images so to test it is good to check rendering of maps, in castles, battlefield, dialogs for possible transparency bugs (e.g. blacked image parts in place of transparency of sprites).
As the changes are the same for the same type of images the check may include viewing each type of render, e.g.:
- check the render …
> Disable transform layer for images where it is not needed (to speed-up image processing)

- src/fheroes2/battle/battle_interface.cpp
fix #7452 
This PR makes the engine to set "STATIC" hero animation after casting a spell.
> Fix hero last frame delay after the spell casting animation

- src/engine/image_tool.cpp
A quick fix for #7449
This PR puts the check for need of transform layer into the right place.
In previous PR it was placed to the part where non-transparent images were loaded. So the transform layer was considered as needed for all images.
There is no noticeable bug in #7449, but it does not work as intended without this fix.
> Fix the misplaced check for the need of transform layer while loading ICN images

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/game/difficulty.cpp
- src/fheroes2/game/difficulty.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
This pull request fixes multiple issues:
- apply weekly monster growth bonuses only when the first AI player starts its turn (close #6939). This eliminates a possibility to abuse this bonus by human players when they capture a castle on the first day of week.
- global events which were marked as not applicable for AI players were still used for them. For example, AI players should not have events deducting their resources in Great War II map as human players do.
> Apply AI growth bonus only on first AI player turn

- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/spell/spell.cpp
See https://handbookhmm.ru/2-spells for details.
Also renamed variables and functions with names correlated to "blind answer" to "blind retaliation" and added a few comments.
> The Shield spell should not affect the damage of the castle towers

- files/lang/be.po
- files/lang/bg.po
- files/lang/cs.po
- files/lang/de.po
- files/lang/dk.po
- files/lang/es.po
- files/lang/fr.po
- files/lang/hu.po
- files/lang/it.po
- files/lang/lt.po
- files/lang/nb.po
- files/lang/nl.po
- files/lang/pl.po
- files/lang/pt.po
- files/lang/ro.po
- files/lang/ru.po
- files/lang/sk.po
- files/lang/sv.po
- files/lang/tr.po
- files/lang/uk.po
- files/lang/vi.po
- src/fheroes2/army/army.cpp
In the original game the grammar is "Zounds... peasants" not "Zounds of peasants"
> Fix Zounds grammar

- src/fheroes2/kingdom/kingdom.cpp
The bonus which AI has should be applied only on a positive gold income.
> Add an extra check for AI Gold income bonus

- src/fheroes2/agg/agg_image.cpp
Credits to @Districh-ru for the solution.
We have to use the `Copy()` function to avoid the `_singleLayer` attribute to be set to true, because this happens when you just use the `=-operator` since the regular Army button is rightly set to be single layered after the PR #7449
Fix #7514
> Fix Army info button in level up dialog

- .github/workflows/clang_analyzer.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/code_style_check.yml
- .github/workflows/iwyu.yml
- .github/workflows/make.yml
- android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
Fixes issues like this one:
https://github.com/ihhub/fheroes2/actions/runs/5809318729/job/15748134142
Apparently, `libasan` and `libtsan` are broken or not installed on the current revision of Ubuntu 20.04 image from GitHub.
> Fix a few recently introduced code smells, fix GitHub Actions build with ASAN & TSAN

- src/fheroes2/dialog/dialog_marketplace.cpp
- src/fheroes2/kingdom/resource_trading.cpp
Fix #7547
If one (or both) of the resources is not selected (this will always happen at the beginning because we cannot select both resources at the same time) their type is `Resource::Unknown` - this means that resource is not selected.
This case is now handled and `getTradeCost()` returns 0 as we may get only nothing for nothing.
> Fix marketplace assertion if one of the resources is not selected

- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
The same event will later be handled in the `Heroes::MoveStep()` anyway.
BTW there is a difference in handling of events with "Cancel event after first visit" checkbox not set. In OG this event fires every time when a hero steps on it, even if this event has already happened in this kingdom:
https://github.com/ihhub/fheroes2/assets/32623900/4484e35a-d5b7-4c00-b65e-47950eb72e27
in fheroes2 this is not the case - such an event fires just once for each kingdom (video from this PR):
https://github.com/ihhub/fheroes2/assets/32623900/7f34d6c3-db0a-4226-81b9-249c20094d3b
I suppose that this difference is for a reason, so I'm not going to do anything about it in this PR.
> Don't handle an event on the map twice

- src/fheroes2/ai/normal/ai_normal_hero.cpp
AI heroes "knew" what is inside Treasure and Sea chests and it was visible when they ignore some chests while moving to more distant ones. This is wrong and breaks user experience of "fair" AI.
You can check this save file on master branch and this branch: 
[Chests.zip](https://github.com/ihhub/fheroes2/files/12327199/Chests.zip)
What is done in this pull request:
- make Treasure and Sea chests to have the "same" averaged value, removing the knowledge what it inside (except the fact that there is an important for the human player artifact)
- Treasure Chest should have the same distance modifier as Sea Chest
- artifact check was missing for the chests for Courier heroes
- an assertion was triggered for Sea Chests when an AI hero picks it up on the way
> AI heroes shouldn't know what exactly a Treasure or Sea Chest contains

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface.h
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/editor/editor_interface_panel.h
- src/fheroes2/game/game_interface.h
- src/fheroes2/gui/interface_base.h
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/interface_gamearea.h
- src/fheroes2/maps/ground.cpp
- src/fheroes2/maps/ground.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_helper.h
Relates to #6845
This PR adds Editor ability to place (draw) specified terrain on a map by 1x1, 2x2 or 4x4 brush or by selecting a rectangle area on map.
Terrain interconnections are not implemented in this PR and they will be done in one of the next Editor related PRs.
Currently you cannot hold mouse button and draw withe selected brush by moving the cursor as it is done in original Editor, jus one draw in the selected area by one mouse click. This function will be implemented after the implementation of terrain interconnection.
https://github.com/ihhub/fheroes2/assets/113276641/4cb8e4e7-d937-46d4-94fd-f41c8041ee53
> Implement basic terrain draw in Map Editor (currently without terrain connections)

- src/fheroes2/kingdom/puzzle.cpp
Solves https://github.com/ihhub/fheroes2/issues/7448 by allowing exiting puzzle map during reveal animation.
> Allow early exit from puzzle map during reveal animation

- src/engine/image.cpp
Relates to https://github.com/ihhub/fheroes2/issues/7574
This PR modifies the color distance calculation formula to better fit human perception (https://en.wikipedia.org/wiki/Color_difference).
One disadvantage of this PR is that it takes about 40% more time to calculate `rgbToId` array data (120 ms vs 85 ms) during game load.
For the comparison:
Ideal color transitions (click to view in non-scaled size):
Master build:
This PR:
The change is noticeable for the dark colors: (there are less noticeable flashes wile fading the credits page)
Master build:
This PR:
<details><summary>Another comparison (castle screen)</summary>
Master build:
This PR:
</details>
> Use "Redmean" color distance calculation for GetPALColorId()

- src/fheroes2/kingdom/kingdom_overview.cpp
Close #7618, relates to #7574
This PR fixes:
- update of Army Bar in Kingdom Overview if Hero is bought in a castle other than an opened one;
- rise by 1 pixel town/castle names;
- remove rendering an not needed extra shadow for Kingdom Overview dialog in case if heroes number was changed.
This PR also slightly optimizes the code (by caching some variables and by excluding some redundant operations) so it might resolve the small game hang after closing the Castle screen (#7574).
> Kingdom Overview: fix update of Army Bar in Towns/Castles, fix render of extra dialog shadow after recruiting/dismissing a hero

- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
If the selected game language is not the same as the save game then in the Hero View dialog we cannot see any name. This is because old Text doesn't support invalid characters. The new class does with ? symbols.
Before:
After:
Also castle name is not being displayed:
After:
Recruit message in the status bar will be fixed in a separate pull request.
Of course it doesn't solve the problem with invalid characters but at least it is better to show something than an empty text.
> Fix missing hero and town name in dialogs

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/maps/mp2.cpp
fix #7648
Although I'm perfectly sure about the `OBJ_HEROES` case, I'm not so sure about removed cases (barriers, monsters, resources and even other object types in PoL). Are there really any known maps where similar objects are located on water or should be accessed directly from water?
> Fix the weird logic of MP2::isWaterActionObject()

- src/fheroes2/gui/ui_dialog.cpp
- src/fheroes2/gui/ui_dialog.h
- src/fheroes2/heroes/heroes_action.cpp
close #5242
The icons are right clickable.
You can test the change using this save file:
[xanadu.zip](https://github.com/ihhub/fheroes2/files/12444369/xanadu.zip)
> Add small skill icons for Xanadu visit dialog

- src/fheroes2/heroes/heroes_action.cpp
If a map contains a lot of eyes of magi it would take ages to show all of them. This is a solution to avoid such.
Try this save file on this branch and on master:
[Hut_of_Magi.zip](https://github.com/ihhub/fheroes2/files/12441063/Hut_of_Magi.zip)
> Cancel Hut of Magi reveal area animation when a player clicks any button

- src/fheroes2/dialog/dialog_quickinfo.cpp
Fix #7670
- hero does not know skill, has all skill slots occupied = 'already has max skills'
- hero does know skill, has all skill slots occupied = 'already knows this skill'
- hero does not know skill, can learn new skills = no second brackets
- hero does know skill, can learn new skills = 'already knows this skill'
> Do not show second brackets when hero can learn secondary skill from witch hut

- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
This has been bothering me for long enough now.
Army Order sounds like and means something more similar to this
If Turn Order isn't accepted, then alternatives are "Battle Queue" or "Turn Queue".
I've changed the relevant identifiers I could find that were using some variant of "army order".
> Change Army Order to Turn Order

- src/fheroes2/battle/battle_interface.h
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/gui/interface_list.h
- src/fheroes2/gui/ui_scrollbar.cpp
Close #7497, relates to #1892
This PR implements variable size for Save/Load dialog, using StandardWindow class.
- The horizontal size of window is extended not to cut the save file names if a name was given in fheroes2 (you can rename save file in OS and if the name is very long it will be cut with '...' at the end).
- The vertical size is set automatically according to the selected screen height and available save files: dialog is not higher than (screen height - 100) and not lower than 4 rows in the list.
- Fixed rendering of slider when item count in the list is equal or less than rows in dialog (when there is nowhere to scroll in the list).
- Added setting the `needRedraw` to `true` in cases when list was changed (list item removed, list item unselected).
- Applied most proposals of …
> Rework the Save/Load game dialog to allow variable dialog size and support Evil interface

- .github/workflows/android.yml
- .github/workflows/clang_analyzer.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/clang_tidy_comments.yml
- .github/workflows/cmake.yml
- .github/workflows/code_style_check.yml
- .github/workflows/iwyu.yml
- .github/workflows/make.yml
- .github/workflows/msvc.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/translation_update.yml
This should fix intermittent "Can't use 'tar -xzf' extract archive file" failures in our CI. See https://github.com/actions/checkout/issues/1448 for details.
> Bump actions/checkout to v4

- src/fheroes2/dialog/dialog_selectfile.cpp
Fix regressions after #7662:
- fix cursor position setting in text input field in Save dialog:
- clicking to the right of a file name and trying to type a letter caused the game crash;
- if the filename was truncated with '...', clicking on it resulted in an unpredictable cursor position;
- fix display redraw after closing the Virtual Keyboard: the part outside of the Save dialog was updated with a delay.
> Fix regressions after #7662: cursor position setting in text input field and display restoration after closing the virtual keyboard

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/gui/ui_font.cpp
Relates to #7101:
Fixes the first issue (diagonal elements has offset in special effects applied to them leading to an empty gap in between lines) shown here: https://github.com/ihhub/fheroes2/pull/6194#issuecomment-1337224782
This PR:
Master build:
> Fix empty space between diagonal lines in button font.

- src/fheroes2/heroes/skill.cpp
close #7702
But I'm not sure about the wording. Why not "... that was cast by an enemy during combat"?
> Adjust the description of the Eagle Eye skill

- src/fheroes2/maps/maps.cpp
This PR optimizes the calculation of `getAroundIndexes()` function, which is used for many in-game actions (e.g. checking if we need to draw the attack cursor near the monster):
- cache some variables;
- remove the `isValidAbsPoint()` calls in the loop;
- do not do loops for tiles out of map boundaries (check it before starting the loops).
Now this function in future can be used with non-square maps, previously it used map width as map height.
> Optimize `getAroundIndexes()` function

- src/fheroes2/game/fheroes2.cpp
In this case users won't claim that the application crashes for no reason.
> Display missing resource dialog not less than 5 seconds

- .github/workflows/sonarcloud.yml
Our codebase is gradually growing (and Microsoft may be gradually getting carried away with saving money), and, when changing any popular header file that is included in many project files, or during the recurrent upgrade of GitHub Ubuntu runner images (with some newer compiler) the time for a full SonarCloud analysis is dangerously close to 30 minutes.
> Bump the timeout for SonarCloud Analyzer workflow to 60 minutes

- android/app/build.gradle
- android/build.gradle
- android/isotools/build.gradle
- script/android/install_packages.bat
- script/android/install_packages.sh
- script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/37 and https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/38 for details. Also this PR bumps target Android SDK version to 34 (Android 14) and updates the Android Gradle Plugin to the latest available version.
> Update Windows & Android dependencies

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_render.cpp
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
- src/fheroes2/world/world_pathfinding.cpp
Rename some cryptic functions and variables.
> Code cleanup for Maps::Tiles

- src/engine/localevent.cpp
- src/engine/localevent.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
Related to #7765
The ability to confirm actions is supported for moves, melee attacks, shots, and spell casts.
It would be good to check its work on desktop devices (with mouse), on touch-only devices AND on touch devices with the mouse (it should behave adequately and not require unnecessary clicks when performing operations with the mouse, as well as in the case when pointing at the cell is performed with the mouse, but triggering the action is performed with the touch). Also it would be good to check its work on PSV and Switch.
> Add the ability to confirm actions in battle for touch devices

- docs/README_android.md
Follow-up to #7767
I added this description to the README for Android, but, strictly speaking, this mechanics works on any devices with a touchpad/touchscreen (for example, on Windows tablets).
> Describe the mechanics of confirming combat actions on touch devices

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/monster/monster.cpp
- src/fheroes2/monster/monster.h
fix #7784
Units with this ability should not retaliate to an attack if they were paralyzed by this particular attack.
> Fix the logic of MonsterAbilityType::ALWAYS_RETALIATE in regard to paralyzed units

- src/fheroes2/heroes/heroes_dialog.cpp
Adjusted the position of luck and morale icons in hero info window to match the original version. Fix #1424
> Adjusted the position of luck and morale icons

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
Related to #7824
<details>
<summary>Crusaders vs Water Elementals</summary>
https://github.com/ihhub/fheroes2/assets/32623900/f6506051-9f83-48db-97e4-e39add4475df
This PR:
https://github.com/ihhub/fheroes2/assets/32623900/23afaffb-816a-4463-bcac-e5ac5cd6c2ef
</details>
<details>
<summary>Attacking wide units in reverse direction</summary>
https://github.com/ihhub/fheroes2/assets/32623900/924978ae-31e3-476b-ac62-e582e1d81009
This PR:
https://github.com/ihhub/fheroes2/assets/32623900/5fc0769e-5423-45f0-8e9e-eab2c3718dbd
</details>
> Fix the AI first strike logic

- src/fheroes2/army/army_bar.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/dialog/dialog_buyboat.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/gui/skill_bar.cpp
- src/fheroes2/resource/resource.cpp
We need to use only one class to avoid ambiguity in using text related classes. Places where the text rendering was changes:
- army / monster bar
- battle log, unit number in the battle and battle order, damage info dialog
- shipyard message about boat purchase
- primary and secondary skills bars
- resource rendering for building requirements
- `Loading video. Please wait...` text when starting The Succession Wars campaign
Also this pull request does:
- fixes long sentences in battle log (fix #6357):
- open battle log has the same offset between lines like every else in the game: 17 pixels instead of 15 pixels. In this case the log is by 8 pixels higher. The text offset in the log is 16 pixels from all sides.
To test pull request compare the corresponding dialogs with texts on master …
> Reduce old Text class usage within the code

- src/fheroes2/ai/normal/ai_normal_spell.cpp
Fixes #7656  . Fixes #7793.
Kept it in the same PR for easier testing since all changes are relative to each other.
- Added bonus value to damage spells if it destroys a stack (most noticeable with spells such as Chain Lightning and Armageddon)
- Better estimate of enemy spellcasting potential for Anti-magic
- Haste/Slow bonus was too high
- Slight reduction of priority on Blind and Berserk
- Bigger bonus for a permanent resurrect
> Adjust AI combat spell heuristics

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/ai/normal/ai_normal_spell.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
Fixes #7857 . Handfighting check caused AI to flip between defence and offence modes constantly. Also wrapped a common unit modes check as a function.
> Fix archer evaluation regression

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface.h
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/editor/editor_interface_panel.h
- src/fheroes2/gui/cursor.cpp
- src/fheroes2/maps/maps_tiles_helper.cpp
https://github.com/ihhub/fheroes2/assets/19829520/6185e4ee-d468-495e-9af2-1a95c6744956
There are 2 problems which should be addressed later:
- while changing the terrain we should remove all **main** objects from a tile
- while using the eraser we should remove all **main** objects from a tile
Both issues will be addressed in a separate pull request.
> Add functionality to place monsters in the Editor

- src/fheroes2/editor/editor_interface.cpp
0 means default. This is important as we need to save this value into the map format and later read and set during map loading.
> Fix the correct default monster count in the Editor by default

- src/fheroes2/editor/editor_interface_panel.h
Because a new map is always filled with Water so a user needs to make another selection to select another terrain type.
> Make Grass as a default terrain for new maps in the Editor

- src/fheroes2/editor/editor.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_mainmenu.cpp
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_hotkeys.h
- src/fheroes2/game/game_mainmenu.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
Since we are going to release the Editor in the future we should start building it for release builds now to catch any issues in the code. This will also help us with testing as we don't need to provide debug builds anymore. A special config flag is required to prevent users playing with an unfinished product and complain about it.
> Build the Editor for release but allow only with a specific config flag

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/army/army_ui_helper.cpp
- src/fheroes2/army/army_ui_helper.h
- src/fheroes2/battle/battle_dialogs.cpp
Fix #1611
Margins fixed and displaying starts from the right of the window so overlapping is more appealing. 
To test with different army sizes you can setup a hardcoded army in battle_dialogs.cpp, l. 500:
```
Troops killedcustom = Troops(); 
Troop troop = Troop(Monster::AIR_ELEMENT, 10);
Troop troopBoar = Troop( Monster::BOAR, 10 );
killedcustom.PushBack( troop, troop.GetCount() );
killedcustom.PushBack( troopBoar, 5 );
const Troops killed1 = killedcustom; //_army1->GetKilledTroops();
```
I'm new to c++ and memory management on this level, so if you could be extra alert on that while reviewing, then that would be great.
> Combat victory window creature position

- src/fheroes2/dialog/dialog_quickinfo.cpp
This will tell you when right-clicking a barrier if the corresponding tent has been visited or not.
This is helpful for those XL maps when you don't remember what colors of tents you have visted and don't want to play Where's Waldo trying to find them.
> Add "tent visited" info to barrier quick info dialog

- src/fheroes2/army/army_ui_helper.cpp
- src/fheroes2/battle/battle_dialogs.cpp
> Fix troops sprites overlap in quick info

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/gui/interface_icons.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/heroes/heroes_spell.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
fix #7930
`QuickInfo()` API was somewhat overcomplicated - too many overloads, multiple default arguments, so I tried to put it in some order.
> Show proper Quick Info window for a hero during battle, reorganize the functions related to the Quick Info display

- src/fheroes2/dialog/dialog_recruit.cpp
Fix #7936 
This PR fixes MIN/MAX button render when switching creature upgrades in recruit window.
https://github.com/ihhub/fheroes2/assets/113276641/063dd50c-877d-4aee-bdbd-9f9b1eb170f6
> Fix recruit dialog MIN/MAX button when switching creature upgrades

- android/build.gradle
- script/android/install_packages.bat
- script/android/install_packages.sh
- script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/39 for details. Also this PR bumps AGP version to 8.1.2.
> Update hashes for Android & Windows dependency packages

- src/engine/rand.cpp
- src/engine/rand.h
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/ai/normal/ai_normal_castle.cpp
- src/fheroes2/ai/normal/ai_normal_spell.cpp
- src/fheroes2/battle/battle.h
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_army.h
- src/fheroes2/battle/battle_catapult.cpp
- src/fheroes2/battle/battle_catapult.h
- src/fheroes2/battle/battle_command.cpp
- src/fheroes2/battle/battle_command.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/battle/battle_tower.cpp
- src/fheroes2/battle/battle_tower.h
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/castle/castle.cpp
fix #7964
This PR prohibits the use of the `Battle::Arena`'s random generator by external code (mostly by AI decision-making code), which was the main reason for the non-reproducibility by a human of results of battles performed by AI.
It also redesignes the `Battle::Commands` in order to be able to perform additional checks at compile time and introduces a few minor improvements.
> Fix the random generator usage by the non-Arena code

- src/engine/rand.h
Leftover after #7967, reported by SonarCloud.
> Remove unused function

- src/fheroes2/campaign/campaign_data.cpp
Prize and not Price. Orb with capital O. This PR also makes it the same as the OG.
> Fix description text in Wizard's Isle 3rd scenario.

- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/kingdom/color.cpp
- src/fheroes2/kingdom/color.h
Fixing the patrol zone is merely a cosmetic action, but it helps to avoid some confusion.
> Move the barrier color constants to the anonymous namespace and fix the patrol zone for imprisoned heroes

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_grave.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_pathfinding.cpp
With the newer version of the GitHub Ubuntu Runner Image, which is currently [rolling out](https://github.com/actions/runner-images?tab=readme-ov-file#available-images), the `<type_traits>` header is not detected as required in a few places anymore.
> Eliminate redundant headers that were detected as required by IWYU with older compilers

- src/fheroes2/maps/mp2.cpp
This PR removes special passability for castles since the normal case passability works exactly the same.
> Remove special case for castle passability

- src/fheroes2/agg/icn.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_move.cpp
- src/fheroes2/heroes/heroes_recruits.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
- make Heroes::UNKNOWN entry first. Having this entry as non-zero was preventing to add new heroes in the future
- add much more checks in the code and rewrite certain functions to be human readable
- rearrange some code to have some sort of structure (it is still a huge mess)
This pull request needs very extensive testing to make sure that it doesn't break things:
- verify that all heroes from old saves are the same as loading the same files by master branch build.
- verify that all heroes from new saves are the same as before making a save.
- verify that heroes transferred between scenarios in campaigns are correct.
- verify that basic functionality with heroes for new and old saves is correct. This includes but not limited to checking heroes in castles, hiring and …
> Add support for the future new heroes

- .github/workflows/clang_tidy.yml
- .github/workflows/clang_tidy_comments.yml
Without special configuration, `actions/checkout` checks out so-called "virtual merge commit", which is an imaginary commit that merges PR branch into target base branch (usually `master` branch):
```
PR branch
|
V
A - B - C
/        |
M         |
\        |
D - E - F
^
|
base branch (master)
```
and Clang-Tidy checks are running on this commit. But there is a problem: if the same file was changed both in PR branch and in the base branch, then `fixes.yml` generated by Clang-Tidy will not be applicable to the pull request diff, because pull request diff is created between the PR branch and so-called "best common ancestor" of PR branch and base branch (this is just my guess, but it seems that it is). In the example above, pull request diff is generated between `A` and `F`, and changes in …
> Clang-Tidy workflow: use head ref instead of the ref of virtual merge commit

- src/fheroes2/dialog/dialog_hotkeys.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/gui/ui_window.cpp
- src/fheroes2/gui/ui_window.h
This PR optimizes `ui_window.cpp` code a bit and moves the scrollbar background generation and rendering code and button rendering code to `ui_window`. It slightly reduces the code duplication in dialogs with lists.
This PR also forces to update the dialog area on the screen on the next redraw call after the dialog is closed.
This PR affects all "Select ..." dialogs, including save/load and hotkeys dialogs: shadow and dialog rendering, dialog items (scrollbar, buttons) rendering and positioning.
> Move scrollbar background and button rendering code to 'ui_window'

- src/fheroes2/agg/agg_image.cpp
fix #7987
We must use **LoadOriginalICN()** function only when dealing with the same ICN id.
As a side bonus: we won't load certain ICN resources twice as it was before the changes.
> Fix several issues with loading ICN resources

- src/fheroes2/maps/maps_tiles.cpp
Passability rules are complex. It is hard to understand how they work. This pull request slightly brushes up the logic by doing 3 things:
- remove leftover code related to image index checks as it is not needed at all.
- remove passability rules update along the sides of a map. This is an important to do as we are going to implement passability rendering in the Editor and we should display proper things. This change does not affect anything as a hero cannot come outside the map.
- reduces code complexity by removing incapsulated loops and checks.
This is how Broken Alliance map passabilities were before the changes (click to enlarge):
and after:
I tested multiple maps to compare with master branch and the passability rules remain the same.
> Simplify passability rules

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles_render.cpp
This PR:
- replaces the `( ( ( addon._layerType >> 1 ) & 1 ) == 0 )` to more explicit and  an easier-to-understand form:
this change affects the tile passability determination when starting a new map;
- removes redundant `& 0x03` from `_layerType & 0x03` in Bottom layer objects rendering function:
this change affects map (game area) rendering;
- fixes `containsSprite()` function: currently used only for setting the sound to the ROCK object.
<details><summary>Broken Alliance map comparison</summary>
<p>
Master build:
This PR:
</p>
</details>
> Minor code clean in 'maps_tiles'

- src/fheroes2/game/game_interface.h
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_focus.cpp
- src/fheroes2/gui/interface_icons.cpp
- src/fheroes2/gui/interface_icons.h
- src/fheroes2/gui/interface_list.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
Fix #7989
This PR:
- fixes update for all types of lists (in example, save file lists) after item remove;
- disables the forced rendering of game buttons (next hero, move hero, ...) on hero focus change and castle focus change;
- removes redundant `ResetFocus()` for every frame of hero movement: `ResetFocus()` is called by `~FocusUpdater()` in `Action()` method for move to each tile;
- adds hero/castle cursor setting when no hero or castle is in focus;
- fixes redraw type setting for heroes/castles icons: in master build both lists were updated regardless of which one was specified in redraw mask;
- changes icons and focus update behavior on hero recruitment (including rescuing from Jail) and dismiss/loss;
- includes minor code clean-up;
- fixes a bug of Kingdom Overview when a hero was …
> Fix items list update after deleting an item: fix dismissing a hero from the Kingdom Overview dialog

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_thievesguild.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
This PR reworks the code for the Thieves Guild (Oracle) dialog and:
- fixes #7728;
- adds a fade animation when opening/closing the dialog;
- adds a shadow to the Oracle dialog;
- implements a workaround to eliminate color name overlap (discussible, can be reverted):
master build: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/d45c7465-1063-4159-970c-a092b00a406b)
this PR: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/4c9cb3ee-d741-4f3f-a61e-22634d20c57b);
- aligns monster sprites vertically:
master build: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/1c8d7307-aac5-44d5-bd8f-4308644b36ba)
this PR: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/0aa36d37-90e2-4265-b321-6f1141b6fab8);
- does some optimizations in …
> Rework the Thieves Guild (Oracle) dialog code and minor fixes to Hero dialog rendering

- src/fheroes2/gui/interface_events.cpp
This PR fixes this issue:
Minor issue found: after the hero diggs, the "Hero movement" button doesn't change its state to disabled if it was active before digging.
_Originally posted by @drevoborod in https://github.com/ihhub/fheroes2/issues/8000#issuecomment-1791301681_
> Reset hero path after digging and update hero buttons

- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_selectitems.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/editor/editor_interface_panel.h
- src/fheroes2/maps/map_object_info.cpp
- src/fheroes2/maps/map_object_info.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/mp2.cpp
This pull request adds an ability to place Treasure type objects on the Adventure Map within the Editor.
The new and old item lists were rendering images and text incorrectly. This pull request fixes it. To verify the changes add these lines:
```cpp
fheroes2::DrawRect( display, { destination.x + middleImageOffsetX - ( itemSprite.width() / 2 ),
destination.y, itemSprite.width(), itemOffsetY * 2 }, 80 );
fheroes2::DrawRect( display, { destination.x + textOffsetX, destination.y, background->activeArea().width - textOffsetX - 55, itemOffsetY * 2 }, 96 );
```
at line 159 in **dialog_selectitems.cpp** file (`void renderItem()` method) to observe how text and item rendering is done.
**Note**: object erasure is not handled in this pull request and requires a set of changes that should be done …
> Add treasure placement in the Editor

- src/fheroes2/dialog/dialog_thievesguild.cpp
As discussed in https://github.com/ihhub/fheroes2/pull/8006, now the Oracle dialog`s background will use the selected in options interface to be consistent with the dialog borders and many other dialogs in the game.
> Make Oracle dialog use selected interface mode (Good/Evil)

- src/fheroes2/gui/ui_window.cpp
This PR fixes a regression after #7984 
Regression (dialog was temporarily enlarged for testing):
This PR (dialog was temporarily enlarged for testing):
> Fix dialog borders generation regression for StandardWindow()

- src/engine/localevent.cpp
- src/engine/localevent.h
This should allow gestures to be handled correctly even when using different touchpads for different fingers. Although I have not met with this yet, in theory multiple touchpads can be used simultaneously, and in this case, without these changes, the game may not behave as the user expects.
> Make the touch device ID part of the finger ID

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_cell.cpp
- src/fheroes2/battle/battle_cell.h
fix #7786
https://github.com/ihhub/fheroes2/assets/32623900/5a9a4a74-0e3d-49b5-a0a1-0c7c6c64aa10
> Properly evaluate potential attack positions for wide units

- src/fheroes2/campaign/campaign_data.cpp
This adds the hardcoded alliance to scenario 6 of the Archibald campaign called Rebellion. The description text for this map states that the enemies are allied.
Will add any other I can find that are missing.
EDIT: Checked every mission for every campaign and all of them work already.
It should be noted that the original game's AI is known to attack allied heroes and flag allied mines at times. I checked whether they went and captured each other's castles.
Here are the notes I made during testing
<details>
Check scenarios:
Evil scenarios:
1 - f4a (free 4 all)
2 - f4a
3 - 1 enemy
4 - 1 enemy
5 - 1 enemy
6 - missing alliance
7 - 1 enemy
8 - 1 enemy
9 - 1 enemy
10 - 1 enemy
Good scenarios
1 - f4a
2 - f4a
3 - 1 enemy
4 - working alliance
5 - 1 enemy
6 - working alliance
7 - 1 enemy
8 - 1 …
> Add missing AI team alliance to Evil campaign's 6th scenario

- src/fheroes2/castle/buildinginfo.cpp
Currently in the `master` branch:
https://github.com/ihhub/fheroes2/assets/32623900/ebbd8948-1059-46d2-8112-b3e01a395e86
With this PR:
https://github.com/ihhub/fheroes2/assets/32623900/ae8eab62-7a7e-42f3-a482-1cbbcb4975c1
> Castle building info dialog: do not show quick info for hidden buttons

- src/fheroes2/maps/maps_fileinfo.cpp
The data should be read sequentially, jumping within a file is a bad way of reading it. I have no idea how fast file loading would become but logically it should be faster.
Also, this pull request adds a bit of data population for the new format as well.
relates to #6681
> Speed up OG map format reading

- src/fheroes2/ai/ai_hero_action.cpp
Focus update should be done only if the defender is still alive. This wasn't the case in the related ticket.
close #7881
> Fix invalid focus update after AI hero battle

- src/fheroes2/game/game_campaign.cpp
This one resolves #7511.
- Splitted difficulty icons for separate rendering to allow further changes.
- Recalculated things based on difficulty icon size and its shadow size.
- Increased dialog width, slightly inreased top margin for description text and also dialog height.
English, good interface:
Bulgarian, evil interface:
Some difficulty options disabled (test):
Dialog window width increased to 600 (test):
> Increased width and height of the Campaign Difficulty selection dialog

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/dialog/dialog_gameinfo.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/editor/editor_mainmenu.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_io.cpp
- src/fheroes2/game/game_over.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
- src/fheroes2/gui/player_info.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/view_world.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_fileinfo.h
- src/fheroes2/system/settings.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
- src/fheroes2/world/world_pathfinding.cpp
- remove duplicated methods from Settings class. It shouldn't even have Maps::FileInfo object
- rename some Maps::FileInfo members to have more readable code
> Code cleanup for Maps::FileInfo structure

- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/heroes/heroes_action.cpp
> Add Tree of Knowledge claimed and cost info to quick info dialog

- src/engine/localevent.cpp
relates to #8098 I decided to extract this part of the code as the original pull request needs a lot of extra work.
If a user has active CAPS LOCK and uses SHIFT while typing, the letters must be non-capital.
> Take into an account SHIFT and CAPS LOCK being used at the same time

- src/fheroes2/battle/battle_only.cpp
The buttons are not actually active, so it's confusing to have them there:
- Before:
- After:
Related: #4352
> Hide swap army/artifact buttons in the Battle Only

- src/fheroes2/dialog/dialog_quickinfo.cpp
Mostly for too wide translations.
- Before: 
- After: 
Related: #8173
> Fix too wide text in quick hero info box

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface.h
- src/fheroes2/editor/editor_mainmenu.cpp
- src/fheroes2/editor/history_manager.cpp
- src/fheroes2/editor/history_manager.h
- src/fheroes2/maps/map_format_helper.cpp
This will allow us to modify object properties, validate correlation between map format and World class and also edit map properties such as description or victory condition.
> Store Map Format within Editor to allow any changes to be done directly within the format

- src/fheroes2/ai/normal/ai_normal_hero.cpp
- check if at least one creature can be recruited
- evaluate the value of the object based on the number of monsters the AI can recruit
> Improve the AI logic for pay to hire dwellings on Adventure Map

- src/engine/render_processor.h
- src/engine/serialize.cpp
- src/fheroes2/maps/maps_tiles.h
- restructure few structures / classes to reduce padding. Maps::Tiles size was reduced from 96 to 88 bytes so it saves 288 KB on XL maps for 64-bit builds
- use single write operation for writing a string into a stream
> Small memory optimizations

- src/engine/image.cpp
This PR makes `makeShadow()` to make a shadow for the input single-layer image like for the fully non-transparent double-layer image.
> Implement makeShadow() to work with single-layer images

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/resources/fheroes2.rc
- speed up TIL images. Previously most of images were made as 2-layered images causing extra operations being executed. Also, rearranging loops improves CPU caching.
- change the ICN image validation conditions. ICN::UNKNOWN shouldn't be even called.
- `GetModesSprite()` function should return a const reference instead of making a copy of an image
- reduce the scope of ICN images
> Small improvements over image loading

- VisualStudio/fheroes2/common.props
- VisualStudio/fheroes2/sources.props
- src/resources/fheroes2.manifest
- src/resources/fheroes2.rc
close #8209
According to my observations, this fix works just fine in case of 1 monitor and _almost_ fine in case of multiple monitors with different scale - sometimes, when transferring the app window between monitors having a different scale, the window size suddenly changes (in the direction of the monitor to which the transfer is carried out - that is, if the window is transferred from a monitor with a larger scale to a monitor with a smaller scale, then the window becomes smaller in size, and vice versa). This happens _sometimes_ and I was not able to find some kind of pattern. Probably this is due to some of pitfalls described here:
https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows?redirectedfrom=MSDN#common-pitfalls-win32
but …
> Mark fheroes2 as DPI-aware on Windows

- src/fheroes2/ai/ai.h
- src/fheroes2/ai/ai_common.cpp
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_castle.cpp
- src/fheroes2/ai/normal/ai_normal_kingdom.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/castle/castle.cpp
- src/resources/fheroes2.rc
close #8207
Demo video:
https://github.com/ihhub/fheroes2/assets/32623900/dc1d3998-a340-4eab-ab07-5c9943f98ff3
In the `master` branch AI hero has not enough movement points to attack my hero after dismissing the Dragons:
https://github.com/ihhub/fheroes2/assets/32623900/9d076999-c7c2-4f62-a0a9-f5ae4c1806c8
> AI: implement the logic to transfer the slowest troops to the garrison at the end of the turn to try to get a movement bonus on the next turn

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_arena.cpp
Related to #8221
In this video the pumped-up AI-controlled hero surrenders (after a farewell spellcast), and is rehired by AI on the next turn:
https://github.com/ihhub/fheroes2/assets/32623900/93ab4a32-ad8f-423f-a090-de42539ed3e3
I did not introduce any special coefficients for the necessary gold reserve, because currently, when AI is going to retreat, it already has a little army, and the value of a pumped hero, and even with artifacts, in any case exceeds the value of those remnants of his army at the time of surrender.
This PR does not address a suggestion to improve the UI regarding the display of the amount of gold received due to surrender.
> Allow AI heroes to surrender if the conditions of retreat have been met, but it is impossible to retreat

- src/fheroes2/maps/maps_tiles_render.cpp
Close #8223 
This PR fixes fog generation for the next cases (V - has fog; X - no fog; ? - any fog state):
```
XVX  XV?  ?VX  ?X?
VVV  VVX  XVV  XVV
XVX  ?X?  ?X?  ?VX
```
For the fist case there was a typo in the code, for the others the fog directions analyzer is corrected according to the code for this case:
```
?X?  
VVX  
XV?  
```
> Fix fog sprite selection for several conditions

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_army.h
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/game/difficulty.cpp
- src/fheroes2/game/difficulty.h
- src/fheroes2/resource/resource.cpp
- src/fheroes2/resource/resource.h
After some thought, I decided it was worth trying the approach described by @Alucard648 in [this comment](https://github.com/ihhub/fheroes2/issues/8221#issuecomment-1875625475). Indeed, there are situations when it is a pity to lose an existing AI army during a retreat, sometimes it may even contain high-level units.
> Allow the AI-controlled hero to surrender if his kingdom has sufficient gold reserves

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal.h
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/campaign/campaign_scenariodata.cpp
- src/fheroes2/game/game_static.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/heroes/skill.h
- AI heroes should not know what skill Witch's Hut contains till they visit it
- change the logic for Scout AI heroes to prioritize skills needed for their role
- scout territory for AI hero when he receives Scouting skill
I am not sure whether it is worth adding logic for save files in order to fix incorrect visited object information for Witch's Hut. One point against it is that heroes are loaded before kingdom.
> Improve AI heroes interaction with Witch's Hut object

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/normal/ai_normal_hero.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
- speed up decision making regarding Hut of Magi
- add correction coefficient for object value calculation that depends on time. The longer AI heroes play the lesser distance penalty.
- adjust fog discovery priorities for different AI hero roles
- add fog discovery value correction over time for AI heroes. In other words AI heroes will tend to uncover more fog over time.
- ~~adjust Observation Tower evaluation to exclude fog that can be uncover just by hero stepping on the object~~
- speed up Stables evaluation
- ~~remove hardcoded bonus values for Daemon Cave~~
- avoid visiting Oasis and Watering Hole if they bring no benefit
- improve picking correct tile index for fog discovery. Previously, AI heroes will choose any first tile that allows to uncover fog. Now the search continues to …
> Improve AI heroes behavior on the Adventure Map

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_cell.cpp
- src/fheroes2/battle/battle_cell.h
- src/fheroes2/battle/battle_grave.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_pathfinding.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/monster/monster.h
Usually, units covering shooters do not attack neighboring enemy units if there are no enemy units directly threatening the covered shooters - this way they prolong their lives (and, accordingly, a cover for the shooters) without taking unnecessary retaliatory damage. However, units that ignore retaliation can safely attack any enemy.
https://github.com/ihhub/fheroes2/assets/32623900/01666961-12ab-4f6e-a049-1f7bc60d8261
This PR:
https://github.com/ihhub/fheroes2/assets/32623900/a87b69c7-1a4a-4a18-9dca-dcd618da1d7c
> Allow units that ignore retaliatory strikes to attack neighboring enemy units while covering archers

- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_selectitems.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/maps/map_object_info.cpp
- add missing 5 monster dwellings
- add all power-ups objects
> Implement Power-ups object placement in the Editor

- src/fheroes2/army/army.cpp
- src/fheroes2/army/army.h
- src/fheroes2/world/world_pathfinding.cpp
Related to https://github.com/ihhub/fheroes2/pull/8235#discussion_r1444103847
The difference with the `master` branch is that in the `master` branch, until at least one tile is found next to which there is fog, tiles next to which there is an obstacle are also considered, and there can be quite a lot of such tiles until a first tile with fog nearby is found (and then tiles without fog nearby will be discarded anyway). With this PR, there are two passes - during the first pass, only tiles are considered, next to which there is fog (and in the vast majority of cases this is the end of it), and during the second pass, the tiles next to which there is an obstacle will be considered. In a typical case, this speeds up the process, but in the worst case (when there is no fog near any of the …
> Optimize the AIPathfinder::getFogDiscoveryTile()

- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_selectitems.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/maps/map_object_info.cpp
This PR adds Mountains, Rocks and Trees objects placing in Editor.
The object selection dialog will be improved later.
> Implement Mountains, Rocks and Trees placing in Editor

- src/fheroes2/campaign/campaign_scenariodata.cpp
The OG never refers to it as "The Price of Loyalty" iirc:
This fixes this issue:
> Use proper name for PoL campaign in High Scores

- src/fheroes2/ai/normal/ai_normal_battle.cpp
Such archers may not always attack enemy units in close proximity to friendly units due to fear of friendly fire, so covering friendly units should help by attacking enemy units.
Currently in the `master` branch:
https://github.com/ihhub/fheroes2/assets/32623900/c0c659fd-8c7a-4ed1-a8f6-d8b531bbcf65
With this PR:
https://github.com/ihhub/fheroes2/assets/32623900/13e23882-fd04-4d8b-821a-10d2dab9f92d
> Defensive tactics in battle: allow units covering archers with the AREA_SHOT capability to attack neighboring units on their own

- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/heroes/skill.h
This discloses how much the diplomacy skill affects the cost of surrender, and adds that the cost of surrender is under normal circumstances half the total cost of troops remaining in the army, in gold only.
> Add infos on the cost of surrender

- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_dialogs.cpp
The window had to be widened to allow having two strings. This is better than increasing the height of the window since there's barely anything left to use in standard 640x480.
This phrasing was come up with thanks to the help of native speaker ObsessiveRepulsive:
Close #8221
> Add surrender cost to battle result dialog

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/game/game_credits.cpp
This PR adds single-layer images support and fixes Clang-Tidy issues in image `Resize()` function.
In this PR a bug with Subpixel Accuracy resize (https://github.com/ihhub/fheroes2/pull/8310) is fixed:
Also in this PR `Resize()` and `SubpixelResize()` functions are split.
> Improve image Resize() function to properly work with single-layer images and split it to Resize() and SubpixelResize() functions

- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_selectitems.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/maps/map_object_info.cpp
This PR adds Adventure (action) miscellaneous objects to editor database.
Currently this objects are added (and shown) in the order of their appearance in game ICNs.
> Implement Adventure (action) Miscellaneous objects placing in Editor

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_selectitems.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/map_format_helper.h
- src/fheroes2/maps/map_object_info.cpp
- src/fheroes2/maps/map_object_info.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_helper.h
This PR adds Landscape (non action) miscellaneous objects to editor database.
There are lots of such objects, currently they are added (and shown) in the order of their appearance in game ICNs. I hope I didn't miss any non-action objects. :)
Later we well make a new dialog to show these objects by groups (lake, cactus, flowers, ... ). Suggestions for this dialog are accepted.
> Implement Landscape Miscellaneous (non action) objects placing in Editor

- src/fheroes2/kingdom/puzzle.cpp
- src/fheroes2/kingdom/puzzle.h
This PR is a part of #8012 and includes:
- fix of some SonarQube and Clang-Tidy issues;
- fix of control panel (EXIT in radar area) render when opening a Puzzle dialog: in master branch it is often rendered with a delay;
- use `Copy()` instead of `Blit()` where possible;
- schedule the cursor update after Puzzle dialog is closed.
> Puzzle dialog rendering improvement

- src/fheroes2/kingdom/view_world.cpp
- src/fheroes2/kingdom/view_world.h
This PR is a part of #8012 and includes:
- fix of some SonarQube and Clang-Tidy issues;
- make View World use reference to the gameArea of given interface (AdventureMap / EditorInterface);
- do not make gameArea copies for the View World (use reference).
- schedule the cursor update after View World is closed.
> View World rendering improvement

- src/fheroes2/dialog/dialog_selectitems.cpp
> Use the same name for terrain objects within the Editor

- .github/workflows/clang_tidy_comments.yml
Normally, Info-ZIP's `unzip` command should remove "parent dir" path components (''../'') from the names of extracted files. However, since we don't need to recreate some directory structure here at all, It's better to be safe than sorry.
> Clang-Tidy comments workflow: junk the paths while unzipping the user-provided ZIP archive

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface.h
- src/fheroes2/editor/history_manager.cpp
- src/fheroes2/editor/history_manager.h
- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/map_format_helper.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_helper.h
- src/fheroes2/world/world_loadmap.cpp
- add checks for objects placement on the Adventure Map
- add abort logic for history manager to revert changes back to the previous state if there is an error
- add logic to load objects on the Adventure Map for the future map loading
> Change the logic to handle the future map loading

- .github/workflows/android.yml
- .github/workflows/clang_analyzer.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/clang_tidy_comments.yml
- .github/workflows/cmake.yml
- .github/workflows/code_style_check.yml
- .github/workflows/iwyu.yml
- .github/workflows/make.yml
- .github/workflows/msvc.yml
- .github/workflows/pr_author_auto_assign.yml
- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/translation_update.yml
Most workflows don't need any permissions at all.
* Workflows that use `ncipollo/release-action` need the `contents: write` to be able to upload releases;
* Workflows that create PRs (like `translation_update.yml`) and PR comments (like `clang_tidy_comments.yml`) need the `pull-requests: write` permission;
* `translation_update.yml` workflow also needs the `contents: write` permission to be able to create the PR branch;
* `pr_author_auto_assign.yml` workflow needs the `pull-requests: write` permission to be able to assign PR authors to their PRs.
I also recommend setting the minimum default permissions for the `GITHUB_TOKEN` in repo settings -> Actions -> General:
This PR also uses `github-script` instead of `bash` to parse untrusted input and set environment variables and imposes …
> GitHub Actions: Request only the minimum necessary permissions for workflows

- .github/workflows/make.yml
macOS 11 image is [deprecated](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) and will be removed by June 2024. Binaries are still x86_64.
> Migrate the build workflow from macOS 11 to 12

- src/Makefile
- src/dist/Makefile
For some reason, in the latest `devkita64` Docker image `sdl2-config --libs` uses not the "canonical" way of linking the library (`-lSDL2`), but the "full path" way (`/opt/devkitpro/portlibs/switch/lib/libSDL2.a`), what our `SDL2_mixer` linkage heuristics was not designed for, and the linkage was made in the wrong sequence.
Before:
https://github.com/ihhub/fheroes2/actions/runs/7757283009/job/21156607398#step:5:282
Now:
https://github.com/ihhub/fheroes2/actions/runs/7760886470/job/21168314572#step:5:282
> Fix the Nintendo Switch build

- src/fheroes2/battle/battle_only.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
Shifted second hero's morale and luck indicators 4px to the right.
Fix #7660
> Corrected icons alignment on the meeting screen.

- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
Three improvements in this PR:
1. Conditions for showing interrupt dialog streamlined - we always show the confirmation dialog, regardless which kind of input has triggered the interrupt.
2. It is now possible to interrupt your own auto battle mode on AI's turn.
3. It is now possible to interrupt with left/right mouse click anywhere on the screen.
AI vs AI debug mode battles are unaffected - we are making sure that the color requesting the interrupt belongs to a human.
Human vs human behaves as it suppose to, meaning you can only interrupt your own auto battle status.
Fix #4387
> Auto combat toggling improvements.

- src/fheroes2/campaign/campaign_savedata.cpp
- src/fheroes2/campaign/campaign_savedata.h
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
fix #8351
This PR also fixes a number of issues where the difficulty setting for the campaign was not taken into account. For example, in the `master` branch:
https://github.com/ihhub/fheroes2/assets/32623900/d6c2928f-17f8-4629-a79a-669f131a9e94
With this PR:
https://github.com/ihhub/fheroes2/assets/32623900/3ef52347-b339-4a2f-a01a-a180ee982cce
> Adjust the difficulties of campaign scenarios that were hard-coded in the original game

- src/fheroes2/ai/normal/ai_normal_battle.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/game/game_static.cpp
- src/fheroes2/game/game_static.h
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/resource/artifact_info.cpp
Add a description about ranged penalty being when having the archery skill.
Add ranged penalty Get function to `GameStatic` and use in relevant places in the code.
Fix #8398
> Add info about ranged penalty elimination to archery skill description

- src/fheroes2/battle/battle_dialogs.cpp
> Add multiline stats in hero info window in battle

- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/monster/monster_info.cpp
- src/fheroes2/monster/monster_info.h
Fix part of #8409 regarding a bug in the game logic.
> Fix the mechanics of Genie special ability

- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/system/save_format_version.h
fix #8418
According to my observations, in the original game, troops for carry over are always taken from the one of the heroes available in the kingdom who was hired first (including the hero originally present on the map at the beginning of the scenario). That is, if nothing happened to the hero initially present on the map, then his troops will be taken. If this hero was lost, the troops of the hero who was hired after him will be taken. If this hero was lost, but then rehired, then the troops of the hero who was hired after him will still be taken. It doesn't matter which hero won the last battle of the campaign scenario.
If the scenario was won, but there is not a single hero in the human player's kingdom, then no troops are carried over, and in the mission to which they were …
> Fix the troops carry over mechanics for campaign

- src/engine/localevent.cpp
- src/engine/localevent.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/interface_list.h
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/gui/ui_scrollbar.cpp
- src/fheroes2/gui/ui_scrollbar.h
On the smaller touch screens (mobile phones) it is quite difficult to navigate scenario list dialogs or load game dialogs if there are a lot of list items in them. Using a thin scrollbar or small arrows is the only possible way. Hero/castle lists are even harder to operate. Having more than 4 heroes/castles requires the user to fight with even smaller scrollbars.
This PR addresses this inconvenience, as presented on a video below.
https://github.com/ihhub/fheroes2/assets/84446398/da0b5d9c-1264-4230-b4a4-6d53bcf00fbc
close #2420
> Convenient list scrolling for touch screens

- src/fheroes2/dialog/dialog_selectitems.cpp
Relates to #6845 
This PR removes the leftover of initial variant of mine select dialog.
There is no need to check `selectedResourceType` since it is not used in `redrawAppearanceText()`. The `selectedResourceType` variable is changed to the correct value when the mine is changed. But the changed value was not properly transferred to the `redrawAppearanceText()` lambda.
> Fix crash when selecting mines in the map editor

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
On the smaller touch screens (mobile phones) it is quite difficult to input the correct attack angle. Currently the only option is to click on the appropriate sub-region of a target hex, which is an extremely small area on mobile phones.
This PR addresses this inconvenience, as presented on a video below. An additional input method is introduced, namely "drawing" an attack angle between the source cell and the target cell of attack. Once the attack direction sword is drawn by this method, it gets confirmed by tapping the target cell.
https://github.com/ihhub/fheroes2/assets/84446398/b4ec84f1-b297-43f2-924a-7deb1bb9f97b
Close #7070
> added possibility to "draw" the attack angle between two hexes

- src/fheroes2/dialog/dialog_selectcount.cpp
> Fix sphinx title offset

- src/fheroes2/dialog/dialog_levelup.cpp
This makes it possible to use the left and right hot keys to select between two skills in the level up dialog. 
Relates to https://github.com/ihhub/fheroes2/issues/5270
> Make the default left and right hotkeys select skills in the level up dialog

- src/fheroes2/battle/battle_dialogs.cpp
> Fix hero battle info text X offset

- src/fheroes2/army/army.cpp
If your army is only composed of Neutral troops, then this is what is displayed in current `Master`:
I've corrected it to Neutral in this PR as that is what those troops are called.
Note that in the OG this dialog would display "Multiple", but IMO that is wrong.
> Fix wrong name for Neutral race troops

- src/fheroes2/gui/ui_font.cpp
This adds a circumflex accent over the `I` and `i` in the ISO8859-16 encoding, both of which are used in Romanian.
> Add more ISO8859-16 characters

- src/fheroes2/dialog/dialog_selectcount.cpp
This changes _units_ into _creatures_ because in the rest of the game a unit is refered to as a stack of creatues not a single creature. Keeping the game more consistent.
Also changes _slot_ into _unit_ to be more inline of the rest of the terminology of the game. Though keeping instead of _unit_ are also fine. Keeping slots might be more clear, but the image selector makes it clear enough in my mind.
Example: Current on top and this suggestion down below
> Small change of phrasing of creature seperation

- src/fheroes2/CMakeLists.txt
This change fixes `fheroes2.exe` cosmetically, which was built without icon and details (Windows only).
Hopefully this will not break the compilation under e.g. Linux.
> Update CMakeLists.txt for a nicer fheroes2.exe

- files/lang/ro.po
This does another batch of translations:
* Translates the main *Config* menu and submenus (graphics, audio, etc).
* Translates the *Credits* page.
xref: #8496
> Improve Romanian translations #2

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/maps/map_format_info.h
- src/fheroes2/monster/monster.h
- src/fheroes2/world/world_loadmap.cpp
Later we can make it's own dialog window to control monster join condition, but it outside of OG scope.
> Add a window to change Monster properties

- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
`numberOfColorsPresent` variable was introduced in #8348, but then the validation of the value of this variable was removed in #8560, so now this variable is only written and never read, which is detected by (newer?) compilers as unused variable and breaks the build in strict mode.
> Fix some unused variable cases

- src/fheroes2/maps/map_object_info.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
Background layer is designed for objects that are a part of background terrain and these objects must be rendered first.
This pull request also fixes cases described [here](https://github.com/ihhub/fheroes2/pull/8588#issuecomment-2077260122).
> Update layer type for several objects

- src/fheroes2/gui/cursor.cpp
Relates to https://github.com/ihhub/fheroes2/issues/6845
To reproduce the issue on 'master' branch disable Animation within the Editor and use software rendering mode (`cursor soft rendering = on` in **fheroes2.cfg**).
When cursor image is not changed and the cursor must be shown after closing info dialog the **CursorRestorer** destructor now will now force display render to show the cursor.
https://github.com/ihhub/fheroes2/assets/113276641/07bac4c4-3282-4af5-94ec-be0d19e5617a
The cases when cursor image is changed we should be handled in the corresponding code: the corresponding cursor handler must be called. This case is not fixed in this PR.
> Fix software cursor show delay

- src/fheroes2/gui/ui_dialog.cpp
These changes are made to work better with https://github.com/ihhub/fheroes2/pull/8615
When the cursor should be hidden (showing message by the right click) now we do not change the cursor theme to help https://github.com/ihhub/fheroes2/pull/8615 to show it quicker.
Also this PR slightly optimizes the render loop. (This dialog with animation can be checked, in example, in Tavern).
> Minor improvements to 'showMessage()' function

- src/fheroes2/dialog/dialog_selectfile.cpp
This PR fixes bugs observed in #8613 :
- deletion of the last file in the Load Game dialog results in game crash;
- deleting the save name in Save Game dialog does not show that the OK button is disabled (but it is);
- deleting the save name in Virtual Keyboard in Save Game dialog does not disable the OK button;
- if the Virtual Keyboard was opened for an empty save name and the non-empty name was given the OK button remains disabled after the keyboard dialog closes.
> Fix some bugs in save/load game dialog

- src/fheroes2/gui/ui_text.cpp
This PR fixes a regression after https://github.com/ihhub/fheroes2/pull/8604: If a multi-font text contains a very-long word (e.g. a path to file that contains no spaces) the render of such text will crash if this word is not left-aligned.
It is because previously to detect that the word really is the first in the sentence the condition `x == 0` (offset from the left in text ROI) was checked. But it is not always true.
Now the engine will check if the "first" word that not fits the line starts from the right part of the line than it will be moved to the next line.
To check the issue just press right mouse button on every save file in Load game dialog.
> Fix a crash when rendering a multi-font text with very long words

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface.h
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/editor/editor_interface_panel.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- remove objects that do not belong to the new terrain
- update castles' basements according to the new terrain
Things to test:
- erasure tool works as intended
- placing water over objects that cannot be placed on water (and vice versa) results in their removal
- town basements should be updated according to new terrain
- general object placement on different terrain types
> Properly handle objects while changing terrain

- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/editor/editor_save_map_window.cpp
This PR optimizes save game/map dialog not to render the whole dialog when only the save name was changed.
> Do not redraw save dialog fully when only editing the save name

- src/fheroes2/maps/maps_fileinfo.cpp
We show file names, not map names. So we should sort maps by file name.
> Fix maps sorting in Editor

- src/fheroes2/editor/editor_save_map_window.cpp
This PR fixes the issue on small resolutions when there are more maps to display (maximum 22) than can fit the height of the map list.
Master build:
> Fix Save map dialog list rendering

- src/fheroes2/editor/editor_interface.h
- src/fheroes2/maps/map_format_helper.h
- src/fheroes2/maps/map_format_info.h
- src/fheroes2/maps/map_object_info.h
To reduce the amount of data to be stored in map files.
Also, add NONE entry to indicate empty group.
This is a format breaking change. All old maps will not work after.
> Modify ObjectGroup underlying type

- src/engine/serialize.cpp
close #8646
Such a check exists in `StreamBuf::putRaw()` method.
> Fix std::string serialization

- src/fheroes2/gui/ui_scrollbar.cpp
Fix #8644
Limit minimum slider length by the size of start part + end part ( = 2 * startPartLength )
> Fix slider render: limit minimum slider length

- src/fheroes2/maps/map_format_info.cpp
- src/fheroes2/maps/map_format_info.h
Also, add a check for versions.
We are bumping the minimum version to 2 to avoid all existing map being made in the past.
> Expand map format for the future changes

- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/editor/editor_castle_details_window.cpp
- src/fheroes2/editor/editor_event_details_window.cpp
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/editor/editor_save_map_window.cpp
- src/fheroes2/editor/editor_sphinx_window.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/gui/player_info.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
We need to figure out how to properly support texts for all languages.
> Allow only English to be used for text input within the Editor

- src/fheroes2/editor/editor_interface.cpp
If Hide Interface mode is enabled in the engine: temporary disable it while organizing the Editor's interface and then restore the setting.
> Fix Editor interface items positions when Hide Interface mode is enabled in the engine

- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact.h
- src/fheroes2/resource/artifact_info.cpp
Relates to https://github.com/ihhub/fheroes2/issues/6845
The Editor allows to placing the Magic Book on the Adventure Map.
This PR fixes the game logic that allows placing such artifacts on the map when starting a new game from the Resurrection map.
It also adds a simple Magic Book picking-up phrase.
> Allow picking-up the Magic Book artifact from the Adventure Map

- src/fheroes2/agg/agg_image.cpp
This PR fixes original heroes sprites that are used in Editor. These issues are fixed:
- all Knight heroes have two leftmost columns cut;
- green Knight, Sorceress and Warlock, and all Yellow heroes have cycling colors in their sprite;
- orange Random hero has purple flag;
- blue Random hero and orange Necromancer heroes have a shifted flag.
> Fix ICN::MINIHERO issues

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/map_format_helper.h
- src/fheroes2/maps/map_format_info.cpp
- src/fheroes2/maps/map_format_info.h
Rename the Maps::Map_Format::ObjectInfo structure to TileObjectInfo to avoid confusion with Maps::ObjectInfo.
> Rename the Maps::Map_Format::ObjectInfo structure to TileObjectInfo

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_fileinfo.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
- src/fheroes2/world/world.cpp
This PR sets the last loaded or saved map in Editor as a default selected map for the new Standard Game. It will be selected only if the map can be played.
> Set the last edited map file as a default for the new Standard game

- src/fheroes2/editor/editor_interface.cpp
This PR restricts map maker from placing Ultimate Artifact on non-digable tile.
> Do not allow placing Ultimate Artifact on non-digable terrain in Editor

- src/fheroes2/castle/castle_building_info.cpp
Fix the "copy-paste" typo in random dwelling name text
> Fix Dwelling 5 text accidentally named as Dwelling 6

- src/fheroes2/gui/interface_events.cpp
This changes the check to see what is current color according to the settings. Thanks to @Districh-ru for solution.
Fix #8723
> Fix crash when using quick switch to hero when castle is current object 

- src/fheroes2/gui/ui_text.cpp
Fix #8716 
When clicking lower than the already entered text the cursor position must be at the end of text, but not at the end of ( text + cursor_character ).
> Fix text editing crash

- src/fheroes2/dialog/dialog_selectcount.cpp
This PR forces not to use the customized hotkeys for OK and CANCEL as they can be set as input characters in text input dialog.
ESC will always be forced as a CANCEL hotkey.
ENTER will always be forced as an OK hotkey only for the single-line text.
Also the input of a new line (by pressing Enter key) is implemented for the multi-line texts.
> Force use the non-typeable hotkeys for text input dialog and allow starting a new line in multiline texts

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/fheroes2/FileManagement.java
- android/app/src/main/java/org/fheroes2/MapFileManagerActivity.java
- android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
- android/app/src/main/java/org/fheroes2/ToolsetActivity.java
- android/app/src/main/res/layout/activity_map_file_manager.xml
- android/app/src/main/res/layout/activity_toolset.xml
- android/app/src/main/res/values/strings.xml
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
close #8730
Nothing particularly complicated, Save File Manager-like UI. Only FH2M files are supported - maps in other formats could not be created by our Editor, they are "import-only", the "Extract HoMM2 assets" button in the Toolset itself successfully copes with this.
> Android: implement the file manager for FH2M maps

- src/engine/localevent.cpp
In case we decide to upgrade to SDL3.
> Code cleanup for event types to avoid having everything in 1 pile

- src/fheroes2/maps/map_format_info.cpp
- src/fheroes2/maps/map_object_info.cpp
fix #8784
Also related to #8785.
However, I am not sure about the logic of ordering in the objects list (did I put the Graveyard on the list to the correct place?).
> Put the Graveyard object to the correct category, "hide" the ugly versions of Graveyard sprites

- src/fheroes2/ai/normal/ai_normal_hero.cpp
Fix #8809
I think both the task and the list of enemy armies should be updated.
I'm not totally confident this is the right place for `_enemyArmies` (i.e. this might hide a problem elsewhere).
> Prevent a crash when a hero is killed defending a castle

- src/fheroes2/maps/map_object_info.cpp
To make sure that all objects handle object parts in the same way,
> Add checks to verify object layer type

- src/engine/serialize.cpp
- src/engine/serialize.h
- src/engine/zzlib.cpp
- src/engine/zzlib.h
- src/fheroes2/game/game_io.cpp
- src/fheroes2/game/highscores.cpp
We must avoid opening a file twice for reading and writing as it is unsafe and inefficient. Additionally, I added extra checks for stream operation failure.
> Speed up save file loading and saving operations

- src/fheroes2/ai/ai_hero_action.cpp
fix #8830
Ideally, of course, it would be necessary to correct the assessment of the hero's strength, ignoring the castle bonuses in certain cases, but these bonuses are taken into account so deeply that it is not so easy to do this.
> AI: fix the assertion failure when visiting an object that is impossible to stand on

- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
- src/fheroes2/spell/spell_info.cpp
- src/fheroes2/spell/spell_info.h
Related to #8834
This PR just makes sure that `OBJ_EVENT` objects will not be overwritten when summoning a boat. The problem (and the need) to replicate the behavior of the original game in this case is still questionable.
> Bring the logic of the Summon Boat spell for the human player in line with its logic of operation in the case of AI

- VisualStudio/fheroes2/sources.props
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/agg/icn.h
- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/editor/editor_rumor_window.cpp
- src/fheroes2/editor/editor_rumor_window.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
> Add an ability to edit Rumors for maps

- src/fheroes2/editor/editor_interface_panel.cpp
This is before the changes:
And this is after the changes:
> Show pressed monster button on Editor panel while clicking on it

- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/maps/map_format_info.h
- src/fheroes2/maps/maps_fileinfo.cpp
relates to #8717
- fix rendering while changing victory or loss condition
- fix obtain artifact incorrect metadata handling
- add an option to allow normal victory for "Accumulate Gold" victory condition
> Allow normal victory for "Accumulate gold" condition

- src/fheroes2/editor/history_manager.cpp
The value of `_latestObjectUIDAfter` was never set previously. Now it is set in `prepare()` method that is called from `ActionCreator::commit()` method.
> Fix UIDs restoration after Redo operation in Editor

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_selectitems.h
- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/editor/editor_map_specs_window.h
- src/fheroes2/gui/ui_castle.cpp
- src/fheroes2/gui/ui_castle.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/map_format_info.h
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/world/world_loadmap.cpp
close https://github.com/ihhub/fheroes2/issues/8717
This PR adds ability to set in Editor the next special conditions:
- Capture a specific town.
- Defeat a specific hero.
- Lose a specific town.
- Lose a specific hero.
It adds functions to get a list of heroes or towns present on the map.
> Implement special victory and loss conditions for heroes and towns

- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/map_object_info.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
The objects order on the same tile is determined by the current main addon object type (checked by `getObjectTypeByIcn()` function) and the layer type of the new tile being placed.
This PR fixes the `getObjectTypeByIcn()` function that was giving object type only for the main tile and giving `OBJ_NONE` for all other tiles. Now the function checks all object tiles.
It also forbids main addon swap if a new tile is the background layer one and the current tile already has an object with ID.
Master build:
https://github.com/ihhub/fheroes2/assets/113276641/140d8fac-6d5b-491a-af13-e3186577a294
This PR:
https://github.com/ihhub/fheroes2/assets/113276641/d3e15a10-bc20-41ca-b2ec-d9c4db49130f
> Fix swap of the main tile addon if a top object already exists in that tile

- src/engine/screen.cpp
- src/fheroes2/campaign/campaign_data.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/h2d/h2d.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
- src/fheroes2/spell/spell.cpp
And also a bit of code cleanup
> Fix some SonarQube code smells

- src/engine/localevent.cpp
This PR allows to type "/", "*", "-", "+" and "." symbols from the keypad then Num Lock is on.
> Allow to type "/", "*", "-", "+" and "." from the keypad

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/castle/castle_mageguild.cpp
- src/fheroes2/castle/castle_tavern.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/dialog/dialog_armyinfo.cpp
- src/fheroes2/dialog/dialog_artifact.cpp
- src/fheroes2/dialog/dialog_file.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/dialog/dialog_hotkeys.cpp
- src/fheroes2/dialog/dialog_language_selection.cpp
- src/fheroes2/dialog/dialog_levelup.cpp
- src/fheroes2/dialog/dialog_resolution.cpp
- src/fheroes2/editor/editor_event_details_window.cpp
- src/fheroes2/editor/editor_sphinx_window.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_highscores.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/player_info.cpp
- src/fheroes2/gui/ui_campaign.cpp
- src/fheroes2/gui/ui_dialog.cpp
- src/fheroes2/gui/ui_dialog.h
- src/fheroes2/gui/ui_kingdom.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes_action.cpp
This PR replaces the usage of `showMessage()` by `showStandardTextMessage()` where `fheroes2::Text` is used.
Also in such updated places `std::move()` is now mostly used to prevent sting copying.
This PR affects most pop-up messages. The most changes are done to the hero's actions dialogs.
> Use showStandardTextMessage() instead of showMessage() where possible and reduce string copying by using std::move()

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles_helper.cpp
Fix #8852
This PR fixes some issues for the original maps made by hack or some original editor bug when an action object is placed to the bottom player addons instead of the main main tile object.
It:
- reverts the implemented in https://github.com/ihhub/fheroes2/pull/6395 bottom layer to main object swap;
- fixes object type update for the case when an action object is placed to the bottom layer and the main tile object is not empty;
- fixes artifact type setting to correspond the shown artifact sprite when artifact is placed to the bottom layer.
Important! This PR fixes only the new games, not the saved games
Such map "hacks" can be observed on the map **LOSTRELI.MP2** ("Lost Relic").
Master build (the picked up artifact is not the same as shown on the map): …
> Fix original maps bottom layer (hacky) placed resources and artifacts

- src/fheroes2/editor/editor_map_specs_window.cpp
This PR fixes a small part of background that is not rendered after drop list is closed:
> Fix map special conditions render after drop list is closed

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/gui/interface_base.cpp
- src/fheroes2/gui/interface_base.h
- src/fheroes2/heroes/heroes_action.cpp
Fix #7518
This PR:
- forces the heroes icons update after any battle during player actions;
- forces heroes and castles update during AI actions after the battle with the human player;
- also makes some minor code improvements to heroes action code including AI actions.
Master build (AI actions):
https://github.com/user-attachments/assets/e20f597f-f0d1-4128-bd04-a972e5c3be6d
This PR (AI actions): 
https://github.com/user-attachments/assets/74d0a483-6f66-4e4f-a903-90fa54d75d62
This PR (player actions):
https://github.com/user-attachments/assets/76df81b6-ab0c-4d71-ab55-42d67d1c4308
> Update hero spell points indicator after the battle and before performing defeated opponent fade animation

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/ai_planner.h
- src/fheroes2/ai/ai_planner_hero.cpp
- src/fheroes2/world/world_pathfinding.cpp
- src/fheroes2/world/world_pathfinding.h
fix #9015
Currently in the `master` branch, the "patrol mode" is implemented as follows: objects outside the patrol radius are simply not considered as targets for the hero in "patrol mode". This leads to the possibility of behavior like this:
https://github.com/user-attachments/assets/2b42c8c9-7bde-4f67-89eb-566df29c11f2
This hero has the patrol mode enabled and a patrol radius of 4 tiles, thus, the artifact is "sort of" in this radius, so he does not hesitate to simply run through the already-explored territory to this object, even along a trajectory that is outside the patrol zone. I believe something similar could have happened in #9015, just on a larger scale.
With this PR:
https://github.com/user-attachments/assets/6715af88-4a08-41a1-bc3e-7f8e4372fc0e
Also, this PR removes any …
> Handle the AI hero's patrol mode in the AI pathfinder

- android/app/jni/Android.mk
- src/CMakeLists.txt
- src/Makefile
* `-Winit-self` and `-Wuninitialized` are part of the `-Wall`;
* `-Wextra-semi` is C++ only;
* New warnings: `-Wcast-qual` and `-Wsuggest-override`, which are supported both by GCC and Clang.
> Tune the set of C/C++ compiler warnings

- src/tools/extractor.cpp
To avoid potential signed overflow.
> Extractor tool: use unsigned arithmetic to calculate the hash

- src/fheroes2/ai/ai_common.cpp
- src/fheroes2/ai/ai_common.h
- src/fheroes2/ai/ai_planner_castle.cpp
- src/fheroes2/castle/buildinginfo.cpp
- src/fheroes2/castle/buildinginfo.h
- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/castle/castle_building.cpp
- src/fheroes2/castle/castle_building_info.cpp
- src/fheroes2/castle/castle_building_info.h
- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/editor/editor_castle_details_window.cpp
- src/fheroes2/game/difficulty.cpp
- src/fheroes2/game/difficulty.h
fix #9020
Currently in the `master` branch, buildings that are "under construction" have not actually been built yet, and the resources for their construction have not yet been written off from the kingdom's balance. #8358 tried to solve this issue "head-on" by pre-calculating the final kingdom balance and drawing it in advance, but this approach did not always work well due to the possibility of further redrawing the "actual" balance on top of the previously drawn "pre-calculated" one in certain cases. I decided not to try to "catch" these redraws because I believe that this approach is too error-prone, so I decided to implement the opposite logic - buy a building first, and only then build it.
With this PR:
https://github.com/user-attachments/assets/005f4d88-0d9d-4fe5-97d5-17ba3a6f49b9 …
> Rework the castle buildings construction logic

- .clang-tidy
- src/fheroes2/audio/audio_manager.cpp
Also added the `google-explicit-constructor` check for Clang-Tidy. Unfortunately, there is no non-vendor-specific check for this.
> Fix the recently introduced code smell

- src/engine/image_tool.cpp
`reinterpret_cast` is not needed here.
> Replace reinterpret_cast with static_cast

- src/engine/system.cpp
- src/engine/system.h
- src/fheroes2/dialog/dialog_file.cpp
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_save_map_window.cpp
- src/fheroes2/game/game_campaign.cpp
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
- src/fheroes2/world/world.cpp
`std::filesystem`'s `stem()` doesn't return the empty string if filename begins with dot and has no other dots (`/foo/.bar` -> `.bar`), so I preferred to replicate this behavior in our home-grown support library.
Also this PR fixes the following issues:
* Issues with files whose names consist only of an extension (`.sav`, `.fh2m` and so on) . Currently in the `master` branch, when trying to display a list of save files, among which there is at least one file with a name consisting only of an extension (e.g. `.sav`), we will get the assertion failure inside the `getLineWidth()`. Since such filenames are absolutely legal, I decided to fix this. Savefiles with this PR:
https://github.com/user-attachments/assets/121a4561-71fa-47ae-b9cd-6ba9e43ca64f
Please note that users are able to load and …
> Fix multiple file-related bugs

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/maps/map_format_info.h
This pull request solves 3 major problems with the Editor:
- before the changes any modification of **castle properties** couldn't be undone by clicking Undo button or using a hotkey. The only way to undo changes was to go to the castle and revert them manually
- we were committing actions even if no changes were being done for the map. For example, you can open a monster count dialog and just press OKAY leading to creation of a new action which does nothing.
- we were creating actions and undoing them when no changes were done. This causes the Editor to hang for few seconds (at least on my setup) as it reloads the whole map. Of course it is almost not noticeable in release mode but we were wasting heavy resources for doing nothing.
> Fix multiple issues with action creation in the Editor

- android/app/jni/Android.mk
- src/CMakeLists.txt
- src/Makefile
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
- src/fheroes2/battle/battle_cell.cpp
- src/fheroes2/battle/battle_cell.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/dialog/dialog_levelup.cpp
- src/fheroes2/dialog/dialog_marketplace.cpp
- src/fheroes2/dialog/dialog_recruit.cpp
- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_thievesguild.cpp
- src/fheroes2/editor/editor_save_map_window.cpp
- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom_overview.cpp
- src/fheroes2/maps/map_format_info.cpp
- src/fheroes2/resource/resource.cpp
- src/fheroes2/system/players.h
GCC has the [-Wmissing-declarations](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wno-missing-declarations) warning option, which can be used to detect global functions that are not declared in header files (Clang also has an option with the same name, but it has a different meaning there and is enabled by default).
Also this PR fixes the incorrect behavior of the "Gift" button in the Marketplace dialog. In the `master` branch:
https://github.com/user-attachments/assets/e95a20f2-ba5c-43b3-bb4d-8ef9110cfcb4
With this PR:
https://github.com/user-attachments/assets/5acbec32-1ec3-4338-9368-2b13c12a75cf
It's obvious from the old code that the authors wanted to do something like this, but in the end it didn't work.
> Turn on the -Wmissing-declarations warning and move all detected global functions to the anonymous namespace

- android/app/jni/Android.mk
- src/CMakeLists.txt
- src/Makefile
- src/engine/audio.cpp
- src/engine/core.cpp
- src/engine/image_tool.cpp
- src/engine/localevent.cpp
- src/engine/screen.cpp
- src/engine/serialize.h
- src/engine/smk_decoder.cpp
- src/engine/system.cpp
- src/engine/zzlib.cpp
- src/fheroes2/game/fheroes2.cpp
Close the long-standing TODO by enabling a few more useful compiler warnings. Unfortunately, SDL headers still cannot be compiled with them, and they are not treated as system headers since `sdl2-config --cflags` uses `-I` flag and not `-isystem` (gcc and clang do not issue warnings for system headers), so I had to disable new warnings for them using pragmas. Fortunately, we have relatively few files that use SDL headers.
Also this PR migrates a few places in the code to RAII.
Also this PR replaces custom `std::function`-based deleters in `std::unique_ptr`s by pointer-to-function-based. The reasons are as follows:
1. `std::unique_ptr`'s destructor as well as various methods like `reset()` require that deleter should not throw. However, with `std::function`, deleter may throw if we …
> Enable a few more compiler warnings, add more RAII for C-style "alloc()/free(), open()/close()"-like function pairs

- src/fheroes2/dialog/dialog_quickinfo.cpp
In current `master` if you right click a tree which was visited and claimed by a hero who is now under your command the quick info would say `"not claimed"`, which is wrong. Visiting the tree will not give you the chance to level up this hero.
This PR also restores the behavior observed in the original game, although originally the info would say "visited" or "not visited".
Bug introduced in: https://github.com/ihhub/fheroes2/pull/8147
> Fix visited info when hero has visited a tree under another player's control

- src/fheroes2/army/army_bar.cpp
Moving a hero's last unit by dragging and dropping caused the game to crash.
This PR adds a check that returns early if the last unit should be saved.
> Prevent redistribution of hero's last unit

- src/fheroes2/dialog/dialog_chest.cpp
Fixes #9025 by centering the gold pile and XP sprites horizontally in relation to their respective buttons ("YES" and "NO") in the adventure map treasure chest dialog window.
> Center sprites and text in adventure map treasure chest dialog

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
Fix #9123
When loading a saved game the `objectCounter` is left as it was before the game load. Oh fheroes2 start it is set to 0. So after loading a saved game from the main menu the `objectCounter` starts from 0 and it leads to duplication of map objects' UIDs.
This PR adds a loop though all loaded tiles to get the maximum UID value and set `objectCounter` equal to the found value.
**This PR fixes the cause of the #9123 issue but not the result of setting the incorrect UID that is present in the attached save file.** The attached save file will contain the explained bug which happens when `removeObjectFromMapByUID()` is called. In that save two boats with the same ID are positioned in the nearby tiles and are considered as one 2-tile object by this function.
> Set UID counter to the maximum object's UID value after loading a saved game

- src/fheroes2/agg/m82.cpp
Looking through the TODO comments, I found this one. After some thought about possible solutions and further testing, I found it a soft of misleading, since this issue (if there is one) applies not only (and not so much) to multi-tile objects, as to chains of single-tile objects, such as coasts or streams, which this function just cannot (and shouldn't) handle. In other words, this (potential) issue is not related to this function itself, but to playback of environment sounds in general.
Speaking of the playback, I have to say that I've done quite a few tests and found that the current mechanics of playing environment sounds work quite well in 3D audio mode. Yes, it would be possible to "combine" sounds in neighboring directions even more to better avoid unsynchronized sounds of the same …
> Remove the misleading TODO comment

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/game/game_startgame.cpp
This PR fixes the next issue:
>https://github.com/user-attachments/assets/192b3708-d730-4cd9-90d6-716f7db17cb0
>
>How to reproduce:
>
>* Select the "fill mode";
>* Move the mouse cursor to the radar area and press the left mouse button;
>* Scroll the editor area a bit using the radar;
>* Without releasing the left mouse button, move the cursor to the editor area and back to the radar;
>* Release the left mouse button while mouse cursor is on radar;
>* Radar does not respond to new left-click and mouse cursor movement, scrolling does not work;
>* After releasing the left mouse button again, everything starts working again.
_Originally posted by @oleg-derevenetz in https://github.com/ihhub/fheroes2/issues/9133#issuecomment-2369319940_
This PR also max a change from …
> Properly handle radar dragging in Editor when area select brush is used

- src/fheroes2/maps/maps_tiles_helper.cpp
Fix #9131
This PR also fixes a possible monster change when placing an object with a shadow to the right of the monster issue found by **Borasdk** on Discord.
> Editor and fh2m maps: set OBJECT_LAYER when placing a monster on the map

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
This PR optimizes the Damage Info pop-up dialog rendering and fixes some minor bugs:
- render dialog once to image (when it has to pop-up) and then just copy this image to `display` on every `redraw()` call;
- do not reset `Game::BATTLE_POPUP_DELAY` on every `HumanTurn` loop even if this dialog is turned off;
- properly show dialog near the two-cell wide units and do not update it if the cursor is moved to the next cell of the same unit;
- hide dialog when the cursor is moved out of the cells area (when the unit is at the edge of the battlefield).
Master build:
https://github.com/user-attachments/assets/e6a881d1-8c36-49d5-a6b1-cabbb7dadc26
This PR:
https://github.com/user-attachments/assets/98209ae5-07aa-487a-8482-385396cb529c
> Battlefield: optimize Damage Info pop-up dialog rendering

- src/fheroes2/battle/battle_interface.cpp
Fix #6357 by splitting long phrases into two lines:
For more tests I temporarily reduced the allowed text width (not in this PR, only on my PC - only for test):
> Battle log: split long phrases into two lines

- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_helper.h
Fix #9132
In original Editor the Eraser does not erase objects by selecting only their top layer parts.
In the game there could be very small or even empty top layer parts like the upper tiles of Towns.
So not to confuse map maker and to correspond the original Editor behavior this PR skips checking the Top layer when getting objects to remove in the highlighted area.
> Do not take into account top layer when selecting objects to erase.

- src/fheroes2/gui/interface_status.cpp
- src/fheroes2/gui/interface_status.h
- src/fheroes2/heroes/heroes_action.cpp
Fix #9021
This PR also basely adds sand grains to the hourglass animation during the enemy's turn.
Currently only the "loop" part of this animation is used and updated only with the hourglass (rare and non-smooth):
In future this part should be updated along with the turn progress value generation (TODO is left in the code).
Also a small code clean is performed in interface_status.cpp/.h
> Status Window: update army info after the battle, add sand grains to the hourglass animation and code clean

- src/fheroes2/maps/maps_tiles.cpp
There should be no valid reason for `World::getCastleEntrance()` to return `nullptr` for a tile with `OBJ_CASTLE`.
> Add an additional assertion

- .github/workflows/make.yml
macOS 12 is now [deprecated](https://github.com/actions/runner-images/issues/10721) with all the usual consequences - less runners, intermittent failures and so on.
> Migrate the build from macOS 12 to macOS 13

- src/fheroes2/game/game_startgame.cpp
- src/fheroes2/gui/interface_buttons.cpp
- src/fheroes2/gui/interface_icons.cpp
- src/fheroes2/gui/interface_icons.h
- src/fheroes2/gui/interface_radar.cpp
- src/fheroes2/gui/interface_status.cpp
Fix the regression introduced by #8408.
Currently in the `master` branch:
https://github.com/user-attachments/assets/5c9aed12-27e0-4170-896e-3761687a1338
With this PR:
https://github.com/user-attachments/assets/99698337-d834-46ef-be1d-60e6713c0010
> Fix the order in which events are handled by various UI elements in the "no interface" mode

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/ai_planner.h
- src/fheroes2/ai/ai_planner_hero.cpp
- src/fheroes2/ai/ai_planner_kingdom.cpp
- src/fheroes2/gui/interface_events.cpp
- src/fheroes2/gui/interface_focus.cpp
- src/fheroes2/gui/interface_status.cpp
- src/fheroes2/gui/interface_status.h
- src/fheroes2/heroes/heroes_move.cpp
This PR makes the AI turn hourglass animation more smooth and makes sand grains animation to update along with the map animation.
It also reworks the AI turn progress calculation a bit.
https://github.com/user-attachments/assets/d59f8587-e1ba-4776-931d-aec1fa84a8ce
https://github.com/user-attachments/assets/0e3fa9e6-c7b6-4918-961e-0a10f197de2c
> Make hourglass animation during AI turn more smooth

- src/fheroes2/game/game_scenarioinfo.cpp
Fix #9177 
The total area being cleared/restored is now increased ~~because the new map editor allows for longer map names than the original.~~ <-This is wrong: 17 characters was the max amount for original maps and it's the same for fheroes2.
> Fix map titles not being cleared when changing map

- src/fheroes2/castle/castle.h
- src/fheroes2/castle/castle_building.cpp
- src/fheroes2/castle/castle_dialog.cpp
Fix #9158
The issue was that:
- the order of rendering is the Statue and then the Crystal Garden;
- when these buildings are both built they have an extra image that is used instead of their separate images and is rendered above them.
This PR removes the redundant rendering of single Statue and Crystal Garden images when they are both built: it was not visible but in master build all three images ( Statue, Crystal Garden, image of both buildings) were rendered.
An extra rendering is done for the case when the Statue is built over the Crystal Garden to swap their render priority during fade-in animation.
https://github.com/user-attachments/assets/d2d7f029-e15d-4387-a859-ec46a0dd159c
> Fix Sorceress Statue construction fade-in animation

- src/engine/translations.cpp
- src/engine/translations.h
- src/fheroes2/system/settings.cpp
Since we support multi-language texts (see #9125) we do language switching, which results in heavy operations. We need to optimize the language switching work and this pull request addresses only I/O operations that usually are the slowest.
Partially relates to #6681
> Cache translation file loading operations

- .github/workflows/cmake.yml
The corresponding vcpkg issue has been fixed by the upstream:
https://github.com/microsoft/vcpkg-tool/pull/1501
> Remove the temporary workaround intended to fix the Windows CMake build

- src/fheroes2/agg/agg_image.cpp
When using Italian and French assets the deletion call to the `imageArray` vector would go out of bounds. This did not happen in release builds.
The solution was to not use the subtraction operator `-` and instead write the result that gets added to the beginning position parameter of the delete() call. Using parentheses would have worked too.
Additionally this fixes the normal font î being empty in `master`.
> Fix debug build crash with French and Italian assets

- src/fheroes2/kingdom/view_world.cpp
Even the original game doesn't have the popup dialogs but we need them to be consistent with UI everywhere.
> Add missing popup dialogs to buttons within View World mode

- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
Fixed in map info in editor, and map info and title in scenario setup.
The map title in the map setup dialog aka `game_scenarioinfo` will adjust the available length according to the width of the select button which can vary according to the language.
I chose to always center-align the text because making the text move to the left and make use of the available space there looked weird. The empty space on the left will always be equal to the width of the select button, this will ensure that if we implement a second button there with a new feature, there will be space for this new button to be of equal length to the select button so that we keep symmetry.
This PR:
> Shorten map title when too long in several places

- src/fheroes2/gui/ui_keyboard.cpp
Added Czech Virtual Keyboard
P.S. Special letters Ť, Ó, Ň, Ď that are not available on physical keyboard are not included.
> Added Czech Virtual Keyboard

- src/fheroes2/gui/ui_scrollbar.cpp
Fix #9212
Currently to update the scrollbar image position after its image is changed we call `moveToIndex( _currentIndex )` just to update image and not to move the slider.
In the future we should do position update in `setImage()` function for this case and use `moveToIndex()` only when we want to move the scrollbar (by mouse or by keyboard).
This change needs many changes in the code and tests so in this PR I've only reverted a change in `moveToIndex()` done in #9201.
> Fix incorrect Scrollbar position after it is upscaled

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/ai_planner_hero.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_helper.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- update object type after a hero boards a boat and removes the boat sprite from a tile (close #9141)
- fix a crash while a hero tries to disembark from a whirlpool (close #9214)
What was the problem:
1. A hero "owns" tile's object type while stepping on a tile. If a tile was for example marked as bush, then a hero class remembers this type and sets the tile's object type as a hero.
2. In case when a hero board a boat he remembers the type as "boat" and marks as a "hero" object type.
3. In situation when a hero travels by boat and "steps on" an object the tile is going to be marked as "hero" object type. More importantly, if an object was marked as main addon / main object part of that tile it will be moved to bottom layer objects (see `Maps::Tiles::setBoat()` method). This is the **first …
> Fix invalid behavior and crash while interacting with whirlpools by heroes on boats

- src/fheroes2/castle/castle.cpp
- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/map_object_info.h
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_helper.h
- src/fheroes2/maps/maps_tiles_render.cpp
- src/fheroes2/maps/maps_tiles_render.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
As highlighted in #9217 map tile object related code is a black box for most of developers. This code is very convoluted and hard to read. This pull request does simple renaming of **Addon** into **Object Part** to make it easier to read.
Other naming is welcome as well!
> Rename Addon into Object Part

- src/engine/image.h
- src/fheroes2/battle/battle_animation.h
- src/fheroes2/castle/captain.cpp
- src/fheroes2/castle/captain.h
- src/fheroes2/castle/castle.h
- src/fheroes2/gui/interface_gamearea.h
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_recruits.h
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/heroes/skill.h
- src/fheroes2/kingdom/kingdom.h
* `AnimationReference`: already has defaulted move assignment operator, no harm to have defaulted move constructor as well;
* `VecCastles`: just a non-owning vector of pointers, no restrictions on copy/move are needed;
* `GameArea`: already has the defaulted copy constructor, no harm to have defaulted move constructor, default assignment operators are always deleted because of the `BaseInterface & _interface` member;
* `VecHeroes`: just a non-owning vector of pointers, no restrictions on copy/move are needed;
* `Recruit`: just a POD type, no restrictions on copy/move are needed;
* `SecSkills`: just a vector of POD types, no restrictions on copy/move are needed;
* `Kingdom`: already has defaulted move assignment operator, no harm to have defaulted move constructor as well.
> Fix some code smells related to the resource management

- src/engine/image_tool.cpp
This PR combines duplicated code for the same color pixels consequence, does Transform type value calculation only if `transformValue & 0x40` is true and adds a **TODO** to decode (by checking one bit: `transformValue & 0x80`) and store the shining contour data which is used in some images, in example:
Using this contour data should help us close #3319
> Reduce code duplication in ICN decode and a little speed-up for transform decode

- src/fheroes2/agg/m82.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/maps/maps_tiles_render.cpp
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world_loadmap.cpp
This is an intermediate step towards unification of ObjectPart and ObjectPartInfo structures. The first one should be derived from the last but this will be done in another pull request.
> Rename all members of ObjectPart structure

- sonar-project.properties
I'm not 100% sure that this will work, because, apparently, this cannot be checked using a pull request.
> SonarCloud: Ignore cpp:S106 (Standard outputs should not be used directly to log anything) for command-line tools

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
The code was taken from #8429.
Reefs are always impassable so we need to check them before any other object part on a tile.
> Fix reef passability

- src/fheroes2/maps/map_object_info.cpp
- src/fheroes2/maps/map_object_info.h
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles_helper.cpp
The previous implementation was based on hardcoded values and differs from our set of object part information. Having a single source of truth is easier to handle the code.
As a bonus point this PR speeds up whirlpool initialization at map or save file loading.
> Standartize code to update POL objects

- src/fheroes2/game/game_highscores.cpp
> Fix overlapping text in the High Scores dialog

- script/android/install_packages.bat
- script/android/install_packages.sh
This PR should fix the #9234. See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/55 for details.
> Update hash for Android dependency package

- src/fheroes2/ai/ai_battle.cpp
fix #9254
https://github.com/user-attachments/assets/e3b1a880-127a-47b5-b732-c2a1e5eb79f9
> Fix the attack value estimation for a Hypnotized unit with the ALL_ADJACENT_CELL_MELEE_ATTACK ability

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles.h
We need to check bottom objects from in an opposite order for passability as action objects are considered special ones and all calculations for object parts below them are nullified.
> Update initial tile passability calculations

- android/app/build.gradle
Here is the changelog:
https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
In theory, there are no critical changes that can break something.
> Android: update the desugar_jdk_libs_nio dependency to 2.1.3

- src/engine/agg_file.cpp
- src/engine/serialize.cpp
- src/engine/serialize.h
- src/engine/tinyconfig.cpp
- src/engine/tools.cpp
- src/engine/translations.cpp
- src/engine/translations.h
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/maps/map_format_info.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_objects.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/world/world.cpp
- src/tools/82m2wav.cpp
- src/tools/extractor.cpp
- src/tools/h2dmgr.cpp
- src/tools/xmi2midi.cpp
* Added more sanity checks when loading a MO file;
* Store the translated strings themselves instead of just pointers to parts of the buffer. Previously, it was assumed that the strings in the buffer always null-terminated (and that's how it should be according to the MO format specification), but if the MO file is corrupted, then this may not be the case. As a result, this may result in reading beyond the buffer boundaries.
* Added support for both big-endian and little-endian versions of MO files with endianness autodetection;
* Removed the TODO comment regarding the hash table and an explanatory comment was written instead;
* Fixed a suspicious place in `agg_image.cpp` in regard to endianness;
* Added the ability for `ROStreamBuf` to work in two modes: "view mode" (working on top of …
> Improve & speed up the translation-related code a bit

- src/fheroes2/gui/ui_font.cpp
- src/fheroes2/gui/ui_keyboard.cpp
Add missing right single quotation mark letter generation.
It was easy to do since Russian and Ukrainian languages share the same letters and code page.
relates to #8826
> Add Belarusian language support for Virtual Keyboard

- src/engine/audio.cpp
> Use the platform-dependent byte order for the SDL audio format

- src/engine/localevent.cpp
fix #9305
In SDL2 v.2.30.7 the touchpads IDs for PS Vita have been changed: https://github.com/libsdl-org/SDL/pull/10537
Unfortunately, the change was done not in all the code and the front touch do not work in the current release version of SDL2 yet. :(
But a fix has already been made for the future version of SDL2: https://github.com/libsdl-org/SDL/pull/11442
It's good that the VitaSDK developers forced the specified fix: https://github.com/vitasdk/packages/pull/324
and everything should work fine after we update the ID for touchpad.
> Update PS Vita touchpad ID after it has changed in SDL2 v2.30.7

- Makefile.vita
- src/engine/dir.cpp
- src/engine/dir.h
- src/engine/system.cpp
- src/engine/system.h
fix #9309
* Don't try to find the actual case-sensitive path using its case-insensitive variant;
* Use the native filesystem API to get the list of files in a directory instead of `std::filesystem::directory_iterator`;
* Place the fheroes2 version info into the `param.sfo`;
* Optimize the `ListFiles::FindFileInDir()`.
> Speed up getting a list of files on PS Vita

- src/fheroes2/ai/ai_planner_castle.cpp
Follow-up to the #9283
Use the correct terminology: we don't necessarily need a **free** slot to hire units, a unit can be hired even if there are no free slots, but the same unit is already present in the army.
> AI::Planner::reinforceCastle() : paraphrase a few comments

- src/fheroes2/ai/ai_battle_spell.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
This method has the logic specific for AI - for instance, it considers the unit to be affected by the Blind spell if unit is affected by the Paralyze spell. This is handy for AI, but is not suitable for general use.
> Move the Battle::Unit::isUnderSpellEffect() with the AI-only logic to the AI code

- src/dist/engine/Makefile
- src/dist/fheroes2/Makefile
- src/dist/thirdparty/libsmacker/Makefile
- src/dist/tools/Makefile
Follow-up to #9328
Related to #9331
#9331 has occurred due to `VPATH` logic. When `VPATH` is used, all prerequisites which are not found at their paths are also looked at paths listed in `VPATH`. For instance, if we have a `Makefile` like this:
```make
VPATH := ../src/engine
all: libengine.a
[...]
```
then, if `libengine.a` is not located in the current directory, it will be looked in the `../src/engine` directory, and, if it's here (left from the previous build) and is up-to-date, it will not be rebuilt and will not be created at the current directory.
With this PR, I minimized the use of `VPATH` just to the `fheroes2` directory (there are no other options here because there are many subdirectories). For the rest of the cases, I have specified the paths to dependencies explicitly. I also …
> Limit the use of VPATH for GNU Make

- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps_tiles_helper.cpp
Fix  #9322 and fix #9184
This PR fixes such chest objects during map load and take into account a possible case when object type does not match the ICN while performing the fade-out animation.
~It also has some lines updated by the new clang-format. :)~
> Fix a bug when picking up an object whose type does not match its sprite on the map

- src/fheroes2/battle/battle_interface.cpp
fix #9338
With this PR:
https://github.com/user-attachments/assets/258448ad-3f2c-409c-a18a-0d32e7eb065a
> Reset the damage info popup when the spell cast has been cancelled

- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/spell/spell.cpp
- src/fheroes2/spell/spell.h
The original game does not have logic where it chooses whether a spell should be Combat or Adventure and only then does randomization based on the chosen category. Instead, it simply picks a random spell based on a level.
How it was discovered: I put 30 Shrine of the First Circle on a map and visited all of them by a hero. I counted how many spells belong to Adventure category while playing the map in the original game. It was only 3 spells out of 30 instead of expected ~15 per our old logic.
The old logic in the engine also explains why the Dimension Door spell was so often in Pyramids as the chance of getting this spell was wooping 25%.
> Fix spell randomization logic for Artifacts and the Adventure Map objects

- VisualStudio/fheroes2/sources.props
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_spell_selection.cpp
- src/fheroes2/editor/editor_spell_selection.h
- src/fheroes2/maps/maps_tiles_helper.cpp
- src/fheroes2/world/world_loadmap.cpp
this pull request should be merged after #9335
> Add ability to set spells in Shrine in the Editor

- src/fheroes2/editor/editor_interface.cpp
Fix #9353
This PR force reset two cursor indicator parameters when loading or making a new map in editor.
Previously if you hold a cursor over game area when it has square cursor marker and press L to load a new map (or N to make a new one) the `_tileUnderCursor` index is stored and if a loaded/new map is smaller than this index you'll get an assertion because for the first frame it tries to render this marker beyond the map borders.
> Editor: Reset the "tile under cursor" value, stored from a previously edited map

- src/fheroes2/dialog/dialog_selectcount.cpp
Fix #9345
This PR applies language selection when positioning the text cursor and if the text language is different from the current selected language.
I also adds extra 4 pixels area at the right part of the text input field to the "positioning" clickable area to help position the cursor at the end of the line.
> Fix cursor positioning with non-English characters and improve positioning at the end of the line

- .github/workflows/make.yml
An alternative to #9360.
`ubuntu-24.04` is now `ubuntu-latest`, and all this voodoo magic that was used to install ARM64 packages on the Ubuntu GitHub image no longer works, because `apt` now uses new configs of a different format, located in different places.
This PR fixes the build by downgrading the `ubuntu-latest` to `ubuntu-22.04` for all ARM64 targets.
> Fix the Linux ARM64 build

- .github/workflows/android.yml
- .github/workflows/cmake.yml
- .github/workflows/codechecker.yml
- .github/workflows/iwyu.yml
- .github/workflows/make.yml
- .github/workflows/translation_update.yml
- sonar-project.properties
According to the information about GitHub Runners which can be found [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners) Ubuntu runners have 4 cores. This means that we can speed up the compilation as previously every runner had only 2 cores.
What was changed:
- remove the hardcoded number of threads for Sonar Scanner. It can detect them automatically.
Before:
```bash
04:35:10.371 INFO  Available processors: 4
04:35:10.373 INFO  Using 2 threads for analysis, according to value of "sonar.cfamily.threads" property.
```
After:
```bash
02:09:57.107 INFO  Available processors: 4
02:09:57.109 INFO  Using 4 threads for analysis.
```
- use `$(nproc --all)` where possible for all Ubuntu runners. This approach makes us to …
> Speed up GitHub Actions

- src/fheroes2/agg/agg_image.cpp
Spell Scroll is the only artifact that consists of 1 image so what we needed to do is to center it properly in a tile.
close #8757
> Fix Spell Scroll artifact X position on the Adventure Map

- src/fheroes2/gui/ui_keyboard.cpp
> Show '-' sign for numeric keypad only if a range allows to use negative values

- src/fheroes2/editor/editor_object_popup_window.cpp
This is to help map makers to know already placed objects:
relates to #8589
> Show Monster and Artifact names in the popup dialog of the Editor

- src/fheroes2/dialog/dialog_selectscenario.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_fileinfo.h
A tiny step forward. Plus one issue with hotkey usage was fixed.
Relates to #5270
> Expand Text Support mode for New Map selection dialogs

- src/fheroes2/maps/maps_tiles.cpp
- src/resources/fheroes2.rc
This is more a cosmetic change. The passability in general has not been changed. However, you will see less red corners for tiles.
Before the changes:
After the changes:
You can save 2 images and compare them to see what I mean by "red corners".
> Improve side tile passability logic

- src/fheroes2/maps/maps_tiles.cpp
If a tile below has impassable top part then there is no need to mark the bottom part of the current tile as impassable. These changes do **not** affect the passability.
Before:
After:
> Remove additional passability marks on the bottom part of tiles

- src/dist/Makefile.emscripten
- src/engine/serialize.cpp
- src/engine/thread.cpp
* Don't create an empty anonymous namespace for non-Emscripten builds (code smell from SonarCloud);
* Limit the scope of the disabled Emscripten-specific `-Wvariadic-macro-arguments-omitted` warning.
> Fix a few recently introduced code smells

- files/emscripten/index.html
* Add the `<!DOCTYPE html>`;
* Remove the `text-stroke` CSS property. This property is non-standard and should be used with the `-webkit-` vendor prefix only (and property with the correct name is already in use).
> Fix some of the HTML errors reported by SonarQube

- src/fheroes2/battle/battle_interface.cpp
> Display spell name in dialog for spell casting error

- VisualStudio/tools/h2dmgr/sources.props
- VisualStudio/tools/pal2img/sources.props
- VisualStudio/tools/til2img/sources.props
After #9063, `engine/image_tool.cpp` depends on the `engine/agg.file.h`, which is not included in the `sources.props` of the corresponding tools. This doesn't break the build because the file itself is in place, but it still need to be added to the corresponding `sources.props` for the sake of convenience of working with relevant projects in the Visual Studio IDE.
> Update the sources.props for tools

- src/fheroes2/army/army.cpp
- src/fheroes2/dialog/dialog_quickinfo.cpp
- src/fheroes2/heroes/heroes_indicator.cpp
The morale modifier is now calculated when using an undead army. The previous behaviour was inconsistent depending on where the modifier was coming from (artifact vs hero).
Grayed out the morale icon if the hero is using an undead army. 
fixes #2419
> Improved morale ui when all troops are undead

- .github/workflows/make.yml
- src/dist/Makefile.emscripten
- src/engine/thread.cpp
https://github.com/emscripten-core/emscripten/pull/23094 was merged recently, but there is no new release with these changes yet (and accordingly, there is no new docker image), so I decided to apply a temporary patch for now using our CI (it will be removed when the new Emscripten docker image will be released).
* It works in general;
* Background music playback is now resumed correctly (more or less, see below);
* "Feeding" the player with musical chunks from MIDI/MP3/OGG decoders by SDL_mixer is still performed in the main thread, and not in the background threads, like it's done on other platforms, so the background music still chokes when the main thread is busy with something;
* OGG backend periodically crashes like this:
```
res0.c:821 Uncaught RuntimeError: divide by zero
at …
```
> Emscripten: re-enable the -pthread compiler flag

- docs/DEVELOPMENT.md
- docs/README_emscripten.md
Related to #9411
Please note that this documentation mentions the "emsdk 4.0 or later" as a prerequisite, but currently the latest version of emsdk is 3.1.74. That's because our port requires the following change in emsdk:
https://github.com/emscripten-core/emscripten/pull/23094
and this change will be generally available only since the [next emsdk release (4.0)](https://github.com/emscripten-core/emscripten/pull/23235).
> Add the basic developer's documentation for the Wasm port

- src/fheroes2/maps/maps_tiles.cpp
This is to help in debugging and understanding of passability rules.
Also fix the number of monsters not being shown for some of Adventure Map dwellings.
> Update debug info being shown for tiles

- src/fheroes2/dialog/dialog_selectitems.cpp
This PR fixes the reset of Ore mine selection in Editor after clicking OK and then reopening this dialog:
> Fix selected Ore mine reset in Mine placing dialog (Editor)

- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/maps/maps_tiles.cpp
No passability was changed for 15 tested (mostly XL) maps.
> Simplify passability logic when a bottom tile is a true action object

- src/engine/logging.h
Related to the https://github.com/ihhub/fheroes2/pull/9444#issuecomment-2592428569
Here is the version with our "custom" launcher (non-multithreaded build, because GitHub Pages doesn't allow to return the custom HTTP headers):
https://oleg-derevenetz.github.io/fheroes2/
And here is the version with the "stock" launcher from Emscripten (and with bundled assets from the demo version):
https://oleg-derevenetz.github.io/fheroes2/demo/
I prefer to use the `emscripten_out()` and not JS `console.*` because it can be intercepted by the custom printing function in the launcher (see how it's done in the "stock" launcher above, it has a sort of "console" below the game canvas - it can be also useful for the text support mode, BTW). I don't use the `emscripten_dbg()` though, because its limitations …
> WebAssembly: improve the logging

- src/fheroes2/editor/editor_interface.cpp
> Fix overlap of FPS info and popup message in the Editor

- .github/workflows/make.yml
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> Use the github-hosted arm64 runners to build for arm64

- src/engine/localevent.cpp
- src/engine/localevent.h
- src/fheroes2/game/game_hotkeys.cpp
- src/fheroes2/game/game_hotkeys.h
Sometimes it is needed to debug with and without the developer mode.
In example: when you need to check the rendering (and you don't need the extra rendered passabilities and other) and also to check the tile info in console.
Without this PR you need to quit fheroes2, edit the fheroes2.cfg by setting the magic debug value and restart fheroes2.
This PR also adds **\`** (backquote) and **~** (tilde) to the processed keys and makes ` the default key to toggle the developer mode.
> Add a button to toggle developer mode in debug build

- .github/workflows/cmake.yml
- .github/workflows/make.yml
- .github/workflows/msvc.yml
In this PR:
* Both multithreaded and non-multithreaded WebAssembly binaries are now built in parallel;
* The WebAssembly release is not created/updated anymore, since it is mostly useless without a Web server - you can't just run it locally using the `file://` URL. In future there will be GitHub Pages version instead;
* Workflows are optimized a bit. Although there is no way to skip the matrix jobs using the job-level `if:` statement (because it is evaluated [before](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif) the matrix is applied), we still can skip the job steps depending on both external parameters (such as `github.event_name`) and matrix parameters. Thanks to this, now the jobs that should not be performed during the pushes to …
> WebAssembly: build both the multithreaded and non-multithreaded versions in parallel, optimize the workflows a bit

- src/engine/image.cpp
This PR does full `memcpy()` of image data if a full image copy is requested instead of calling `mamcpy()` in a loop for every image line.
> Do full image copy with one 'memcpy()' call

- src/fheroes2/agg/agg_image.cpp
For instance, the Android release build is failing because of this:
https://github.com/ihhub/fheroes2/actions/runs/12853012354/job/35835681593
> Fix the build with NDEBUG

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world.cpp
Relates to #5716
This PR:
- removes the logic for setting flags for pre v.1.0 experimental feature to capture Magic Garden, Windmill and Water Wheel;
- reduces the size of `ICN::FLAG32` sprites vector;
- fixes mine flag rendering when it is on (and mostly over) the top edge of the Adventure map:
Master build:
https://github.com/user-attachments/assets/aba99eeb-5597-4a09-b5a8-5b41bffeb7cb
This PR:
https://github.com/user-attachments/assets/02486932-3d6e-4fd7-8fbc-0f9212bd6578
> Fix mine flag rendering and don't crop its sprite, remove unused flag setting logic

- src/fheroes2/dialog/dialog_quickinfo.cpp
Fix the hero + level being too long for the info box. We shorten the hero name and keep the level in case this is an enemy hero and we've cast Identify Hero. Knowing the level is more useful than the name because regardless of stats it can indicate other things.
Problem:
<details>
</details>
This PR:
Reported on Discord
Current translations are compatible but they need to be updated. I suggest doing this after the merge and after the bot has updated the POs.
> Shorten hero name if name plus level is too long

- src/fheroes2/gui/interface_events.cpp
This PR is a suggested fix/compromise and works as a draft to test. More polish needs to be done before it can be merged.
fix #9474 (proposal)
This gives feedback when pressing and has the small additional bonus of helping completely new players understand why the hero can't move anymore (I've seen and heard about impatient gamers quit the game after this).
https://github.com/user-attachments/assets/82c94804-0238-47b6-a3da-b59973606cf1
The current dialog:
> Add a dialog pop up when pressing standing horse

- src/fheroes2/dialog/dialog_game_settings.cpp
Fixes this:
<details>
</details>
Likely related #9471
> Render the main menu after calling settings dialog from new game dialog

- .github/workflows/clang_tidy.yml
- .github/workflows/cmake.yml
- .github/workflows/codechecker.yml
- .github/workflows/iwyu.yml
- .github/workflows/sonarcloud.yml
- CMakeLists.txt
- src/engine/CMakeLists.txt
- src/fheroes2/CMakeLists.txt
- src/tools/CMakeLists.txt
`CMAKE_COMPILE_WARNING_AS_ERROR` is available [since](https://cmake.org/cmake/help/latest/variable/CMAKE_COMPILE_WARNING_AS_ERROR.html) CMake 3.24.
> CMake: use the CMAKE_COMPILE_WARNING_AS_ERROR instead of ENABLE_STRICT_COMPILATION

- src/fheroes2/dialog/dialog_gameinfo.cpp
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/editor/editor_map_specs_window.h
- src/fheroes2/editor/editor_save_map_window.cpp
- src/fheroes2/editor/editor_save_map_window.h
- src/fheroes2/game/game_scenarioinfo.cpp
> Increase maximum allowed map name length from the original 17 characters to 50

- src/fheroes2/heroes/heroes_indicator.cpp
- all values are going to be rendered strictly within the given black area.
- if an experience string is too long "M" (million) notation is going to be used
relates to #9433
> Rework rendering of experience indicator

- script/homm2/extract_homm2_resources_from_cd_image.sh
Instead of following the same pattern as Succession Wars and Price of Loyalty CDs, which maintained the maps and data resources in plain directories, the Gold CD stores these resources within a CAB file, extracted by the installer during installation.
This change extracts map and data resources from this CAB, when given a Gold CD image.
I've verified that this works as expected against the original Gold CD image.
> Extract resources from Gold CD CAB

- src/engine/image.h
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/army/army_bar.cpp
- src/fheroes2/dialog/dialog.h
- src/fheroes2/dialog/dialog_box.cpp
- src/fheroes2/dialog/dialog_giftresources.cpp
- src/fheroes2/editor/editor_daily_event_spec_window.cpp
- src/fheroes2/editor/editor_event_details_window.cpp
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/editor/editor_sphinx_window.cpp
- src/fheroes2/gui/skill_bar.cpp
- src/fheroes2/gui/ui_dialog.cpp
- src/fheroes2/gui/ui_dialog.h
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
- src/fheroes2/maps/map_format_info.h
- src/fheroes2/maps/maps_objects.cpp
- src/fheroes2/maps/maps_objects.h
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
- src/fheroes2/world/world_loadmap.cpp
- the Adventure Map event now supports giving a Secondary Skill and also Experience
- the corresponding Editor dialog was reworked to add the new functionality
- many other places where we call a separate dialog to set amount of something were lacking needed images
close #8731
> Expand the functionality of the Adventure map event

- src/fheroes2/heroes/heroes_dialog.cpp
> Fix assertion for a maximum spell points

- src/fheroes2/agg/agg_image.cpp
This fixes a case where min button and max button's don't have the same shadow and are not at the same offset in dialogs when using German assets. This is due to #9525 where embedded shadows were removed from these buttons. The German Min button was forgotten.
The German min/max buttons are the same as the engine generated ones and equal to the English ones anyways.
> Fix German original assets MIN button

- changelog.txt
- script/packaging/common/fheroes2.metainfo.xml
- src/fheroes2/maps/maps_tiles.cpp
This is due some maps being hacked or the OG editor's bugs.
Since, we haven't released 1.1.6 this PR serves as a hot fix which should go to the release.
> Remove assertion for passability checks

- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/gui/skill_bar.cpp
- src/fheroes2/heroes/skill.cpp
- src/fheroes2/heroes/skill.h
This PR:
* Fixes the minimum value of the Knowledge skill (it should be 1 and not 0);
* Fixes the MIN/MAX buttons operation in the `Dialog::SelectCount()`. How to reproduce:
* Open the dialog;
* Try to enter some value other than min/max value using the keyboard;
* Press the MIN or MAX button;
* Try to edit the new value (e.g. by pressing the Backspace button).
In the `master` branch:
https://github.com/user-attachments/assets/186643b6-4caa-4ec4-aead-3fe184a2fabb
With this PR:
https://github.com/user-attachments/assets/417318f1-c0d6-485f-a4f5-5ebea7b850cd
> Fix the operation of MIN/MAX buttons in various dialogs

- src/fheroes2/maps/map_object_info.cpp
- src/fheroes2/maps/maps_tiles_render.cpp
This change makes the rendering little bit slower. However, this change is required to add future objects with animation. In the future we are going to remove `ICN::getAnimatedIcnIndex()` function to avoid hardcoded stuff to be present.
How it was tested to make sure that the animation logic is correct:
modify `void populateObjectData()` function to add the following code:
```cpp
for ( const auto & objects : objectData ) {
for ( const auto & objectInfo : objects ) {
for ( const auto & info : objectInfo.groundLevelParts ) {
if ( info.animationFrames == 0 ) {
continue;
}
for ( uint8_t i = 0; i < info.animationFrames * 2; ++i ) {
assert( ICN::getAnimatedIcnIndex( MP2::getIcnIdFromObjectIcnType( info.icnType ), info.icnIndex, i, true ) == info.icnIndex + ( i % info.animationFrames ) + 1 );
} …
```
> Use Adventure Map object animation information from a correct place

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/editor/editor_castle_details_window.cpp
- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/gui/ui_button.cpp
- src/fheroes2/gui/ui_button.h
- src/fheroes2/gui/ui_text.h
- src/fheroes2/monster/monster.cpp
- src/fheroes2/monster/monster_info.cpp
- src/fheroes2/monster/monster_info.h
- src/fheroes2/resource/artifact.cpp
- src/fheroes2/resource/artifact_info.cpp
- src/fheroes2/resource/artifact_info.h
This pull request contains 2 major changes:
- highlight that some variables contain **untranslated** text. This is important for developers to know this if translation of a text is required before rendering it
- remove hidden string translation code from all button related functions. The code has become bigger but much easier to understand
> Standardize translation related code

- src/fheroes2/battle/battle_main.cpp
fix #9592
If I understood correctly, this is exactly how it should work. Here is a video of the artifact transfer process (the source has been modified a bit to allow the artifact transfer on retreat or surrender):
https://github.com/user-attachments/assets/a3ffc057-92b0-45b4-8c76-36117e24208b
> Fix the logic of transferring artifacts after a battle

- src/fheroes2/heroes/heroes_move.cpp
fix #9600
On the `master` branch:
https://github.com/user-attachments/assets/db0c90f8-0cf3-440a-a9b7-ee3bbc94c5d8
With this PR:
https://github.com/user-attachments/assets/4adeafe3-a656-40af-8b50-125e140d3ef1
> Do not center on the defeated hero after an instant movement

- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps_objects.cpp
- src/fheroes2/maps/maps_objects.h
- src/fheroes2/system/save_format_version.h
- src/fheroes2/world/world_loadmap.cpp
This pull request fixes the problem with incorrect text display in Sign and Bottle Adventure Map objects for the following situations:
- a save file with sign text was saved under one in-game language but then loaded under another one
- a sign was saved for a map of language A then the map was started to be played with an in-game language B
The first case will be also fixed for the original maps.
relates to #8589
> Add proper translation support for Sign objects

- src/fheroes2/gui/interface_gamearea.cpp
- src/fheroes2/gui/interface_gamearea.h
- src/fheroes2/maps/maps_tiles_render.cpp
- src/fheroes2/maps/maps_tiles_render.h
Relates to #5716
This PR makes rendering of tall top layer objects after rendering the "ufit" sprites (heroes, monsters and other sprites that do not fit one tile). This fixes the issues: https://github.com/ihhub/fheroes2/issues/5716#issuecomment-1596156366, https://github.com/ihhub/fheroes2/issues/5716#issuecomment-1595729230, https://github.com/ihhub/fheroes2/issues/5716#issuecomment-1594354665
It also adds a check not to render flags and ghosts over the top map edge if the nearby tile is not revealed. This fixes this issue: https://github.com/ihhub/fheroes2/issues/5716#issuecomment-2678953114
The flags of enemy heroes, boats and monster's heads that are near the top map border and are under the fog are also not rendered now.
Ghosts for abandoned and haunted mines are now drawn over all …
> Fix rendering of tall objects and extra objects (ghosts and flags) over the top map edge

- src/fheroes2/game/game_static.cpp
- src/fheroes2/game/game_static.h
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/kingdom/kingdom.cpp
- src/fheroes2/kingdom/kingdom.h
The previous logic was not intuitive to understand as we were mixing objects that effect Morale and Luck. These 2 effects are now separate. This change removes hardcoded list of objects so while adding new ones we don't need to modify the hardcoded stuff all over the code. Moreover, since Morale and Luck are separated so we could in the future add objects that affect both types.
A bonus point: the logic is much faster now since we run through a list of visited objects only once.
> Clean up code for Morale and Luck effect Adventure Map objects

- src/fheroes2/ai/ai_hero_action.cpp
The best way to observe the incorrect state is to give the control for the AI in debug mode.
> Fix visited status for certain Adventure Map objects for AI

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
`master` branch, notice that sometimes the dialog "freezes":
https://github.com/user-attachments/assets/30138933-0b12-4023-a956-6fbb8cc349a4
this branch:
https://github.com/user-attachments/assets/e84c55c1-6a3b-41b9-9708-b5084855b85d
> Fix a delay during battle after showing a monster info dialog by right clicking

- src/fheroes2/ai/ai_battle.h
- src/fheroes2/ai/ai_battle_spell.cpp
> Implement Dragon Slayer spell selection for the AI

- src/fheroes2/system/settings.cpp
This is the proposed fix to #9625.
The issue is that we are trying to find the race of a player that is not in game. I've added an extra check to return the "good" interface in that case.
We might disagree and say that we should instead use the race of the selected hero in battle only mode, but I wasn't sure if this is really what we wanted and felt it might be safer to simply consider it outside of a game and review the code later if we want to change that logic.
cc: @ihhub 
Fixes #9625
> Do not apply dynamic interface if the player is not ingame

- src/fheroes2/ai/ai_hero_action.cpp
Fix #9629 
If Genie Lamp is removed after all Genies are recruited AI should not mark this tile (without any object) as visited.
> Do not set visited state if genie lamp is removed from the map

- .github/workflows/sonarcloud.yml
The previously used action is marked as [deprecated](https://github.com/SonarSource/sonarcloud-github-c-cpp).
> SonarCloud: use the new SonarSource actions instead of the deprecated one

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface.h
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/editor/editor_interface_panel.h
- src/fheroes2/editor/history_manager.h
Buttons redu and undo are disable if no actions were made in the Editor.
Also they become disable/enable if actions were made/revert in the Editor.
> Add disable/enable logic for Editor's undo/redo buttons (#9450)

- .github/workflows/cmake.yml
I'm tired of waiting for GitHub to update its Windows image.
> CMake (Windows SDL2) job: auto-update vcpkg to the latest version

- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/castle/buildinginfo.cpp
- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle_building_info.cpp
Fixes #8808.
I also slightly adjusted the wording to more clearly indicate that:
* Flying units aren't affected by the moat's movement penalty, but do still suffer the defense penalty if they land in it.
* The moat ends a unit's turn on *any* movement in it, not just entering.
> Add defense penalty to moat building info and adjust wording

- src/fheroes2/gui/interface_list.h
Lists (save/load etc.) can be scrolled with arrow keys or navigation keys (page up/down, home, end), but the selection doesn't move with the latter, making them useless without additional mouse input and in conflict with arrows keys (list position jumps back to selection on arrow presses). This PR resolves that conflict by moving selection along with navigation keys, making all navigation keys useful and working together.
> List item selection moves along with navigation keys

- src/fheroes2/gui/ui_keyboard.cpp
This PR fixes the issue posted by @oleg-derevenetz in https://github.com/ihhub/fheroes2/issues/9672#issuecomment-2755582485
> Fix close of the caller dialg when closing the Virtual keyboard dialog by a hotkey

- src/fheroes2/gui/ui_button.cpp
This PR allows to use CANCEL hotkey or OK hotkey to close the dialog that has the only one OK or CANCEL button in the `buttonGroup` to assist players interaction with such dialogs.
This PR also adds reset of hotkey pressed state after hotkey is processed to avoid possible processing of this hotkey in the caller dialog.
> Allow to close a dialog with a single OK or CANCEL button in a button group by OK and CANCEL hotkeys

- src/fheroes2/gui/ui_window.cpp
A small mistake made in #9597.
With this PR:
> Fix gap between buttons in symmetric button dialog

- src/engine/image.cpp
- src/engine/image.h
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/gui/ui_window.cpp
- src/fheroes2/heroes/heroes_meeting.cpp
Fixes: https://github.com/ihhub/fheroes2/issues/7106
Previous pr with duscussions: https://github.com/ihhub/fheroes2/pull/9654
I moved the shadow generation from `StandardWindow::render()` to new function - `addShadowForRectangularDialog()`.  `StandartWindow`, `Heroes::MeetingDialog` and `Battle::PopupDamageInfo` are using this function
> Add shadow for Heroes Meeting dialog

- src/fheroes2/gui/ui_text.cpp
When displaying the truncated strings in edit fields they are redrawn for every cursor blink and for every string change and the size of the truncation symbol is recalculated each time.
This PR caches this width in std::map for the size of the given font.
> Cache the truncation symbol width ("...")

- src/fheroes2/heroes/heroes_action.cpp
> Add color name to Traveler Tent's popup message

- .codechecker-ignore
- .codechecker-review-status-config
- .github/workflows/codechecker.yml
See https://github.com/Ericsson/codechecker/blob/master/docs/analyzer/user_guide.md#setting-with-config-file for the config file syntax details.
The idea here is to mark as false positive hashes that correspond to the specific issues instead of ignoring the entire file (although, of course, we still can ignore the entire file if necessary). In any case, it will increase flexibility.
> CodeChecker: use the new recently introduced config format

- src/fheroes2/dialog/dialog_recruit.cpp
- src/fheroes2/dialog/dialog_selectcount.cpp
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
close #1631
related to #9672
Key changes compared to `master` branch:
1. The value starts to be entered from scratch when the corresponding dialog window is opened or when value has been changed not using keyboard events.
2. The Backspace and Delete keys both clear the input buffer completely (the value starts to be entered from scratch - exactly as in paragraph 1). This makes the behavior more sane in a number of scenarios (especially when the range of acceptable values does not include zero).
3. The minus sign can only be entered at the beginning of the number input. The corresponding key is ignored when the number is already partially entered from the keyboard. This makes the behavior more sane when the range of acceptable negative values does not match the range of acceptable positive …
> Improve the input of numbers from the hardware keyboard

- src/fheroes2/castle/castle_dialog.cpp
- src/fheroes2/castle/castle_town.cpp
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/editor/editor_castle_details_window.cpp
- src/fheroes2/gui/statusbar.cpp
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
- src/fheroes2/heroes/heroes_dialog.cpp
This PR fixes text alignment issues with descenders in status bars across the game and adds a new ROI-based text drawing method to improve text rendering control. The issue was most noticeable with characters like `g, j, p, q, y`
Closes https://github.com/ihhub/fheroes2/issues/1745
Closes https://github.com/ihhub/fheroes2/issues/1675
Closes https://github.com/ihhub/fheroes2/issues/1728
> [!IMPORTANT]
> I'm new to C++ and this project. I'm sure there are test cases I'm missing. Please let me know and I'll work to improve! 
- Fixed status bar text alignment by removing the +3 Y-offset in ROI definitions
- Added a new `drawRoi` method to `MovableText` class for region-based text rendering
- Updated status bar text rendering to use the new ROI-based drawing method
- Improved text positioning …
> Fix status bar offset to prevent text from overlapping status bar bottom border

- src/fheroes2/gui/ui_keyboard.cpp
Follow-up to the #9690
Unlike the #9690, this PR works both on virtual keyboard and virtual numpad. Currently, the "left", "right", "home" and "end" keys are supported.
> Allow to move the virtual keyboard cursor using the hardware keyboard buttons

- android/app/src/main/AndroidManifest.xml
Android 16 introduces feature "adaptive layouts" that will [ignore](https://developer.android.com/about/versions/16/behavior-changes-16?hl=en#adaptive-layouts) the orientation, resizability, and aspect ratio restrictions when app is running on screens with certain size, unless the app is a game. fheroes2 is not targeting the Android 16 yet, but it eventually will, so care should be taken to set the correct application category in advance.
> Android: set the application category to "game"

- .github/workflows/clang_tidy_comments.yml
While I'm here, let's modernize the `clang_tidy_comments.yml` workflow a bit and use a more terse syntax in some places.
> Clang-Tidy comments workflow: simplify the logic a bit

- .github/workflows/codechecker.yml
- .github/workflows/iwyu.yml
- .github/workflows/pull_request.yml
Related to #9721
Since we have a complex structure of interdependent reusable workflows, we cannot just use the `paths` option as proposed in #9721. However, we can perform the relevant filtering ourselves by writing quite a bit of code.
Unlike build workflows, which may depend on files of a diverse kind (C/C++, Java, Gradle, shell, Python, translations, even documentation, which is bundled into resulting artifacts), CodeChecker and IWYU workflows should only be run if the source files related to C/C++ were changed, so this restriction looks relatively safe. Also the CodeChecker is the slowest workflow we have.
> GitHub Actions: run the CodeChecker and IWYU workflows only if some C/C++ files were changed

- src/dist/Makefile.emscripten
When I attempted to load the game with OGG files from the GOG distribution, the emscripten build did not work out of the box.
This adds the OGG video format to the SDL2 mixer formakes to enable those music files to work.
> Add OGG audio format support for Emscripten build

- src/engine/audio.cpp
Currently, the resumption of music playback doesn't work in the non-multithreaded Emscripten builds (music tracks always start playing from the beginning), because the current logic in `master` branch relies on the use of inter-thread synchronization to ensure the correct order of actions. In the non-multithreaded Emscripten builds there are no threads, so this logic doesn't work as expected.
> Fix the resumption of music playback for Emscripten builds

- android/app/build.gradle
- src/dist/Makefile.emscripten
- src/engine/audio.cpp
- src/engine/audio.h
- src/fheroes2/audio/audio_manager.cpp
- src/fheroes2/audio/audio_manager.h
- src/fheroes2/game/fheroes2.cpp
This PR is a part of the effort to fix the #8375,  #8376, #8379, #8795.
The idea is as follows: while Fluidsynth MIDI backend operates with heavy soundfont file (which it apparently loads every time it tries to play a MIDI file), Timidity MIDI backend operates with relatively small GUS patches (and apparently it does not load those instruments that are not needed to play a specific MIDI file or maybe uses other optimizations), which minimizes the delay at the start of the playback.
To test this idea, I made a special build of `SDL_mixer` with Timidity MIDI backend on Windows and used it along with this PR. The results are shown below.
Further roadmap:
* Merge this PR;
* Merge the https://github.com/microsoft/vcpkg/pull/45141 to add the Timidity backend support to the vcpkg port;
* Build …
> MIDI: allow to pick up custom timidity.cfg

- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/gui/ui_text.cpp
- src/fheroes2/gui/ui_text.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
fix #9728
Relates to #9730 
This PR adds an `area()` method to the `Text` class that calculates the area that the displayed text string will occupy.
The multi-line text version of this method is not implemented in this PR and may be implemented later when needed.
https://github.com/user-attachments/assets/3d202691-d165-4fba-9b14-7cc65f827dd8
> Fix clearing diacritic signs in movable text used in status bar

- script/windows/install_packages.bat
The final touch.
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/60 for details.
1. Much fewer DLLs are now required;
2. Now there is no problem which backend SDL_mixer will choose if both `soundfonts` and `timidity` folders are present in the `Program Files` at the same time.
> Windows: remove fluidsynth from dependencies

- script/windows/install_packages.bat
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/61 for details.
> Windows: remove DLLs related to wavpack library

- src/engine/tools.h
Slightly optimize the `CountBits()` function not to check all 32 bits.
This PR implements the [algorithm by Brian Kernighan](https://yuminlee2.medium.com/brian-kernighans-algorithm-count-set-bits-in-a-number-18ab05edca93).
> Update the CountBits() algorithm

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/ai_hero_action.h
- src/fheroes2/ai/ai_planner.h
- src/fheroes2/ai/ai_planner_hero.cpp
- src/fheroes2/ai/ai_planner_kingdom.cpp
- src/fheroes2/game/game_startgame.cpp
close #2625
The idea is to propagate game state value all up to the function where we check it. AI heroes never even reset their ACTION state.
> End game immediately during AI turn if there are changes in game

- .github/workflows/cmake.yml
It's better to be safe than sorry.
> Windows CMake workflow: use $VCPKG_INSTALLATION_ROOT instead of the hardcoded path

- docs/README.md
They are not needed for end users but only useful for development on GitHub.
relates to #9775
> Remove SonarCloud badges from the main website page

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/game/game_static.cpp
- src/fheroes2/game/game_static.h
- src/fheroes2/heroes/heroes.cpp
- src/fheroes2/heroes/heroes.h
- src/fheroes2/heroes/heroes_action.cpp
- src/fheroes2/maps/maps.cpp
- src/fheroes2/maps/maps.h
fix #1434 
This PR makes the scouting (reveal) area to math the one in the original game.
The comparison of minimaps is shown on the screen shots below. The top revealed areas from the left to right for radius:
- 4 (hero);
- 5 (hero + Basic Scouting), the same will be for Town/Castle;
- 6 (hero + Advanced Scouting);
- 7 (hero + Expert Scouting);
- 8 (hero + Expert Scouting + Telescope artifact);
- 9 (Eye of the Magi);
- 19 (Observation Tower);
- in the bottom left - a hero at the Hut of the Magi.
Master build:
Original game:
This PR:
> Make the scouting area consistent with the original game

- src/fheroes2/ai/ai_battle_spell.cpp
- src/fheroes2/army/army_troop.cpp
- src/fheroes2/army/army_troop.h
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/castle/castle_well.cpp
- src/fheroes2/kingdom/speed.cpp
- src/fheroes2/kingdom/speed.h
This PR make some code clean in CPP/H files `battle_troop`, `army_troop` and `speed`.
In `speed` two functions are moved to anonymous namespace since they are not used outside, the speed type is now `uint32_t` to avoid casting.
In `battle_troop` and `army_troop` some methods were made inline, the private methods and variables were renamed to correspond the suggested code style and some Clang-tidy issues were fixed.
> Some code clean: battle_troop, army_troop, speed

- src/engine/localevent.cpp
- src/engine/render_processor.cpp
- src/engine/render_processor.h
- src/engine/timing.cpp
- src/engine/timing.h
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game_delays.cpp
- src/fheroes2/game/game_delays.h
This pull requests contains multiple changes related to rendering coupled with timers:
- **timing.h|cpp** files: make all methods of classes inlined as they are tiny
- **localevent.cpp**: avoid calling `fheroes2::getBoundaryRect()` since no case exists that we need it. Also, check cycling readiness just at the very end before rendering
- **render_processor.cpp**: standartize time frame for each render call
- **render_processor.h**: we missed to reset the timer when enabling cycling
- **game_delays.cpp**: we had invalid default values for some times and also we were setting some timers after resetting them
> Optimize rendering and timers

- src/fheroes2/heroes/heroes_action.cpp
fix #6965
This PR:
https://github.com/user-attachments/assets/48f430ba-4e1c-4ce2-9e29-7f374a4a35f9
> Fix skip of render end of hero's move before interacting with action object

- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/gui/ui_tool.cpp
- src/fheroes2/gui/ui_tool.h
fix #3301
This PR makes the Disruptive Ray and Teleport spells rendering look close to the original game. The "wave" effect in the original game looks a bit buggy (especially at the beginning of the Disruptive Ray spell effect) so i did not fully reproduce it.
The creatures count and movement grid are hidden during the animation like it is done in the original game.
The parameters of spell effects can be adjusted.
This PR also restructures the `RedrawTroopSprite()` method's code to apply Stone and Mirror Image visual effects also to the `_spriteInsteadCurrentUnit` that is used for some spells animations where there is a need to apply effects to the creature's sprite. Doing this there is no more need to apply such effects to `_spriteInsteadCurrentUnit` in every method that prepare it for …
> Battlefield: make Disrupting Ray and Teleport spells animation closer to the original game

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_troop.cpp
Relates to #9805
This PR only updates the Bag Luck animation to have animation delays closer to the OG.
The animation speed can be adjusted.
This PR:
https://github.com/user-attachments/assets/f34319a3-a173-493b-8b89-088e9ebbe140
Not done in this PR:
The ability to deal zero damage by Bad Luck halving or by other damage modifiers should be more investigated and discussed separately.
And talking about triggering Bad Luck more often: I found only the chances for HoMM3 (https://heroes.thelazy.net/index.php/Luck) where the chance of Bad Luck is 2 times higher than of Good Luck. The chance for Bad Luck in HoMM2 should be more investigated...
> Battlefield. Fix Bad Luck animation to be closer to the original game

- src/fheroes2/battle/battle_interface.cpp
solves #8796
Previously troop counts were drawn after the troops themselves.
This seems to cause the moving troops to override the troop count
I swapped the order and now the troop count should be in front of the moving monster
> Battle Interface: drawing troop count after (moving) monster

- src/fheroes2/gui/ui_font.cpp
- src/fheroes2/gui/ui_keyboard.cpp
Part of #8826 
Added Danish keyboard:
Added Ø to font:
> Add Danish language to virtual keyboard

- src/fheroes2/gui/ui_language.cpp
Reading resources from an AGG file and calculating CRC32 value from it is not an instance operation. Also, since we want to minimize I/O operations from file storage it is important to cache it. This should improve the startup time of the application as well as FPS value for the Select Game Language dialog.
Just small facts:
- the engine startup calls `getResourceLanguage()` function **5** times
- the Select Game Language dialog needs wooping **52** calls of the same function
> Cache resource language calculations to improve the performance

- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/maps/map_format_info.cpp
- src/fheroes2/maps/map_format_info.h
This field is optional and requires to be filled for map makers providing maps to be a part of the fheroes2 bundle. This is a much more elegant solution rather than proving contact details in the description of the map or in a separate file.
> Add an optional field for map creator's notes

- src/fheroes2/dialog/dialog_selectitems.cpp
- src/fheroes2/dialog/dialog_selectitems.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_interface_panel.cpp
- src/fheroes2/editor/editor_interface_panel.h
Relates to #9766 
This PR removes the specially coded color for mines that assumed to have many map objects in the database for each player color.
The color for mines is now set in `CapturableObjectMetadata`.
> Clean Editor-related code: remove the unused mine color property

- .github/workflows/make.yml
- .github/workflows/pages.yml
- .github/workflows/push.yml
- docs/deployments/WEB_DEPLOYMENT.md
This PR introduces a new "Play Online" feature to our website, allowing users to play fheroes2 directly in their browser. This is implemented through Emscripten integration and requires changes to our site deployment process to support it.
> [!IMPORTANT]
> Try and [play online](https://justinbburris.github.io/fheroes2/play-online)! 
- Added new `/play-online` section to the website
- Integrated Emscripten build into the site structure
- Upload Emscripten builds into latest-commit releases
- Created GitHub Actions workflow to automate the build and deployment process
The implementation required changes to our deployment process to support the Emscripten build:
- New GitHub Actions workflow (`.github/workflows/pages.yml`) that:
- Builds the Jekyll site
- Downloads and integrates the latest …
> Add Play Online Feature to Website

- src/fheroes2/editor/editor_interface_panel.cpp
Remove the (now) redundant conditional structure.
Relates to #9824
> Fix Sonar Cloud "cpp:S3923" issue

- src/engine/tools.h
- src/fheroes2/world/world.cpp
* SFINAE: `std::numeric_limits<T>::max_exponent` is an [exclusive upper-bound](https://en.cppreference.com/w/cpp/types/numeric_limits/max_exponent) of the exponent and not an inclusive one (the maximum allowed exponent for a finite value is `max_exponent - 1` and not `max_exponent` itself);
* Deduplicated a few lines of code by simplification of the `if constexpr` in both `checkedCast()` implementations;
* Added `const` according to the Sonar hint;
* Merged a few `if` statements according to the Sonar hint.
> Fix some recently introduced code smells

- .github/workflows/pages.yml
- .github/workflows/push.yml
Otherwise this workflow fails on forks (because GitHub Pages are usually not enabled/configured on them).
Also this PR simplifies the `pages.yml` workflow a bit by avoiding extra copy operations.
> Only run GitHub Pages workflow in the base repo

- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
This PR:
- inlines `isNearIndexes()` and `isValidIndex()` methods;
- adds `Battle::Board::GetCell( const int32_t position )` not to use `Battle::Cell * Battle::Board::GetCell( const int32_t position, const int dir = CENTER )` because for this case we don't need to check direction and to get index by direction;
- uses `operator[]` instead of `at()` in release version because the index is already checked in the upper lines;
- moves precalculations that are not needed for all `case`s.
> Minor battlefield cell related code speed-up

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
fix #7083 
This PR moves two "not flat" obstacles to the "high" obstacles rendering function.
This PR:
> Battlefield. Fix rendering of high obstacles

- src/fheroes2/heroes/heroes_indicator.cpp
- src/fheroes2/heroes/heroes_indicator.h
fix #9433 
This PR does rendering of "long" Spell Points values in two lines to fully and properly show them in the output field. The field for this case is expanded to the top.
The introducing of thousands (e.g. "1K" for 1000-1999) will not fix the issue because not all three-digit values already fit:
> Render hero's "current / max" Spell Points in two lines if they don't fit in one line

- src/fheroes2/ai/ai_battle.cpp
- src/fheroes2/ai/ai_battle.h
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
After implementing the `checkedCast()` for floating-point -> integer conversions in #9819 it became obvious that unit threat evaluation logic with conversions from `double` to `int32_t` wasn't a good idea. For instance, although this battle works just fine in this PR:
https://github.com/user-attachments/assets/28f835a3-3441-4ab2-a67a-969e3e7f5705
it crashes in the `master` branch due to `std::bad_optional_access` exception here:
https://github.com/ihhub/fheroes2/blob/4d3b56f8bde4d54335cfb2febfa9c6444ea85a17/src/fheroes2/battle/battle_troop.cpp#L1160
since the result of the `attackerThreat * 100` expression doesn't fit into `int32_t`, so in this PR I decided to remove all these extra `double` -> `int32_t` -> `double` conversions (since most of the threat evaluation code in the …
> Use the double-precision floating-point values for unit threat evaluation

- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/ai/ai_planner.h
- src/fheroes2/ai/ai_planner_hero.cpp
`AI::Planner` class is not quite a suitable place for this logic, since this logic has nothing to do with _planning_ 🙂 and is not used somewhere outside of the AI code. Since it is used only by `ai_hero_action.cpp`, I moved the corresponding function to the anonymous namespace in that file.
> AI: move the guardian spell cast logic from the AI planner to the anonymous namespace

- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/gui/ui_font.cpp
This PR restores the ASCII characters (`$` and `&`) for French assets.
It also restores the `*` character that has a sprite in SW assets, but is replaced with the dot (`.`) in English PoL assets.
So mapmakers of SW maps could use this character in their maps.
Russian version by "Buka" has `*` character in both SW and PoL assets, so it also could be used in maps made by this version.
This PR also fixes the vertical offset of `$` and `&` characters.
The other replaced ASCII characters are replaced with the dot (`.`) sprite like it is done in English assets.
> Fix (restore) ASCII characters for French assets

- src/fheroes2/ai/ai_hero_action.cpp
fix #4141, fix #5146
This PR adds extra centering map on the hero when he interacts with an action object:
https://github.com/user-attachments/assets/348e11c7-9d79-4796-9f0f-e50e0deadb36
https://github.com/user-attachments/assets/2184e9d7-e684-48bf-950e-0b24abe06396
> Fix map center positioning when AI interacts with action object

- src/fheroes2/world/world.cpp
- src/fheroes2/world/world.h
This method became unused after https://github.com/ihhub/fheroes2/pull/9845.
> Remove the unused method

- .github/workflows/msvc.yml
See https://github.com/actions/runner-images/issues/12045 for details.
> MSVC workflow: migrate to the windows-2022 runner

- src/fheroes2/world/world.cpp
This fheroes2-specific rumor makes it less likely for other useful rumors to appear, like those giving the general area of the UA, and this diminishes the original value of the Tavern. It's also more likely that a player will see the download link in the Credits or in the docs than randomly in the Tavern.
Fix #2199
> Remove rumor about latest update

- android/app/build.gradle
The digest file is generated during the build, so the potential difference in hash function performance is not so important, and comparing digests during game startup will not suffer, because they are relatively small anyway.
> Android: use SHA512 hash instead of MD5 during the generateAssetsDigest build step to further minimize the likelihood of hash collisions

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/editor/editor_map_specs_window.cpp
- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/maps/map_format_info.cpp
- src/fheroes2/maps/map_format_info.h
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/world/world_loadmap.cpp
This PR fixes tiles initialization when creating a new map. Previously only the top row was initialized.
It also renames the variable `size` to `width` because it actually is the width of the map which is the same as the map height because we support only squared maps.
> Fix tiles initialization when creating a new map from scratch

- src/fheroes2/army/army.cpp
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/gui/interface_status.cpp
- src/fheroes2/heroes/heroes.cpp
fix #9869 
The incorrect 1st level troop is shown because before dismissing the defeated hero from the kingdom his army is always reset to one 1st level troop according to hero's race.
This PR removes the reset of the defeated army right after the battle because the reset is also done when dismissing the defeated hero from the kingdom right after the hero fade-out animation.
https://github.com/user-attachments/assets/9bc3e4ab-9dfa-4d69-833e-2ff86ec5f017
This PR also slightly updates the logic for `Troops::isValid()`, `Troops::GetOccupiedSlotCount()` and `Army::drawMultipleMonsterLines()`.
> Fix showing one 1st level troop in hero's army diring hero fade-out animation after loosing the battle

- src/fheroes2/maps/map_format_helper.cpp
- src/fheroes2/world/world_loadmap.cpp
This PR adds simple checks for repeat of objects' UIDs during `fh2m` map load.
If the repeats are detected the information about this will be output to the console and log file.
The shown information may help to fix the already made maps by the very first versions of editor and to check the editor correctness in the future while testing editor-related PRs.
> Detect doubled objects' UIDs in fh2m maps in debug build

- src/engine/tools.h
- src/fheroes2/dialog/dialog_selectfile.cpp
- src/fheroes2/maps/maps_fileinfo.cpp
- src/fheroes2/maps/maps_fileinfo.h
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
Solves #1211
Introduces a new configuration `save file sorting` that changes the way sorting works in the load dialog
✅ Allows sorting by timestamp rather than filename
✅ Doesn't change the default behavior
~~❌No UI improvements~~
✅ Awesome UI thanks to @zenseii
> Add ability to sort save files by name or date

- src/engine/rand.h
On 32bit systems `static_cast<std::ptrdiff_t>(std::numeric_limits<uint32_t>)::max()` returns a negative number and this assert always fails.
> Fix assert in rand.h that always fails on 32bit systems

- .gitignore
- src/engine/rand.cpp
- src/engine/rand.h
- src/fheroes2/agg/agg_image.cpp
- src/fheroes2/army/army.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_board.cpp
- src/fheroes2/battle/battle_board.h
- src/fheroes2/world/world.cpp
Addresses performance issues raised in #9867 
- implements PCG32 random engine
- replaces mt19937 with PCG32 random engine
Doesn't address other performance issues (Not reusing random engine)
✅ No external dependencies
✅ Fixes seeding issues of mt19937 (only 2<sup>32</sup> possible seeds out of only 2<sup>19937</sup>)
✅ State reduced from 5000 bytes to 16 bytes
❔ Possible speed boost (haven't measured)
Note:
There is some performance to be gained by further optimizing `PCG32::rotateRight` but I'm not sure it's worth the hassle.
The operation should be compiled to a `rotr` instruction but compilers don't seem to agree with me.
c++20 has builtin std::rotr which should be faster but not available in c++17.
Possibilities:
- use _rotr instrinsic on MSVC. This may require either giving up on …
> Improvement(Random): replace mt19937 with PCG32

- src/fheroes2/agg/agg_image.cpp
This makes the minimum button width match the original buttons.
> Use original button sizes as minimum size for editor and main menu buttons

- src/engine/screen.cpp
- src/engine/screen.h
- src/fheroes2/game/fheroes2.cpp
- src/fheroes2/system/settings.cpp
- src/fheroes2/system/settings.h
Solves #1228 
Saves the position of the window in fheroes2.conf.
The position is captured every time the window is moved, and saved to settings when the game exits.
It's possible to capture only when the game exits, but then we might not save the correct position if the user swaps to Fullscreen mode before quitting.
> feat: remember position of game window

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/maps/maps_tiles.cpp
fix #9935 
When removing an object part from the tile we need to update passabilities not only in that tile but also in the tiles around.
> Fix passabilites update after map erasing an object in Editor

- src/fheroes2/maps/maps_tiles.cpp
- src/fheroes2/maps/maps_tiles_helper.cpp
The issue found by **Moucheron Quipet** on Discord:
"On the editor, trying to place a lighthouse next to a pre-flagged one cause this error to happen :
This PR fixes the behavior of objects sorting on a tile (it is done when placing a new object).
Now if the Flag is found in the ground objects it will not be moved to the main object part.
This PR also fixes the incorrect erasure of an object (Lighthouse) if you click on a flag near it.
> Fix placing objects that overlaps the flag of already placed object and fix erasure of object by clicking on its flag

- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/game/game.cpp
- src/fheroes2/game/game_scenarioinfo.cpp
Fix #9944
The issue happens if you star a map (or simply open a scenario info dialog when staring a new map and close it) then go to editor, change the players parameters, save the map and try to start a new game: the players parameters will be restored from the previous version of the map (now overwritten while saving).
This PR adds the reset of stored players' parameters to reload them when starting a new map.
It also removes redundant `Game::SavePlayers()` and `Game::LoadPlayers()` when changing the map because:
- there is no need to save players parameters from the previous map for the new different map, the parameters are always saved when leaving this dialog;
- the `Game::LoadPlayers()` immediately exits if the map name is different from the map name in ``Game::SavePlayers()` call …
> Fix update of map and players info when restarting the map that was changed and saved in Editor

- src/fheroes2/maps/maps_tiles.cpp
close #9286
The bug is also present in the original game due to incorrect object information.
> Fix rendering bug for a particular crack object

- src/fheroes2/editor/editor_interface.cpp
This PR fixes a regression after #9948 (fond by **Moucheron Quipet** on Discord) that made the engine crash if you save a map in editor and then try to load a different map in editor:
The issue was present always but it did no harm while "saved" players and `Settings::Get().GetPlayers()` operate with the same data.
This PR resets the players vector as well as the "saved" players data data when exiting editor. And there is no need to reset the "saved" players data when saving a map.
This OR also make the exit from editor to the engine main menu act the same the the exit to editor's main menu - with fade in/out and with resetting the data.
> Fix the regressing that forced a crash after saving a map in editor and loading another map

- src/fheroes2/battle/battle_action.cpp
Fix #9981
A regression after #9895
https://github.com/user-attachments/assets/285f973c-58ee-4418-b78f-7c692b9d9594
> Fix animation of the appearance of summoned elementals

- .github/workflows/make.yml
`macos-13` runner is [closing down](https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/) and won't be available soon.
> Use the macos-14 runner instead of the macos-13

- src/fheroes2/castle/castle.cpp
- src/fheroes2/castle/castle.h
- src/fheroes2/editor/editor_interface.cpp
- src/fheroes2/world/world.h
This PR fixes:
- a crash when giving a random castle a name of 72 random names: currently the castle count is limited to 72, but a TODO is left to allow custom named castles to be excludeв from  this limit;
- a bug after removing the castle: the castle data was not removed from `vec_castles`.
> Fix castles handling in Editor

- src/fheroes2/maps/map_format_helper.cpp
This PR fixes the next bug:
1. Make a new map (or open a map), add 2 or more players and set the Special Victory Condition to "One side defeats another".
2. Remove the players (or leave only 1 player on the map).
3. Save the map.
4. You'll get a crash!
Then it will appear every time you try to open the maps list (until you remove the map from your hard drive):
`Assertion failed: map.alliances.size() == 2, file D:\h2\git\src\fheroes2\maps\maps_fileinfo.cpp, line 492`
> Fix a crash after saving a map when victory condition was "One side defeats another" and then the players were removed from map

- src/fheroes2/maps/maps_tiles.h
This PR removes redundant check for `MP2::OBJ_CASTLE` in `isRoad()` method because the active tile is already marked as road (`_isTileMarkedAsRoad` == `true`) in `isSpriteRoad()` function:
https://github.com/ihhub/fheroes2/blob/e6b634925b3957200be87a973caf209f6ecdd84c/src/fheroes2/maps/maps_tiles.cpp#L356-L363
> Remove redundant check for `MP2::OBJ_CASTLE` in `isRoad()` method

- .github/workflows/make.yml
There is no corresponding directory on https://ftp.debian.org/debian/dists/ anymore.
> Nintendo Switch: add temporary workaround to fix the build

- src/fheroes2/spell/spell_storage.cpp
- src/fheroes2/spell/spell_storage.h
This PR does a code clean in `spell_storage.h` and `.cpp`:
- remove public unused `void Append( const Artifact & )` method (just do `Append( Spell( artifact.getSpellId() ) );`),
- do not `.reserve()` spell storage,
- return a copy of spell storage for `level == -1` instead of filling new spell storage by calling `push_pack()` in a loop for all items.
> Code clean in `spell_storage.h` and `.cpp`

- src/fheroes2/world/world.cpp
fix #10042
After digging in `master` branch the hole object is places with `BACKGROUND_LAYER` set. When passabilities are updated (in example, after picking-up a nearby chest) the hole is considered as a one high high object.
This PR sets the `TERRAIN_LAYER` for the digging hole.
(The holes places in original and fheroes2 editors places holes to `TERRAIN_LAYER`).
This PR does not fix the saves that already have holes after digging, but fixes the new placed holes after digging.
> Set proper object layer when placing a hole on the map after digging

- .github/workflows/make.yml
- src/fheroes2/ai/ai_battle.cpp
- src/fheroes2/ai/ai_battle.h
- src/fheroes2/ai/ai_hero_action.cpp
- src/fheroes2/battle/battle.h
- src/fheroes2/battle/battle_action.cpp
- src/fheroes2/battle/battle_arena.cpp
- src/fheroes2/battle/battle_arena.h
- src/fheroes2/battle/battle_army.cpp
- src/fheroes2/battle/battle_army.h
- src/fheroes2/battle/battle_dialogs.cpp
- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
- src/fheroes2/battle/battle_main.cpp
- src/fheroes2/battle/battle_only.cpp
- src/fheroes2/battle/battle_troop.cpp
- src/fheroes2/battle/battle_troop.h
- src/fheroes2/heroes/heroes_action.cpp
fix #10020
<details>
<summary>1. Ghosts: losses, experience and Necromancy</summary>
https://github.com/user-attachments/assets/ef61be86-03a6-4eb2-aa7d-94129a6405dd
OG behavior:
https://github.com/user-attachments/assets/68929300-155e-47bb-859a-a0c660105eb4
This PR:
https://github.com/user-attachments/assets/ddacfae2-3ebc-42a6-b79a-080d0210a3db
</details>
<details>
<summary>2. Resurrect spell and Necromancy</summary>
https://github.com/user-attachments/assets/07105b60-e6b6-4d1d-92b9-7e1aeaae30fe
OG behavior:
https://github.com/user-attachments/assets/a1b68a3e-cba7-497c-8f80-fd1fbf8aca78
This PR:
https://github.com/user-attachments/assets/dc227a9a-4a06-4409-8b47-a962a5902880
</details>
So far, these are all the differences with the original game that I …
> Bring the logic of calculating experience and losses in line with the logic of the original game

- src/fheroes2/campaign/campaign_savedata.cpp
- src/fheroes2/campaign/campaign_savedata.h
- src/fheroes2/system/save_format_version.h
We are still missing a feature to review completed scenarios in a campaign. In the original game it is possible to do and for each scenario it displays the number of days spent in relation to the scenario. This change saves the same information to be used in the future UI updates.
relates to #4381
> Save days spent value for each scenario of campaign

- .codechecker-review-status-config
- src/engine/smk_decoder.cpp
- src/engine/smk_decoder.h
- src/fheroes2/game/game_newgame.cpp
- src/fheroes2/game/game_video.cpp
- add missing logging for video processing
- use micro-seconds per frame (usf) rather than doing double conversion from usf to fps and then to milli-seconds per frame as conversion between float values always adds some error
> Improve video processing logic

- src/fheroes2/ai/ai_planner_hero.cpp
The previous logic accounts only for cases when the Wagon object contains an artifact.
close #9149
> Fix Wagon object evaluation for the AI when it contains resources

- android/app/src/main/java/org/fheroes2/MapFileManagerActivity.java
- android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
- android/app/src/main/java/org/fheroes2/ToolsetActivity.java
- android/app/src/main/res/layout/activity_map_file_manager.xml
- android/app/src/main/res/layout/activity_save_file_manager.xml
- android/app/src/main/res/layout/activity_toolset.xml
Without this, some parts of Toolset activities UI (e.g. toolbars) may overlap with the system bars (navigation bar or status bar) on Android 15. Tested on Android 14 and Android 15 devices with both buttons-based and gesture-based navigation bars.
See https://developer.android.com/about/versions/15/behavior-changes-15?hl=en#window-insets for details.
> Make the Toolset activities compatible with Android 15 edge-to-edge enforcements

- .github/workflows/sonarcloud.yml
fix #10135
It seems that there was some "vulnerability" in SonarCloud:
https://community.sonarsource.com/t/security-advisory-sonarqube-scanner-github-action/147696
It was "fixed" in such a way that:
* Environment variables can no longer be used in the scanner parameters.
* Only paths located inside the working directory now can be specified. Even if you specify the absolute path, it will be forcibly prepended by `/home/runner/fheroes2/fheroes2`, e.g. `/home/runner/fheroes2/fheroes2//usr/local/...`. Fortunately, this can still be circumvented by symlinks (in a way, not head-on).
* Comma operation in paths is broken, that is, now it is impossible to specify multiple paths separated by commas in one parameter, as before. I hope it gets fixed eventually, because this is a [documented …
> GitHub Actions: fix the SonarCloud workflow

- src/fheroes2/gui/ui_button.cpp
- src/fheroes2/heroes/heroes_dialog.cpp
Buttons should be drawn after the state check.
relates to #10113
> Fix Hero Dialog EXIT button flickering

- src/fheroes2/editor/editor_interface_panel.cpp
> Do not show cell selection frame when no monster is selected for a brush in the Editor

- src/fheroes2/battle/battle_interface.cpp
- src/fheroes2/battle/battle_interface.h
We have a plenty of space on the screen for high resolutions. So, no need to overlap an already small battlefield.
The turn order will stay the same if the display high is not enough to put the dialog above the battlefield.
close #6522
> Show Turn Order dialog above the arena if there is enough space
